--devbgascension

-- Bytecode (Base64):
-- BgMhBG1hdGgDY29zA3NpbgVVRGltMgNuZXcIZ2V0Q29vcmQHVmlzaWJsZQhQb3NpdGlvbgdEZXN0cm95CkRpc2Nvbm5lY3QEU2l6ZQFZBk9mZnNldAFYBUNsb25lCmZyb21PZmZzZXQGUGFyZW50CUhlYXJ0YmVhdAdDb25uZWN0CEluZmluaXR5BGdhbWUKUnVuU2VydmljZQpHZXRTZXJ2aWNlCEluc3RhbmNlBUZyYW1lB1ZlY3RvcjIDb25lC0FuY2hvclBvaW50BkNvbG9yMxBCYWNrZ3JvdW5kQ29sb3IzCFVJQ29ybmVyBFVEaW0MQ29ybmVyUmFkaXVzAAUMAgAAAAcEAAAFAgICF7sJAANSAwAApAICAAAEAICfAgICuxgAA1IEAACkAwQAAAwAgJ8DAgIJBQMDlQQFBaQFCAAAHGCAbwYJAAkIAQLsBwgEbwgJAAkLAQMJCgsC7AkKBJ8FBQCCBQAACgMBAwIEAAQAgAMDBAAMAIACAAAAAAAA8D8DBAMFBAAcYIACAAAAAAAA4D8ADgYBGAAAAAAAAQAAAAABAAEAAQEAAQEAAPwADwAAAAAGAQQAAAYDAAAFAQIU+wIAAE0BAoAAAAAADgEPAPsBAQA1AgC7AQAAAG8EAgD7BQIACQMEBfsEAwCfAgMCMAIBOwMAAAD7AwIAPgQABUMCAwQhAQIE3gECAIIAAQAGAwcDBgIYLURU+yEZQAMIAgAAAAAAAPA/AgAAAAAAAABAACMAARgAAAAAAQAAAAAAAAAAAAEAAAAAAiQAAAAAAgACAAAACfsAAAC8AABQAAAAAJ8AAgH7AAEAvAAAGgEAAACfAAIBggABAAIDCQMKACoAARgAAAAAAQAAAAErAAAAAAgBAgAABgMAAAUBBy1NBAAvAQAAAE0DBHgCAAAATQIDcAMAAABbAQIATQUALwEAAABNBAV5BQAAAE0DBHADAAAAPgIDBPsDAAC8AwM6BgAAAJ8DAgKkBAkAACBwgFIFAQBSBgEAnwQDAjAEAy8BAAAAMAADJAoAAACMBAAA+wYBAE0FBv0LAAAA2QcAABIAAAASAAMAEgEE/xIAAgC8BQXHDAAAAJ8FAwJSBgMA2QcBABIAAwASAAUAwQQAAIIGAwANAmZmZmZmZtY/AwsDDAMNAgAAAAAAAABAAw4DDwMEAxAEACBwgAMRAxIDEwIBAhsUARgAAAAAAAAAAQAAAAAAAAEAAAABAAAAAAAAAQACAQAAAAAAAAAAAAAHAAAAAAAcAAAAAAYAAAECACyjAAAApAABAAAAAEBvAgIAvAAAFgMAAACfAAMCpAEGAAAUQIBvAgcAnwECAqQDCwAAKJCAPgIDCDACAegMAAAApAIOAAAU0ICMAwEAjAQBAIwFAQCfAgQCMAIBnw8AAACkAgYAABRAgG8DEACfAgICpAMSAAAUEIGMBAEAjAUAAJ8DAwIwAwJPEwAAADABAiQUAAAAwAMVABgDALsWAAAAwAMXABIAAQASAAAAggMCABgDFQQAAABAAxYDFwMYAwUEABRAgAMZAgAAAAAAAABAAxoDGwQAKJCAAxwDHQQAFNCAAx4DHwMgBAAUEIEDIQMRBgADBgYDAgADAQABGAACAAAAAAACAAAAAQAAAAABAAAAAAAAAAIAAAABAAAAAAAAAQADAAANAAAWAQAAAAAES9UjefM2rJt5EUntrIBWBVxqsMGbDUYwAkMTUURMo47P1i0e68hShw==

local u1 = game:GetService("RunService")
local u2 = Instance.new("Frame")
u2.AnchorPoint = Vector2.one / 2
u2.BackgroundColor3 = Color3.new(1, 1, 1)
local v3 = Instance.new("UICorner")
v3.CornerRadius = UDim.new(1, 0)
v3.Parent = u2
function getCoord(p4, p5)
    local v6 = math.cos(p4)
    local v7 = math.sin(p4)
    local v8 = v7 * v7 + 1
    return UDim2.new(0.5, p5 * v6 / v8, 0.5, p5 * v7 * v6 / v8)
end
return function(u9) --[[Function name: Infinity, line 27]]
    --[[
    Upvalues:
        [1] = u2
        [2] = u1
    --]]
    local v10 = u9.Size.Y.Offset * 0.35
    local u11 = u9.Size.X.Offset / 2
    local u12 = u2:Clone()
    u12.Size = UDim2.fromOffset(v10, v10)
    u12.Parent = u9
    local u13 = 0
    local u15 = u1.Heartbeat:Connect(function(p14) --[[Anonymous function at line 35]]
        --[[
        Upvalues:
            [1] = u9
            [2] = u12
            [3] = u13
            [4] = u11
        --]]
        if u9.Visible then
            u12.Position = getCoord(6.283185307179586 * u13, u11)
            u13 = (u13 + p14 / 2) % 1
        end
    end)
    return u12, function() --[[Anonymous function at line 42]]
        --[[
        Upvalues:
            [1] = u12
            [2] = u15
        --]]
        u12:Destroy()
        u15:Disconnect()
    end
end