--devbgascension

-- Bytecode (Base64):
-- BgM1BHRhc2sFZGVsYXkMQ2FuUGxheVNvdW5kClNvdW5kR3JvdXADSXNBC0dldENoaWxkcmVuBG1hdGgGcmFuZG9tBUNsb25lCEdldFNvdW5kB0Rlc3Ryb3kDR2V0DVNvdW5kIEVmZmVjdHMIU2V0dGluZ3MGdHlwZW9mBnN0cmluZwR3YXJuGVNvdW5kICclKicgZG9lcyBub3QgZXhpc3QGZm9ybWF0BmFzc2VydAZWb2x1bWUEc3FydApUaW1lTGVuZ3RoCEluc3RhbmNlA25ldwRQYXJ0CEFuY2hvcmVkCkNhbkNvbGxpZGUMVHJhbnNwYXJlbmN5BFNpemUGQ0ZyYW1lCXdvcmtzcGFjZQ1DdXJyZW50Q2FtZXJhBlBhcmVudARQbGF5DlBsYXlMb2NhbFNvdW5kBVNvdW5kBE5hbWUGRm9sZGVyBlNlYXJjaARnYW1lEVJlcGxpY2F0ZWRTdG9yYWdlCkdldFNlcnZpY2UMU291bmRTZXJ2aWNlB3JlcXVpcmUGQ2xpZW50CUZyYW1ld29yawhTZXJ2aWNlcwlMb2NhbERhdGEGU2hhcmVkBVR5cGVzBkFzc2V0cwZTb3VuZHMACAMAAgAAABT7AQAA+wIBAIcAAQIOAA8A+wAAAPsBAQCHAgABeAICAGoCAAH7AQAA+wIBAIcAAQKMAQAAfQAFAAEAAAD7AAAA+wEBAMYCAABqAgABggABAAECAAAAAAAA8D8AFgABGAAAAAABAAAAAAEAAAAAAAEAAAADFwAAAAAEAQEAAAYDAAAFAQMa+wIAAIcBAgArAQMA+wEAAIwCAABqAgEA+wIAAIcBAgCMAgUAfQIDAAEAAACpAQAAggECAPsBAACHAgEAlQICAGoCAQCkAQMAAAgQgG8CBADZAwAAEgIAABIAAACfAQMBqQEBAIIBAgAFAgAAAAAAAPA/AwEDAgQACBCAApqZmZmZmak/AQANAwEYAAAAAQAAAgAAAAABAAIAAAACAAAAAAAACQAOAAAAAAYBAAAABgMAAAUBBxZvAwAAvAEA/gEAAACfAQMCDgENALwBAGgCAAAAnwECAqQDBQAAEDCAjAQBABwFAQCfAwMChwIBA7wDAjoGAAAAnwMCAIIDAAC8AQA6BgAAAJ8BAgCCAQAABwMEAwUDBgMHAwgEABAwgAMJACMKARgAAAAAAAEAAAEAAAAAAAEAAAACAAAAJAAAAAACAAEAAAAF+wAAALwAAFAAAAAAnwACAYIAAQABAwsAWAABGAAAAAABWQAAAAACAAEAAAAF+wAAALwAAFAAAAAAnwACAYIAAQABAwsAXwABGAAAAAABYAAAAAALAgMAAAcEAAAFAg+IhwH7AgAAvAICfwAAAACfAgICDgIGAE0FAsoDAAAATQQFcAIAAAA+AwQBZQABAIwDAQDGBAAAuywAA1IGAACkBQUAAABAQJ8FAgLwBScABgAAgPsGAQCHBQYAKwULAKQGCAAAAHBAbwgJAFIKAAC8CAiNCgAAAJ8IAwJSBwgAnwYCAcEEAACCAAEAbwgLALwGBf4MAAAAnwYDAg4GDgC8BgVoDQAAAJ8GAgKkCBAAADzggIwJAQAcCgYAnwgDAocHBgi8CAc6EQAAAJ8IAgJSBAgAZQAJALwGBToRAAAAnwYCAlIEBgBlAAQAvAUAOhEAAACfBQICUgQFALsBBANSBgQApAUTAAAAIEGfBQIBTQUESxQAAAC7GQMDUgcDAKQGFgAAVOCAnwYCAgkFBQYwBQRLFAAAAE0FBNYXAAAADgEBAIwFBQAOASgApAYaAABkgIFvBxsAnwYCAqkHAQAwBwZFHAAAAKkHAAAwBwbTHQAAAIwHAQAwBwbZHgAAAG8HHwAwBwYvIAAAAKQHIgAAZBCCUggBAJ8HAgIwBwaFIQAAAKQIJAAAADBCTQcISCUAAAAwBwYkJgAAADAGBCQmAAAAvAcE7icAAACfBwIBpAcqAACkgIJSCAUA2QkAABIABgCfBwMBZQAFAPsGAgBSCAQAvAYGLCsAAACfBgMBpAYqAACkgIJSBwUA2QgBABIBBP+fBgMBwQQAAIIEAgAsAwwCAAAAAAAAWUADDQMOAw8EAABAQAMQAxEEAABwQAMSAxMDBAMFAwYDBwMIBAA84IADCQMUBAAAIEEDFQMWBABU4IADFwMYAxkEAGSAgQMaAxsDHAMdBwAAgD8AAIA/AACAPwAAAAADHgMfBABkEIIDIAQAADBCAyEDIgMjAwEDAgQApICCAyQCAwQtJAEYDQAAAAEAAAAAAAAAAwEAAAAAAAABAAEBAAAAAAAAAAABAOoAAAAAAQAAAQAAAAAAAQAAAAACAAAAABUAAAACAAAAAAIAAAAAAAAAAAAHAAEBAwEAAAABAAABAAABAAABAAABAAAAAAABAAAAAAABAAEAAAEAAAAAAAAEAAAAAAMAAAAAAAQAJAAAAAAJAQIAAAYDAAAFAQcevAEAaAAAAACfAQIEZAEXAG8IAQC8BgX+AgAAAJ8GAwIrBgUAbwgDALwGBf4CAAAAnwYDAg4GBQD7BgAATQcFugQAAABqBQYHZQAIAG8IBQC8BgX+AgAAAJ8GAwIOBgMA+wYBAFIHBQCfBgIBbgHo/wIAAACCAAEABgMGAyUDBQMEAyYDJwBnKAEYAAAAAAEAAAAAAAAAAAABAAAAAAEAAAAAAQAA/AAHaAAAAAANAAABAgA1owAAAKQAAQAAAABAbwICALwAABYDAAAAnwADAqQBAQAAAABAbwMEALwBARYDAAAAnwEDAqQCBgAAAFBATQYATQcAAABNBQYcCAAAAE0EBUMJAAAATQMEaAoAAACfAgICpAMGAAAAUEBNBQASCwAAAE0EBe8MAAAAnwMCAk0FAIENAAAATQQFKA4AAAD/BQAAAAAAAP8GAAAAAAAAwAcPABIABQDACBAAwAkRABIAAgASAAYAEgABAMAKEgASAAYAEgAKAFILCgBSDAQAnwsCAYIJAgATAykEAAAAQAMqAysDLAMtBAAAUEADLgMvAzADMQMyAzMDNAM1BgEGAgYFBgYEAQIFBgEAARgAAgAAAAAAAQAAAAAAAQAAAAAAAAAAAAABAAAAAAAAAwAAAAEAAQACABYKAAAAOgAACwAAAwEAAAAABwB9Ycd7ug+RMrkLU7ON2tmbF2lR4gxaioO3nnj7DxXQi0EQPlVFwRE=

local v1 = game:GetService("ReplicatedStorage")
local u2 = game:GetService("SoundService")
local u3 = require(v1.Client.Framework.Services.LocalData)
require(v1.Shared.Types)
local u4 = {}
local function u7(p5) --[[Anonymous function at line 103]]
    --[[
    Upvalues:
        [1] = u4
        [2] = u7
    --]]
    for _, v6 in p5:GetChildren() do
        if v6:IsA("Sound") or v6:IsA("SoundGroup") then
            u4[v6.Name] = v6
        elseif v6:IsA("Folder") then
            u7(v6)
        end
    end
end
u7(v1.Assets.Sounds)
return function(p8, p9) --[[Function name: PlayLocalSound, line 45]]
    --[[
    Upvalues:
        [1] = u3
        [2] = u4
        [3] = u2
    --]]
    local v10 = u3:Get()
    local v11 = not v10 and 1 or v10.Settings["Sound Effects"] / 100
    local u12
    if typeof(p8) == "string" then
        local v13 = u4[p8]
        if not v13 then
            warn((("Sound \'%*\' does not exist"):format(p8)))
            return
        end
        if v13:IsA("SoundGroup") then
            local v14 = v13:GetChildren()
            u12 = v14[math.random(1, #v14)]:Clone()
        else
            u12 = v13:Clone()
        end
    else
        u12 = p8:Clone()
    end
    assert(u12)
    u12.Volume = u12.Volume * math.sqrt(v11)
    local v15 = p9 and 5 or u12.TimeLength
    if p9 then
        local u16 = Instance.new("Part")
        u16.Anchored = true
        u16.CanCollide = false
        u16.Transparency = 1
        u16.Size = Vector3.new(1, 1, 1)
        u16.CFrame = CFrame.new(p9)
        u16.Parent = workspace.CurrentCamera
        u12.Parent = u16
        u12:Play()
        task.delay(v15, function() --[[Anonymous function at line 88]]
            --[[
            Upvalues:
                [1] = u16
            --]]
            u16:Destroy()
        end)
    else
        u2:PlayLocalSound(u12)
    end
    task.delay(v15, function() --[[Anonymous function at line 95]]
        --[[
        Upvalues:
            [1] = u12
        --]]
        u12:Destroy()
    end)
    return u12
end