--devbgascension

-- Bytecode (Base64):
-- BgMdBkNGcmFtZQNuZXcGQW5nbGVzBk9yaWdpbgRFbWl0BkFzc2V0cwlQYXJ0aWNsZXMKU3BsYXNoR29sZAZTcGxhc2gEZ2FtZRFSZXBsaWNhdGVkU3RvcmFnZQpHZXRTZXJ2aWNlB3JlcXVpcmUGU2hhcmVkCUZyYW1ld29yawdDbGFzc2VzDFdvcmxkRW1pdHRlcglVdGlsaXRpZXMWRW1pdFBhcnRpY2xlQXRQb3NpdGlvbgRHb2xkBFJhdGULTnVtYmVyUmFuZ2UGUmFkaXVzCExpZmV0aW1lEUdyYXZpdHlNdWx0aXBsaWVyBVNwZWVkDk51bWJlclNlcXVlbmNlFk51bWJlclNlcXVlbmNlS2V5cG9pbnQMVHJhbnNwYXJlbmN5AAIIAQMAAAYDAAAFAQgf+wEAAKQDAgAABACAUgQAAJ8DAgKkBAQAAAwAgG8FBQCMBgAAjAcAAJ8EBAIJAgMEMAIBQwYAAACMBAoAvAIBVgcAAACfAgMB+wUBAE0EBYEIAAAATQMErgkAAABNAgNoCgAAAPsDAgBSBAAAUgUCAIwGKACfAwQBggABAAsDAQMCBAAEAIADAwQADACAAhgtRFT7Ifk/AwQDBQMGAwcDCAAVCQEYAAEAAAAAAAAAAAAAAAABAAAAAgAAAAAAAAEAAAAAARYAAAAACwAAAQIAYaMAAACkAAEAAAAAQG8CAgC8AAAWAwAAAJ8AAwKkAQUAAABAQE0FABIGAAAATQQFHAcAAABNAwQYCAAAAE0CA1wJAAAAnwECAqQCBQAAAEBATQYAEgYAAABNBQYcBwAAAE0EBbUKAAAATQME+gsAAACfAgICTQMB7wwAAABNBgCBDQAAAE0FBq4OAAAATQQFyw8AAACfAwICjAQAADAEA/YQAAAApAQSAAAwEIGMBQAAbwYTAJ8EAwIwBANxFAAAAKQEEgAAMBCBbwUVAG8GFgCfBAMCMAQDyxcAAACkBBIAADAQgYwFAACfBAICMAQD0BgAAACkBBIAADAQgYwFBQCMBgoAnwQDAjAEAywZAAAApAQbAAAwoIH/BQAAAwAAAKQGHQAAMMCBjAcAAIwIAACfBgMCpAcdAAAwwIFvCB4AjAkAAJ8HAwKkCB0AADDAgYwJAQCMCgEAnwgDAMUFBgABAAAAnwQCAjAEA9kfAAAAwAQgABIAAwASAAAAEgACAIIEAgAhAwoEAAAAQAMLAwwDDQQAAEBAAw4DDwMQAxEDEgMTAwIDBgMHAxQDFQMWBAAwEIECAAAAAAAAGkADFwIAAAAAAAD4PwIAAAAAAAAEQAMYAxkDGgMbBAAwoIEDHAQAMMCBAgAAAAAAAOA/Ax0GAAEAAQABGAACAAAAAAACAAAAAAAAAAAAAAEAAAAAAAAAAAAAAwAAAAAAAAAAAQAAAQAAAAAAAAEAAAAAAAABAAAAAAABAAAAAAAAAQAAAAEAAAAAAQAAAAABAAAAAAAA/QAABgAAAAoBAAAAAAG81zLrA5DlR44TWH8eoiQRj7y5X/mkerjj1vxsWWOt5wY2VQiDZq4w

local u1 = game:GetService("ReplicatedStorage")
local v2 = require(u1.Shared.Framework.Classes.WorldEmitter)
local u3 = require(u1.Shared.Framework.Utilities.EmitParticleAtPosition)
local u4 = v2.new(u1.Assets.Particles.Gold)
u4.Rate = 0
u4.Radius = NumberRange.new(0, 6.5)
u4.Lifetime = NumberRange.new(1.5, 2.5)
u4.GravityMultiplier = NumberRange.new(0)
u4.Speed = NumberRange.new(5, 10)
u4.Transparency = NumberSequence.new({ NumberSequenceKeypoint.new(0, 0), NumberSequenceKeypoint.new(0.5, 0), NumberSequenceKeypoint.new(1, 1) })
return function(p5) --[[Function name: Splash, line 21]]
    --[[
    Upvalues:
        [1] = u4
        [2] = u1
        [3] = u3
    --]]
    local v6 = u4
    v6.Origin = CFrame.new(p5) * CFrame.Angles(1.5707963267948966, 0, 0)
    v6:Emit(10)
    u3(p5, u1.Assets.Particles.SplashGold, 40)
end