--devbgascension

-- Bytecode (Base64):
-- BgNcCmF1dG9TdHJva2UEJSolKgF4BmZvcm1hdBBmb3JtYXRBbW91bnRUZXh0BE5hbWUGSW1hZ2VzBk5vcm1hbAZNeXRoaWMFU2hpbnkADFVua25vd25JbWFnZQhnZXRJbWFnZQVJbm5lcgZCdXR0b24ESWNvbgVJbWFnZQZBbW91bnQORmluZEZpcnN0Q2hpbGQEVGV4dAdWaXNpYmxlB0xpbWl0ZWQFTGV2ZWwPR2V0TGV2ZWxGcm9tUGV0BEx2bCAIUmljaFRleHRZPHN0cm9rZSBjb2xvcj0iIzAwMjk1RSIgam9pbnM9Im1pdGVyIiB0aGlja25lc3M9IjIiPjxmb250IHNpemU9IjE4Ij4gJSo8L2ZvbnQ+JSo8L3N0cm9rZT4GUmFyaXR5CUxlZ2VuZGFyeQZTZWNyZXQIVUlTdHJva2UGQ29sb3IzA25ldwVDb2xvcgVDeWNsZQVTcGVlZAROb25lB2Zyb21IZXgHIzAwMjk1ZQZFZmZlY3QGUmVtb3ZlEEJhY2tncm91bmRDb2xvcjMHZnJvbVJHQgNBZGQKU2hpbnlMaWdodAxQb3Rpb25NeXRoaWMFU2hpZnQHUmFpbmJvdwZDb21tb24MUmFyaXR5Q29sb3JzCkJhY2tncm91bmQKVUlHcmFkaWVudAZBc3NldHMJR3JhZGllbnRzDUhhc0Nvbm5lY3Rpb24MR2V0QXR0cmlidXRlCkRlc3Ryb3lpbmcHQ29ubmVjdAxTZXRBdHRyaWJ1dGUVRmluZEZpcnN0Q2hpbGRPZkNsYXNzByMwMDI5NUUHRW5hYmxlZAtJbWFnZUNvbG9yMwZMb2NrZWQLRGlzcGxheU5hbWUDc2V0Am9zBWNsb2NrCFJvdGF0aW9uBGdhbWURUmVwbGljYXRlZFN0b3JhZ2UKR2V0U2VydmljZQpSdW5TZXJ2aWNlB1BsYXllcnMHcmVxdWlyZQZTaGFyZWQFVHlwZXMERGF0YQRQZXRzBVV0aWxzDFBldExldmVsVXRpbAZDbGllbnQDR3VpDEFuaW1hdGVDb2xvcglDb25zdGFudHMJRnJhbWV3b3JrCVV0aWxpdGllcwZTdHJpbmcMRm9ybWF0U3VmZml4BHNpemUJSGVhcnRiZWF0EWFuaW1hdGVkR3JhZGllbnRzAAYJAQMAAAYDAAAFAQIR+wIAAE0BAucAAAAAbwMBAPsFAQBvBgIAnwUCAvsGAgBSBwAAjAjoA58GAwK8AwONAwAAAJ8DBAJSAgMAnwECAIIBAAAEAwEDAgMDAwQAFwUBGAAAAAAAAAAAAAAAAAAAAAAAGAAAAAAKAQIAAAAo+wIAAE0DALoAAAAAhwECA00DAeMBAAAATQIDEAIAAABNAwCkAwAAACsDAwBNAwC0BAAAAA4DFABNAwHjAQAAAG8FBQBNCACkAwAAAA4IAgBvBwMAZQABAG8HBgBNCQC0BAAAAA4JAgBvCAQAZQABAG8IBgC8BQWNBwAAAJ8FBAJSBAUAhwIDBFIDAgArAwMA+wQBAE0DBEUIAAAAggMCAAkDBgMHAwgDCQMKAwIDCwMEAwwAHg0BGAAAAAABAAAAAQAAAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAACAAAAAAAfAAAAAAMAAgAAAAX7AAAA+wEBAMYCAABqAgABggABAAAAmQEAARgAAAAAAZoAAAAAFwUIAAAKBwAABQUPDwEBgdAF+wYAAE0HAboAAAAAhwUGB00GBeMBAAAATQoALAIAAABNCQqsAwAAAE0ICSwCAAAATQcIrgQAAAD7CgAATQsBugAAAACHCQoLTQsJ4wEAAABNCgsQBQAAAE0LAaQGAAAAKwsDAE0LAbQHAAAADgsUAE0LCeMBAAAAbw0IAE0QAaQGAAAADhACAG8PBgBlAAEAbw8JAE0RAbQHAAAADhECAG8QBwBlAAEAbxAJALwNDY0KAAAAnw0EAlIMDQCHCgsMUggKACsIAwD7CwEATQgLRQsAAAAwCAepDAAAAE0JACwCAAAATQgJrAMAAABNBwgsAgAAAG8JDQC8BwcDDgAAAJ8HAwIOBxIATQgBKw0AAABHCAwAAAAAAA4CCgD7CAIATQkBKw0AAACfCAICMAgH9Q8AAACpCAEAMAgHgBAAAABlAAMAqQgAADAIB4AQAAAATQkALAIAAABNCAmsAwAAAG8KEQC8CAgDDgAAAJ8IAwIOCAgATQoFJhEAAABHCgIAAAAAgKkJAAGpCQEAMAkIgBAAAABNCwAsAgAAAE0KC6wDAAAATQkKLAIAAABvCxIAvAkJAw4AAACfCQMCDgkoAPsKAwBSDAEAvAoKBxMAAACfCgMCbwsUAA4EAQBvCwkATQwJ0RUAAAAODBEAjA0BALcNAgAKAAAAqQwAAakMAQAwDAmAEAAAAG8NFgBSDwsAUhAKALwNDY0KAAAAnw0EAlIMDQAwDAn1DwAAAGUADACpDAEAMAwJgBAAAABvDQgAUg8LAFIQCgC8DQ2NCgAAAJ8NBAJSDA0AMAwJ9Q8AAAD7DAAATQ0BugAAAACHCwwNTQoL8hcAAACpCwEA8AoFABgAAADwCgIAGQAAAKkLAAGpCwEATQ0ALAIAAABNDA2sAwAAAG8OGgC8DAwDDgAAAJ8MAwIODDcATQ0BpAYAAAAODR4ATQ8ALAIAAABNDg+sAwAAAE0NDm0aAAAApA4dAABwsIGMDwEAjBABAIwRAQCfDgQCMA4NpB4AAAD7DgQATQ0OeR8AAABNEAAsAgAAAE0PEKwDAAAATQ4PbRoAAABvDwYA4hAhAG8RIgAwERAsIAAAAJ8NBAFlABYA+w4EAE0NDj8jAAAATRAALAIAAABNDxCsAwAAAE0OD20aAAAAnw0CAU0PACwCAAAATQ4PrAMAAABNDQ5tGgAAAKQOJQAAkLCBbw8mAJ8OAgIwDg2kHgAAAA4DNQD7DQUATRAALAIAAABNDxCzJwAAALwNDWkoAAAAnw0DAfsOBABNDQ4/IwAAAE0PACwCAAAATQ4PrAMAAACfDQIB+w4EAE0NDj8jAAAATRAALAIAAABNDxCsAwAAAE0ODywCAAAAnw0CAU0OACwCAAAATQ0OrAMAAACkDh0AAHCwgYwPAACMEAEAjBEAAJ8OBAIwDg2fKQAAAE0PACwCAAAATQ4PrAMAAABNDQ4sAgAAAKQOKwAAqLCBjA+pAIwQ/wCMEZwAnw4EAjAODZ8pAAAAZQDqAE0NAbQHAAAADg1LAPsNBQBNEAAsAgAAAE0PELMnAAAAvA0NXywAAACfDQMB+w4EAE0NDnkfAAAATQ8ALAIAAABNDg+sAwAAAG8PBwDiECEAbxEtADARECwgAAAAnw0EAfsOBABNDQ55HwAAAE0QACwCAAAATQ8QrAMAAABNDg8sAgAAAG8PLgDiECEAbxEtADARECwgAAAAnw0EAU0OACwCAAAATQ0OrAMAAACkDh0AAHCwgYwPAQCMEAEAjBEBAJ8OBAIwDg2fKQAAAE0PACwCAAAATQ4PrAMAAABNDQ4sAgAAAKQOHQAAcLCBjA8BAIwQAQCMEQEAnw4EAjAODZ8pAAAA+w4EAE0NDj8jAAAATREALAIAAABNEBGsAwAAAE0PECwCAAAATQ4PrgQAAACfDQIBZQCcAE0NAaQGAAAADg0oAE0OACwCAAAATQ0OrAMAAACkDh0AAHCwgYwPAQCMEAEAjBEBAJ8OBAIwDg2fKQAAAE0PACwCAAAATQ4PrAMAAABNDQ4sAgAAAKQOKwAAqLCBjA/iAIwQpwCMEf8Anw4EAjAODZ8pAAAA+w4EAE0NDnkfAAAATQ8ALAIAAABNDg+sAwAAAG8PLwDiECEAbxEtADARECwgAAAAnw0EAWUAIwAOCxoATQ4ALAIAAABNDQ6sAwAAAKQOHQAAcLCBjA8BAIwQAQCMEQEAnw4EAjAODZ8pAAAA+w4EAE0NDmwwAAAATQ8ALAIAAABNDg+sAwAAAG8PMQDiECEAbxEtADARECwgAAAAnw0EAWUACAD7DgQATQ0OPyMAAABNDwAsAgAAAE0OD6wDAAAAnw0CAfsNBQBNEAAsAgAAAE0PELMnAAAAvA0NaSgAAACfDQMB+w4EAE0NDj8jAAAATRAALAIAAABNDxCsAwAAAE0ODywCAAAAnw0CAU0NAaQGAAAADg0PAE0PACwCAAAATQ4PrAMAAABNDQ4sAgAAAKQOKwAAqLCBjA/cAIwQgQCMEewAnw4EAjAODZ8pAAAAZQAOAE0PACwCAAAATQ4PrAMAAABNDQ4sAgAAAKQOKwAAqLCBjA8bAIwQnACMEewAnw4EAjAODZ8pAAAATQ4ALAIAAABNDQ6sAwAAAPAKCAAyAACApA4rAACosIGMDykAjBDNAIwR/wCfDgQCZQANAPAKCAAZAACApA4dAABwsIGMDwEAjBABAIwRAQCfDgQCZQAEAPsQAQBNDxAUMwAAAIcODwowDg2fKQAAAE0PACwCAAAATQ4P7TQAAABNDQ76NQAAAE0OAaQGAAAADg4MAPsSBgBNERKBNgAAAE0QEfw3AAAATQ8QpAYAAABNDg+kHgAAADAODaQeAAAAZQALAPsSBgBNERKBNgAAAE0QEfw3AAAATQ8QdDEAAABNDg+kHgAAADAODaQeAAAAbxA4ALwODRI5AAAAnw4DAisODQBNDw1iOgAAANkRAAASAgcAEgANALwPD8c7AAAAnw8DAW8ROACpEgEAvA8NLjwAAACfDwQBDgsEAPsPBwCpEAEAahAPDWUAAwD7DwcAxhAAAGoQDw1NEAAsAgAAAE0PEKwDAAAAbxEaALwPD7g9AAAAnw8DAg4PFABNEgAsAgAAAE0REqwDAAAATRARbRoAAAAOAwcApBErAACosIGMEicAjBNdAIwUHQCfEQQCKxEEAKQRJQAAkLCBbxI+AJ8RAgIwERCkHgAAAA4DFgBNEgAsAgAAAE0REu00AAAATRAR+jUAAACpEQAAMBEQ8D8AAABNEQAsAgAAAE0QEe00AAAApBErAACosIGMEn0AjBP/AIwUWQCfEQQCMBEQAEAAAABlABQATREALAIAAABNEBHtNAAAAKQRHQAAcLCBjBIBAIwTAQCMFAEAnxEEAjAREABAAAAATRIALAIAAABNERLtNAAAAE0QEfo1AAAAMAsQ8D8AAABNEgAsAgAAAE0REqwDAAAATRARLAIAAABvEkEAvBAQAw4AAACfEAMCDhAIAE0SAaxBAAAAKhICAAEAAACpEQABqREBADAREIAQAAAATRMALAIAAABNEhOsAwAAAE0REiwCAAAAbxNCALwREQMOAAAAnxEDAg4RHADwCgwAGQAAgPsTBABNEhNsMAAAAFITEQBvFDEA4hUhAG8WLQAwFhUsIAAAAJ8SBAFlAAUA+xMEAE0SEz8jAAAAUhMRAJ8SAgFNEgG6AAAAADASEfUPAAAA8AoCABkAAACpEgABqRIBADASEYAQAAAATRUALAIAAABNFBWsAwAAAE0TFCwCAAAATRITZxkAAADwCgIAGQAAAKkTAAGpEwEAMBMSgBAAAACCAAEAQwMGAwcDDgMPAxADCAMJAwoDAgMLAwQDDAMRAxIDEwMUAxUDFgMXAxgDGQMaAxsDHAMdAx4DHwMgAyEEAHCwgQMiAyMDJAUBIAIAAAAAAADoPwMlAyYEAJCwgQMnAygDKQMqAysEAKiwgQMsAgAAAAAAAOA/Ay0DLgMvAzADMQMyAzMDNAM1AzYDNwM4AzkDOgM7AzwDPQM+Az8DQANBAQIqQgEYEgAAAAEAAQAAAAAAAADsAAAAAQAAAAEAAAAAAAEAAAAAAAAAAAAAAAAAAAAAAAAAAgAAAAAPAAIAAAAAAAAAAAABAQAAAAABAAAAAAABAAAAAgAABAAAAAAAAAABAQAAAAAAAAADAAAAAAAAAAAAAQEAAAAAAQEBAgAAAQAAAAAAAAEAAAAAAAAAAAACAAABAAAAAAAAAAAEAAAAAAABAAAAAAAAAgAAAAAAAAABAQAAAQAAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAAAAAgAAAAAAAAAAAAEAAAAAAAAAAAAAAAQBAAAAAAAAAAEAAAAAAAAAAQAAAAAAAAAAAAEAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAIAAAEAAAAAAAAAAQAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAMAAAEAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAACAQAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAACAAAAAAAAAAMAAAAAAAAAAQAAAAAAAAAAAAIAAAEAAAAAAAAAAAAAAAAAAAIAAAAAAAAAAAAAAAAAAwAAAAEAAQAAAAAAAAEAAQAAAAAAAAIAAAD6AAkAAAAAAAEAAAEAAAAAAAAAAAAAAAIAAAAAAAAAAAAAAwAAAAEBAAAAAAAAAAMAAAAAAwEAAAACAAADAAAAAAAAAAEBAAAAAAAAAAAAAAAAAAAAAAAAAAMBAAAAAAAAAAABAAAAAAAAAAAAAAAAAgAAAAAAAAAAAAAAAQAAAAAAAAADAAAAAAAAAAAAAQEAAAAAAAAAAwAAAAAAAAAAAAEBAAEAAAAAAAAAAAAAAgAAAAACAAAAAQAAAAAAAwAAAAAAAAAAAAAAAAABHwAAAAAGAAEAAAAOpAIEAAAMIICfAgECWwECASEAAQD7AQAAxgIAAMYDAABkAQIAMAAEOAUAAABuAf3/AQAAAIIAAQAGAgAAAAAAgHZAAgAAAAAAAFlAA0MDRAQADCCAA0UAxwEAARgAAAAAAAEAAAABAP8AA8gAAAAAEgAAAQIAhQGjAAAApAABAAAAAEBvAgIAvAAAFgMAAACfAAMCpAEBAAAAAEBvAwQAvAEBFgMAAACfAQMCpAIBAAAAAEBvBAUAvAICFgMAAACfAgMCpAMHAAAAYEBNBQASCAAAAE0EBe8JAAAAnwMCAqQEBwAAAGBATQcAEggAAABNBgfGCgAAAE0FBugLAAAAnwQCAqQFBwAAAGBATQgAEggAAABNBwihDAAAAE0GBz0NAAAAnwUCAqQGBwAAAGBATQoATQ4AAABNCQofDwAAAE0ICaEMAAAATQcItBAAAACfBgICpAcHAAAAYEBNCgASCAAAAE0JCqEMAAAATQgJ6BEAAACfBwICpAgHAAAAYEBNCgASCAAAAE0JCgcSAAAAnwgCAqQJBwAAAGBATQwAEggAAABNCwyhDAAAAE0KC9ETAAAAnwkCAqQKBwAAAGBATQ8AEggAAABNDg8cFAAAAE0NDrUVAAAATQwNoRYAAABNCwzGFwAAAJ8KAgL/CwAAAAAAAMYMAABNDQnvGAAAAJ8NAQKMDxQAvA0NDxkAAACfDQMCwAwaABIACQASAA0AEgAKAMANGwASAAQAEgAIANkOAgASAAQAEgAIABIBDP8SAAUAEgAHABIABgASAAAAEgALAE0PAf0cAAAAwBEdABIACwC8Dw/HHgAAAJ8PAwHiDyEAMA4PUx8AAAAwCw9pIAAAAMEMAACCDwIAIgNGBAAAAEADRwNIA0kDSgNLBAAAYEADTANNA04DTwNQA1EDUgNTAwoDVANVAxoDVgNXA1gDWQMhA1oGAAYBA1sGBAM6A0IDXAUCHyAEAAEDBAEAARgAAgAAAAAAAQAAAAAAAQAAAAAAAgAAAAAAAAEAAAAAAAAAAAEAAAAAAAAAAAEAAAAAAAAAAAAAAQAAAAAAAAAAAQAAAAAAAAEAAAAAAAAAAAEAAAAAAAAAAAAAAAADAAMCAAAAAAAAAQAAAAcAAAwAAAAAAAAAAJ0AAAAAAAAIAQABAAAAAQAAAAAFcdQnSZ1bAzdDEE3dHzIMgpWVFxLcM5YE3DKn90a4pvr0e7yGBVYLNw==

local u1 = game:GetService("ReplicatedStorage")
local v2 = game:GetService("RunService")
game:GetService("Players")
require(u1.Shared.Types)
local u3 = require(u1.Shared.Data.Pets)
local u4 = require(u1.Shared.Utils.PetLevelUtil)
local u5 = require(u1.Client.Gui.Utils.Shiny)
local u6 = require(u1.Shared.Utils.AnimateColor)
local u7 = require(u1.Shared.Constants)
local u8 = require(u1.Shared.Utils.RichText)
local u9 = require(u1.Shared.Framework.Utilities.String.FormatSuffix)
local u10 = {}
local u11 = u8.new():size(20)
local function u13(p12) --[[Anonymous function at line 23]]
    --[[
    Upvalues:
        [1] = u8
        [2] = u11
        [3] = u9
    --]]
    return u8.autoStroke((("%*%*"):format(u11("x"), (u9(p12, 1000)))))
end
local function v35(p14, p15, p16, p17, p18) --[[Anonymous function at line 42]]
    --[[
    Upvalues:
        [1] = u3
        [2] = u7
        [3] = u13
        [4] = u4
        [5] = u6
        [6] = u5
        [7] = u1
        [8] = u10
    --]]
    local v19 = u3[p15.Name]
    local _ = v19.Images
    local v20 = p14.Inner.Button.Inner.Icon
    local v21 = u3[p15.Name]
    local v22 = v21.Images.Normal
    if p15.Mythic or p15.Shiny then
        v22 = v21.Images[("%*%*"):format(p15.Mythic and "Mythic" or "", p15.Shiny and "Shiny" or "")]
    end
    v20.Image = v22 or u7.UnknownImage
    local v23 = p14.Inner.Button.Inner:FindFirstChild("Amount")
    if v23 then
        if p15.Amount == nil or not p16 then
            v23.Visible = false
        else
            v23.Text = u13(p15.Amount)
            v23.Visible = true
        end
    end
    local v24 = p14.Inner.Button:FindFirstChild("Limited")
    if v24 then
        v24.Visible = v19.Limited ~= nil
    end
    local v25 = p14.Inner.Button.Inner:FindFirstChild("Level")
    if v25 then
        local v26 = u4:GetLevelFromPet(p15)
        local v27 = p18 and "" or "Lvl "
        if v25.RichText then
            v25.Visible = v26 > 1
            v25.Text = ("<stroke color=\"#00295E\" joins=\"miter\" thickness=\"2\"><font size=\"18\"> %*</font>%*</stroke>"):format(v27, v26)
        else
            v25.Visible = true
            v25.Text = ("%*%*"):format(v27, v26)
        end
    end
    local v28 = u3[p15.Name].Rarity
    local v29 = v28 == "Legendary" and true or v28 == "Secret"
    if p14.Inner.Button:FindFirstChild("UIStroke") then
        if p15.Mythic then
            p14.Inner.Button.UIStroke.Color = Color3.new(1, 1, 1)
            u6.Cycle(p14.Inner.Button.UIStroke, "Mythic", {
                ["Speed"] = 0.75
            })
        else
            u6.None(p14.Inner.Button.UIStroke)
            p14.Inner.Button.UIStroke.Color = Color3.fromHex("#00295e")
        end
    end
    if p17 then
        u5:Remove(p14.Inner.Effect)
        u6.None(p14.Inner.Button)
        u6.None(p14.Inner.Button.Inner)
        p14.Inner.Button.BackgroundColor3 = Color3.new(0, 1, 0)
        p14.Inner.Button.Inner.BackgroundColor3 = Color3.fromRGB(169, 255, 156)
    elseif p15.Shiny then
        u5:Add(p14.Inner.Effect)
        u6.Cycle(p14.Inner.Button, "Shiny", {
            ["Speed"] = 0.5
        })
        u6.Cycle(p14.Inner.Button.Inner, "ShinyLight", {
            ["Speed"] = 0.5
        })
        p14.Inner.Button.BackgroundColor3 = Color3.new(1, 1, 1)
        p14.Inner.Button.Inner.BackgroundColor3 = Color3.new(1, 1, 1)
        u6.None(p14.Inner.Button.Inner.Icon)
    else
        if p15.Mythic then
            p14.Inner.Button.BackgroundColor3 = Color3.new(1, 1, 1)
            p14.Inner.Button.Inner.BackgroundColor3 = Color3.fromRGB(226, 167, 255)
            u6.Cycle(p14.Inner.Button, "PotionMythic", {
                ["Speed"] = 0.5
            })
        elseif v29 then
            p14.Inner.Button.BackgroundColor3 = Color3.new(1, 1, 1)
            u6.Shift(p14.Inner.Button, "Rainbow", {
                ["Speed"] = 0.5
            })
        else
            u6.None(p14.Inner.Button)
        end
        u5:Remove(p14.Inner.Effect)
        u6.None(p14.Inner.Button.Inner)
        if p15.Mythic then
            p14.Inner.Button.Inner.BackgroundColor3 = Color3.fromRGB(220, 129, 236)
        else
            p14.Inner.Button.Inner.BackgroundColor3 = Color3.fromRGB(27, 156, 236)
        end
        local v30 = p14.Inner.Button
        local v31
        if v28 == "Common" then
            v31 = Color3.fromRGB(41, 205, 255)
        elseif v28 == "Secret" then
            v31 = Color3.new(1, 1, 1)
        else
            v31 = u7.RarityColors[v28]
        end
        v30.BackgroundColor3 = v31
    end
    local u32 = p14.Inner.Background.UIGradient
    if p15.Mythic then
        u32.Color = u1.Assets.Gradients.Mythic.Color
    else
        u32.Color = u1.Assets.Gradients.Rainbow.Color
    end
    if not u32:GetAttribute("HasConnection") then
        u32.Destroying:Connect(function() --[[Anonymous function at line 153]]
            --[[
            Upvalues:
                [1] = u10
                [2] = u32
            --]]
            u10[u32] = nil
        end)
        u32:SetAttribute("HasConnection", true)
    end
    if v29 then
        u10[u32] = true
    else
        u10[u32] = nil
    end
    if p14.Inner.Button:FindFirstChildOfClass("UIStroke") then
        p14.Inner.Button.UIStroke.Color = p17 and Color3.fromRGB(39, 93, 29) or Color3.fromHex("#00295E")
    end
    if p17 then
        p14.Inner.Background.UIGradient.Enabled = false
        p14.Inner.Background.ImageColor3 = Color3.fromRGB(125, 255, 89)
    else
        p14.Inner.Background.ImageColor3 = Color3.new(1, 1, 1)
        p14.Inner.Background.UIGradient.Enabled = v29
    end
    local v33 = p14.Inner.Button.Inner:FindFirstChild("Locked")
    if v33 then
        v33.Visible = p15.Locked == true
    end
    local v34 = p14.Inner.Button.Inner:FindFirstChild("DisplayName")
    if v34 then
        if v28 == "Secret" then
            u6.Shift(v34, "Rainbow", {
                ["Speed"] = 0.5
            })
        else
            u6.None(v34)
        end
        v34.Text = p15.Name
        v34.Visible = v28 == "Secret"
    end
    p14.Inner.Button.Inner.Secret.Visible = v28 == "Secret"
end
v2.Heartbeat:Connect(function() --[[Anonymous function at line 199]]
    --[[
    Upvalues:
        [1] = u10
    --]]
    local v36 = os.clock() * 100 % 360
    for v37 in u10 do
        v37.Rotation = v36
    end
end)
return {
    ["set"] = v35,
    ["animatedGradients"] = u10
}