--devbgascension

-- Bytecode (Base64):
-- BgNWC0xvY2FsUGxheWVyDkdldFBsYXllcldvcmxkE1RyYW5zaXRpb25Eb2dneUljb24IZ2V0SW1hZ2UMQWJzb2x1dGVTaXplBVN0YXJ0BFNpemUBWAZPZmZzZXQBWQRtYXRoBGNlaWwGRmluaXNoA1RvcAdWaXNpYmxlBkJvdHRvbQVVRGltMgNuZXcETGVmdAVSaWdodAZNaWRkbGUGdXBkYXRlB0xvYWRpbmcESWNvbgVWYWx1ZQNzaW4IUG9zaXRpb24GQ3JlYXRlBFBsYXkRSW1hZ2VUcmFuc3BhcmVuY3kEdGFzawR3YWl0FkJhY2tncm91bmRUcmFuc3BhcmVuY3kISW5maW5pdHkFTGFiZWwQVGV4dFRyYW5zcGFyZW5jeQpmcm9tT2Zmc2V0BFRpbWUHQ2xlYW51cAdEZXN0cm95BUNsb25lBUltYWdlBFRleHQJUGxheWVyR3VpBlBhcmVudANtYXgISW5zdGFuY2ULTnVtYmVyVmFsdWUHVUlTY2FsZQdFbmFibGVkGEdldFByb3BlcnR5Q2hhbmdlZFNpZ25hbAdjb25uZWN0CUhlYXJ0YmVhdAdDb25uZWN0A0FkZAVDbG9zZQVkZWxheQ5QbGF5VHJhbnNpdGlvbgRnYW1lB1BsYXllcnMKR2V0U2VydmljZRFSZXBsaWNhdGVkU3RvcmFnZQxUd2VlblNlcnZpY2UKUnVuU2VydmljZQdyZXF1aXJlBlNoYXJlZAlGcmFtZXdvcmsHQ2xhc3NlcwRNYWlkBkNsaWVudANHdWkFVXRpbHMJVXRpbGl0aWVzB1NjYWxlVUkIR3VpRnJhbWUJV29ybGRVdGlsBERhdGEGV29ybGRzDVRyYW5zaXRpb25HdWkJVHdlZW5JbmZvBEVudW0LRWFzaW5nU3R5bGUEU2luZQRCYWNrD0Vhc2luZ0RpcmVjdGlvbgJJbgAHBAADAAAADPsAAAD7AwEATQIDMQAAAAC8AACOAQAAAJ8AAwL7AwIAhwIDAE0BAgcCAAAAggECAAMDAQMCAwMAHAQBGAAAAAAAAAABAAAAAB0AAAAACQABAAAAdPsBAABNAAFxAAAAAPsFAABNBAUcAQAAAE0DBC8CAAAATQIDeQMAAABNAQJwBAAAAE0FAHgGAAAAPgQFBT4FAQUmAwQFuwcDAqQCCQAAIHCAnwICAvsFAABNBAXfCgAAAE0DBJgLAAAAjAXs/7cFAgACAAAAqQQAAakEAQAwBAOADAAAAPsFAABNBAXfCgAAAE0DBBMNAAAAjAXs/7cFAgACAAAAqQQAAakEAQAwBAOADAAAAPsFAABNBAXfCgAAAE0DBJgLAAAApAQQAAA84ICMBQEAjAYAAIwHAABSCAIAnwQFAjAEAy8CAAAA+wUAAE0EBd8KAAAATQMEEw0AAACkBBAAADzggIwFAQCMBgAAjAcAAFIIAgCfBAUCMAQDLwIAAAD7BQAATQQF3woAAABNAwTGEQAAAKQEEAAAPOCAbwUSADkHAQA+BgcFUgcBAIwIAACfBAUCMAQDLwIAAAD7BQAATQQF3woAAABNAwQFEwAAAKQEEAAAPOCAbwUSADkHAQA+BgcFjAcAAFIIAQCfBAUCMAQDLwIAAAD7BQAATQQF3woAAABNAwQOFAAAAPsGAABNBQYcAQAAAE0EBS8CAAAAMAQDLwIAAACCAAEAFQMFAwYDBwMIAwkCAAAAAAAAAEADCgMLAwwEACBwgAMNAw4DDwMQAxEDEgQAPOCAAxMCAAAAAAAA4D8DFAMVADQWARgAAAABAAAAAAAAAAABAAAAAAAAAAABAAAAAAAAAAAAAAABAAAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAATUAAAAACwEDAAAGAwAABQECIvsDAABNAgNsAAAAAE0BAoABAAAADgEbAPsBAQBbAgACQwEBAt4BAQD7AwAATQIDbAAAAABNAQKuAwAAAKQCBgAAFECAbwMHAIwEAACMBQAA+wgCAE0HCOwIAAAA+woBALsYCgKkCQwAACyggJ8JAgJbCAkJQwYHCJ8CBQIwAgE7DQAAAIIAAQAOAxcDDwIAAAAAAAAUQAMYAxEDEgQAFECAAgAAAAAAAOA/AxkCAAAAAAAAJEADCwMaBAAsoIADGwBNAAEYAAAAAAAAAQAAAAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAk4AAAAACgAGAAAAYfsBAABNAAFsAAAAAKkBAQAwAQCAAQAAAPsAAQD7AgIA+wMDAOIEAwCMBQAAMAUE7AIAAAC8AACWBAAAAJ8ABQK8AADuBQAAAJ8AAgH7AAEA+wQAAE0DBGwAAAAATQIDrgYAAAD7AwMA4gQIAIwFAAAwBQSjBwAAALwAAJYEAAAAnwAFArwAAO4FAAAAnwACAaQACwAAKJCAbwEMAJ8AAgH7AAEA+wIEAPsDBQDiBA4AjAUAADAFBDoNAAAAvAAAlgQAAACfAAUCvAAA7gUAAACfAAIB+wABAPsEAABNAwRsAAAAAE0CAykPAAAA+wMFAOIECACMBQAAMAUEowcAAAC8AACWBAAAAJ8ABQK8AADuBQAAAJ8AAgH7AAEA+wQAAE0DBGwAAAAATQIDwxAAAAD7AwUA4gQTAKQFFgAAVECBbwYXAIwHAACMCAEAjAns/58FBQIwBQQ7EQAAAIwFAAAwBQQkEgAAALwAAJYEAAAAnwAFArwAAO4FAAAAnwACAYIAAQAYAxcDDwMZBQECAxwDHQMYAx4FAQcDHwMgBAAokIACAAAAAAAA0D8DIQUBDQMiAyMDGwMkBQIREgMRAxIEAFRAgQIAAAAAAADgPwBcAAEYAAAAAAAAAQAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAAAAQAAAAEAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAQAAAAAAAAAAAQAA/gAAAwAAAV0AAAAACgAMAAAAlAH7AAAAnwABAfsAAQD7BAIATQMEbAAAAABNAgPDAQAAAPsDAwDiBAQApAUHAAAYUIBvBggAjAcAAIwIAQCMCQAAnwUFAjAFBDsCAAAAjAUBADAFBCQDAAAAvAAAlgkAAACfAAUCvAAA7goAAACfAAIB+wABAPsCBAD7AwUA4gQMAIwFAQAwBQQ6CwAAALwAAJYJAAAAnwAFArwAAO4KAAAAnwACAfsAAQD7BAIATQMEbAAAAABNAgMpDQAAAPsDBQDiBA8AjAUBADAFBKMOAAAAvAAAlgkAAACfAAUCvAAA7goAAACfAAIB+wABAPsCBgD7AwMA4gQRAIwF1P4wBQTsEAAAALwAAJYJAAAAnwAFArwAAO4KAAAAnwACAfsAAQD7BAIATQMEbAAAAABNAgOuEgAAAPsDBwDiBA8AjAUBADAFBKMOAAAAvAAAlgkAAACfAAUCvAAA7goAAACfAAIBpAAVAABQMIFvARYAnwACAfsBAgBNAAEcFwAAAKkBAAAwAQCAGAAAAPsBAgBNAAHfGQAAAKkBAQAwAQCAGAAAAPsBAgBNAAEcFwAAAKQBBwAAGFCAnwEBAjABAC8aAAAA+wAIAJ8AAQH7AAEA+wMCAE0CAxwXAAAA+wMJAOIEGwCkBR0AAHBQgPsGCgD7BwoAnwUDAjAFBC8aAAAAvAAAlgkAAACfAAUCvAAA7goAAACfAAIBpAAVAABQMIH7AgkATQECSh4AAACfAAIB+wALALwAAPEfAAAAnwACAfsAAgC8AABQIAAAAJ8AAgGCAAEAIQMXAyMDGwMkBQICAwMRAxIEABhQgAIAAAAAAADgPwMcAx0DIQUBCwMiAx4FAQ4DGQUBEAMYAx8DIAQAUDCBAgAAAAAAANA/AwYDDwMNAwcFARoDJQQAcFCAAyYDJwMoAGoAARgAAAEAAAAAAAAAAQAAAAAAAAAAAQAA/gAAAwAAAgAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAAAAQAAAAIAAAAAAAEAAAAAAAEAAAAAAAAAAQABAAAAAAAAAAAAAAAAAAAAAAAAAQAAAAAAAQAAAAEAAAABawAAAAASAg8AAAcEAAAFAgMF1QH7AwAATQID7wAAAACfAgEC+wMBALwDAzoBAAAAnwMCAk0EA98CAAAAqQUAADAFBIADAAAATQQDHAQAAACpBQEAMAUEgAMAAABNBANsBQAAAKkFAAAwBQSAAwAAAE0FA2wFAAAATQQFrgYAAAD7BgIA+wkDAE0ICTEHAAAAvAYGjggAAACfBgMC+wgEAIcHCAZNBQcHCQAAADAFBKkKAAAATQUDbAUAAABNBAWuBgAAAIwFAQAwBQSjCwAAAE0FA2wFAAAATQQFwwwAAACMBQEAMAUEJA0AAABNBQNsBQAAAE0EBSkOAAAAjAUBADAFBKMLAAAATQUDbAUAAABNBAXDDAAAADAABPUPAAAA+wUFAE0EBZkQAAAAMAQDJBEAAABNBwNxEwAAAE0GB3kUAAAATQgDcRMAAABNBwh4FQAAAJ4SBgMHAAAApAUYAABcYIGfBQMCWwQFEk0FAxwEAAAApAYaAAAAkIGfBgECMAYFLxsAAADZBQAAEgADAPsGBgBNCANsBQAAAE0HCCkOAAAAnwYCA4wIAACkCR0AAADAgW8KHgCfCQICjArIADAKCewfAAAAjAoBADAKBjogAAAAUgoFAJ8KAQH7CgcATQwDbAUAAABNCwwrIQAAAJ8KAgGpCgEAMAoD8CIAAABNCgMcBAAAAG8MGwC8CgqUIwAAAJ8KAwJSDAUAvAoK5yQAAACfCgMB+w0IAE0MDf0lAAAA2Q4BABIAAwASAQj/EgAJALwMDMcmAAAAnwwDALwKAl8nAAAAnwoAAVIMAwC8CgJfJwAAAJ8KAwFSDAkAvAoCXycAAACfCgMBUgwHALwKAl8nAAAAnwoDAfsKCQC8CgpjKAAAAJ8KAgH7CgoATQwDHAQAAAD7DQsA4g4pAKQPKwAAqJCBUhAEAFIRBACfDwMCMA8OLxsAAAC8CgqWLAAAAJ8KBQK8CgruLQAAAJ8KAgGkCjAAALzggm8LMQDZDAIAEgADABICCgASAAkAEgIMABIABgASAg0AnwoDAaQKMAAAvOCC+w0LAE0MDUozAAAAlQsMMtkMAwASAAEAEgIKABIAAwASAg4AEgAGABICDQASAAkAEgIMABIABQASAgsAEgAEABIAAgCfCgMBwQgAAIIAAQA0AxIDKQMNAw8DBgMXAxgDAQMCAwMDKgMeAyMDJAMiAysDLAMtAgAAAAAAAPg/AwUDCAMKAwsDLgQAXGCBAxEEAACQgQMHAy8EAADAgQMwAxkDIQMxAzIDMwM0AzUDNgM3AzgFARsDJQQAqJCBAxwDHQMfAzkEALzgggKamZmZmZnJPwIAAAAAAADgPwMmBAECAwQhOgEYCAAAAAEAAAABAAAAAAEAAAAAAQAAAAABAAAA8wAAAAAAAAEAAAAMAAEAAAAAAAABAAAAAAAAAQAAAAAAAAEAAAAAAAEAAAAAAgAAAAAAAAAAAAAAAAABAAAAAAAAAgANAAAAAAABAQAAAAEAAAEAAAIAAQAAAAAAAgAAAQAAAAAAAAAAAAIAAAAAAAAAAAAAAAAHAAAAAQAAAAEAAAACAAAAAgAAAAAAAAAAAAAAAAAAAAAAAgAAAAAAAAAAAAAOAAAAAAAAAAAAAAAAAAAAAAAAABcAHQAAAAAUAAABAgCVAaMAAACkAAEAAAAAQG8CAgC8AAAWAwAAAJ8AAwKkAQEAAAAAQG8DBAC8AQEWAwAAAJ8BAwKkAgEAAAAAQG8EBQC8AgIWAwAAAJ8CAwKkAwEAAAAAQG8FBgC8AwMWAwAAAJ8DAwKkBAgAAABwQE0IARIJAAAATQcIHAoAAABNBgcYCwAAAE0FBnYMAAAAnwQCAqQFCAAAAHBATQkBTQ0AAABNCAkfDgAAAE0HCKEPAAAATQYHKRAAAACfBQICpAYIAAAAcEBNCwFNDQAAAE0KCxwKAAAATQkKtREAAABNCAkfDgAAAE0HCA4SAAAAnwYCAqQHCAAAAHBATQoBTQ0AAABNCQofDgAAAE0ICZUTAAAAnwcCAqQICAAAAHBATQsBEgkAAABNCguhDwAAAE0JCiAUAAAAnwgCAqQJCAAAAHBATQwBEgkAAABNCwzGFQAAAE0KC9gWAAAAnwkCAk0KADEXAAAATQsB5RgAAADGDAAAMAwLJBkAAACkDBwAAGyggW8NHQCkDiEAIHzgwZ8MAwKkDRwAAGyggW8OIgCkDyEAIHzgwZ8NAwKkDhwAAGyggW8PIgCkECQAI3zgwaQRJwAmlODBnw4EAqQPHAAAbKCBbxAoAKQRIQAgfODBnw8DAqQQHAAAbKCBbxEoAKQSIQAgfODBpBMnACaU4MGfEAQCwBEpABIACAASAAAAEgAJAMASKgASAAQAEgALABIACAASAAAAEgAJABIACgASAAUAEgAGABIAAwASAAcAEgACABIADAASAA0AEgAPABIADgCCEgIAKwM7BAAAAEADPAM9Az4DPwNAA0EEAABwQANCA0MDRANFA0YDRwNIAyIDSQNKA0sDTANNA04DAQNPAy0DUAMSBABsoIECAAAAAAAA6D8DUQNSA1MEIHzgwQKamZmZmZnZPwNUBCN84MEDVQNWBCaU4MECmpmZmZmZuT8GAAYFAgAFAQABGAACAAAAAAABAAAAAAABAAAAAAABAAAAAAACAAAAAAAAAAAAAAEAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAEAAAAAAAAAAAEAAAAAAAAAAAEAAAAAAAAAAAMAAQABAAACAAAAAAABAAAAAAABAAAAAAAAAAEAAAAAAAEAAAAAAAAABAAAAAUAAAAAAAAAAAAAAAAAAABjAQAAAAAGcP/wz+luFDVCO5pbnKwXZDVODdM/hIMT/RnoMq21iIJnfJ7sKd99sA==

local u1 = game:GetService("Players")
local v2 = game:GetService("ReplicatedStorage")
local u3 = game:GetService("TweenService")
local u4 = game:GetService("RunService")
local u5 = require(v2.Shared.Framework.Classes.Maid)
local u6 = require(v2.Client.Gui.Utils.Infinity)
local u7 = require(v2.Client.Framework.Utilities.Gui.ScaleUI)
local u8 = require(v2.Client.Gui.GuiFrame)
local u9 = require(v2.Shared.Utils.WorldUtil)
local u10 = require(v2.Shared.Data.Worlds)
local u11 = u1.LocalPlayer
local u12 = v2.TransitionGui
u12.Parent = nil
local u13 = TweenInfo.new(0.75, Enum.EasingStyle.Sine)
local u14 = TweenInfo.new(0.4, Enum.EasingStyle.Sine)
local u15 = TweenInfo.new(0.4, Enum.EasingStyle.Back, Enum.EasingDirection.In)
local u16 = TweenInfo.new(0.1, Enum.EasingStyle.Sine)
TweenInfo.new(0.1, Enum.EasingStyle.Sine, Enum.EasingDirection.In)
return function(p17, u18) --[[Function name: PlayTransition, line 33]]
    --[[
    Upvalues:
        [1] = u5
        [2] = u12
        [3] = u9
        [4] = u1
        [5] = u10
        [6] = u11
        [7] = u6
        [8] = u7
        [9] = u4
        [10] = u8
        [11] = u3
        [12] = u13
        [13] = u14
        [14] = u16
        [15] = u15
    --]]
    local u19 = u5.new()
    local u20 = u12:Clone()
    u20.Finish.Visible = false
    u20.Start.Visible = true
    u20.Loading.Visible = false
    u20.Loading.Icon.Image = u10[u9:GetPlayerWorld(u1.LocalPlayer)].TransitionDoggyIcon
    u20.Loading.Icon.ImageTransparency = 1
    u20.Loading.Label.TextTransparency = 1
    u20.Loading.Infinity.ImageTransparency = 1
    u20.Loading.Label.Text = p17
    u20.Parent = u11.PlayerGui
    local v21 = u20.AbsoluteSize.X
    local v22 = u20.AbsoluteSize.Y
    local u23 = math.max(v21, v22) * 1.5
    u20.Start.Size = UDim2.new()
    local function u28() --[[Anonymous function at line 52]]
        --[[
        Upvalues:
            [1] = u20
        --]]
        local v24 = u20.AbsoluteSize
        local v25 = u20.Start.Size.X.Offset
        local v26 = v24.Y / 2 - v25 / 2
        local v27 = math.ceil(v26)
        u20.Finish.Top.Visible = v27 > -20
        u20.Finish.Bottom.Visible = v27 > -20
        u20.Finish.Top.Size = UDim2.new(1, 0, 0, v27)
        u20.Finish.Bottom.Size = UDim2.new(1, 0, 0, v27)
        u20.Finish.Left.Size = UDim2.new(0.5, -v25 / 2, v25, 0)
        u20.Finish.Right.Size = UDim2.new(0.5, -v25 / 2, 0, v25)
        u20.Finish.Middle.Size = u20.Start.Size
    end
    local u29, v30 = u6(u20.Loading.Infinity)
    local u31 = 0
    local u32 = Instance.new("NumberValue")
    u32.Value = 200
    u29.BackgroundTransparency = 1
    u28()
    u7(u20.Loading.UIScale)
    u20.Enabled = true
    u20.Start:GetPropertyChangedSignal("Size"):connect(u28)
    u19:Add(u4.Heartbeat:Connect(function(p33) --[[Anonymous function at line 77]]
        --[[
        Upvalues:
            [1] = u20
            [2] = u31
            [3] = u32
        --]]
        if u20.Loading.Visible then
            u31 = u31 + p33 * 5
            local v34 = u31
            u20.Loading.Icon.Position = UDim2.new(0.5, 0, 0, u32.Value + math.sin(v34) * 10)
        end
    end))
    u19:Add(u20)
    u19:Add(u32)
    u19:Add(v30)
    u8:Close()
    u3:Create(u20.Start, u13, {
        ["Size"] = UDim2.fromOffset(u23, u23)
    }):Play()
    task.delay(0.2, function() --[[Anonymous function at line 92]]
        --[[
        Upvalues:
            [1] = u20
            [2] = u3
            [3] = u32
            [4] = u14
            [5] = u29
            [6] = u16
        --]]
        u20.Loading.Visible = true
        u3:Create(u32, u14, {
            ["Value"] = 0
        }):Play()
        u3:Create(u20.Loading.Icon, u14, {
            ["ImageTransparency"] = 0
        }):Play()
        task.wait(0.25)
        u3:Create(u29, u16, {
            ["BackgroundTransparency"] = 0
        }):Play()
        u3:Create(u20.Loading.Infinity, u16, {
            ["ImageTransparency"] = 0
        }):Play()
        u3:Create(u20.Loading.Label, u16, {
            ["Position"] = UDim2.new(0.5, 0, 1, -20),
            ["TextTransparency"] = 0
        }):Play()
    end)
    task.delay(u13.Time + 0.5, function() --[[Anonymous function at line 106]]
        --[[
        Upvalues:
            [1] = u18
            [2] = u3
            [3] = u20
            [4] = u15
            [5] = u29
            [6] = u16
            [7] = u32
            [8] = u14
            [9] = u28
            [10] = u13
            [11] = u23
            [12] = u19
        --]]
        u18()
        u3:Create(u20.Loading.Label, u15, {
            ["Position"] = UDim2.new(0.5, 0, 1, 0),
            ["TextTransparency"] = 1
        }):Play()
        u3:Create(u29, u16, {
            ["BackgroundTransparency"] = 1
        }):Play()
        u3:Create(u20.Loading.Infinity, u16, {
            ["ImageTransparency"] = 1
        }):Play()
        u3:Create(u32, u15, {
            ["Value"] = -300
        }):Play()
        u3:Create(u20.Loading.Icon, u14, {
            ["ImageTransparency"] = 1
        }):Play()
        task.wait(0.25)
        u20.Start.Visible = false
        u20.Finish.Visible = true
        u20.Start.Size = UDim2.new()
        u28()
        u3:Create(u20.Start, u13, {
            ["Size"] = UDim2.fromOffset(u23, u23)
        }):Play()
        task.wait(u13.Time)
        u19:Cleanup()
        u20:Destroy()
    end)
end