--devbgascension

-- Bytecode (Base64):
-- BgPxAQtHZXRDaGlsZHJlbgVGcmFtZQNJc0EESWNvbgpVcGRhdGVJY29uBE5vbmUFTGFiZWwHRGVzdHJveQNHZXQFSXRlbXMFQ2xvbmUFT3RoZXIETmFtZQVVRGltMglmcm9tU2NhbGUIUG9zaXRpb24GUGFyZW50BkNyZWF0ZQRQbGF5BHRhc2sFZGVsYXkEVGltZQpEaXNjb3ZlcmVkBEl0ZW0JR2V0UmFyaXR5BlNlY3JldAdTaG93QWxsBFR5cGUDUGV0Bkhhc0FueQNuZXcEU2l6ZQZDb2xvcjMLSW1hZ2VDb2xvcjMGQW1vdW50B1Zpc2libGUIQ3VycmVuY3kFdGFibGUFY2xvbmUVR2V0Q3VycmVuY3lNdWx0aXBsaWVyBG1hdGgEY2VpbAlMZWdlbmRhcnkFQ3ljbGUHUmFpbmJvdwVTcGVlZAxSYXJpdHlDb2xvcnMKVGV4dENvbG9yMwtMYXlvdXRPcmRlcgZDaGFuY2UEVGV4dAxGb3JtYXRBbW91bnQCb3MFY2xvY2sEUGFnZQclKiAvICUqBmZvcm1hdA5yZW5kZXJJdGVtUGFnZQpEaXNjb25uZWN0BmNyZWF0ZRJHZXRUZXh0Qm91bmRzQXN5bmMBWQpUZXh0Qm91bmRzB1VJU2NhbGUFU2NhbGUHUGFkZGluZwRMaW5lDVRleHRBY2Nlc3NvcnkJQWNjZXNzb3J5BnR5cGVvZgZzdHJpbmcFSW1hZ2UIVGV4dFNpemUKZnJvbU9mZnNldAlVSVBhZGRpbmcEVURpbQxQYWRkaW5nUmlnaHQERm9udAdWZWN0b3IyBVdpZHRoC0dldFRleHRTaXplAVgDQmFyAAhQcm9ncmVzcwRGaWxsBUFscGhhBkJ1dHRvbgRQb29sCVR3ZWVuSW5mbwRFbnVtC0Vhc2luZ1N0eWxlBkxpbmVhcghDYWxsYmFjawhJbnN0YW5jZRNHZXRUZXh0Qm91bmRzUGFyYW1zCEZvbnRGYWNlCFJpY2hUZXh0BWRlZmVyGEdldFByb3BlcnR5Q2hhbmdlZFNpZ25hbAdDb25uZWN0C21ha2VFbGVtZW50B2Zyb21IZXgHIzFiYWRlYwcjMjE3YWQ5ByNlMWYzZmYHIzhjY2RmZgVTaGlueQcjZWNkZTFiByNkOTdkMjAHI2ZmZmZlNAcjZjNmZjc0Bk15dGhpYwcjZWMyMGM3ByM4YTMwZDkHI2ZmZjdmZgcjZTVhMmZmEEJhY2tncm91bmRDb2xvcjMKQmFja2dyb3VuZAVUaXRsZQZCb3R0b20KVUlHcmFkaWVudA1Db2xvclNlcXVlbmNlFUNvbG9yU2VxdWVuY2VLZXlwb2ludAVDb2xvcgphcHBseVN0eWxlDkdldERlc2NlbmRhbnRzCUd1aU9iamVjdAdDb250ZW50DFVJTGlzdExheW91dBNBYnNvbHV0ZUNvbnRlbnRTaXplBkNhbmNlbAxUcmFuc3BhcmVuY3kFUXVpbnQWQmFja2dyb3VuZFRyYW5zcGFyZW5jeQVfbWFpZAdDbGVhbnVwCEVsZW1lbnRzCGZ1bmN0aW9uA0FkZARJbmZvBGZpbmQEZ3N1YgdNeXRoaWMgC1Jhcml0eU9yZGVyCVBlcm1hbmVudAhTdWJUaXRsZQZQb3Rpb24ITXl0aGljJSoHIFNlY3JldAZSYXJpdHkEVGllcgMgJSoEc2l6ZQdUaWVyICUqBEdsb3cRSW1hZ2VUcmFuc3BhcmVuY3kFU2hpZnQLUG90aW9uU2hpbnkFQXBwbHkGT2Zmc2V0BnVwZGF0ZQxJc0FuY2VzdG9yT2YHVG9vbHRpcAhfb3ZlcmxheQdPdmVybGF5DkZpbmRGaXJzdENoaWxkBUNvdmVyDERhaWx5UmV3YXJkcw9pc092ZXJsYXlBY3RpdmUGTW92ZVRvB0NoYW5nZWQERmlyZQRIaWRlBWFwcGx5BE1vZGUIS2V5Ym9hcmQHb25FbnRlcgdvbkxlYXZlCk1vdXNlRW50ZXIKTW91c2VMZWF2ZQlBY3RpdmF0ZWQHT25FbnRlcgJJRAVHZXRJZAlJc0VuYWJsZWQPQW5jZXN0cnlDaGFuZ2VkDHNldExhc3RFbnRlcgpQcm9jZXNzaW5nEEdldE1vdXNlTG9jYXRpb24MQWJzb2x1dGVTaXplEEFic29sdXRlUG9zaXRpb24LR2V0R3VpSW5zZXQDbWluA21heANUaXALQW5jaG9yUG9pbnQIUm90YXRpb24EZ2FtZRFSZXBsaWNhdGVkU3RvcmFnZQpHZXRTZXJ2aWNlB1BsYXllcnMLVGV4dFNlcnZpY2UKUnVuU2VydmljZRBVc2VySW5wdXRTZXJ2aWNlCkd1aVNlcnZpY2UMVHdlZW5TZXJ2aWNlB3JlcXVpcmUGU2hhcmVkBERhdGEIQnVpbGRlcnMOVG9vbHRpcEJ1aWxkZXIFVXRpbHMFU3RhdHMISXRlbVV0aWwJRnJhbWV3b3JrB0NsYXNzZXMETWFpZAZTaWduYWwMQW5pbWF0ZUNvbG9yBkNsaWVudAhTZXJ2aWNlcwlJbnB1dE1vZGUFVHlwZXMJQ29uc3RhbnRzCVV0aWxpdGllcwVldmVyeQlMb2NhbERhdGEEUGV0cwZTdHJpbmcNRm9ybWF0UGVyY2VudAlJbmRleFV0aWwSRm9ybWF0Um9tYW5OdW1lcmFsCVN0YXRzVXRpbAtMb2NhbFBsYXllcglQbGF5ZXJHdWkJU2NyZWVuR3VpBUlubmVyCFRlbXBsYXRlCkNoaWxkQWRkZWQNUmVuZGVyU3RlcHBlZAAdCAADAAAAHfsAAAC8AABoAAAAAJ8AAgRkABEAbwcBALwFBP4CAAAAnwUDAg4FDAD7BQEATQcErgMAAAC8BQUhBAAAAJ8FAwH7BgIATQUGPwUAAABNBgTDBgAAAJ8FAgFuAO7/AgAAAPsAAAC8AABQBwAAAJ8AAgGCAAEACAMBAwIDAwMEAwUDBgMHAwgAkwEAARgAAAAAAAEAAAAAAQAAAAAAAQAAAAAA/QAGAAAAAZQAAAAAFAERAAAArAL7AQAAvAEBfwAAAACfAQICKwEBAIIAAQAOAEQA+wMBAE0CAzgBAAAAvAICOgIAAACfAgICbwMDADADAroEAAAA+wQBAE0DBDgBAAAApAQHAAAYUIBvBQgAjAYBAJ8EAwIwBAM7CQAAAPsDAQAwAwIkCgAAAPsDAgD7BgEATQUGOAEAAAD7BgMA4gcLAKQIBwAAGFCAbwkMAIwKAQCfCAMCMAgHOwkAAAC8AwOWDQAAAJ8DBQK8AwPuDgAAAJ8DAgH7AwIAUgUCAPsGAwDiBwsApAgHAAAYUIBvCQ8AjAoBAJ8IAwIwCAc7CQAAALwDA5YNAAAAnwMFArwDA+4OAAAAnwMCAaQDEgAARACB+wUDAE0EBUoTAAAA2QUAABIAAgASAgQAEgIFAJ8DAwH7AwEATQIDOAEAAAC8AgJoFAAAAJ8CAgRkAhQAbwkVALwHBv4WAAAAnwcDAg4HDwD7BwQATQkGrhcAAAC8BwchGAAAAJ8HAwH7CAUATQcIPxkAAABNCAbDGgAAAJ8HAgG8BwZQGwAAAJ8HAgFuAuv/AgAAAE0CAW0cAAAA+wgGAHgHCB1bBgcelQUGHfsGBgBbAwYejAQBAKgDngD7BwcAhwYHBQ4GmwD7BwQATQkGyh8AAAC8BwclIAAAAJ8HAwLwBwUAIQAAgPsJCABNCAmMIgAAAA4IjgD7CAkAvAgIOgIAAACfCAICTQkGyh8AAABNCgkRIwAAAPAKNQAkAACATQoJugQAAAD7DAoAhwsMCvsMCwBSDgEAUg8KALwMDC0lAAAAnwwEAisMAwD7DQgATQwNjCIAAAArDAIAjA32/2UAAQCMDQAATQ4IrhcAAACkDycAAJhQgIwQAQBSEQ0AjBIBAFITDQCfDwUCMA8OLygAAABNDwiuFwAAAE0OD8MaAAAADgwHAKQPKgAAmJCCjBABAIwRAQCMEgEAnw8EAisPAwCkDyoAAJiQgp8PAQIwDw4AKwAAAE0OCCssAAAAqQ8AADAPDoAtAAAAZQAaAE0KCREjAAAA8AoXAC4AAICkCjEAAMDwglILCQCfCgICTQ0KKywAAAD7DgwAUhABAE0RCgkuAAAAqRIBALwODocyAAAAnw4FAgkMDQ67BwwCpAs1AADQMIOfCwICMAsKKywAAABSCQoA8AcDADYAAADwBw0AIQAAgPsLBQBNCgt5NwAAAE0LCMMaAAAAbww4AOINOgBvDjsAMA4NLDkAAACfCgQBZQAIAE0KCMMaAAAA+w0NAE0MDRQ8AAAAhwsMBzALCnM9AAAAMAUIAD4AAABNCgjDGgAAAPsLDgBNDAaMPwAAAKkNAQCfCwMCMAsK9UAAAAD7CwEATQoLOAEAAAAwCggkCgAAAPsKBABNDAiuFwAAAFINCQC8CgohGAAAAJ8KBAH7CgQATQwIKywAAABSDQkAvAoK9UEAAACfCgQBiwNi/6QDRAAADCGEnwMBAt4DDwD7BAEATQMElkUAAABvBUYA+wcGAPsIEAC8BQWNRwAAAJ8FBAJSBAUAMAQD9UAAAAD7BAEATQMElkUAAAD7BRAAjAYBALcGAgAFAAAAqQQAAakEAQAwBAOALQAAAIIAAQBIAwkDCgMLAwwDDQMOAw8EABhQgAIAAAAAAAD4PwMQAxEFAQkCAAAAAAAA4D8DEgMTAgAAAAAAAPi/AxQDFQQARACBAxYDAQMCAwMDBAMFAwYDBwMIAxcCAAAAAAAA8D8CAAAAAAAAGEADGAMZAxoDGwMcAx0DHgMfBACYUIADIAMhBACYkIIDIgMjAyQDJQMmAycEAMDwggMoAykDKgQA0DCDAysDLAMtAy4FATkCmpmZmZmZ2T8DLwMwAzEDMgMzAzQDNQM2BAAMIYQDNwM4AzkBAIYBOgEYAAAAAAEBAwEAAAAAAAEAAAEAAAAAAAAAAAABAAABAAAAAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAABAAAAAAAAAAAACgAAAAAAAAEAAAAAAQAAAAAAAQAAAAAAAQAA/AAIAAEAAAAAAAAAAQABBAAAAAAAAQAAAAAABAAAAAEAAQAAAAEAAQABAAAAAAAAAAAAAQAAAAEAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAABAAAAAAABAAAAAQAAAAEAAAAAAAAAAAAAAAAAAAAAAQMAAAABAAAAAAAAAAAAAAACAAAAAAAAAAMAAQAAAAAAAAAAAQAAAAABAAAAAAAAAQAAAAAAANsnAAAAAQAAAAAAAAAAAAAAAQAAAAAAAAAAAAABhwAAAAADAAQAAAAZ+wAAAIwBAQBgARUAAAAAAKQBAgAABACAnwEBAvsCAQAmAAECbwEDAGABDQAAAAAA+wACAJUAAATeAAIA+wACAPsBAABgAQMAAAAAAIwAAQDeAAIA+wADAKkBAQCfAAIBggABAAUDNQM2BAAEAIACAAAAAAAABEACAAAAAAAA8D8A0wEAARgAAAAAAAAAAAAAAAABAAABAAAAAQACAAAC1AAAAAAIAAQAAAAi+wEAAE0AATgAAAAAvAAAaAEAAACfAAIEZAAUAG8HAgC8BQT+AwAAAJ8FAwIOBQ8A+wUBAE0HBK4EAAAAvAUFIQUAAACfBQMB+wYCAE0FBj8GAAAATQYEwwcAAACfBQIBvAUEUAgAAACfBQIBbgDr/wIAAAD7AAMAvAAAGgkAAACfAAIBggABAAoDCgMBAwIDAwMEAwUDBgMHAwgDOwDjAQABGAAAAAAAAAABAAAAAAEAAAAAAAEAAAAAAAEAAPwABwAAAAHkAAAAAAsACQAAADv7AAAAbwEAANkCAAASAgEAEgICABICAwASAgQAnwADAvsCAQCMAwEAYAMDAAIAAACMARQAZQABAIwBAAD7AgUApAMDAAAIEICMBAEAjAXs/4wGAAD7CgYAHAkKAIwKAwB9CQMACgAAAIwIRgBlAAEAjAiWAEMHAQifAwUCMAMCLwQAAAD7AwUATQIDOAUAAACkAwMAAAgQgIwEAQCMBQAAjAYBAPsIAQCMCQEAYAkDAAgAAACMB+z/ZQABAIwHAACfAwUCMAMCLwQAAAD7AgQAnwIBAdkCAQASAgUAEgIHABICCAASAAAAggICAAYCAAAAAAAA0D8DDgMfBAAIEIADIAMKAgID0gE8ARgAAAAAAAAAAAoAAAAAAAABAAAAAAAAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAAAAAAACAAIAAAAAANMAAAAABwADAAAAEfsAAAD7AgEAvAAA7gAAAACfAAMC+wECAKQCAwAACBCAjAMBAIwEAACMBQAATQYAeAQAAACfAgUCMAIBLwUAAACCAAEABgM9Aw4DHwQACBCAAz4DIACAAgABGAAAAAAAAQAAAAAAAAAAAAABAQEAAAAKAAIAAAAV+wAAAKQBAgAABACAjAIBAIwDAACMBAAA+wgAAE0HCKEDAAAATQYHeAQAAAD7CQEATQgJKwUAAABNBwiEBgAAAOwFBgefAQUCMAEALwcAAACCAAEACAMOAx8EAAQAgAM/Az4DQANBAyAAhQIAARgAAAAAAAAAAAAAAAAAAAAAAAAAAAEGAQAAAA4CEwAAAMYCTQIAEQAAAADwAhoAAQAAgPsCAAC8AgI6AgAAAJ8CAgJNAwLpAwAAAE0FAOkDAAAARwUCAAAAAICpBAABqQQBADAEA4AEAAAApAMHAAAYUICMBAEAjAUAAIwGAABNBwAvCAAAAJ8DBQIwAwIvCAAAAIICAgBNAgARAAAAAPACcgAJAACA+wIBALwCAjoCAAAAnwICAk0EACkKAAAAuywEAqQDDAAAALBAnwMCAvADCgANAACATQQCrg4AAABNAwTDDwAAAE0EACkKAAAAMAQDqRAAAABlAAgA+wMCAE0FAq4OAAAATQYAKQoAAAC8AwMhEQAAAJ8DBAFNBQAvCAAAAFsEBRK7BwQCpAMVAABQMIGfAwICpAQHAAAYUICMBQEAjAYAAIwHAABNCAAvCAAAAJ8EBQIwBAIvCAAAAE0EAsMPAAAAMAMEbhYAAABNBALDDwAAAE0FAPUXAAAAMAUE9RcAAABNBAKuDgAAAKQFGQAAYFCATQYALwgAAABNBwAvCAAAAJ8FAwIwBQQvCAAAAE0EAmIaAAAApAUcAAAYsIGMBgAATQkALwgAAAA+CAkduwcIAqQHFQAAUDCBnwcCAp8FAwIwBQS+HgAAAPsEAwBNBgD1FwAAAFIHAwBNCQLDDwAAAE0ICTkfAAAApAkhAAAYAIJNCwHXIwAAAHgKCyJSCwMAnwkDALwEBLokAAAAnwQAAk0FAsMPAAAApAYHAAAYUICMBwAATQgEeSUAAACMCQEAjAoAAJ8GBQIwBgUvCAAAAIICAgBNAgARAAAAAPACKAAmAACA+wIEALwCAjoCAAAAnwICAk0DAsMPAAAATQUA9RcAAACQBAUnMAQD9RcAAABNBALkKAAAAE0DBG8pAAAApAQHAAAYUIBNBQAWKgAAAIwGAACMBwEAjAgGAJ8EBQIwBAMvCAAAAE0EAuQoAAAATQMEbykAAABNBQAWKgAAAG8GKwC3BgIABQAAAKkEAAGpBAEAMAQDgAQAAACCAgIATQIAEQAAAADwAgYALAAAgPsCBQC8AgI6AgAAAJ8CAgKCAgIATQIAEQAAAADwAkcALQAAgPsCBgC8AgI6AgAAAJ8CAgKMAwEATQQAQi0AAACMBQAAUgYEAMYHAADGCAAAZAYJAPsLAgBNDQrKLgAAALwLCyUvAAAAnwsDAvALAgAwAAAAlQUFMW4G9v8CAAAAPgcFMrsHBwKkBhUAAFAwgZ8GAgKkBzUAANAwg58HAQKkCDcAABhgg28JOACkCjwAO+iQw58IAwLZCQAAEgIHABIAAgASAggAEgAIABICAgASAgkAEgED/xIABAASAAAAEgIKABICCwASAgwAEgINABICDgASAg8AEgEH/xIABgDZCgEAEgIQABIABgASAQf/EgED/xIACQASAAIAEgAEABICAgASAgkAMAoARj0AAADBAwAAggICAMEDAAD7AhEAvAICOgIAAACfAgICTQMA9RcAAAAwAwL1FwAAAE0DAC8IAAAAMAMCbhYAAACkAz8AABjgg28EQACfAwICTQQA9RcAAAAwBAP1FwAAAE0EAmFBAAAAMAQDOR8AAABNBAAvCAAAADAEAy8IAAAATQUB1yMAAAB4BAVCMAQD1yMAAACpBAEAMAQD0UMAAACkBEYAABRBhNkFAgASAgMAEgADABIAAgCfBAIBbwZHALwEApRIAAAAnwQDAtkGAwASAAIAEgISALwEBMdJAAAAnwQDAYICAgBKAxwDQgMLA0MDJAMOAx8EABhQgAMgA0QDRQNGBAAAsEADRwMEAwcDSAMFApqZmZmZmek/AykDKgQAUDCBA0kDMwNKBABgUIADSwNMBAAYsIECAAAAAAAABEADTQNOA08EABgAggIAAAAAAABEQANQA1EDUgNTA1QDVQNWA1cCexSuR+F6hD8DWANZAxgDGQMaAgAAAAAAAPA/AgAAAAAAABhAAzUDNgQA0DCDA1oEABhggwJmZmZmZmbWPwNbA1wDXQQ76JDDA14DXwQAGOCDA2ADYQIAAAAAAAA5QANiAxQDYwQAFEGEAz8DZANlBAEEBQZJZgEYAAAAAAEAAAABAAAAAAAAAAAAAQAAAAAAAAAAAAECAAAAAQAAAAEAAAAAAAAAAQAAAAAAAAAAAgAAAAAAAAADAAAAAAAAAQAAAAAAAAAAAAEAAAABAAAAAAABAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAIAAAAAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAICAAAAAgAAAAEAAAAAAAABAAAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAABAgAAAAEAAAAGAgAAAAEAAAACAgABAQAAAAEAAAAAAAAAAf4ABwAAAAABAAABAAAAAAABAAAAAAAAAAAAAAAAAAAAAABMAAAAAAAAAAAAHQACAAADAAAAAQAAAAEAAAACAAAAAQAAAAEAAAABAAAAAQAAAAABAAADAAAAAAAABQAAAAAAAAAAAARKAAAAAA0BAQAAAHGkAQIAAAQAgG8CAwCfAQICpAICAAAEAIBvAwQAnwICAqQDAgAABACAbwQFAJ8DAgKkBAIAAAQAgG8FBgCfBAIC8AAWAAcAAICkBQIAAAQAgG8GCACfBQICUgEFAKQFAgAABACAbwYJAJ8FAgJSAgUApAUCAAAEAIBvBgoAnwUCAlIDBQCkBQIAAAQAgG8GCwCfBQICUgQFAGUAFgDwABUADAAAgKQFAgAABACAbwYNAJ8FAgJSAQUApAUCAAAEAIBvBg4AnwUCAlICBQCkBQIAAAQAgG8GDwCfBQICUgMFAKQFAgAABACAbwYQAJ8FAgJSBAUA+wUAADADBZ8RAAAA+wYAAE0FBu0SAAAAMAQFABMAAAD7BwAATQYHuhQAAABNBQbtEgAAADAEBQATAAAA+wcAAE0GB7oUAAAATQUGExUAAAAwAgWfEQAAAPsHAABNBge6FAAAAE0FBvoWAAAApAYZAABgcIH/BwAAAwAAAKQIGwAAYKCBjAkAAFIKAgCfCAMCpAkbAABgoIFvChwAUgsCAJ8JAwKkChsAAGCggYwLAQBSDAEAnwoDAMUHCAABAAAAnwYCAjAGBaQdAAAAggABAB4DIQNnBAAEAIADaANpA2oDawNsA20DbgNvA3ADcQNyA3MDdAN1A3YDdwMiA3gDeQN6A3sDHwQAYHCBA3wEAGCggQIbL90kBoHFPwN9AI4CfgEYAAAAAAEAAAABAAAAAQAAAAIAAQAAAAABAAAAAAEAAAAAAQAAAAAAAgABAAAAAAEAAAAAAQAAAAABAAAAAAMAAAEAAAAAAQAAAAAAAAEAAAAAAAABAAAAAAAAAAABAAAAAAEAAAAAAQAAAAAAAP0AAAUPAQAAAAgAAgAAABb7AAAAvAAARwAAAACfAAIEZAAKAG8HAQC8BQT+AgAAAJ8FAwIOBQUA+wYBAE0FBj8DAAAA+wYAAJ8FAgFuAPX/AgAAAPsAAAC8AABQBAAAAJ8AAgGCAAEABQN/A4ABAwMDBgMIAM4CAAEYAAAAAAABAAAAAAEAAAAA/gAFAAAAAU8BAAAADAADAAAAMvsDAABNAgO6AAAAAE0BAoABAAAADgECAIwARgBlAAEAjAAAAPsCAABNAQK+AgAAAKQCBQAAEDCAjAMBAIwE2P+MBQEA9QYGAJ8CBQIwAgEvBwAAAPsCAABNAQIkCAAAAKQCCgAAJDCA+wQBAE0DBNcLAAAA+wsAAE0KC74CAAAATQkKNA0AAABNCAnGDgAAAE0HCHgPAAAA+woCAE0JCisQAAAATQgJhBEAAADsBgcIlQUGDEMEBQCfAgMCMAIBLwcAAACCAAEAEgN4AyQDgQEDDgMfBAAQMIACAAAAAAAANMADIAMRA0oEACQwgANQAgAAAAAAADRAA4IBA4MBAz4DQANBAN4DAAEYAAAAAAAAAAAAAQAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAHfAQAAABYDDwAAAKsG+wMAAA4DBQArAgQA+wMAALwDA6EAAAAAnwMCASsCKAD7AwEAjAQAADAEA9kBAAAA+wMBAKQEBAAADCCAbwUFAG8GBgCMBwEAnwQEAjAEA58HAAAA+wMCAPsFAQCkBgkAAAyAgG8HCgCkCA4ADTCwwJ8GAwLiBxAApAgEAAAMIICMCQEAjAoBAIwLAQCfCAQCMAgHnwcAAACMCAEAMAgHOg8AAAC8AwOWEQAAAJ8DBQK8AwPuEgAAAJ8DAgLeAwAATQMAwRMAAAC8AwPxFAAAAJ8DAgHeAQMATQMBIhUAAADGBAAAxgUAAGQDJwD7CAQAUgkHAFIKAQCfCAMCDggiAE0JB0YWAAAADgkQAFIKCQBSCwgAnwoCArssCgNSDAoApAsYAAAAcEGfCwIC8AsHABkAAIBNCwDBEwAAAFINCgC8CwtfGgAAAJ8LAwEwBggAGwAAAPsLBQBNCgu+HAAAADAKCCQdAAAATQoAwRMAAADZDAAAEgAIABICBgC8CgpfGgAAAJ8KAwFuA9j/AgAAAMYDAABNBAG6HgAAAA4EzwFNBQG6HgAAAE0EBXofAAAATQYBuh4AAABNBQbKIAAAAFIGBAAOBgUApAYjAACIEIJSBwQAbwgkAJ8GAwIOBgcApAcmAACUEIKQCAQnbwkoAG8KJwCfBwQCUgQHAPsJBwBNCAmYKQAAAIcHCAQrBwQA8AQCACoAAACpBwABqQcBAA4HGADwBAMAKwAAAPAEFQAqAACAbwMrAPsJBgBNCAl5LAAAAPsNBQBNDA26HgAAAE0LDL4cAAAATQoLeh8AAABNCQqpLQAAAG8KLgDiCzAAbwwxADAMCywvAAAAnwgEAWUARADwBCAAMgAAgG8DMgD7CQYATQgJPzMAAAD7DQUATQwNuh4AAABNCwy+HAAAAE0KC3ofAAAATQkKqS0AAACfCAIB+wwFAE0LDLoeAAAATQoLvhwAAABNCQp6HwAAAE0ICaktAAAA+wsHAE0KCxQ0AAAATQkKZzIAAAAwCQhzNQAAAGUAIwD7CQYATQgJPzMAAAD7DQUATQwNuh4AAABNCwy+HAAAAE0KC3ofAAAATQkKqS0AAACfCAIB+wwFAE0LDLoeAAAATQoLvhwAAABNCQp6HwAAAE0ICaktAAAA+wsHAE0KCxQ0AAAAhwkKBCsJBgCkCQQAAAwggIwKAQCMCwEAjAwBAJ8JBAIwCQhzNQAAAA4GAQBvAyQAKwdMAA4FSwD7CAgAUgoFALwICCU2AAAAnwgDAvAIAwArAAAA8AglADIAAID7DQUATQwNuh4AAABNCwy+HAAAAE0KC3ofAAAATQkKwzcAAACkCgQAAAwggIwLAQCMDAEAjA0BAJ8KBAIwCglzNQAAAPsKBgBNCQp5LAAAAPsOBQBNDQ66HgAAAE0MDb4cAAAATQsMeh8AAABNCgvDNwAAAG8LLgDiDDAAbw0xADANDCwvAAAAnwkEAWUAHAD7CgYATQkKPzMAAAD7DgUATQ0Ouh4AAABNDA2+HAAAAE0LDHofAAAATQoLwzcAAACfCQIB+w0FAE0MDboeAAAATQsMvhwAAABNCgt6HwAAAE0JCsM3AAAA+wwHAE0LDBQ0AAAAhwoLCDAKCXM1AAAAUgMIAGUADQD7CQYATQgJPzMAAAD7DQUATQwNuh4AAABNCwy+HAAAAE0KC3ofAAAATQkKwzcAAACfCAIBKwUFAE0JAboeAAAATQgJqTgAAAAOCFAAjAic/w4FBQBNCQUROQAAAPAJAgA6AACAjAim/00KAboeAAAATQkKqTgAAAAOCScA+wkIAPsOBQBNDQ66HgAAAE0MDb4cAAAATQsMrjsAAAC8CQkhPAAAAJ8JAwH7DQUATQwNuh4AAABNCwy+HAAAAE0KC647AAAATQkKwzcAAABNCwG6HgAAAE0KC6k4AAAAMAoJqTgAAAD7DQUATQwNuh4AAABNCwy+HAAAAE0KC647AAAATQkKwzcAAACpCgEAMAoJgD0AAABlAAwA+wkIAPsOBQBNDQ66HgAAAE0MDb4cAAAATQsMrjsAAABSDAUAvAkJITwAAACfCQQB+wwFAE0LDLoeAAAATQoLvhwAAABNCQp6HwAAAKQKPwAADOCDjAsBAFIMCACMDQEAjA7x/58KBQIwCgkvQAAAAGUAGwD7CwUATQoLuh4AAABNCQq+HAAAAE0ICXofAAAApAk/AAAM4IOMCgEAjAv2/4wMAQCMDfH/nwkFAjAJCC9AAAAA+wgIAPsNBQBNDA26HgAAAE0LDL4cAAAATQoLrjsAAAC8CAghPAAAAJ8IAwEOBQgATQgFETkAAADwCAUAQQAAgE0IBbRCAAAADggBAG8DQgAOBigA+wwFAE0LDLoeAAAATQoLvhwAAABNCQp6HwAAAE0ICaktAAAAbwpDAPAEAwAyAACAbwxEAGUAAQBvDCcAvAoKjUUAAACfCgMCUgkKADAJCPVGAAAA+wkGAE0ICXksAAAA+w0FAE0MDboeAAAATQsMvhwAAABNCgt6HwAAAE0JCqktAAAAbwokAOILMABvDAoAMAwLLC8AAACfCAQBZQAMAPsMBQBNCwy6HgAAAE0KC74cAAAATQkKeh8AAABNCAmpLQAAAJAJBCcwCQj1RgAAAA4FNgBNCAUROQAAAPAIMwBBAACA+wkJAE0KBbpHAAAAhwgJCk0JCPJIAAAA8AkrACsAAIBNCgiLSgAAAJAJCkmMCgEAYAolAAkAAAD7DgUATQ0Ouh4AAABNDA2+HAAAAE0LDHofAAAATQoLqS0AAABNDAr1RgAAAG8OSwD7EQoATRAR7wMAAACfEAECjBISALwQEA9MAAAAnxADAm8STQD7FAsAUhUJAJ8UAgK8EhKNRQAAAJ8SAwJSERIAnxACArwODo1FAAAAnw4DAlINDgBzCwwNMAsK9UYAAAD7DAUATQsMuh4AAABNCgu+HAAAAE0JCnofAAAATQgJwzcAAABNCgG6HgAAAE0JCvVGAAAAMAkI9UYAAABlAA0A+wUGAE0EBT8zAAAA+wkFAE0ICboeAAAATQcIvhwAAABNBgd6HwAAAE0FBqktAAAAnwQCAfADKAAkAACA+wQMAG8FJACfBAIB+wYFAE0FBiQdAAAATQQFIU4AAACMBQAAMAUEo08AAAD7BgUATQUGJB0AAABNBAUhTgAAAKQFBAAADCCAjAYBAIwHAQCMCAEAnwUEAjAFBABQAAAA+wUGAE0EBXksAAAA+wcFAE0GByQdAAAATQUGIU4AAABvBiQA4gcwAG8IUQAwCAcsLwAAAJ8EBAFlAJYA8AMoAEIAAID7BAwAbwVCAJ8EAgH7BgUATQUGJB0AAABNBAUhTgAAAIwFAAAwBQSjTwAAAPsGBQBNBQYkHQAAAE0EBSFOAAAApAUEAAAMIICMBgEAjAcBAIwIAQCfBQQCMAUEAFAAAAD7BQYATQQFbFIAAAD7BwUATQYHJB0AAABNBQYhTgAAAG8GUwDiBzAAbwgKADAIBywvAAAAnwQEAWUAbQDwAygAKwAAgPsEDABvBTMAnwQCAfsGBQBNBQYkHQAAAE0EBSFOAAAAjAUAADAFBKNPAAAA+wYFAE0FBiQdAAAATQQFIU4AAACkBQQAAAwggIwGAQCMBwEAjAgBAJ8FBAIwBQQAUAAAAPsFBgBNBAVsUgAAAPsHBQBNBgckHQAAAE0FBiFOAAAAbwYuAOIHMABvCDEAMAgHLC8AAACfBAQBZQBEAPADJQAyAACA+wYFAE0FBiQdAAAATQQFIU4AAACMBQAAMAUEo08AAAD7BgUATQUGJB0AAABNBAUhTgAAAKQFBAAADCCAjAYBAIwHAQCMCAEAnwUEAjAFBABQAAAA+wUGAE0EBXksAAAA+wcFAE0GByQdAAAATQUGIU4AAABvBjIA4gcwAG8IUQAwCAcsLwAAAJ8EBAFlABsA+wUGAE0EBT8zAAAA+wcFAE0GByQdAAAATQUGIU4AAACfBAIB+wYFAE0FBiQdAAAATQQFIU4AAACkBQQAAAwggJ8FAQIwBQQAUAAAAPsGBQBNBQYkHQAAAE0EBSFOAAAAbwUKADAFBKNPAAAA+wQMAG8FMwCfBAIBKwIDAPsEDQDGBQAAnwQCAfsFBQBNBAW6HgAAAE0GAboeAAAARwYCAAAAAICpBQABqQUBADAFBIA9AAAA+wUFAE0EBSQdAAAApAVVAABQ4YNNBgHXVgAAAIwH6AOfBQMCMAUEL0AAAAD7BQUATQQFJB0AAACpBQEAMAUEgD0AAACkBFkAAGBxhdkFAQASAgUAEgABABICDgCfBAIBggABAFoDhAEDhQEDIQMfBAAMIIACtd/aiZKQwD8Cg1K0ci8w4D8DdgNaBAAMgIACAAAAAAAA4D8DWwNcA4YBBA0wsMADhwEFAgcPAxIDEwOIAQOJAQOKAQNeA0YEAABwQQOLAQOMAQMxA4EBAxEDeAONAQMYA0cDjgEEAIgQggNxA48BBACUEIIDVAOQAQORAQOSAQMrAywDkwEDLQMuBQEvApqZmZmZmdk/AxoDBgMvAzADGQMHA0gDHAOUAQMEAwUDJAMOBAAM4IMDIAMdA2wDlQEDlgEDOQMzAw0DlwECAAAAAAAA8D8DmAEDmQEDmgEDmwEDnAEDnQEDIgLNzMzMzMzkPwOeAQOfAQNKBABQ4YMDUAMUA2MEAGBxhQIJCq0CoAEBGAAAAAEAAAADAQAAAAEAAAAAAAAAAAEAAAAAAAAAAAEAAAAAAAAAAQAA/gAAAwAA/QYAAAAAAQIAAAAAAQAAAAEEAAEBAAABAAAAAAAAAQAAAAAABAABAAAAAAEAAAAAAAAA8AAaAQAAAQAAAAEAAAACAAAAAAAAAQEAAAAAAAADAAAAAAAAAAABAAAAAAEBAAAAAAAAAAAAAAAAAAAAAAAAAgABAQAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAAAAwAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAAAAAAAAAADAQMAAQAAAAABAAAAAQAAAAAAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAAAAAAAAAgAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAIAAgAAAAAAAAAAAAAAAAMAAAAAAAEBAAAAAAECAAAAAAEAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAIAAAAAAAAAAAAAAAIAAAAAAAAAAAAAAAAAAAAAAwAAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAwAAAAABAAABBwEAAAAAAAAAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAAAAAACAAAAAAAAAAAAAAADAAAAAAEAAAABAAAAAQAAAQAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABgAAAAAAAAAAAAAAAAAAAAIAAAAAAAAAAAAAAAAEAAEAAAEAAAAAAAAAAQAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAIAAQAAAQAAAAAAAAABAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAgABAAABAAAAAAAAAAEAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAAACAAEAAAAAAAAAAQAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAIAAAAAAAAAAAEAAAAAAAAAAAABAAAAAAAAAAIAAAMCAAADAAAAAAAAAAAAAAEAAAAAAAAAAAAAAQAAAAAAAgAAAAAAAAUuAQAAAAwAAgAAADj7AwAATQIDugAAAABNAQKAAQAAAA4BAgCMAEYAZQABAIwAAAD7AgAATQECvgIAAACkAgUAABAwgIwDAQCMBNj/jAUBAPUGBgCfAgUCMAIBLwcAAAD7AgAATQECJAgAAACkAgoAACQwgPsHAABNBgckCAAAAE0FBi8HAAAATQQFeQsAAABNAwRwDAAAAPsLAABNCgu+AgAAAE0JCjQOAAAATQgJxg8AAABNBwh4EAAAAPsKAQBNCQorEQAAAE0ICYQSAAAA7AYHCJUFBg1DBAUAnwIDAjACAS8HAAAAggABABMDeAMkA4EBAw4DHwQAEDCAAgAAAAAAADTAAyADEQNKBAAkMIADUgOhAQIAAAAAAAA0QAOCAQODAQM+A0ADQQDnA6IBARgAAAAAAAAAAAABAAAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAegBAAAACgEBAAAGAwAABQEHPPsBAAC8AQFoAAAAAJ8BAgRkATMAbwgBALwGBf4CAAAAnwYDAg4GLgBSCAAAvAYFeQMAAACfBgMCKwYpAE0GBboEAAAA8AYmAAUAAABNBgW6BAAAAPAGIgAGAAAATQYFLwcAAACkBwoAACSAgIwIAQCMCQEAnwcDApoGGQAHAAAATQYFgAsAAAAOBhUAbwgMALwGBQMNAAAAnwYDAisGDgBvCA4AvAYFAw0AAACfBgMCKwYJAG8IDwC8BgUDDQAAAJ8GAwIrBgQATQYFugQAAADwBgMAEAAAgKkGAQCCBgIAbgHM/wIAAACpAQAAggECABEDAQOAAQMDA6MBAw0DpAEDpQEDIAMOAw8EACSAgAMkA6YBA6cBAwIDqAEDqQEA8wOqAQEYAAAAAAABAAAAAAEAAAAAAQAAAAEAAAAEAAAAAAAAAAAAAAABAAAAAAEAAAAAAQAAAAABAAAAAgDyABIA9AEAAAAEAAYAAAAd+wAAAJ8AAQLeAAEADgAUAPsBAgBSAwAAvAEBLwAAAACfAQMB+wECALwBAXcBAAAAnwECAfsBAwD7AgQAnwECAfsCBQBNAQKFAgAAAPsDBAC8AQHdAwAAAJ8BAwGCAAEA+wEFALwBAc8EAAAAnwECAYIAAQAFA6ABA6sBA6wBA60BA64BAI0ErwEBGAAAAQIBAAAAAAIAAAABAAACAAAAAAAAAAIAAAACDgIAAAACAAQAAAAN+wAAAPsBAQCfAAICDgABAIIAAQD7AQIATQABDQAAAADwAAMAAQAAgPsAAwCfAAEBggABAAIDsAEDsQEAnQSyAQEYAAAAAAECAAAAAAEAAh4CAAAAAgAEAAAADvsAAAD7AQEAmgAKAAEAAAD7AQIATQABDQAAAADwAAUAAQAAgPsAAwC8AADPAgAAAJ8AAgGCAAEAAwOwAQOxAQOuAQCmBLMBARgAAAAAAAAAAAABAAAAAicCAAAAAgAFAAAAEvsBAABNAAENAAAAAPAAAgABAACAggABAPsAAQD7AQIAmgAGAAEAAAD7AAMAvAAAzwIAAACfAAIBggABAPsABACfAAEBggABAAMDsAEDsQEDrgEArwQAARgAAAAAAAECAAAAAQAAAAACAAIwAgAAAAkDBgAAACnZAwAAEgACABICAAASAgEAEgICABIAAQASAAAA2QQBABICAwASAAEAEgIEABIAAwDZBQIAEgIFABIAAQASAgQAEgAAAE0GARQAAAAAUggEALwGBscBAAAAnwYDAU0GAd0CAAAAUggFALwGBscBAAAAnwYDAU0GAR4DAAAA2QgDABICBAASAgUAEgABABIAAAASAAMAvAYGxwEAAACfBgMBggABAAQDtAEDZQO1AQO2AQQODxARjAS3AQEYAAAAAAAAABAAAAAACQAAAAAGAAAAAAABAAAAAAACAAAAAAAAAAAAAAoNAgAAAAMBAwAAABb7AQAAxgIAAJ8BAgHGAQAA3gEBAPsCAgBNAQIkAAAAAKkCAAAwAgGAAQAAAE0BAIUCAAAAvAEB3QMAAACfAQIBTQEAwQQAAAC8AQHxBQAAAJ8BAgGCAAEABgMRAyQDrAEDrQEDiAEDiQEAvASuAQEYAAAAAQACAAAAAAABAAAAAAEAAAAAAT4CAAAAAwEBAAAACPsCAAAOAgQA+wIAAE0BAqwAAAAAggECAMYBAACCAQIAAQO4AQDGBLkBARgAAAAAAAAAAEcCAAAAAwEBAAAABvsCAABHAgIAAAAAgKkBAAGpAQEAggECAAAAygS6AQEYAAAAAAAASwIAAAAEAgEAAAAHRwEFAAAAAID7AgAAvAICzwAAAACfAgIBggABAAEDrgEA2gQAARgAAAEAAAACWwIAAAAEAQMAAAYDAAAFAYcT3gAAAPsBAQAOAQYA+wEBALwBARoAAAAAnwECAcYBAADeAQEADgAIAE0BAIsBAAAAwAMCABICAgC8AQHHAwAAAJ8BAwLeAQEAggABAAQDOwO7AQYWA2UBFtMEvAEBGAABAAEAAAABAAIBAAAAAAAAAAZUAgAAAAMBAQAAAAlNAQC6AAAAAPABBQABAACA+wEAALwBAc8CAAAAnwECAYIAAQADAw0DvQEDrgEA5AQAARgAAAAAAQAAAAJlAgAAABEBBwAAAKAB+wIAAE0BAoQAAAAA+wMBALwDAwYBAAAAnwMCAuwCAwH7BgIATQUGcQIAAADsBAUBpAUFAAAQMICMBgMAjAcDAJ8FAwImAwQF+wYDAE0FBnECAAAA7AQFAU0GAnkHAAAAlQUGBk0HAngJAAAAeAYHCPsJBABNCAkNCgAAAPAIAwALAACAxgcAAGUAAQD7BwUADgcRAE0KB3UMAAAA7AkKAfsKBgC8CgpXDQAAAJ8KAgJDCAkKTQsHcQIAAADsCgsBQwkICk0KCXkHAAAAlQUKDk0GCHgJAAAATQsDeQcAAABNDAR5BwAAACYKCwyeEwUECgAAAFIJBQCkCBEAAEDwgJ8IAwJNDAN4CQAAAE0NBHgJAAAAJgsMDZ4TBgQLAAAAUgoGAKQJEQAAQPCAnwkDAk0LAngJAAAAJgoLCQ4HDwBNDgd1DAAAAE0QB3ECAAAAPg8QEkMNDg/sDA0B+w0GALwNDVcNAAAAnw0CAkMLDA1NDAt4CQAAACYKDAmBEgoFEwAAAFINCgBvDhMApAwVAABQ8ICfDAMCTQ4EeAkAAAB4DQ4TnhMMAw0AAACkCxEAAEDwgJ8LAwJSCgsA+wwDAE0LDLEWAAAApAwFAAAQMICMDQEAbw4XAJ8MAwIwDAvoGAAAAPsMAwBNCwyxFgAAAKQMGgAAEJCBjA0AAIwOAACMDwAAUhAKAJ8MBQIwDAs7GwAAAPsMAwBNCwyxFgAAAIwMAAAwDAs4HAAAAPsMAwBNCwwkHQAAAKQMBQAAEDCAjA0AAIwOAACfDAMCMAwL6BgAAAD7DAMATQsMJB0AAACkDB8AAHiQgVINCABSDgkAnwwDAjAMCzsbAAAAggABACADQQO+AQO/AQNPAx8EABAwgAIAAAAAAABEQANSAgAAAAAAAElAAz4DsAEDsQEDwAEDwQECAAAAAAAAJEADKQPCAQQAQPCAAgAAAAAAAABAAgAAAAAAAD5AA8MBBABQ8IADxAECAAAAAAAA4D8DxQEDDgQAEJCBAxADxgEDEQNKBAB4kIEA9gSrAQEYAAAAAgAAAAABAAAAAAAAAAAAAQAAAAIAAAEAAAIAAAAAAAAAAQEAAAAAAAAAAQAAAAEAAAEAAwAAAAAAAAAAAAABAAAAAAAAAAAAAAEAAAEBAAAAAAAAAAAAAAABAAACAAAAAAAAAAAAAAAAAAAAAgAAAAAAAAAAAAEAAAAAAAAAAAAAAAEAAAAAAAIAAAAAAAAAAAABAAAAAAAAAAAAB3cCAAAAAgABAAAABfsAAAC8AAB3AAAAAJ8AAgGCAAEAAQOrAQCgBQABGAAAAAABoQIAAAACAAMAAAAM+wAAAA4ACQD7AQEATQABDQAAAADwAAUAAQAAgPsAAgC8AAB3AgAAAJ8AAgGCAAEAAwOwAQOxAQOrAQClBQABGAAAAAAAAAABAAAAAqYCAAAALwAAAQIAugOjAAAApAABAAAAAEBvAgIAvAAAFgMAAACfAAMCpAEBAAAAAEBvAwQAvAEBFgMAAACfAQMCpAIBAAAAAEBvBAUAvAICFgMAAACfAgMCpAMBAAAAAEBvBQYAvAMDFgMAAACfAwMCpAQBAAAAAEBvBgcAvAQEFgMAAACfBAMCpAUBAAAAAEBvBwgAvAUFFgMAAACfBQMCpAYBAAAAAEBvCAkAvAYGFgMAAACfBgMCpAcLAAAAoEBNCwASDAAAAE0KC8YNAAAATQkKuw4AAABNCAmGDwAAAJ8HAgKkCAsAAACgQE0MABIMAAAATQsMoRAAAABNCgshEQAAAE0JCtASAAAAnwgCAqQJCwAAAKBATQ0AEgwAAABNDA0cEwAAAE0LDBgUAAAATQoLdhUAAACfCQICpAoLAAAAoEBNDgASDAAAAE0NDhwTAAAATQwNGBQAAABNCwwfFgAAAJ8KAgKkCwsAAACgQE0OABIMAAAATQ0OoRAAAABNDA3oFwAAAJ8LAgKkDAsAAACgQE0QAE0YAAAATQ8QHBMAAABNDg9DGQAAAE0NDv4aAAAAnwwCAqQNCwAAAKBATREAEgwAAABNEBEcEwAAAE0PEBgUAAAATQ4PQhsAAACfDQICpA4LAAAAoEBNEAASDAAAAE0PEO8cAAAAnw4CAqQPCwAAAKBATREAEgwAAABNEBEHHQAAAJ8PAgKkEAsAAACgQE0UABIMAAAATRMUHBMAAABNEhO1HgAAAE0REsQfAAAAnxACAqQRCwAAAKBATRUATRgAAABNFBUcEwAAAE0TFEMZAAAATRITaCAAAACfEQICpBILAAAAoEBNFQASDAAAAE0UFcYNAAAATRMU6CEAAACfEgICpBMLAAAAoEBNGAASDAAAAE0XGBwTAAAATRYXtR4AAABNFRahIgAAAE0UFX0jAAAAnxMCAqQUCwAAAKBATRcAEgwAAABNFhehEAAAAE0VFnQkAAAAnxQCAqQVCwAAAKBATRgAEgwAAABNFxihEAAAAE0WF9ElAAAAnxUCAqQWCwAAAKBATRsAEgwAAABNGhscEwAAAE0ZGrUeAAAATRgZoSIAAABNFxiQJgAAAJ8WAgKkFwsAAACgQE0bABIMAAAATRoboRAAAABNGRohEQAAAE0YGRMnAAAAnxcCAk0YATEoAAAATRoYmSkAAABNGRp6KgAAAE0cGXUrAAAATRscnSwAAABNGhssLQAAAE0cGr4uAAAATRsc3S8AAABNHRq+LgAAAE0cHSkwAAAATR4avi4AAABNHR7DMQAAAE0fGr4uAAAATR4fPzIAAABNIBq+LgAAAE0fIKwzAAAATSIZdSsAAABNISKdLAAAAE0gIUs0AAAATSIavi4AAABNISJCGwAAAE0jITg1AAAATSIj8jYAAADGIwAAxiQAAMYlAADGJgAA4ic5AE0oCe86AAAAnygBAjAoJ8E3AAAATSgK7zoAAACfKAECMCgnhTgAAADAKDsAEgAbABIAHAASAAgAEgACABIAHgASAB8AEgAhABIAEQASAAYAEgALABIAIgASABIAEgAUABIAFwASAA8AEgATABIAEAASAB0AEgAZAMApPAASABoA2SoCABIBJv8SACAAEgAGABIBJf8SACgAEgAaABIACwASAA8AEgAIABIAEgASABUAEgAWABIAKQASAST/EgAZADAqJy89AAAAwCo+ABIAGgASABkATSsauj8AAABvLUAAvCsrlEEAAACfKwMCUi0qALwrK8dCAAAAnysDAU0sGr4uAAAATSssNEMAAABvLUQAvCsrlEEAAACfKwMCUi0qALwrK8dCAAAAnysDAcAqRQASABkA2SsFABIBJf8SACcAEgEk/xIAKgASAAwAEgEj/zArJ4FGAAAA2SsGABIBJP8SASX/EgAaADArJ89HAAAA2SsHABIBJf8wKyc2SAAAANkrCAASASX/MCsnHEkAAADGKwAA2SQJABIBI/8SASv/EgAnAMErAABNLBiZKQAAAE0rLGtKAAAAwC1LABIAJwC8KyvHQgAAAJ8rAwFNKxkrTAAAANksCwASACsAEgAEABIAGQASABoAEgAMABIBI/8SAAUAMCwnd00AAABvLk4AvCwalEEAAACfLAMCwC5PABIAJwC8LCzHQgAAAJ8sAwFNLAPPUAAAANkuDQASASP/EgAMABIAJwC8LCzHQgAAAJ8sAwFNLBokUQAAAKktAAAwLSyAQAAAAMYsAAAwLBskUQAAAMYsAAAwLBwkUQAAAMYsAAAwLB0kUQAAAMYsAAAwLB4kUQAAAMYsAAAwLB8kUQAAAMYsAAAwLCEkUQAAAMYsAAAwLCIkUQAAAMEjAACCJwIAUgPHAQQAAABAA8gBA8kBA8oBA8sBA8wBA80BA84BA88BA9ABBAAAoEAD0QED0gED0wED1AED1QED1gED1wED2AED2QED2gED2wED3AED3QED3gED3wEDWQPgAQPhAQPiAQPjAQPkAQPlAQPmAQPnAQPoAQNiA+kBA+oBA+sBA+wBA+0BA6QBAwID7gEDgQEDQgNFAwcDUwNYA6gBAwoD7wEDiAEDrAEFAjc4Ax8GBwYIA6ABBgwDeAMkA2QDZQOCAQODAQYNA7cBA64BA7kBA7oBA/ABBhgDQAOrAQO/AQYaA/EBAxEOBwgLDA0SExQVFxgZGhsBAAEEAAIAAAAAAAEAAAAAAAEAAPwAAAEAAAAAAAEAAAAAAAH9AAAAAAEAAAAAAAIAAAAA/QAAAAAAAQAAAAAAAAAAAP8BAAAAAAAAAAAAAAEAAAD+AAAAAAAAAQAAAAAAAAAA/wAAAAAAAAAAAAABAAAAAP8AAAAAAAEAAAAAAAABAAD+AAAAAQAAAAAAAAAAAAAB/gAAAAAAAAAAAAEAAAAAAP8AAAEAAAAAAAAAAAAAAAD/AAAAAAAAAAABAAAAAAAA/wABAAAAAAAAAAAAAAAAAf4AAAAAAAAAAAADAAEAAAD8AAAAAAACAAAAAQAAAAEA/AABAAAAAQAAAAEAAAAAAP0AAAABAAAAAwIBAg8BAADnAAEAAAAABQAAAAAAAAAA+gAAAAAAAAAAAADFAB8AABwAAAAAAAAAAAAAAAAAALpGAAUAAAAAAAAAAAABAAAA+gAAAAAAAAAGABkAAAAAAOEAADAAAAAAAAoAAAAEAADCBwIAAAAAEQAAAAAAAAAA5gALAAAAAAAAAAAAKgAAAMsAAAAABQAAAAAAAAAABwD0AAABAAABAAABAAABAAAB+wABAAABAAACAAEAAAAEAAAAAwAAAAMAAAABAAAAAgAAAAIAAAABAAAAAgAAAAIAAAABAAAAAgAAAAEAAAACAAAABQAAAAQAAAAGAAAAGQAAAAYAAADkAAAAugAAAAYAAAAfAAAAPgAAACEAAAA1AAAADAAAAAUAAAAAHAEgTCW/1j/1M+QmscqwOb7bC7gTwrNMah04+gRiQFl73WQBm6hubgQ=

local v1 = game:GetService("ReplicatedStorage")
local v2 = game:GetService("Players")
local u3 = game:GetService("TextService")
local v4 = game:GetService("RunService")
local u5 = game:GetService("UserInputService")
local u6 = game:GetService("GuiService")
local u7 = game:GetService("TweenService")
require(v1.Shared.Data.Builders.TooltipBuilder)
local u8 = require(v1.Shared.Utils.Stats.ItemUtil)
local v9 = require(v1.Shared.Framework.Classes.Maid)
local v10 = require(v1.Shared.Framework.Classes.Signal)
local u11 = require(v1.Shared.Utils.AnimateColor)
local u12 = require(v1.Client.Framework.Services.InputMode)
require(v1.Shared.Framework.Classes.Pool)
require(v1.Shared.Types)
local u13 = require(v1.Shared.Constants)
local u14 = require(v1.Shared.Framework.Utilities.every)
local u15 = require(v1.Client.Framework.Services.LocalData)
local u16 = require(v1.Shared.Data.Pets)
local u17 = require(v1.Shared.Framework.Utilities.String.FormatPercent)
local u18 = require(v1.Shared.Utils.IndexUtil)
local u19 = require(v1.Shared.Utils.RichText)
local u20 = require(v1.Shared.Framework.Utilities.String.FormatRomanNumeral)
local u21 = require(v1.Shared.Utils.Stats.StatsUtil)
local v22 = v2.LocalPlayer
local u23 = v22.PlayerGui.ScreenGui
local u24 = u23.Tooltip.Frame.Inner
local u25 = u24.Content.Padding
local u26 = u24.Content.Accessory
local u27 = u24.Content.Label
local u28 = u24.Content.Bar
local u29 = u24.Content.Button
local u30 = u23.Tooltip.Frame.Cover
local u31 = u24.Content.Pool
local u32 = u31.Items.Template
local u33 = nil
local u34 = nil
local u35 = nil
local u36 = nil
local u37 = {
    ["_maid"] = v9.new(),
    ["Changed"] = v10.new()
}
local function u80(u38, p39) --[[Anonymous function at line 73]]
    --[[
    Upvalues:
        [1] = u25
        [2] = u26
        [3] = u8
        [4] = u3
        [5] = u28
        [6] = u29
        [7] = u31
        [8] = u15
        [9] = u7
        [10] = u11
        [11] = u32
        [12] = u16
        [13] = u18
        [14] = u21
        [15] = u13
        [16] = u17
        [17] = u14
        [18] = u27
        [19] = u23
    --]]
    if u38.Type == "Padding" then
        local v40 = u25:Clone()
        v40.Line.Visible = u38.Line ~= nil
        v40.Size = UDim2.new(1, 0, 0, u38.Size)
        return v40
    elseif u38.Type == "TextAccessory" then
        local v41 = u26:Clone()
        local v42 = u38.Accessory
        if typeof(v42) == "string" then
            v41.Icon.Label.Image = u38.Accessory
        else
            u8:UpdateIcon(v41.Icon, u38.Accessory)
        end
        local v43 = u38.Size * 0.8
        local v44 = math.ceil(v43)
        v41.Size = UDim2.new(1, 0, 0, u38.Size)
        v41.Label.TextSize = v44
        v41.Label.Text = u38.Text
        v41.Icon.Size = UDim2.fromOffset(u38.Size, u38.Size)
        local v45 = v41.UIPadding
        local v46 = UDim.new
        local v47 = u38.Size / 2.5
        v45.PaddingRight = v46(0, (math.ceil(v47)))
        local v48 = u3:GetTextSize(u38.Text, v44, v41.Label.Font, Vector2.new(p39.Width - 40, v44))
        v41.Label.Size = UDim2.new(0, v48.X, 1, 0)
        return v41
    elseif u38.Type == "Bar" then
        local v49 = u28:Clone()
        v49.Label.Text = u38.Text or ""
        v49.Progress.Fill.Size = UDim2.new(u38.Alpha, 0, 1, 6)
        v49.Progress.Fill.Visible = u38.Alpha > 0.01
        return v49
    elseif u38.Type == "Button" then
        return u29:Clone()
    elseif u38.Type == "Pool" then
        local u50 = u31:Clone()
        local u51 = u38.Pool
        local v52 = 0
        local u53 = 1
        for _, v54 in u51 do
            if u8:GetRarity(v54.Item) ~= "Secret" then
                v52 = v52 + 1
            end
        end
        local v55 = v52 / 6
        local u56 = math.ceil(v55)
        local u57 = os.clock()
        local u58 = TweenInfo.new(0.35, Enum.EasingStyle.Linear)
        local function u73(p59) --[[Anonymous function at line 134]]
            --[[
            Upvalues:
                [1] = u15
                [2] = u50
                [3] = u7
                [4] = u58
                [5] = u8
                [6] = u11
                [7] = u53
                [8] = u51
                [9] = u38
                [10] = u32
                [11] = u16
                [12] = u18
                [13] = u21
                [14] = u13
                [15] = u17
                [16] = u57
                [17] = u56
            --]]
            local v60 = u15:Get()
            if not v60 then
                return
            end
            if p59 then
                local u61 = u50.Items:Clone()
                u61.Name = "Other"
                u50.Items.Position = UDim2.fromScale(1.5, 1)
                u61.Parent = u50
                u7:Create(u50.Items, u58, {
                    ["Position"] = UDim2.fromScale(0.5, 1)
                }):Play()
                u7:Create(u61, u58, {
                    ["Position"] = UDim2.fromScale(-1.5, 1)
                }):Play()
                task.delay(u58.Time, function() --[[Anonymous function at line 147]]
                    --[[
                    Upvalues:
                        [1] = u61
                        [2] = u8
                        [3] = u11
                    --]]
                    for _, v62 in u61:GetChildren() do
                        if v62:IsA("Frame") then
                            u8:UpdateIcon(v62.Icon)
                            u11.None(v62.Label)
                        end
                    end
                    u61:Destroy()
                end)
            end
            for _, v63 in u50.Items:GetChildren() do
                if v63:IsA("Frame") then
                    u8:UpdateIcon(v63.Icon)
                    u11.None(v63.Label)
                    v63:Destroy()
                end
            end
            local _ = v60.Discovered
            for v64 = (u53 - 1) * 6 + 1, u53 * 6 do
                local v65 = u51[v64]
                if not v65 then
                    break
                end
                local v66 = u8:GetRarity(v65.Item)
                if v66 ~= "Secret" or u38.ShowAll then
                    local v67 = u32:Clone()
                    local v68 = v65.Item
                    if v68.Type == "Pet" then
                        local v69 = v68.Name
                        local _ = u16[v69]
                        local v70 = u18:HasAny(v60, v69) or u38.ShowAll
                        local v71 = v70 and 0 or -10
                        v67.Icon.Size = UDim2.new(1, v71, 1, v71)
                        v67.Icon.Label.ImageColor3 = v70 and Color3.new(1, 1, 1) or Color3.new()
                        v67.Amount.Visible = false
                    elseif v68.Type == "Currency" then
                        v68 = table.clone(v68)
                        local v72 = v68.Amount * u21:GetCurrencyMultiplier(v60, v68.Currency, true)
                        v68.Amount = math.ceil(v72)
                    end
                    if v66 == "Legendary" or v66 == "Secret" then
                        u11.Cycle(v67.Label, "Rainbow", {
                            ["Speed"] = 0.4
                        })
                    else
                        v67.Label.TextColor3 = u13.RarityColors[v66]
                    end
                    v67.LayoutOrder = v64
                    v67.Label.Text = u17(v65.Chance, true)
                    v67.Parent = u50.Items
                    u8:UpdateIcon(v67.Icon, v68)
                    u8:FormatAmount(v67.Amount, v68)
                end
            end
            u57 = os.clock()
            u50.Page.Text = ("%* / %*"):format(u53, u56)
            u50.Page.Visible = u56 > 1
        end
        function u38.Callback() --[[Anonymous function at line 210]]
            --[[
            Upvalues:
                [1] = u14
                [2] = u56
                [3] = u57
                [4] = u53
                [5] = u73
                [6] = u50
                [7] = u51
                [8] = u8
                [9] = u11
            --]]
            local u74 = u14(0.25, function() --[[Anonymous function at line 211]]
                --[[
                Upvalues:
                    [1] = u56
                    [2] = u57
                    [3] = u53
                    [4] = u73
                --]]
                if u56 > 1 and os.clock() - u57 > 2.5 then
                    u53 = u53 + 1
                    if u56 < u53 then
                        u53 = 1
                    end
                    u73(true)
                end
            end)
            local v75 = u56 > 1 and 20 or 0
            u50.Size = UDim2.new(1, -20, 0, v75 + (#u51 <= 3 and 70 or 150))
            u50.Items.Size = UDim2.new(1, 0, 1, u56 > 1 and -20 or 0)
            u73()
            return function() --[[Anonymous function at line 227]]
                --[[
                Upvalues:
                    [1] = u50
                    [2] = u8
                    [3] = u11
                    [4] = u74
                --]]
                for _, v76 in u50.Items:GetChildren() do
                    if v76:IsA("Frame") then
                        u8:UpdateIcon(v76.Icon)
                        u11.None(v76.Label)
                        v76:Destroy()
                    end
                end
                u74:Disconnect()
            end
        end
        return u50
    else
        local u77 = u27:Clone()
        u77.Text = u38.Text
        u77.TextSize = u38.Size
        local u78 = Instance.new("GetTextBoundsParams")
        u78.Text = u38.Text
        u78.Font = u77.FontFace
        u78.Size = u38.Size
        u78.Width = p39.Width - 25
        u78.RichText = true
        task.defer(function() --[[Anonymous function at line 256]]
            --[[
            Upvalues:
                [1] = u3
                [2] = u78
                [3] = u77
            --]]
            local v79 = u3:GetTextBoundsAsync(u78)
            u77.Size = UDim2.new(1, 0, 0, v79.Y)
        end)
        u77:GetPropertyChangedSignal("TextBounds"):Connect(function() --[[Anonymous function at line 261]]
            --[[
            Upvalues:
                [1] = u77
                [2] = u23
            --]]
            u77.Size = UDim2.new(1, 0, 0, u77.TextBounds.Y / u23.UIScale.Scale)
        end)
        return u77
    end
end
local function u86(p81) --[[Anonymous function at line 270]]
    --[[
    Upvalues:
        [1] = u24
    --]]
    local v82 = Color3.fromHex("#1badec")
    local v83 = Color3.fromHex("#217ad9")
    local v84 = Color3.fromHex("#e1f3ff")
    local v85 = Color3.fromHex("#8ccdff")
    if p81 == "Shiny" then
        v82 = Color3.fromHex("#ecde1b")
        v83 = Color3.fromHex("#d97d20")
        v84 = Color3.fromHex("#ffffe4")
        v85 = Color3.fromHex("#f3ff74")
    elseif p81 == "Mythic" then
        v82 = Color3.fromHex("#ec20c7")
        v83 = Color3.fromHex("#8a30d9")
        v84 = Color3.fromHex("#fff7ff")
        v85 = Color3.fromHex("#e5a2ff")
    end
    u24.BackgroundColor3 = v84
    u24.Background.ImageColor3 = v85
    u24.Title.Background.ImageColor3 = v85
    u24.Title.Bottom.BackgroundColor3 = v83
    u24.Title.UIGradient.Color = ColorSequence.new({ ColorSequenceKeypoint.new(0, v83), ColorSequenceKeypoint.new(0.168, v83), ColorSequenceKeypoint.new(1, v82) })
end
function u37.Apply(p87, u88, p89) --[[Anonymous function at line 301]]
    --[[
    Upvalues:
        [1] = u36
        [2] = u30
        [3] = u7
        [4] = u35
        [5] = u80
        [6] = u24
        [7] = u11
        [8] = u13
        [9] = u8
        [10] = u16
        [11] = u19
        [12] = u20
        [13] = u86
        [14] = u34
        [15] = u23
    --]]
    if u36 and not p89 then
        u36:Cancel()
    end
    if not p89 then
        u30.Transparency = 0
        u30.BackgroundColor3 = Color3.new(0.129412, 0.505882, 1)
        u36 = u7:Create(u30, TweenInfo.new(0.5, Enum.EasingStyle.Quint), {
            ["BackgroundColor3"] = Color3.new(1, 1, 1),
            ["BackgroundTransparency"] = 1
        }):Play()
    end
    p87._maid:Cleanup()
    u35 = u88
    for v90, v91 in u88.Elements do
        local u92 = u80(v91, u88)
        if u92 then
            local v93 = v91.Callback
            if v93 then
                local v94 = v93(u92)
                if typeof(v94) == "function" then
                    p87._maid:Add(v94)
                end
            end
            u92.LayoutOrder = v90
            u92.Parent = u24.Content
            p87._maid:Add(function() --[[Anonymous function at line 334]]
                --[[
                Upvalues:
                    [1] = u92
                    [2] = u11
                --]]
                for _, v95 in u92:GetDescendants() do
                    if v95:IsA("GuiObject") then
                        u11.None(u92)
                    end
                end
                u92:Destroy()
            end)
        end
    end
    local v96 = nil
    if u88.Title then
        local v97 = u88.Title.Info
        local v98 = u88.Title.Item
        local v99
        if v97 then
            v99 = string.find(v97, "Mythic")
        else
            v99 = v97
        end
        if v99 then
            v97 = string.gsub(v97 or "", "Mythic ", "")
        end
        local v100 = u13.RarityOrder[v97] or v97 == "Permanent"
        if v100 and (v97 == "Legendary" or v97 == "Permanent") then
            u11.Cycle(u24.Title.Content.Info.SubTitle, "Rainbow", {
                ["Speed"] = 0.4
            })
            v96 = "Legendary"
        elseif v97 == "Secret" then
            u11.None(u24.Title.Content.Info.SubTitle)
            u24.Title.Content.Info.SubTitle.TextColor3 = u13.RarityColors.Secret
            v96 = "Secret"
        else
            u11.None(u24.Title.Content.Info.SubTitle)
            u24.Title.Content.Info.SubTitle.TextColor3 = u13.RarityColors[v97] or Color3.new(1, 1, 1)
        end
        local v101 = v99 and "Mythic" or v96
        if v100 or not v98 then
            u11.None(u24.Title.Content.Info.Label)
        else
            v101 = u8:GetRarity(v98)
            if v101 == "Legendary" or v101 == "Secret" then
                u24.Title.Content.Info.Label.TextColor3 = Color3.new(1, 1, 1)
                u11.Cycle(u24.Title.Content.Info.Label, "Rainbow", {
                    ["Speed"] = 0.4
                })
            else
                u11.None(u24.Title.Content.Info.Label)
                u24.Title.Content.Info.Label.TextColor3 = u13.RarityColors[v101]
            end
        end
        if v98 or u88.Title.Image then
            local v102 = v98 and v98.Type == "Potion" and -90 or -100
            if u88.Title.Image then
                u8:UpdateIcon(u24.Title.Content.Icon)
                u24.Title.Content.Icon.Label.Image = u88.Title.Image
                u24.Title.Content.Icon.Label.Visible = true
            else
                u8:UpdateIcon(u24.Title.Content.Icon, v98)
            end
            u24.Title.Content.Info.Size = UDim2.new(1, v102, 1, -15)
        else
            u24.Title.Content.Info.Size = UDim2.new(1, -10, 1, -15)
            u8:UpdateIcon(u24.Title.Content.Icon)
        end
        v96 = v98 and (v98.Type == "Pet" and v98.Shiny) and "Shiny" or v101
        if v99 then
            u24.Title.Content.Info.SubTitle.Text = ("Mythic%*"):format(v97 == "Secret" and " Secret" or "")
            u11.Cycle(u24.Title.Content.Info.SubTitle, "Mythic", {
                ["Speed"] = 0.5
            })
        else
            u24.Title.Content.Info.SubTitle.Text = v97 or ""
        end
        if v98 and v98.Type == "Pet" then
            local v103 = u16[v98.Name]
            if v103.Rarity == "Legendary" then
                local v104 = v103.Tier or 1
                if v104 > 1 then
                    local v105 = u24.Title.Content.Info.SubTitle
                    v105.Text = v105.Text .. (" %*"):format((u19.new():size(18)((("Tier %*"):format((u20(v104)))))))
                end
            end
        end
        u24.Title.Content.Info.Label.Text = u88.Title.Text
    else
        u11.None(u24.Title.Content.Info.SubTitle)
    end
    if v96 == "Mythic" then
        u86("Mythic")
        u24.Parent.Glow.ImageTransparency = 0
        u24.Parent.Glow.ImageColor3 = Color3.new(1, 1, 1)
        u11.Cycle(u24.Parent.Glow, "Mythic", {
            ["Speed"] = 0.65
        })
    elseif v96 == "Shiny" then
        u86("Shiny")
        u24.Parent.Glow.ImageTransparency = 0
        u24.Parent.Glow.ImageColor3 = Color3.new(1, 1, 1)
        u11.Shift(u24.Parent.Glow, "PotionShiny", {
            ["Speed"] = 0.5
        })
    elseif v96 == "Legendary" then
        u86("None")
        u24.Parent.Glow.ImageTransparency = 0
        u24.Parent.Glow.ImageColor3 = Color3.new(1, 1, 1)
        u11.Shift(u24.Parent.Glow, "Rainbow", {
            ["Speed"] = 0.4
        })
    else
        if v96 == "Secret" then
            u24.Parent.Glow.ImageTransparency = 0
            u24.Parent.Glow.ImageColor3 = Color3.new(1, 1, 1)
            u11.Cycle(u24.Parent.Glow, "Secret", {
                ["Speed"] = 0.65
            })
        else
            u11.None(u24.Parent.Glow)
            u24.Parent.Glow.ImageColor3 = Color3.new()
            u24.Parent.Glow.ImageTransparency = 0.5
        end
        u86("None")
    end
    if not p89 then
        u34(nil)
    end
    u24.Title.Visible = u88.Title ~= nil
    u24.Parent.Size = UDim2.fromOffset(u88.Width, 1000)
    u24.Parent.Visible = true
    task.defer(function() --[[Anonymous function at line 478]]
        --[[
        Upvalues:
            [1] = u24
            [2] = u88
            [3] = u23
        --]]
        local v106 = u24.Title.Visible and 70 or 0
        u24.Content.Size = UDim2.new(1, -40, 1, -20 - v106)
        u24.Parent.Size = UDim2.fromOffset(u88.Width, u24.Content.UIListLayout.AbsoluteContentSize.Y / u23.UIScale.Scale + 20 + v106)
    end)
end
local function v108() --[[Anonymous function at line 487]]
    --[[
    Upvalues:
        [1] = u24
        [2] = u23
    --]]
    local v107 = u24.Title.Visible and 70 or 0
    u24.Content.Size = UDim2.new(1, -40, 1, -20 - v107)
    u24.Parent.Size = UDim2.fromOffset(u24.Parent.Size.X.Offset, u24.Content.UIListLayout.AbsoluteContentSize.Y / u23.UIScale.Scale + 20 + v107)
end
u24.Title:GetPropertyChangedSignal("Visible"):Connect(v108)
u24.Content.UIListLayout:GetPropertyChangedSignal("AbsoluteContentSize"):Connect(v108)
local function u111(p109) --[[Anonymous function at line 499]]
    --[[
    Upvalues:
        [1] = u23
    --]]
    for _, v110 in u23:GetChildren() do
        if v110:IsA("GuiObject") and (not v110:IsAncestorOf(p109) and (v110.Name ~= "Tooltip" and (v110.Name ~= "_overlay" and (v110.Size == UDim2.fromScale(1, 1) and (v110.Visible and (v110:FindFirstChild("Overlay") or (v110:FindFirstChild("Frame") or (v110:FindFirstChild("Cover") or v110.Name == "DailyRewards")))))))) then
            return true
        end
    end
    return false
end
function u37.OnEnter(u112, u113, u114) --[[Anonymous function at line 524]]
    --[[
    Upvalues:
        [1] = u35
        [2] = u37
        [3] = u34
        [4] = u111
        [5] = u12
        [6] = u33
    --]]
    local function u116() --[[Anonymous function at line 525]]
        --[[
        Upvalues:
            [1] = u114
            [2] = u35
            [3] = u37
            [4] = u34
            [5] = u113
            [6] = u112
        --]]
        local v115 = u114()
        u35 = v115
        if v115 then
            u37:Apply(v115)
            u37:MoveTo()
            u34(u113)
            u112.Changed:Fire(u113)
        else
            u112:Hide()
        end
    end
    local function v117() --[[Anonymous function at line 541]]
        --[[
        Upvalues:
            [1] = u111
            [2] = u113
            [3] = u12
            [4] = u116
        --]]
        if not u111(u113) then
            if u12.Mode == "Keyboard" then
                u116()
            end
        end
    end
    local function v118() --[[Anonymous function at line 550]]
        --[[
        Upvalues:
            [1] = u33
            [2] = u113
            [3] = u12
            [4] = u112
        --]]
        if u33 == u113 and u12.Mode == "Keyboard" then
            u112:Hide()
        end
    end
    u113.MouseEnter:Connect(v117)
    u113.MouseLeave:Connect(v118)
    u113.Activated:Connect(function() --[[Anonymous function at line 559]]
        --[[
        Upvalues:
            [1] = u12
            [2] = u33
            [3] = u113
            [4] = u112
            [5] = u116
        --]]
        if u12.Mode == "Keyboard" then
            return
        elseif u33 == u113 then
            u112:Hide()
        else
            u116()
        end
    end)
end
function u37.Hide(p119) --[[Anonymous function at line 572]]
    --[[
    Upvalues:
        [1] = u34
        [2] = u35
        [3] = u24
    --]]
    u34(nil)
    u35 = nil
    u24.Parent.Visible = false
    p119.Changed:Fire()
    p119._maid:Cleanup()
end
function u37.GetId(_) --[[Anonymous function at line 582]]
    --[[
    Upvalues:
        [1] = u35
    --]]
    if u35 then
        return u35.ID
    else
        return nil
    end
end
function u37.IsEnabled(_) --[[Anonymous function at line 586]]
    --[[
    Upvalues:
        [1] = u35
    --]]
    return u35 ~= nil
end
local u120 = nil
u34 = function(p121) --[[Function name: setLastEnter, line 595]]
    --[[
    Upvalues:
        [1] = u33
        [2] = u120
        [3] = u37
    --]]
    u33 = p121
    if u120 then
        u120:Disconnect()
        u120 = nil
    end
    if p121 then
        u120 = p121.AncestryChanged:Connect(function(_, p122) --[[Anonymous function at line 602]]
            --[[
            Upvalues:
                [1] = u37
            --]]
            if p122 == nil then
                u37:Hide()
            end
        end)
    end
end
v22.PlayerGui.ChildAdded:Connect(function(p123) --[[Anonymous function at line 612]]
    --[[
    Upvalues:
        [1] = u37
    --]]
    if p123.Name == "Processing" then
        u37:Hide()
    end
end)
local u124 = u23.UIScale
function u37.MoveTo(_) --[[Anonymous function at line 630]]
    --[[
    Upvalues:
        [1] = u124
        [2] = u5
        [3] = u23
        [4] = u24
        [5] = u12
        [6] = u33
        [7] = u6
    --]]
    local v125 = u124.Scale
    local v126 = u5:GetMouseLocation() / v125
    local v127 = u23.AbsoluteSize / v125 - Vector2.new(3, 3)
    local v128 = u24.AbsoluteSize / v125
    local v129 = v126.X + 40
    local v130 = v126.Y - 50
    local v131
    if u12.Mode == "Keyboard" then
        v131 = nil
    else
        v131 = u33
    end
    if v131 then
        local v132 = v131.AbsolutePosition / v125 + u6:GetGuiInset()
        v129 = (v132 + v131.AbsoluteSize / v125).X + 10
        v130 = v132.Y
    end
    local v133 = v127.X - v128.X
    local v134 = math.min(v129, v133)
    local v135 = v127.Y - v128.Y
    local v136 = math.min(v130, v135)
    local v137 = v126.Y - v136
    if v131 then
        v137 = ((v131.AbsolutePosition + v131.AbsoluteSize / 2) / v125 + u6:GetGuiInset()).Y - v136
    end
    local v138 = math.max(v137, 30)
    local v139 = v128.Y - 30
    local v140 = math.min(v138, v139)
    u24.Tip.AnchorPoint = Vector2.new(1, 0.5)
    u24.Tip.Position = UDim2.new(0, 0, 0, v140)
    u24.Tip.Rotation = 0
    u24.Parent.AnchorPoint = Vector2.new(0, 0)
    u24.Parent.Position = UDim2.fromOffset(v134, v136)
end
u24:GetPropertyChangedSignal("AbsoluteSize"):Connect(function() --[[Anonymous function at line 672]]
    --[[
    Upvalues:
        [1] = u37
    --]]
    u37:MoveTo()
end)
v4.RenderStepped:Connect(function() --[[Anonymous function at line 677]]
    --[[
    Upvalues:
        [1] = u33
        [2] = u12
        [3] = u37
    --]]
    if u33 and u12.Mode == "Keyboard" then
        u37:MoveTo()
    end
end)
u24.Parent.Visible = false
u25.Parent = nil
u26.Parent = nil
u27.Parent = nil
u28.Parent = nil
u29.Parent = nil
u31.Parent = nil
u32.Parent = nil
return u37