--devbgascension

-- Bytecode (Base64):
-- BgM+BUNsb25lBUNsb3NlBWNsb3NlBE1haW4MVUlMaXN0TGF5b3V0E0Fic29sdXRlQ29udGVudFNpemUBWQdVSVNjYWxlBVNjYWxlB0J1dHRvbnMFVURpbTIKZnJvbU9mZnNldARTaXplB1VubG9ja3MDR2V0BUxhYmVsBVRpdGxlBFRleHQLRGVzY3JpcHRpb24GUGFyZW50BEljb24ESXRlbQpVcGRhdGVJY29uBUltYWdlC0dldENoaWxkcmVuBUZyYW1lA0lzQQdEZXN0cm95BHRhc2sFZGVmZXIDVG9wBERvbmUGVW5sb2NrBE9wZW4EZ2FtZRFSZXBsaWNhdGVkU3RvcmFnZQpHZXRTZXJ2aWNlB1BsYXllcnMHcmVxdWlyZQZTaGFyZWQERGF0YQhCdWlsZGVycw1VbmxvY2tCdWlsZGVyCUZyYW1ld29yawdDbGFzc2VzBFBvb2wFVXRpbHMFU3RhdHMISXRlbVV0aWwGQ2xpZW50A0d1aQhHdWlGcmFtZQ9DbGlja2FibGVCdXR0b24PQXV0b0J1dHRvbkNvbG9yB1BhbGV0dGULTG9jYWxQbGF5ZXIJUGxheWVyR3VpCVNjcmVlbkd1aQhUZW1wbGF0ZQNuZXcGQnV0dG9uA1JlZAAFAgABAAAABfsAAAC8AAA6AAAAAJ8AAgCCAAAAAQMBABgAARgAAAAAABkAAAAAAgABAAAABfsAAAC8AABjAAAAAJ8AAgGCAAEAAQMCABwDARgAAAAAAR0AAAAABgADAAAAIPsFAABNBAVaAAAAAE0DBDQBAAAATQIDxgIAAABNAQJ4AwAAAPsEAQBNAwQrBAAAAE0CA4QFAAAA7AABAvsDAgBNAgPTBgAAABwBAgCMAgAAYAICAAEAAACVAAAH+wEAAKQCCgAAJICAjAMgA5UEAAufAgMCMAIBLwwAAACCAAEADQMEAwUDBgMHAwgDCQMKAgAAAAAAgFFAAwsDDAQAJICAAgAAAAAAwGJAAw0AOQABGAAAAAAAAAAAAAAAAAAAAAEAAAAAAAABAgAAAAAAAAABOgAAAAALAQcAAABuTQEAUQAAAADGAgAAxgMAAGQBKAD7BgAAvAYGfwEAAACfBgICTQcGwwIAAABNCAW6AwAAADAIB/UEAAAATQcG4gUAAABNCAXiBQAAADAIB/UEAAAA+wgBAE0HCFoGAAAAMAcGJAcAAAD7BwIATQkGrggAAABNCgXKCQAAALwHByEKAAAAnwcEAU0HBakLAAAADgcIAE0IBq4IAAAATQcIwwIAAABNCAWpCwAAADAIB6kLAAAAbgHX/wIAAAD7AgEATQEC0wwAAAC8AQFoDQAAAJ8BAgRkAQgAbwgOALwGBf4PAAAAnwYDAg4GAwC8BgVQEAAAAJ8GAgFuAff/AgAAAE0BANMMAAAAxgIAAMYDAABkAQ0A+wYDALwGBjoRAAAAnwYCAvsIAQBNBwjTDAAAADAHBiQHAAAAUgcFAFIIBgD7CQQAnwcDAW4B8v8CAAAApAEUAABMIIHZAgAAEgIBABICBQASAAAAnwECAfsDAQBNAgOYFQAAAE0BAsMCAAAATQIAugMAAAAwAgH1BAAAAPsBAAC8AQE1FgAAAJ8BAgH7AQYAbwMXALwBARYYAAAAnwEDAYIAAQAZAw4DDwMQAxEDEgMTAwQDFAMVAxYDFwMYAwoDGQMaAxsDHAMBAx0DHgQATCCBAx8DIAMhAyIBAiAhARgAAAAAAAEAAAABAAAAAAABAAAAAAABAAAAAAIAAAAAAAAAAQAAAQAAAAAAAAD4AAwAAAAAAAABAAAAAAEAAP4ABgAAAAABAAAAAQAAAAABAAAA/QAGAAAAAAAACAAAAAAAAAAAAgAAAAEAAAAAASEAAAAAFQAAAQIAkQGjAAAApAABAAAAAEBvAgIAvAAAFgMAAACfAAMCpAEBAAAAAEBvAwQAvAEBFgMAAACfAQMCpAIGAAAAUEBNBgASBwAAAE0FBsYIAAAATQQFuwkAAABNAwSFCgAAAJ8CAgKkAwYAAABQQE0HABIHAAAATQYHHAsAAABNBQYYDAAAAE0EBUINAAAAnwMCAqQEBgAAAFBATQgAEgcAAABNBwihDgAAAE0GByEPAAAATQUG0BAAAACfBAICpAUGAAAAUEBNCABNEQAAAE0HCB8SAAAATQYHlRMAAACfBQICpAYGAAAAUEBNCgBNEQAAAE0JCh8SAAAATQgJoQ4AAABNBwjsFAAAAJ8GAgKkBwYAAABQQE0LAE0RAAAATQoLHxIAAABNCQqhDgAAAE0ICdcVAAAAnwcCAqQIBgAAAFBATQoAEgcAAABNCQp4FgAAAJ8IAgJNCQExFwAAAE0LCZkYAAAATQoLehkAAABNDArmGgAAAE0LDJ0bAAAATQ0LWhwAAABNDA3yHQAAAE0OC9MeAAAATQ0O8h0AAADGDgAAMA4MJB8AAADGDgAAMA4NJB8AAABNDgPvIAAAAMAPIQASAAwAnw4CAsAPIgASAAUAwBAjABIADgASAAsAEgAEABIADQASAA8AEgAKABIABQBSEQcATRQLmCQAAABNExRjJQAAAE0SE6wmAAAATRQIrCYAAABNExRvJwAAAJ8RAwFSEQYATRQLmCQAAABNExRjJQAAAE0SE6wmAAAAUhMPAJ8RAwGCEAIAKAMjBAAAAEADJAMlAyYDJwQAAFBAAygDKQMqAysDLAMtAy4DLwMwAzEDMgMzAzQDNQM2AzcDOAM5AzoDIQMaAwQDOwMKAxQDPAYABgEGAwMfAwIDPQM+AwABAwEAARgAAgAAAAAAAQAAAAAAAgAAAAAAAAAAAAABAAAAAAAAAAAAAAEAAAAAAAAAAAAAAQAAAAAAAAAAAQAAAAAAAAAAAAABAAAAAAAAAAAAAAEAAAAAAAADAAEAAAABAAAAAgAAAAEAAAABAAABAAACAAAAAAQABAAAAAAAAAAoAAAAAAAAAAAAAAABAAAAAAAAAAADAQAAAAAEuVS4xkaIx5uLkNJSnXpMZj4aGRuCX/Fh9WyD1657UFKKIPTA8kY4tQ==

local v1 = game:GetService("ReplicatedStorage")
local v2 = game:GetService("Players")
require(v1.Shared.Data.Builders.UnlockBuilder)
local v3 = require(v1.Shared.Framework.Classes.Pool)
local u4 = require(v1.Shared.Utils.Stats.ItemUtil)
local u5 = require(v1.Client.Gui.GuiFrame)
local v6 = require(v1.Client.Gui.Utils.ClickableButton)
local v7 = require(v1.Client.Gui.Utils.AutoButtonColor)
local v8 = require(v1.Shared.Palette)
local u9 = v2.LocalPlayer.PlayerGui.ScreenGui
local u10 = u9.Unlock.Frame
local u11 = u10.Main.Template
local u12 = u10.Buttons.Template
u11.Parent = nil
u12.Parent = nil
local u13 = v3.new(function() --[[Anonymous function at line 24]]
    --[[
    Upvalues:
        [1] = u11
    --]]
    return u11:Clone()
end)
local function u14() --[[Anonymous function at line 28]]
    --[[
    Upvalues:
        [1] = u5
    --]]
    u5:Close()
end
v7(u10.Top.Close.Button, v8.Button.Red)
v6(u10.Top.Close.Button, u14)
return function(u15) --[[Function name: Unlock, line 32]]
    --[[
    Upvalues:
        [1] = u13
        [2] = u10
        [3] = u4
        [4] = u12
        [5] = u14
        [6] = u9
        [7] = u5
    --]]
    for _, v16 in u15.Unlocks do
        local v17 = u13:Get()
        v17.Label.Text = v16.Title
        v17.Description.Text = v16.Description
        v17.Parent = u10.Main
        u4:UpdateIcon(v17.Icon, v16.Item)
        if v16.Image then
            v17.Icon.Label.Image = v16.Image
        end
    end
    for _, v18 in u10.Buttons:GetChildren() do
        if v18:IsA("Frame") then
            v18:Destroy()
        end
    end
    for _, v19 in u15.Buttons do
        local v20 = u12:Clone()
        v20.Parent = u10.Buttons
        v19(v20, u14)
    end
    task.defer(function() --[[Anonymous function at line 57]]
        --[[
        Upvalues:
            [1] = u10
            [2] = u9
            [3] = u15
        --]]
        local v21 = u10.Main.UIListLayout.AbsoluteContentSize.Y / u9.UIScale.Scale
        if #u15.Buttons > 0 then
            v21 = v21 + 70
        end
        u10.Size = UDim2.fromOffset(800, v21 + 150)
    end)
    u10.Top.Label.Text = u15.Title
    u13:Done()
    u5:Open("Unlock")
end