--devbgascension

-- Bytecode (Base64):
-- BgMpBm51bWJlcgZhc3NlcnQEbm9uZQRtYXRoA2xvZwVmbG9vcgNhYnMGc3RyaW5nBmZvcm1hdAIlZAUlMC4xZgMwKyQABGdzdWIDJS4kDEZvcm1hdFN1ZmZpeARnYW1lEVJlcGxpY2F0ZWRTdG9yYWdlCkdldFNlcnZpY2UHcmVxdWlyZQZTaGFyZWQJRnJhbWV3b3JrCVV0aWxpdGllcwZTdHJpbmcMRm9ybWF0Q29tbWFzAVQBSwFNAUICUUECUWkCU3gCU3ACT2MCTm8CRGMCVWQCRGQCVGQDUWFkA1FpZAACCgMDAAAIBQAABQMCgg9c+wUAAE0EBWAAAAAAUgUAAJ8EAgBMAQACpAMCAAAAEECfAwAB+wUAAE0EBWAAAAAAUgUBAJ8EAgIrBAUA+wUAAE0EBR8DAAAAUgUBAJ8EAgK7AQQCpAMCAAAAEECfAwIBKwEBAG8BBAC7EQADUgYAAKQFCAAAHGCAnwUCAj4EBQW7DAQCpAMKAAAkYICfAwICjAQBALcDBAAEAAAADgEGAGAABQABAAAA+wQBAFIFAACfBAIAggQAAIwG6AOyBQYD7AQABfsGAgCHBQYDeAcEC7sCBwKkBg0AADBggJ8GAgJvBw4AYAYFAAcAAAA+BAQLlQMDD/sGAgCHBQYDIQcEDw0HAgAQAAAADgIGAKQGEwAASBCBbwcUAFIIBACfBgMCKwYPAKQGEwAASBCBbwcVAFIIBACfBgMCbwgWAG8JFwC8BgbMGAAAAJ8GBAJvCBkAbwkXALwGBswYAAAAnwYEAlIIBgBSCQUAcwcICYIHAgAaAwEDAgQAABBAAwMCAAAAopQabUICoP+PmYqhG0ADBAMFBAAcYIADBgQAJGCAAgAAAAAAQI9AAwcEADBggAJ7FK5H4XqEPwIAAAAAAADwPwIAAAAAAAAAAAMIAwkEAEgQgQMKAwsDDAMNAw4DDwAJEAEYAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAQECAAAAAAAAAAAAAQAAAAAAAQAAAAMAAAEAAgAAAAAAAAABAQEAAgAAAAEAAAAAAAEAAAAAAAAAAAAAAAAAAAEAAAAKAAAAABQAAAECADajAAAApAABAAAAAEBvAgIAvAAAFgMAAACfAAMCpAEFAAAAQEBNBgASBgAAAE0FBhwHAAAATQQFtQgAAABNAwShCQAAAE0CA5oKAAAAnwECAqQCBQAAAEBATQUAEgYAAABNBAUcBwAAAE0DBHULAAAAnwICAv8DAAAQAAAAbwQMAG8FDQBvBg4AbwcLAG8IDwBvCRAAbwoRAG8LEgBvDBMAbw0UAG8OFQBvDxYAbxAXAG8RGABvEhkAbxMaAMUDBBEBAAAAwAQbABIAAgASAAEAEgADAIIEAgAcAxEEAAAAQAMSAxMDFAQAAEBAAxUDFgMXAxgDGQMaAxsDHAMdAx4DHwMgAyEDIgMjAyQDJQMmAycDKAMpBgABAAEAARgAAgAAAAAAAQAAAAAAAAAAAAAAAAEAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAAAAAAAAwAAABoBAAAAAAGGCoLZ21cs9LTO6E3lGKIh0naiw7r+JNmYpa8cvfyoVobbXd9ODZgZ

local v1 = game:GetService("ReplicatedStorage")
local u2 = require(v1.Shared.Framework.Utilities.String.FormatCommas)
local u3 = require(v1.Shared.Framework.T)
local u4 = {
    "K",
    "M",
    "B",
    "T",
    "QA",
    "Qi",
    "Sx",
    "Sp",
    "Oc",
    "No",
    "Dc",
    "Ud",
    "Dd",
    "Td",
    "Qad",
    "Qid"
}
return function(p5, p6, p7) --[[Function name: FormatSuffix, line 9]]
    --[[
    Upvalues:
        [1] = u3
        [2] = u2
        [3] = u4
    --]]
    local v8 = u3.number
    assert(v8(p5))
    local v9 = u3.number(p6) or u3.none(p6)
    assert(v9)
    local v10 = p6 or 1000000000000
    local v11 = math.log(p5) / 6.907755278982137
    local v12 = math.floor(v11)
    if v12 < 1 or v10 and p5 < v10 then
        return u2(p5)
    end
    local v13 = p5 / 1000 ^ v12
    local v14 = u4[v12]
    local v15 = v13 - 1000
    if math.abs(v15) < 0.01 then
        v13 = v13 / 1000
        v14 = u4[v12 + 1]
    end
    return ((v13 % 1 == 0 or p7) and string.format("%d", v13) or string.format("%0.1f", v13):gsub("0+$", ""):gsub("%.$", "")) .. v14
end