--devbgascension

-- Bytecode (Base64):
-- BgMUAAZpcGFpcnMEbWF0aAVmbG9vcgZzdHJpbmcDcmVwEkZvcm1hdFJvbWFuTnVtZXJhbAFNAkNNAUQCQ0QBQwJYQwFMAlhMAVgCSVgBVgJJVgFJAAIMAQEAAA4DAAIFAQIPCQcBDwgNARhvAQAApAICAAAAEED7AwAAnwICBFECDwATCQYA7AgACbsMCAKkBwUAABAwgJ8HAgITCAYAzwAACFIIAQCkCQgAABxggBMKBgFSCwcAnwkDAnMBCAluAvD/AgAAgIIBAgAJAwEDAgQAABBAAwMDBAQAEDCAAwUDBgQAHGCAABQHARgAAwAAAAABAAAAAAABAAEAAAAAAAD9AAYVAAAAABAAAAECAFqjAAAA/wAAAA0AAAD/AQAAAgAAAIwC6ANvAwAAxQECAwEAAAD/AgAAAgAAAIwDhANvBAEAxQIDAwEAAAD/AwAAAgAAAIwE9AFvBQIAxQMEAwEAAAD/BAAAAgAAAIwFkAFvBgMAxQQFAwEAAAD/BQAAAgAAAIwGZABvBwQAxQUGAwEAAAD/BgAAAgAAAIwHWgBvCAUAxQYHAwEAAAD/BwAAAgAAAIwIMgBvCQYAxQcIAwEAAAD/CAAAAgAAAIwJKABvCgcAxQgJAwEAAAD/CQAAAgAAAIwKCgBvCwgAxQkKAwEAAAD/CgAAAgAAAIwLCQBvDAkAxQoLAwEAAAD/CwAAAgAAAIwMBQBvDQoAxQsMAwEAAAD/DAAAAgAAAIwNBABvDgsAxQwNAwEAAAD/DQAAAgAAAIwOAQBvDwwAxQ0OAwEAAADFAAEOAQAAAMABDQASAAAAGAEAkA4AAAA1AQCQDgAAAIIBAgAPAwgDCQMKAwsDDAMNAw4DDwMQAxEDEgMTAxQGAAMHAQABAAEYAAIAAQAAAAAAAQAAAAAAAQAAAAAAAQAAAAAAAQAAAAAAAQAAAAAAAQAAAAAAAQAAAAAAAQAAAAAAAQAAAAAAAQAAAAAAAQAAAAAAAQAAAAAAAAAEAAAADgAAAQAAAAABtcEH3brxwduHBW1JmrLDZwUyBmcEjeLhJyaXsafOXM2Wvsvlyyeiug==

local u1 = {
    { 1000, "M" },
    { 900, "CM" },
    { 500, "D" },
    { 400, "CD" },
    { 100, "C" },
    { 90, "XC" },
    { 50, "L" },
    { 40, "XL" },
    { 10, "X" },
    { 9, "IX" },
    { 5, "V" },
    { 4, "IV" },
    { 1, "I" }
}
function FormatRomanNumeral(p2)
    --[[
    Upvalues:
        [1] = u1
    --]]
    local v3 = ""
    for _, v4 in ipairs(u1) do
        local v5 = p2 / v4[1]
        local v6 = math.floor(v5)
        p2 = p2 % v4[1]
        v3 = v3 .. string.rep(v4[2], v6)
    end
    return v3
end
return FormatRomanNumeral