--devbgascension

-- Bytecode (Base64):
-- BgMMBnN0cmluZwZhc3NlcnQFdXBwZXIDc3ViFFVwcGVyQ2FzZUZpcnN0TGV0dGVyBGdhbWURUmVwbGljYXRlZFN0b3JhZ2UKR2V0U2VydmljZQdyZXF1aXJlBlNoYXJlZAlGcmFtZXdvcmsBVAACCQEBAAAGAwAABQEDG/sDAABNAgNBAAAAAFIDAACfAgIATAEAAqQBAgAAABBAnwEAAaQEBAAADACAjAcBAIwIAQC8BQDwBQAAAJ8FBACfBAACUgIEAIEtAAUGAAAAUgQAAG8FBgCkAwcAABQAgJ8DAwJzAQIDggECAAgDAQMCBAAAEEADAwQADACAAwQCAAAAAAAAAEAEABQAgAAKBQEYAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAAACwAAAAAFAAABAgATowAAAKQAAQAAAABAbwICALwAABYDAAAAnwADAqQBBQAAAEBATQQAEgYAAABNAwQcBwAAAE0CA3UIAAAAnwECAsACCQASAAEAggICAAoDBgQAAABAAwcDCAMJBAAAQEADCgMLAwwGAAEAAQABGAACAAAAAAABAAAAAAAAAAAGAAUBAAAAAAFZ314Z7u5uHWsbNI1WsljqoP5rNwK7qOaKI+0tJxe+0Yejr5DuVruY

local v1 = game:GetService("ReplicatedStorage")
local u2 = require(v1.Shared.Framework.T)
return function(p3) --[[Function name: UpperCaseFirstLetter, line 10]]
    --[[
    Upvalues:
        [1] = u2
    --]]
    local v4 = u2.string
    assert(v4(p3))
    return string.upper(p3:sub(1, 1)) .. string.sub(p3, 2)
end