--devbgascension

-- Bytecode (Base64):
-- BgMZAVgBWQVTY2FsZQZPZmZzZXQHVmVjdG9yMgNuZXcEVW5pdAlNYWduaXR1ZGUEbWF0aAVhdGFuMgNkZWcETGVycAhJbnN0YW5jZQVGcmFtZQZhc3NlcnQLQW5jaG9yUG9pbnQPQm9yZGVyU2l6ZVBpeGVsBkNvbG9yMxBCYWNrZ3JvdW5kQ29sb3IzBVVEaW0yCmZyb21PZmZzZXQEU2l6ZQhSb3RhdGlvbghQb3NpdGlvbghEcmF3TGluZQACFQQAAAAJBgAABQQHBweHfU0EAnkAAAAATQUCeAEAAABNCQB5AAAAAE0ICYQCAAAACQcIBE0JAHkAAAAATQgJcAMAAABDBgcITQoAeAEAAABNCQqEAgAAAAkICQVNCgB4AQAAAE0JCnADAAAAQwcICaQIBgAAFECAUgkGAFIKBwCfCAMCTQwBeQAAAABNCwyEAgAAAAkKCwRNDAF5AAAAAE0LDHADAAAAQwkKC00NAXgBAAAATQwNhAIAAAAJCwwFTQ0BeAEAAABNDA1wAwAAAEMKCwykCwYAABRAgFIMCQBSDQoAnwsDAiYMCwhNDQwHBwAAAE0ODKoIAAAATRENeAEAAABNEg15AAAAAJ4FEQMSAAAApBALAAAokICfEAMCuwoQAqQPDQAAMJCAnw8CAlISCwBvEw4AvBAIXw8AAACfEAQCKwMFAKQREQAAFACBbxISAJ8RAgJSAxEAuwEDA1ISAwCkERQAAAAwQZ8RAgGkEQYAABRAgG8SDgBvEw4AnxEDAjARA+gVAAAAjBEAADARA44WAAAApBEYAAAUcIGMEgEAjBMBAIwUAQCfEQQCMBEDnxkAAACkERwAAGyggVISDgCMEwIAnxEDAjARAy8dAAAAMA8DOB4AAACkERwAAGyggU0SEHkAAAAATRMQeAEAAACfEQMCMBEDOx8AAACCAwIAIAMBAwIDAwMEAwUDBgQAFECAAwcDCAMJAwoEACiQgAMLBAAwkIACAAAAAAAA4D8DDAMNBAAUAIEDDgMPBAAAMEEDEAMRAxIEABRwgQMTAxQDFQQAbKCBAxYDFwMYAAIZARgAAAEAAQAAAAAAAAAAAAEAAAAAAAAAAAABAAAAAAEAAAAAAAAAAAABAAAAAAAAAAAAAQAAAAABAQABAAEAAAAAAAAAAAAAAAABAAAAAAIBAAAAAAIAAAAAAgAAAAAAAAEAAAEAAAAAAAAAAgAAAAAAAAEAAQAAAAAAAAAAAggAAAAAAQAAAQIAB6MAAADAAAAAGAAAkgEAAAA1AACSAQAAAIIAAgACBgADGQEAAQABGAABAAAnAAABAAAAAAGL8yMQsbgZdLk3SYTEw5cMlfzfmjYWqq5/acnS1doIXNvIFubDJUz/

function DrawLine(p1, p2, p3, p4)
    local v5 = p3.X
    local v6 = p3.Y
    local v7 = p1.X.Scale * v5 + p1.X.Offset
    local v8 = p1.Y.Scale * v6 + p1.Y.Offset
    local v9 = Vector2.new(v7, v8)
    local v10 = p2.X.Scale * v5 + p2.X.Offset
    local v11 = p2.Y.Scale * v6 + p2.Y.Offset
    local v12 = Vector2.new(v10, v11)
    local v13 = v12 - v9
    local v14 = v13.Unit
    local v15 = v13.Magnitude
    local v16 = v14.Y
    local v17 = v14.X
    local v18 = math.atan2(v16, v17)
    local v19 = math.deg(v18)
    local v20 = v9:Lerp(v12, 0.5)
    local v21 = p4 or Instance.new("Frame")
    assert(v21)
    v21.AnchorPoint = Vector2.new(0.5, 0.5)
    v21.BorderSizePixel = 0
    v21.BackgroundColor3 = Color3.new(1, 1, 1)
    v21.Size = UDim2.fromOffset(v15, 2)
    v21.Rotation = v19
    v21.Position = UDim2.fromOffset(v20.X, v20.Y)
    return v21
end
return DrawLine