--devbgascension

-- Bytecode (Base64):
-- BgMRDUN1cnJlbnRDYW1lcmEWdmlld3BvcnQgaGFzIG5vIGNhbWVyYQZhc3NlcnQLRmllbGRPZlZpZXcEbWF0aANyYWQMQWJzb2x1dGVTaXplBkNGcmFtZRJQb2ludFRvT2JqZWN0U3BhY2UBWAFZAVoDdGFuB1ZlY3RvcjMDbmV3B1ZlY3RvcjIXUG9pbnRUb1ZpZXdwb3J0UG9zaXRpb24AAhMCAAAACwQAAQUCBwgICy4BXE0DAEgAAAAAgQEDBAEAAABvBAEApAIDAAAAIECfAgMCTQUCYQUAAABbBAUEuxYEAqQDCAAAHGCAnwMCAk0EAHEJAAAATQUChQoAAABSBwEAvAUFxgsAAACfBQMCTQcEeQwAAABNCAR4DQAAAOwGBwhNCAV7DgAAADkHCAC7GwMDUgoDAKQJEAAAPGCAnwkCAgkIBwkJCQgGOQ0IADQ2CQUNBwAAUgwJAFIOBwCkCxMAAEgQgZ8LBAJDCgULTQwKeQwAAACMDgIACQ0OCewLDA1NDgp4DQAAAIwQAgAJDxAI7A0OD1sMDRSpDQAAjA4AAH0OEgAHAAAAqQ0AAIwOAAB9Dg4ACwAAAKkNAACMDgEAfQsKAA4AAACpDQAAjA4AAH0OBgAMAAAAjA4BANQMAgAOAAAAqQ0AAakNAQBNDwR5DAAAAAkOCw9NEAR4DQAAAAkPDBCkEBYAAEhQgVIRDgBSEg8AnxADAlIRDQCCEAMAFwMBAwIDAwQAACBAAgAAAAAAAOA/AwQDBQMGBAAcYIADBwMIAwkDCgMLAwwDDQQAPGCAAw4DDwQASBCBAgAAAAAAAPC/AxAEAEhQgQADEQEYAAAAAAAAAAABAAAAAAAAAQACAAAAAAABAAAAAAIAAAEAAAAAAAECAAAAAAAAAAABAAAAAAEAAAAAAAIAAAAAAAAAAAAAAAAAAAAAAAAAAAEAAAEAAAIAAAAAAAAHAAAAAAEAAAECAAOjAAAAwAAAAIIAAgABBgABAAEAARgAAhsBAAAAAAHrEo8TU7A1ZtnW5Yd8OF0+P75S4nW6dWSjVaMYMCqNxUBLWHuAA9Ri

return function(p1, p2) --[[Function name: PointToViewportPosition, line 3]]
    local v3 = p1.CurrentCamera
    local v4 = assert(v3, "viewport has no camera")
    local v5 = v4.FieldOfView * 0.5
    local v6 = math.rad(v5)
    local v7 = p1.AbsoluteSize
    local v8 = v4.CFrame:PointToObjectSpace(p2)
    local v9 = v7.X / v7.Y
    local v10 = -v8.Z
    local v11 = v10 * math.tan(v6)
    local v12 = v11 * v9
    local v13 = -v11
    local v14 = v8 + Vector3.new(v12, v13, v10)
    local v15 = v14.X / (2 * v12)
    local v16 = v14.Y / (2 * v11) * -1
    local v17
    if v10 >= 0 and (v15 >= 0 and (v15 <= 1 and v16 >= 0)) then
        v17 = v16 <= 1
    else
        v17 = false
    end
    local v18 = v15 * v7.X
    local v19 = v16 * v7.Y
    return Vector2.new(v18, v19), v17
end