--devbgascension

-- Bytecode (Base64):
-- BgMaBG1hdGgFY2xhbXADbWFwDFZpZXdwb3J0U2l6ZQFYAVkDbWluBVNjYWxlBnVwZGF0ZQdPcHRpb25zEkNvbm5lY3REYXRhQ2hhbmdlZBhHZXRQcm9wZXJ0eUNoYW5nZWRTaWduYWwHQ29ubmVjdAdTY2FsZVVJBGdhbWUJV29ya3NwYWNlCkdldFNlcnZpY2UNQ3VycmVudENhbWVyYRFSZXBsaWNhdGVkU3RvcmFnZQdyZXF1aXJlBkNsaWVudAlGcmFtZXdvcmsIU2VydmljZXMJTG9jYWxEYXRhBlNoYXJlZAVUeXBlcwAEBwEAAAAGAwAABQECDXgCAAE+AQIAWwMBA5UCAwJvBQIAjAYBADQuAgQFBgAAUgQCAKQDBgAAFECAnwMEAoIDAgAHAgAAAAAAAI5AAgAAAAAAAHRAApqZmZmZmdk/AjMzMzMzM+M/AwEDAgQAFECAAA4DARgAAAEAAQAAAAAAAAAADwAAAAAJAAIAAAAe+wEAAE0AAbAAAAAATQIAeQEAAABNAwB4AgAAAJ4TAgMDAAAApAEFAAAQMICfAQMCeAQBBz4DBAZbBQMJlQQFCG8HCACMCAEANC4EBAcIAABSBgQApAULAAAoMICfBQQCUgIFAFsCAgz7AwEAMAIDhA0AAACCAAEADgMEAwUDBgMBAwcEABAwgAIAAAAAAACOQAIAAAAAAAB0QAKamZmZmZnZPwIzMzMzMzPjPwMCBAAoMIACAAAAAAAA8D8DCAAXCQEYCQAAAQAAAAAAAAAA9gABAAEAAAAAAAAAABECAAABDwAAAAAMAgIAAAcEAAAFAgeBL9kCAAASAgAAEgAAAPsEAABNAwSwAAAAAE0FA3kBAAAATQYDeAIAAACeEwUDBgAAAKQEBQAAEDCAnwQDAngHBAc+BgcGWwgGCZUHCAhvCggAjAsBADQuBwQKCwAAUgkHAKQICwAAKDCAnwgEAlIFCABbBQUMMAUAhA0AAAD7AwEAbwUOAFIGAgC8AwMoDwAAAJ8DBAH7AwAAbwUAALwDA5QQAAAAnwMDAlIFAgC8AwPHEQAAAJ8DAwGCAAEAEgMEAwUDBgMBAwcEABAwgAIAAAAAAACOQAIAAAAAAAB0QAKamZmZmZnZPwIzMzMzMzPjPwMCBAAoMIACAAAAAAAA8D8DCAMKAwsDDAMNAQEWDgEYCAAAAQAAAQAAAAAAAAAA9gABAAEAAAAAAAAAABECAAQAAAAAAAEAAAAAAAAAAAEPAAAAAAcAAAECACajAAAApAEBAAAAAEBvAwIAvAEBFgMAAACfAQMCTQABSAQAAACkAQEAAAAAQG8DBQC8AQEWAwAAAJ8BAwKkAgcAAABgQE0GAU0IAAAATQUGHAkAAABNBAVDCgAAAE0DBGgLAAAAnwICAqQDBwAAAGBATQUBEgwAAABNBAXvDQAAAJ8DAgLABA4AwAUPABIAAAASAAIAggUCABADDwQAAABAAxADEQMSAxMDFAQAAGBAAxUDFgMXAxgDGQMaBgAGAgIAAgEAARgABwAAAAAAAAABAAAAAAABAAAAAAAAAAAAAAEAAAAAAAADCAAAFwEAAAAAA+Szbv99Ekx91ncEa60T8FAxIWjyfzTr1MBdGhv3vZOxtl0O9QHwKto=

local u1 = game:GetService("Workspace").CurrentCamera
local v2 = game:GetService("ReplicatedStorage")
local u3 = require(v2.Client.Framework.Services.LocalData)
require(v2.Shared.Types)
return function(u4, _) --[[Function name: ScaleUI, line 22]]
    --[[
    Upvalues:
        [1] = u1
        [2] = u3
    --]]
    local function v9() --[[Anonymous function at line 23]]
        --[[
        Upvalues:
            [1] = u1
            [2] = u4
        --]]
        local v5 = u1.ViewportSize
        local v6 = v5.X
        local v7 = v5.Y
        local v8 = (math.min(v6, v7) - 320) / 960 * 0.6 + 0.4
        u4.Scale = math.clamp(v8, 0.4, 1) * 1
    end
    local v10 = u1.ViewportSize
    local v11 = v10.X
    local v12 = v10.Y
    local v13 = (math.min(v11, v12) - 320) / 960 * 0.6 + 0.4
    u4.Scale = math.clamp(v13, 0.4, 1) * 1
    u3:ConnectDataChanged("Options", v9)
    u1:GetPropertyChangedSignal("ViewportSize"):Connect(v9)
end