--devbgascension

-- Bytecode (Base64):
-- BgOFAQZDRnJhbWUDbmV3CFBvc2l0aW9uBVZhbHVlB1ZlY3RvcjMEVW5pdARtYXRoBW5vaXNlB1Bpdm90VG8HU2NhbGVUbwZ1cGRhdGUWTnVtYmVyU2VxdWVuY2VLZXlwb2ludARUaW1lEEZpbGxUcmFuc3BhcmVuY3kGQ3JlYXRlBFBsYXkGQXNzZXRzBEVnZ3MEJSolKgcgR29sZGVuAAZmb3JtYXQFQ2xvbmUOR2V0Qm91bmRpbmdCb3gBWQhJbnN0YW5jZQpBdHRhY2htZW50C1ByaW1hcnlQYXJ0BlBhcmVudARTaXplBklnbm9yZQhBZGRNb2RlbAl3b3Jrc3BhY2UIUmVuZGVyZWQHR2VuZXJpYwtOdW1iZXJWYWx1ZQlIaWdobGlnaHQTT3V0bGluZVRyYW5zcGFyZW5jeQZDb2xvcjMJRmlsbENvbG9yCVBhcnRpY2xlcwlFeHBsb3Npb24LTnVtYmVyUmFuZ2UITGlmZXRpbWUHRW5hYmxlZAhFbGVjdHJpYwlTZXRWb2x1bWUJU2VjcmV0RWdnA0FkZAlIZWFydGJlYXQHQ29ubmVjdARFbnVtCkNhbWVyYVR5cGUKU2NyaXB0YWJsZQdEaXNhYmxlClNldFZpc2libGURU2V0UGxheWVyc1Zpc2libGUERmFsbAR0YXNrBHdhaXQGT3JpZ2luBEVtaXQFU2hha2UJVHdlZW5JbmZvC0Vhc2luZ1N0eWxlBVF1YXJ0BEJhY2sLRmllbGRPZlZpZXcXdHJhbnNmb3JtTnVtYmVyU2VxdWVuY2UFZGVsYXkFRnJhbWUFVURpbTIJZnJvbVNjYWxlEEJhY2tncm91bmRDb2xvcjMWQmFja2dyb3VuZFRyYW5zcGFyZW5jeQRGYWRlB0NsZWFudXAJQ2hhcmFjdGVyCEh1bWFub2lkDkZpbmRGaXJzdENoaWxkDUNhbWVyYVN1YmplY3QGQ3VzdG9tBkVuYWJsZQZVcGRhdGUJQW5pbWF0aW9uBGdhbWUHUGxheWVycwpHZXRTZXJ2aWNlEVJlcGxpY2F0ZWRTdG9yYWdlClJ1blNlcnZpY2UMVHdlZW5TZXJ2aWNlB3JlcXVpcmUGU2hhcmVkBVV0aWxzFUdldFBvc2l0aW9uTmVhclBsYXllcgVUeXBlcwZDbGllbnQMUGxheWVyUmVuZGVyCUZyYW1ld29yawdDbGFzc2VzDFdvcmxkRW1pdHRlcg5QbGF5ZXJDb250cm9scwRNYWlkCVBldFJlbmRlcghTZXJ2aWNlcw5Db2xsaXNpb25Hcm91cAlVdGlsaXRpZXMMU2VxdWVuY2VVdGlsB0VmZmVjdHMGQnViYmxlBU11c2ljB1BoeXNpY3MDR3VpDlBsYXlMb2NhbFNvdW5kBERpcnQLU3ByZWFkQW5nbGUGUmFkaXVzBFJhdGURR3Jhdml0eU11bHRpcGxpZXIFU3BlZWQOTnVtYmVyU2VxdWVuY2UMVHJhbnNwYXJlbmN5BER1c3QLTG9jYWxQbGF5ZXINQ3VycmVudENhbWVyYQlQbGF5ZXJHdWkJU2NyZWVuR3VpBEdyb3cIQ2lyY3VsYXIPRWFzaW5nRGlyZWN0aW9uAkluBVF1aW50BFNpbmUABQwBCAAAEgMAAwUBAggEFwEIBhwBCAVAAVv7AgAAWwECAKQDAwAACBCA+wUBAE0EBTsEAAAAnwMCAowFAAD7CAIA+woDAE0JCuwFAAAACQcICfsJBABNCAnsBQAAAEMGBwiMBwAATDYAAqQEBwAACGCAnwQEAkMCAwT7BgEATQUGOwQAAABvBggAQwQFBvsHAQBNBgcHCgAAAFsFBglDAwQF+wUFAE0EBewFAAAAjAUAAGAFGwAEAAAApAYNAAAwsIBSBwEAjAgAAJ8GAwKkBw0AADCwgFIIAQCMCQAAjApkAJ8HBAKkCA0AADCwgFIJAQCMCmQAjAsAAJ8IBABMNgACpAUHAAAIYICfBQAC+wcFAE0GB+wFAAAACQQFBkMDAwT7BAAAQwQEAN4EAAD7BAYAUgYCALwEBMIOAAAAnwQDAfsEBgD7BwMATQYH7AUAAAC8BAQ0DwAAAJ8EAwH7BAcApAUDAAAIEIBSBgMATQcCOwQAAACfBQMCMAUEhQEAAACCAAEAEAIAAAAAAABCQAMBAwIEAAgQgAMDAwQDBQQACGCABwAAAAAAACBAAAAAAAAAAAACAAAAAAAAJEADBgMHAwgEADCwgAMJAwoAZgsBGAAAAQAAAAAAAQAAAAAAAAAAAAAAAAAAAAEAAAEAAQAAAAACAAAAAAACAAAAAAEAAAAAAAEAAAAAAP0AAAAEAAAAAAMAAAEAAAAAAQAAAAAAAAEAAAAAAAAAAAFnAAAAAAYCAAAAAAmkAgIAAAQAgE0DAEoDAAAATQUA7AUAAABbBAUEnwIDAIICAAAGAwwDAgQABACAAw0CAAAAAAAA+D8DBACiAQABGAAAAAAAAAAAAKMAAAAABgADAAAADvsAAAD7AgEA+wMCAOIEAQCMBQEAMAUEFgAAAAC8AACWAgAAAJ8ABQK8AADuAwAAAJ8AAgGCAAEABAMOBQEAAw8DEACoAQABGAAAAAAAAAAAAAAAAAABqQAAAAAcAhQAABEEAAIFAgOBCBP4AQEIE4ACAcME+wMAAE0CA+8AAAAAnwIBAvsDAQD7BAIAqQUBAJ8DAwL7BwMATQYHgQEAAABNBQZPAgAAAG8HAwBSCQAADgECAG8KBABlAAEAbwoFALwHB40GAAAAnwcEAlIGBwCHBAUGvAQEOgcAAACfBAICvAcElQkAAACfBwICTQYHeAoAAAA+BQYIpAYMAAAAsIBvBw0AnwYCAk0HBJsOAAAADgcLAE0HBJsOAAAAMAcGJA8AAABNCQSbDgAAAE0ICS8QAAAATQcIeAoAAAA+BQcI+wgEAE0HCIURAAAA+wgFAFIKBABvCxIAvAgI8hMAAACfCAQBpAoVAAAAQEFNCQr7FgAAAE0ICfkXAAAAMAgEJA8AAACkCAwAAACwgG8JGACfCAICjAkPADAJCOwZAAAApAkMAAAAsIBvChgAnwkCAm8KGgAwCgnsGQAAAKQKDAAAALCAbwsYAJ8KAgKkCwwAAACwgG8MGwCfCwICjAwBADAMC6IcAAAAjAwBADAMCxYdAAAApAwfAAAA4IGMDQEAjA4BAIwPAQCfDAQCMAwLgCAAAAAwBAskDwAAAPsPAwBNDg+BAQAAAE0NDq4hAAAATQwNliIAAAC8DAw6BwAAAJ8MAgKkDSQAAAAwgm8OJQCfDQICMA0MyyYAAACpDQAAMA0M8CcAAAAwBgwkDwAAAPsQAwBNDxCBAQAAAE0OD64hAAAATQ0OgSgAAAC8DQ06BwAAAJ8NAgKpDgAAMA4N8CcAAAAwBg0kDwAAAPsOBgCMEAAAvA4OHSkAAACfDgMB+w4HAG8PKgCfDgIBjA4AANkPAAASAQ7/EgADABIBBf8SAAkAEgAIABIACgASAAQAEgIEAFIQDwCMEQAAnxACAVISBgC8EAJfKwAAAJ8QAwFSEggAvBACXysAAACfEAMBUhIKALwQAl8rAAAAnxADAVISCQC8EAJfKwAAAJ8QAwFSEgQAvBACXysAAACfEAMB+xMIAE0SE/0sAAAAUhQPALwSEsctAAAAnxIDALwQAl8rAAAAnxAAAfsQBACkETEAMLzgwjARECovAAAA+xAJALwQEF8yAAAAnxACAfsQCgCpEgAAvBAQqTMAAACfEAMB+xALAKkSAAC8EBCpMwAAAJ8QAwH7EAwAqRIAAKkTAQC8EBCjNAAAAJ8QBAH7EA0AUhIIAPsUDgBNExRtNQAAAOIUNgCMFQAAMBUU7BkAAAC8EBCWNwAAAJ8QBQK8EBDuOAAAAJ8QAgGkEDsAAOiQg/sTDgBNEhNtNQAAAE0REko8AAAAnxACAfsQDwCkEj0AAAAQgU0TAzs+AAAAnxICAm8TPwBDERITMBEQQ0AAAAD7EBAA+xMPAE0SE0NAAAAAbxM/AEMREhMwERBDQAAAAPsQDwCMEgoAvBAQVkEAAACfEAMB+xAQAIwSBQC8EBBWQQAAAJ8QAwH7EA0AUhIKAPsUDgBNExSMQgAAAOIUNgCMFQIAMBUU7BkAAAC8EBCWNwAAAJ8QBQK8EBDuOAAAAJ8QAgGkEDsAAOiQg28RQwCfEAIB+xANAFISCgD7FA4ATRMUjEIAAADiFDYAjBUAADAVFOwZAAAAvBAQljcAAACfEAUCvBAQ7jgAAACfEAIBpBA7AADokIP7Ew4ATRITjEIAAABNERJKPAAAAJ8QAgGMEgEAjBADAIwRAQCoEIwApBNFAAAAQISVFRJHPhQVRqQVSgBJIOHCnxMDAvsUDQBSFgkAUhcTAOIYNgBNGgnsGQAAAD4bEkZDGRobMBkY7BkAAAC8FBSWNwAAAJ8UBQK8FBTuOAAAAJ8UAgH7FA0AUhYKAPsYDgBNFxiMQgAAAOIYNgBvGSUAMBkY7BkAAAC8FBSWNwAAAJ8UBQK8FBTuOAAAAJ8UAgH7FA0A+xYEAPsYDgBNFxhHSwAAAOIYTQCMGkYAWxsSTkMZGhswGRhhTAAAALwUFJY3AAAAnxQFArwUFO44AAAAnxQCAfsUDQBSFgsAUhcTAOIYTwANEgMARgAAgIwZAABlAAEAbxlQADAZGBYdAAAAvBQUljcAAACfFAUCvBQU7jgAAACfFAIBjBYBALwUDFZBAAAAnxQDAYwWAwC8FA1WQQAAAJ8UAwH7FREATRQV9VEAAABNFQwvEAAAAMAWUgCfFAMCMBQMLxAAAAD7FA8AjBYKALwUFFZBAAAAnxQDAfsUEACMFgUAvBQUVkEAAACfFAMBjBQDAGASJgAUAAAApBRUAABMkYNvFVUA2RYCABICDQASAAsAEgATAJ8UAwGkFDsAAOiQg00VE0o8AAAAnxQCAfsUDQBSFgoA+xgOAE0XGIxCAAAA4hg2AIwZAAAwGRjsGQAAALwUFJY3AAAAnxQFArwUFO44AAAAnxQCAaQUOwAA6JCD+xgOAE0XGIxCAAAATRYXSjwAAACVFRZWnxQCAYsQdP+kEAwAAACwgG8RVwCfEAICpBFaAABkgYWMEgEAjBMBAJ8RAwIwERAvEAAAAKQRHwAAAOCBjBIBAIwTAQCMFAEAnxEEAjAREJ9bAAAAjBEBADAREDpcAAAA+xESADARECQPAAAA+xENAFITEAD7FQ4ATRQVx10AAADiFV4AjBYAADAWFTpcAAAAvBERljcAAACfEQUCvBER7jgAAACfEQIBpBE7AADokIP7FQ4ATRQVx10AAABNExRKPAAAAJUSE0efEQIB+xENAFITEAD7FQ4ATRQVx10AAADiFV4AjBYBADAWFTpcAAAAvBERljcAAACfEQUCvBER7jgAAACfEQIBvBEC8V8AAACfEQIB+xEEADAHEYURAAAA+xEEAIwSRgAwEhFhTAAAAPsSAgBNERJpYAAAAFISEQAOEgQAbxRhALwSEQNiAAAAnxIDAkcSCQAAAAAA+xMEADASE5xjAAAA+xMEAKQUZQBkvODCMBQTKi8AAAD7EwYAbxVDALwTEx0pAAAAnxMDAfsTCQC8ExPEZgAAAJ8TAgH7ExMAvBMTJmcAAACfEwIB+xMKAKkVAQC8ExOpMwAAAJ8TAwH7EwsAqRUBALwTE6kzAAAAnxMDAfsTDACpFQEAqRYBALwTE6M0AAAAnxMEAcEFAACCAAEAaAMCAxEDEgMTAxQDFQMWAxcCAAAAAAAAAEADGAMZAxoEAACwgAMbAxwDHQMeAwEDHwMgAyEEAABAQQMiAyMDJAMEApqZmZmZmfU/AyUDJgMOAycEAADggQMoAykDKgMrBAAAMIICAAAAAAAA6D8DLAMtAy4DLwMwAzEDMgMzAzQDNQM2BDC84MIDNwM4AzkDOgUBGQMPAxADOwM8BADokIMDDQQAABCBAwMHAAAAAAAAgD8AAAAAAAAAAAM9Az4DPwIAAAAAAADgPwNABAAAQIQCAAAAAAAACEACAAAAAAAA8D8DQQNCBEkg4cIDQwNEBQFMAgAAAAAAABRABQEdAs3MzMzMzOQ/A0UGAQNGBABMkYMCmpmZmZmZyT8CAAAAAAAA0D8DRwNIA0kEAGSBhQNKA0sDTAUBXANNA04DTwNQA1EDUgRkvODCA1MDVAMAAQI8VQEYAAAAAAEAAAABAAAAAAAAAAAAAAAAAAAAAAAAAQAAAAAAAQAAAAEAAAEAAAABAAAAAAAAAwAAAgAAAAAAAQAAAAAAAAACAAAAAQAAAgAAAAEAAAIAAAABAAAAAQAAAQAAAQAAAAAAAAABAAIAAAAAAAAAAAABAAAAAAABAAABAAIAAAAAAAAAAAABAAABAAIAAAAAAQAAAgEAAAAAAAAAABYAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAAAAAAAAAIAAAAAAgAAAAEAAAAAAQAAAAABAAAAAAACAAAAAAAAAAAAAAAAAAABAAAAAAAAAAMAAAAAAAAAAAABAAAAAAAAAAEAAAAAAQAAAAACAAAAAAAAAAAAAAAAAAABAAAAAgAAAAAAAAAAAAAAAAAAAQAAAAAAAAACAAAAAQAAAAAAAAEAAAAAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAAAAQAAAAEAAAABAAAAAAAAAAADAAAAAAEAAAAAAQAAAQAAAAAAAAADAAAAAAEAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAO0XAAAAAQAAAAAAAAEAAAAAAAAAAQAAAQAAAgAAAAAAAAAAAAAAAAAAAQAAAAAAAAAAAgAAAAAAAAAAAAAAAAAAAwAAAQAAAQAAAAIAAAEAAAAAAAEAAQAAAQAAAAADAAAAAAIAAAABAAAAAgAAAAABAAAAAAEAAAAAAAEAPQAAAAAbAAABAgDKAqMAAACkAAEAAAAAQG8CAgC8AAAWAwAAAJ8AAwKkAQEAAAAAQG8DBAC8AQEWAwAAAJ8BAwKkAgEAAAAAQG8EBQC8AgIWAwAAAJ8CAwKkAwEAAAAAQG8FBgC8AwMWAwAAAJ8DAwKkBAgAAABwQE0HARIJAAAATQYHoQoAAABNBQahCwAAAJ8EAgKkBQgAAABwQE0HARIJAAAATQYH7wwAAACfBQICpAYIAAAAcEBNCAFNDQAAAE0HCKMOAAAAnwYCAqQHCAAAAHBATQsBEgkAAABNCgscDwAAAE0JChgQAAAATQgJXBEAAACfBwICpAgIAAAAcEBNCgFNDQAAAE0JClkSAAAAnwgCAqQJCAAAAHBATQ0BEgkAAABNDA0cDwAAAE0LDBgQAAAATQoLdhMAAACfCQICpAoIAAAAcEBNDAFNDQAAAE0LDIsUAAAAnwoCAqQLCAAAAHBATQ8BEgkAAABNDg8cDwAAAE0NDkMVAAAATQwNFBYAAACfCwICpAwIAAAAcEBNEAESCQAAAE0PEBwPAAAATQ4PtRcAAABNDQ5sGAAAAJ8MAgKkDQgAAABwQE0QAU0NAAAATQ8QlxkAAABNDg8nGgAAAJ8NAgKkDggAAABwQE0QAU0NAAAATQ8QfRsAAACfDgICpA8IAAAAcEBNEgFNDQAAAE0REpcZAAAATRARMxwAAACfDwICpBAIAAAAcEBNFAFNDQAAAE0TFB8dAAAATRIToQoAAABNERIsHgAAAJ8QAgJNEQfvHwAAAE0UAYEgAAAATRMUlxkAAABNEhN6IQAAAJ8RAgKMElAAMBIRzyIAAACkEiQAAHwwgowTAABvFCUAnxIDAjASEXEmAAAAjBIAADASEfYnAAAApBIkAAB8MIJvEygAbxQpAJ8SAwIwEhHQKgAAAKQSJAAAfDCCbxMrAIwUGQCfEgMCMBIRLCwAAACkEi4AAHzQgowTAACMFAEAnxIDAjASEdkvAAAApBIkAAB8MIJvEzAAbxQxAJ8SAwIwEhHLMgAAAE0SB+8fAAAATRUBgSAAAABNFBWXGQAAAE0TFPgzAAAAnxICAowTAAAwExL2JwAAAIwTWgAwExLPIgAAAKQTJAAAfDCCjBQAAIwVAgCfEwMCMBMScSYAAACkEyQAAHwwgm8UMABvFTEAnxMDAjATEssyAAAApBMkAAB8MIJvFDQAnxMCAjATEtAqAAAApBMkAAB8MIKMFAUAnxMCAjATEiwsAAAApBMuAAB80IL/FAAAAwAAAKQVNgAAfFCDjBYAAG8XKACfFQMCpBY2AAB8UINvFzAAbxgoAJ8WAwKkFzYAAHxQg4wYAQCMGQEAnxcDAMUUFQABAAAAnxMCAjATEtkvAAAATRMAMTcAAACkFTkAAACAQ00UFUg6AAAATRYTmTsAAABNFRZ6PAAAAOIWQgCkF0QAAHwwhG8YRQCkGUkASBxhxKQaTABLKGHEnxcEAjAXFm09AAAApBdEAAB8MIRvGCkAnxcCAjAXFow+AAAApBdEAAB8MIRvGDAApBlOAE0cYcSfFwMCMBcWYD8AAACkF0QAAHwwhIwYAQCkGVAATxxhxJ8XAwIwFxbHQAAAAKQXRAAAfDCEbxgxAKQZUQBBHGHEnxcDAjAXFkdBAAAAwBdSABIACQASAAQAEgATABIAAQASABQAEgALABIADgASABAAEgACABIACAASAA0AEgAKABIABgASAAMAEgAWABIAEgASABEAEgAMABIAFQASAA8AghcCAFMDVgQAAABAA1cDWANZA1oDWwNcBAAAcEADXQNeA18DYANhA2IDYwNkA2UDZgNnA2gDaQNqA2sDbANtA24DbwNwA3EDcgMCAxEDcwN0AysEAHwwggIAAAAAAAAMQAN1A3YCmpmZmZmZyT8CAAAAAAAA0D8DdwIAAAAAAIA2QAN4A3kEAHzQggN6AgAAAAAAAOA/AgAAAAAAAOg/AywDewKamZmZmZmpPwMMBAB8UIMDfAMhBAAAgEMDfQN+A38DOgM/A4ABA0wDQwUFPT4/QEEDQAQAfDCEApqZmZmZmeE/AzQDQQOBAQRIHGHEA4IBA4MBBEsoYcQDhAEETRxhxAOFAQRPHGHEBEEcYcQGAwEDAQABGAACAAAAAAABAAAAAAABAAAAAAABAAAAAAACAAAAAAAAAAABAAAAAAAAAQAAAAAAAAEAAAAAAAAAAAAAAQAAAAAAAAEAAAAAAAAAAAAAAQAAAAAAAAEAAAAAAAAAAAAAAQAAAAAAAAAAAAABAAAAAAAAAAABAAAAAAAAAQAAAAAAAAAAAQAAAAAAAAAAAAAEAAAAAAAAAAABAAABAAAAAAAAAQAAAQAAAAAAAAEAAAAAAAABAAAAAAAAAQAAAAAAAAMAAAAAAAAAAAEAAAEAAAEAAAAAAAABAAAAAAAAAQAAAAAAAQAAAAAAAQAAAAEAAAAAAQAAAAABAAAAAAAA/QAABwABAAAAAQAAAAEBAAAAAAAAAAAAAQAAAAAAAQAAAAAAAAABAAAAAAAAAAEAAAAAAAAABAAAAAAAAAAAAAAAAAAAAAAAAAAAlwEAAAAABKBW5Is3bBR8kpKOH2yhh0RvMV5yaPu4dkjkT1vina94wZJgk6BflrQ=

local v1 = game:GetService("Players")
local u2 = game:GetService("ReplicatedStorage")
local u3 = game:GetService("RunService")
local u4 = game:GetService("TweenService")
local u5 = require(u2.Shared.Utils.GetPositionNearPlayer)
require(u2.Shared.Types)
local u6 = require(u2.Client.PlayerRender)
local v7 = require(u2.Shared.Framework.Classes.WorldEmitter)
local u8 = require(u2.Client.PlayerControls)
local u9 = require(u2.Shared.Framework.Classes.Maid)
local u10 = require(u2.Client.PetRender)
local u11 = require(u2.Shared.Framework.Services.CollisionGroup)
local u12 = require(u2.Shared.Framework.Utilities.SequenceUtil)
local u13 = require(u2.Client.Effects.Bubble)
local u14 = require(u2.Client.Music)
local u15 = require(u2.Client.Effects.Physics)
local u16 = require(u2.Client.Gui.Utils.PlayLocalSound)
local u17 = v7.new(u2.Assets.Effects.Dirt)
u17.SpreadAngle = 80
u17.Radius = NumberRange.new(0, 3.5)
u17.Rate = 0
u17.GravityMultiplier = NumberRange.new(0.2, 0.25)
u17.Speed = NumberRange.new(22.5, 25)
u17.Transparency = NumberSequence.new(0, 1)
u17.Lifetime = NumberRange.new(0.5, 0.75)
local u18 = v7.new(u2.Assets.Effects.Dust)
u18.Rate = 0
u18.SpreadAngle = 90
u18.Radius = NumberRange.new(0, 2)
u18.Lifetime = NumberRange.new(0.5, 0.75)
u18.GravityMultiplier = NumberRange.new(0.05)
u18.Speed = NumberRange.new(5)
u18.Transparency = NumberSequence.new({ NumberSequenceKeypoint.new(0, 0.2), NumberSequenceKeypoint.new(0.5, 0.2), NumberSequenceKeypoint.new(1, 1) })
local u19 = v1.LocalPlayer
local u20 = workspace.CurrentCamera
local u21 = u19.PlayerGui.ScreenGui
local u22 = {
    ["Fall"] = TweenInfo.new(0.55, Enum.EasingStyle.Circular, Enum.EasingDirection.In),
    ["Shake"] = TweenInfo.new(0.25),
    ["Grow"] = TweenInfo.new(0.5, Enum.EasingStyle.Quint),
    ["Fade"] = TweenInfo.new(1, Enum.EasingStyle.Sine),
    ["Back"] = TweenInfo.new(0.75, Enum.EasingStyle.Back)
}
return function(p23, p24) --[[Function name: Animation, line 60]]
    --[[
    Upvalues:
        [1] = u9
        [2] = u5
        [3] = u19
        [4] = u2
        [5] = u20
        [6] = u11
        [7] = u14
        [8] = u16
        [9] = u3
        [10] = u8
        [11] = u13
        [12] = u10
        [13] = u6
        [14] = u4
        [15] = u22
        [16] = u18
        [17] = u17
        [18] = u12
        [19] = u21
        [20] = u15
    --]]
    local v25 = u9.new()
    local u26 = u5(u19, true)
    local u27 = u2.Assets.Eggs[("%*%*"):format(p23, p24 and " Golden" or "")]:Clone()
    local u28 = u27:GetBoundingBox().Y / 2
    local v29 = Instance.new("Attachment")
    if u27.PrimaryPart then
        v29.Parent = u27.PrimaryPart
        u28 = u27.PrimaryPart.Size.Y / 2
    end
    local v30 = u20.CFrame
    u11:AddModel(u27, "Ignore")
    u27.Parent = workspace.Rendered.Generic
    local u31 = Instance.new("NumberValue")
    u31.Value = 15
    local u32 = Instance.new("NumberValue")
    u32.Value = 1.35
    local u33 = Instance.new("NumberValue")
    local u34 = Instance.new("Highlight")
    u34.OutlineTransparency = 1
    u34.FillTransparency = 1
    u34.FillColor = Color3.new(1, 1, 1)
    u34.Parent = u27
    local v35 = u2.Assets.Particles.Explosion:Clone()
    v35.Lifetime = NumberRange.new(0.75)
    v35.Enabled = false
    v35.Parent = v29
    local v36 = u2.Assets.Particles.Electric:Clone()
    v36.Enabled = false
    v36.Parent = v29
    u14:SetVolume(0)
    u16("SecretEgg")
    local u37 = 0
    local function v47(p38) --[[Anonymous function at line 102]]
        --[[
        Upvalues:
            [1] = u37
            [2] = u26
            [3] = u28
            [4] = u32
            [5] = u31
            [6] = u33
            [7] = u27
            [8] = u20
        --]]
        local v39 = u37 * 36
        local v40 = CFrame.new(u26.Position)
        local v41 = u28 * u32.Value + u31.Value
        local v42 = v40 + Vector3.new(0, v41, 0)
        local v43 = u26.Position + Vector3.new(0, 2.5, 0) + u26.Unit * 10
        if u33.Value > 0 then
            local v44 = math.noise(v39, 0)
            local v45 = math.noise(v39, 0, 100)
            local v46 = math.noise
            v43 = v43 + Vector3.new(v44, v45, v46(v39, 100, 0)) * u33.Value
        end
        u37 = u37 + p38
        u27:PivotTo(v42)
        u27:ScaleTo(u32.Value)
        u20.CFrame = CFrame.new(v43, v42.Position)
    end
    v47(0)
    v25:Add(v29)
    v25:Add(u31)
    v25:Add(u33)
    v25:Add(u32)
    v25:Add(u27)
    v25:Add(u3.Heartbeat:Connect(v47))
    u20.CameraType = Enum.CameraType.Scriptable
    u8:Disable()
    u13:SetVisible(false)
    u10:SetVisible(false)
    u6:SetPlayersVisible(false, true)
    u4:Create(u31, u22.Fall, {
        ["Value"] = 0
    }):Play()
    task.wait(u22.Fall.Time)
    u18.Origin = CFrame.new(u26.Position) + Vector3.new(0, 1, 0)
    u17.Origin = u18.Origin + Vector3.new(0, 1, 0)
    u18:Emit(10)
    u17:Emit(5)
    u4:Create(u33, u22.Shake, {
        ["Value"] = 2
    }):Play()
    task.wait(0.5)
    u4:Create(u33, u22.Shake, {
        ["Value"] = 0
    }):Play()
    task.wait(u22.Shake.Time)
    for v48 = 1, 3 do
        local u49 = TweenInfo.new((v48 + 1) / 3, Enum.EasingStyle.Quart)
        u4:Create(u32, u49, {
            ["Value"] = u32.Value + v48 / 3
        }):Play()
        u4:Create(u33, u22.Shake, {
            ["Value"] = 0.75
        }):Play()
        u4:Create(u20, u22.Back, {
            ["FieldOfView"] = 70 + v48 * 5
        }):Play()
        u4:Create(u34, u49, {
            ["FillTransparency"] = v48 == 3 and 0 or 0.65
        }):Play()
        v35:Emit(1)
        v36:Emit(3)
        v35.Size = u12.transformNumberSequence(v35.Size, function(p50, _) --[[Anonymous function at line 162]]
            return NumberSequenceKeypoint.new(p50.Time, p50.Value * 1.5)
        end)
        u18:Emit(10)
        u17:Emit(5)
        if v48 < 3 then
            task.delay(0.2, function() --[[Anonymous function at line 168]]
                --[[
                Upvalues:
                    [1] = u4
                    [2] = u34
                    [3] = u49
                --]]
                u4:Create(u34, u49, {
                    ["FillTransparency"] = 1
                }):Play()
            end)
            task.wait(u49.Time)
            u4:Create(u33, u22.Shake, {
                ["Value"] = 0
            }):Play()
            task.wait(u22.Shake.Time + 0.25)
        end
    end
    local v51 = Instance.new("Frame")
    v51.Size = UDim2.fromScale(1, 1)
    v51.BackgroundColor3 = Color3.new(1, 1, 1)
    v51.BackgroundTransparency = 1
    v51.Parent = u21
    u4:Create(v51, u22.Fade, {
        ["BackgroundTransparency"] = 0
    }):Play()
    task.wait(u22.Fade.Time + 1)
    u4:Create(v51, u22.Fade, {
        ["BackgroundTransparency"] = 1
    }):Play()
    v25:Cleanup()
    u20.CFrame = v30
    u20.FieldOfView = 70
    local v52 = u19.Character
    if v52 then
        v52 = v52:FindFirstChild("Humanoid")
    end
    if v52 ~= nil then
        u20.CameraSubject = v52
        u20.CameraType = Enum.CameraType.Custom
    end
    u14:SetVolume(0.5)
    u8:Enable()
    u15:Update()
    u13:SetVisible(true)
    u10:SetVisible(true)
    u6:SetPlayersVisible(true, true)
end