--devbgascension

-- Bytecode (Base64):
-- BgM8B0dldE5hbWUFVURpbTIDbmV3Ck5leHROdW1iZXIFQ2xvbmUIUm90YXRpb24IUG9zaXRpb24GUGFyZW50ClVwZGF0ZUljb24JZnJvbVNjYWxlAVgFU2NhbGUGQ3JlYXRlBFBsYXkEdGFzawR3YWl0BFRpbWUHRGVzdHJveQZjcmVhdGUEVHlwZQNQZXQJR2V0QW1vdW50BG1hdGgDbWluBWRlbGF5CEl0ZW1GYWxsBGdhbWURUmVwbGljYXRlZFN0b3JhZ2UKR2V0U2VydmljZQdQbGF5ZXJzDFR3ZWVuU2VydmljZQdyZXF1aXJlBlNoYXJlZAVUeXBlcwVVdGlscwVTdGF0cwhJdGVtVXRpbAtMb2NhbFBsYXllcglQbGF5ZXJHdWkJU2NyZWVuR3VpCF9vdmVybGF5CEluc3RhbmNlBUZyYW1lCmZyb21PZmZzZXQEU2l6ZQdWZWN0b3IyA29uZQtBbmNob3JQb2ludBZCYWNrZ3JvdW5kVHJhbnNwYXJlbmN5CkltYWdlTGFiZWwFTGFiZWwETmFtZQZSYW5kb20JVHdlZW5JbmZvBEVudW0LRWFzaW5nU3R5bGUFUXVhcnQEU2luZQ9FYXNpbmdEaXJlY3Rpb24CSW4AAxABCAAAAHn7AQAAUgMAALwBAVYAAAAAnwEDAvsEAQCHAwQBkAIDAYwDDgBgAwIAAgAAAIIAAQD7AwEAlQQCAmoEAwGkAwUAABAwgPsGAgC8BgaFCAAAAJ8GAgJbBQYHlQQFBowFAACMBgEAjAdkAJ8DBQL7BAMAvAQEOgkAAACfBAIC+wcCALwHB4UIAAAAnwcCAngGBwtbBQYKMAUEOAwAAAAwAwQ7DQAAAPsFBAAwBQQkDgAAAPsFAABSBwQAUggAALwFBSEPAAAAnwUEAfsFBQBSBwQA+wgGAOIJEACkChIAAEQwgE0MA3kTAAAATQsMhBQAAAD7DgIAvA4OhQgAAACfDgICPg0OFfUMCw2fCgMCMAoJOw0AAAC8BQWWFgAAAJ8FBQK8BQXuFwAAAJ8FAgGkBRoAAGSAgfsIBgBNBwhKHAAAAFsGBxufBQIB+wUFAFIHBAD7CAcA4gkQADADCTsNAAAAvAUFlhYAAACfBQUCvAUF7hcAAACfBQIBpAUaAABkgIH7BwcATQYHShwAAACfBQIB+wUAAFIHBAC8BQUhDwAAAJ8FAwG8BQRQHQAAAJ8FAgH7BQEAhwYFAXgGBgJqBgUB+wYBAIcFBgGMBgAAfQUEAAYAAAD7BQEAxgYAAGoGBQGCAAEAHgMBAgAAAAAAAAAAAgAAAAAAAPA/AwIDAwQAEDCAAgAAAAAAAMA/AgAAAAAAAOg/AwQDBQIAAAAAAAA5QAIAAAAAAADgPwMGAwcDCAMJBQENAwoEAEQwgAMLAwwCAAAAAAAAEEADDQMOAw8DEAQAZICBAjMzMzMzM+s/AxEDEgAgEwEYAAAAAAABAAABAAABAgAAAgAAAAAAAAAAAAAAAQAAAAEAAAAAAAAAAQABAAABAAAAAAACAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAIAAAAAAAAAAAAAAAEAAAAAAAIAAAAAAQAAAgAAAAEAAAAAAQAAAiEAAAAACQEDAAAAH00BABEAAAAA8AECAAEAAICCAAEAjAMBAIwFBwD7BgAAUggAALwGBgICAAAAnwYDAEwTAAKkBAUAABAwgJ8EAAJSAQQAjAIBAKgBCwCkBAgAABxggPsGAQC8BgaFCgAAAJ8GAgJbBQYJ+wYCAFIHAACfBAQBiwH1/4IAAQALAxQDFQMWAxcDGAQAEDCAAw8DGQQAHGCAApqZmZmZmbk/AwQAPhoBGAAAAAABAgAAAAAAAAAAAAAAAAABAAAAAAAAAAAA/wM/AAAAAA4AAAECAHSjAAAApAABAAAAAEBvAgIAvAAAFgMAAACfAAMCpAEBAAAAAEBvAwQAvAEBFgMAAACfAQMCpAIBAAAAAEBvBAUAvAICFgMAAACfAgMCpAMHAAAAYEBNBQASCAAAAE0EBe8JAAAAnwMCAqQEBwAAAGBATQgAEggAAABNBwihCgAAAE0GByELAAAATQUG0AwAAACfBAICTQgBMQ0AAABNBwiZDgAAAE0GB3oPAAAATQUGmxAAAACkBhMAAEgQgW8HFACfBgICpAcXAABYUIGMCJYAjAmWAJ8HAwIwBwYvGAAAAKQIHAAAbKCBPgcIGTAHBugdAAAAjAcBADAHBjoeAAAApAcTAABIEIFvCB8AnwcCAqQIIQAAgFCBjAkBAIwKAQCfCAMCMAgHLxgAAACMCAEAMAgHOh4AAABvCCIAMAgHuiMAAAAwBgckJAAAAKQIJgAASFCCnwgBAqQJKAAASHCCbwopAKQLLQAsrKDCnwkDAqQKKAAASHCCbwspAKQMLwAurKDCpA0yADHAoMKfCgQC/wsAAAAAAADADDMAEgAEABIACwASAAgAEgAGABIABQASAAIAEgAJABIACgDADTQAEgAEABIACAASAAwAgg0CADUDGwQAAABAAxwDHQMeAx8DIAQAAGBAAyEDIgMjAyQDJQMmAycDKAMpAyoDAwQASBCBAysDAgMsBABYUIEDLQIAAAAAAAAAQAMuAy8EAGyggQMwAzEDMgMKBACAUIEDMwM0AwgDNQQASFCCAzYEAEhwggIAAAAAAADgPwM3AzgDOQQsrKDCAzoELqygwgM7AzwEMcCgwgYABgECAAEBAAEYAAIAAAAAAAEAAAAAAAEAAAAAAAIAAAAAAAABAAAAAAAAAAAAAAIAAAAAAAAAAgAAAAEAAAAAAAABAAAAAAEAAAIAAAABAAAAAAAAAQAAAQAAAQACAAACAAAAAAABAAAAAAAAAAIABAAAAAAAAAAAHgAAAAkBAAAAAAJ8gHFOHJ93O05EG9pAH9OENIzPB6TUZmOVtJSpRCAhxBp90aEyRTaK

local v1 = game:GetService("ReplicatedStorage")
local v2 = game:GetService("Players")
local u3 = game:GetService("TweenService")
require(v1.Shared.Types)
local u4 = require(v1.Shared.Utils.Stats.ItemUtil)
local u5 = v2.LocalPlayer.PlayerGui.ScreenGui._overlay
local u6 = Instance.new("Frame")
u6.Size = UDim2.fromOffset(150, 150)
u6.AnchorPoint = Vector2.one / 2
u6.BackgroundTransparency = 1
local v7 = Instance.new("ImageLabel")
v7.Size = UDim2.fromScale(1, 1)
v7.BackgroundTransparency = 1
v7.Name = "Label"
v7.Parent = u6
local u8 = Random.new()
local u9 = TweenInfo.new(0.5, Enum.EasingStyle.Quart)
local u10 = TweenInfo.new(0.5, Enum.EasingStyle.Sine, Enum.EasingDirection.In)
local u11 = {}
local function u18(p12) --[[Anonymous function at line 32]]
    --[[
    Upvalues:
        [1] = u4
        [2] = u11
        [3] = u8
        [4] = u6
        [5] = u5
        [6] = u3
        [7] = u9
        [8] = u10
    --]]
    local v13 = u4:GetName(p12)
    local v14 = u11[v13] or 0
    if v14 <= 14 then
        u11[v13] = v14 + 1
        local v15 = UDim2.new(u8:NextNumber() * 0.75 + 0.125, 0, 1, 100)
        local v16 = u6:Clone()
        v16.Rotation = (u8:NextNumber() - 0.5) * 25
        v16.Position = v15
        v16.Parent = u5
        u4:UpdateIcon(v16, p12)
        u3:Create(v16, u9, {
            ["Position"] = UDim2.fromScale(v15.X.Scale, 0.5 - u8:NextNumber() / 4)
        }):Play()
        task.wait(u9.Time * 0.85)
        u3:Create(v16, u10, {
            ["Position"] = v15
        }):Play()
        task.wait(u10.Time)
        u4:UpdateIcon(v16)
        v16:Destroy()
        local v17 = u11
        v17[v13] = v17[v13] - 1
        if u11[v13] <= 0 then
            u11[v13] = nil
        end
    end
end
return function(p19) --[[Function name: ItemFall, line 62]]
    --[[
    Upvalues:
        [1] = u4
        [2] = u8
        [3] = u18
    --]]
    if p19.Type ~= "Pet" then
        local v20 = u4
        for _ = 1, math.min(7, v20:GetAmount(p19)) do
            task.delay(u8:NextNumber() * 0.1, u18, p19)
        end
    end
end