--devbgascension

-- Bytecode (Base64):
-- BgPwAQVDbG9uZQROb25lBmlwYWlycw5HZXREZXNjZW5kYW50cwhCYXNlUGFydANJc0EETmFtZQ1TcGF3blBsYXRmb3JtBXRhYmxlBmluc2VydARtYXRoBnJhbmRvbQRTaXplAVgDbWF4AVoIUG9zaXRpb24BWQdWZWN0b3IzA25ldwdDYXBzdWxlBUNvbG9yBkNvbG9yMwdmcm9tSFNWB1NjYWxlVG8GQ0ZyYW1lB1Bpdm90VG8QSXRlbUJpbGxib2FyZEd1aQhDbGF3SXRlbQZIaXRCb3gHQWRvcm5lZQlQbGF5ZXJHdWkJU2NyZWVuR3VpBlBhcmVudARJY29uClVwZGF0ZUljb24ISXRlbUdVSUQMU2V0QXR0cmlidXRlDENsYXdUb3lNb2RlbAZBZGRUYWcDQWRkB0VuYWJsZWQIc3Bhd25Ub3kKQm9udXNJdGVtcwVwYWlycwR0YXNrBHdhaXQMZ2VuZXJhdGVUb3lzBlRhcmdldA50b2dnbGVDbGF3T3BlbgF4AXkFY2xhbXANdXBkYXRlQ2xhd1BvcwlIZWFydGJlYXQEV2FpdAhkcm9wQ2xhdwNyYWQJd29ya3NwYWNlDUN1cnJlbnRDYW1lcmEDc2luA2Nvcwx1cGRhdGVDYW1lcmEFSW5wdXQHQnV0dG9ucwREcm9wF3VwZGF0ZUlucHV0Rm9yRGlyZWN0aW9uBE1vZGUHS2V5Q29kZQ5Vc2VySW5wdXRTdGF0ZQRFbnVtBUJlZ2luBkJ1dHRvbgdQcmVzc2VkEHByb2Nlc3NVc2VySW5wdXQScHJvY2Vzc0J1dHRvbklucHV0EE1vdXNlQnV0dG9uMURvd24HQ29ubmVjdA5Nb3VzZUJ1dHRvbjFVcApNb3VzZUxlYXZlEWFwcGx5QnV0dG9uRXZlbnRzE2NsaWNrYWJsZUJ1dHRvbk5vb3AHRGVmYXVsdAtob29rQ29udHJvbAREb25lB0NsZWFudXAKQ2FtZXJhVHlwZQ1DYW1lcmFTdWJqZWN0C0ZpZWxkT2ZWaWV3B2NsZWFudXAGSGFzVGFnDHdhc0NvbGxlY3RlZAxHZXRBdHRyaWJ1dGUQR3JhYk1pbmlnYW1lSXRlbQpGaXJlU2VydmVyC1NtYWxsUmV3YXJkBlJlbW92ZQ5GaW5kRmlyc3RDaGlsZApDYW1lcmFMZWZ0C0NhbWVyYVJpZ2h0BHNpZ24CVXAERG93bgVSaWdodARMZWZ0EmZyb21FdWxlckFuZ2xlc1hZWgVWYWx1ZQxEaXNwbGF5TW9kZWwLR2V0Q2hpbGRyZW4HR3JhYmJlcghSb2RfV2VsZAtQaXZvdE9mZnNldAdJbnZlcnNlAkMwDkZpbmlzaE1pbmlnYW1lCEZpbmlzaEF0A25vdwhDb250cm9scwVUaW1lchHij7AgVGltZSBMZWZ0OiAlKgpmb3JtYXRUaW1lBmZvcm1hdARUZXh0BUl0ZW1zA0dldAdDb250ZW50CEl0ZW1OYW1lB0dldE5hbWUISXRlbUluZm8MRm9ybWF0QW1vdW50CUdldFJhcml0eQlMZWdlbmRhcnkFQ3ljbGUHUmFpbmJvdwVTcGVlZAxSYXJpdHlDb2xvcnMKVGV4dENvbG9yMw5Db2xsZWN0ZWRJdGVtcwxzdGF0ZUNoYW5nZWQLQ2xhd01hY2hpbmUEQ2xhdwlCYXNlUGl2b3QIR2V0UGl2b3QGSWdub3JlCEFkZE1vZGVsD0lnbm9yZUNvbGxpc2lvbgtBZGRCYXNlUGFydAhJbnN0YW5jZQ1BbGlnblBvc2l0aW9uFVBvc2l0aW9uQWxpZ25tZW50TW9kZQ1PbmVBdHRhY2htZW50A1JvZAZBdHRhY2gLQXR0YWNobWVudDAITWF4Rm9yY2UOUmVzcG9uc2l2ZW5lc3MTQXBwbHlBdENlbnRlck9mTWFzcxBBbGlnbk9yaWVudGF0aW9uGE9yaWVudGF0aW9uQWxpZ25tZW50TW9kZQlBbGlnblR5cGUHQWxsQXhlcwlNYXhUb3JxdWUKQmFzZU9mZnNldAlTdGlmZm5lc3MIRnJpY3Rpb24KU2NyaXB0YWJsZQpDZW50ZXJQYXJ0CklucHV0QmVnYW4KSW5wdXRFbmRlZAxVSUxpc3RMYXlvdXQLQ29sbGVjdFBhcnQHVG91Y2hlZAVzcGF3bgNydW4EZ2FtZRFSZXBsaWNhdGVkU3RvcmFnZQpHZXRTZXJ2aWNlEFVzZXJJbnB1dFNlcnZpY2UKUnVuU2VydmljZQxUd2VlblNlcnZpY2UHUGxheWVycwdyZXF1aXJlBlNoYXJlZAVUeXBlcwlGcmFtZXdvcmsHQ2xhc3NlcwZTcHJpbmcGQ2xpZW50DlBsYXllckNvbnRyb2xzBE1haWQDR3VpBVV0aWxzEVNldENvcmVHdWlFbmFibGVkCEd1aUZyYW1lB05ldHdvcmsGUmVtb3RlCVV0aWxpdGllcwRNYXRoBFRpbWUPQ2xpY2thYmxlQnV0dG9uD0F1dG9CdXR0b25Db2xvcgdQYWxldHRlCFNlcnZpY2VzDkNvbGxpc2lvbkdyb3VwBVN0YXRzCEl0ZW1VdGlsA0hVRAlJbnB1dE1vZGUEUG9vbBBDcmVhdGVCaW5kaW5nTWFwDEFuaW1hdGVDb2xvcglDb25zdGFudHMOUGxheUxvY2FsU291bmQKUm9ib3QgQ2xhdwZBc3NldHMJTWluaWdhbWVzC0xvY2FsUGxheWVyC01pbmlnYW1lSFVECE1vdmVtZW50CFRlbXBsYXRlCEtleWJvYXJkB0dhbWVwYWQBVwFTAUEBRAFRAUUBRgZEUGFkVXAIRFBhZERvd24IRFBhZExlZnQJRFBhZFJpZ2h0CEJ1dHRvbkwxCEJ1dHRvblIxCEJ1dHRvblIyBUltYWdlClByb3BlcnRpZXMccmJ4YXNzZXRpZDovLzEzNDg3MzU4OTY2OTI1MAhSb3RhdGlvbgAYAgABAAAABfsAAAC8AAA6AAAAAJ8AAgCCAAAAAQMBADAAARgAAAAAADEAAAAAAwEBAAAABvsCAABNAQI/AAAAAFICAACfAQIBggABAAEDAgAyAAEYAAAAAAABMwAAAAARAgYAAAcEAAAFAgMPtQH/AgAAAAAAAKQDAQAAAABA+wQAALwEBEcCAAAAnwQCAJ8DAARRAxAAbwoDALwIB/4EAAAAnwgDAg4ICwBNCAe6BQAAAPAICAAGAACAnjQCBQcAAABSCQIAUgoHAKQICQAAIHCAnwgDAW4D7/8CAACAHAMCAA0DAgAKAACAggABAKQEDQAAMLCAHAUCAJ8EAgKHAwIETQQDLw4AAABNCAR5EQAAAD4HCBB4BgcPgRIGBBIAAABvBxIApAUUAABMsICfBQMCTQkEexUAAAA+CAkQeAcID4ESBwQSAAAAbwgSAKQGFAAATLCAnwYDAqQKDQAAMLCAnwoBAngJChZbCAkQCQcIBaQLDQAAMLCAnwsBAngKCxZbCQoQCQgJBk0NAzsZAAAATQwNeBoAAABNDgR4GgAAAD4NDhBDCwwNlQoLGJUJChdNDQM7GQAAAE0MDXkRAAAAQwsMB00PAzsZAAAATQ4PexUAAABDDQ4INDYLBAkNAABSDAkApAodAABwsIGfCgQC+wwBAE0LDNAeAAAAvAsLOh8AAACfCwICTQwLpCAAAACkDSMAAIgQgqQODQAAMLCAnw4BAm8PJABvECUAnw0EAjANDKQgAAAA+w4CALwMCzQmAAAAnwwDAaQOKAAAcHCCUg8KAJ8OAgC8DAvCKQAAAJ8MAAH7DQEATQwNQyoAAAC8DAw6HwAAAJ8MAgJvDisAUg8AAHMNDg8wDQy6BQAAAE0NCxgsAAAAMA0MFC0AAAD7DwMATQ4PmS4AAABNDQ56LwAAADANDCQwAAAA+w0EAE0PDK4xAAAAUhABALwNDSEyAAAAnw0EAW8PMwBSEAAAvA0LLjQAAACfDQQBbw81ALwNC0U2AAAAnw0DAfsNAAAwDQskMAAAAPsNBQBSDwwAvA0NXzcAAACfDQMB+w0FAFIPCwC8DQ1fNwAAAJ8NAwGpDQEAMA0M8DgAAACCCwIAOQMDBAAAAEADBAMFAwYDBwMIAwkDCgQAIHCAAgAAAAAAAAAAAwsDDAQAMLCAAw0CAAAAAAAA+D8CAAAAAAAAAEADDgKamZmZmZnJPwMPBABMsIADEAIAAAAAAADgPwIAAAAAAAAIQAIAAAAAAADwPwMRAxIDEwMUBABwsIEDFQMBAxYDFwMYBACIEIICZmZmZmZm5j8CMzMzMzMz4z8DGQMaBABwcIIDGwMcAx0DHgMfAyADIQMiAyMDJAMlAyYDJwMoAykDKgCfASsBGAAAAgAAAAAAAAABAAAAAAAAAAABAAAAAAAA/gAGAAABAwAAAAABAAMAAAAAAAAAAAABAAAAAAAAAAAAAgAAAAAAAQAAAAAAAQAAAAAAAAAAAAMAAAAAAgAAAAAAAAD9AAAGAAAAAAABAAAAAAAAAAAAAAABAAAAAQAAAAAAAAIAAAAAAAEAAAAAAQAAAAEAAAAAAAABAAAAAAAAAgAAAAABAAAAAQAAAgAAAAABAAAAAAIAAAKgAAAAAAkAAgAAABP7AQAATQABZQAAAACkAQIAAAAQQFICAACfAQIEFwEIAPsGAQBSBwQAUggFAJ8GAwGkBgUAABAwgG8HBgCfBgIBbgH3/wIAAACCAAEABwMsAy0EAAAQQAMuAy8EABAwgAKamZmZmZm5PwDUATABGAAAAAIAAAAAAQAAAAEAAAD+AATVAAAAAAYBAQAABgMAAAUBAQ77AQAADgACAIwDAQBlAAEAbwMAAIwEAACMBQAATDYAAqQCAwAACBCAnwIEAjACASwEAAAAggABAAUCAAAAAAAA4D8DEwMUBAAIEIADMQCBAjIBGAAAAAAAAAAAAAAAAAABAgEAAAAOAgIAAAsEAAEFAgICCAc7AT/7BAAATQIEmQAAAAD7BAAATQMEmAEAAAD7BAAA+wgAAE0HCJkAAAAAQwYHAIwHAACMCAEATC4AAqQFBAAADCCAnwUEAjAFBJkAAAAA+wQAAPsIAABNBwiYAQAAAEMGBwGMBwAAjAgBAEwuAAKkBQQAAAwggJ8FBAIwBQSYAQAAAPsEAQCMBoQD+wsAAE0KC5kAAAAAJgkKAm8KBQBvCwYATC4AAqQIBAAADCCAnwgEAowJAAD7DQAATQwNmAEAAAAmCwwDbwwFAG8NBgBMLgACpAoEAAAMIICfCgQCTDYAAqQHCQAAIHCAnwcEAgkFBgcwBQQsCgAAAIIAAQALAzMDNAMLAzUEAAwggAKamZmZmZnJvwKamZmZmZnJPwMTAxQEACBwgAMxAIgCNgEYAAAAAAAAAQAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABCQEAAAAJAAcAAABaqQABAN4AAAD7AAEAbwEAADABACwBAAAApAAEAAAMIIBvAQUAnwACAfsAAgBvAQYAMAEALAEAAACkAAQAAAwggIwBAQCfAAIBqQABAN4AAwD7AAEAbwEHADABACwBAAAApAAEAAAMIICMAQEAnwACAYwAAAD7AgQATQECmQgAAABvAgkAtwIHAAEAAAD7AgQATQECmAoAAABvAgkAYAIhAAEAAAD7BQQATQQFmQgAAAAEAwQM+wYEAE0FBpgKAAAABAQFDEMCAwQEAQIL+wIFAPsHBABNBgeZCAAAAOwFBgE5BAUACQMEAPsIBABNBwiYCgAAAOwGBwE5BQYACQQFAJ8CAwH7AwYATQID/Q0AAAC8AgL3DgAAAJ8CAgJSAAIASADU/6QBBAAADCCAbwIPAJ8BAgH7AQIAbwIAADACASwBAAAApAEEAAAMIIBvAgsAnwECAakBAADeAQAAqQEAAN4BAwCCAAEAEAcAAIA/AAAAAAAAAAAAAAAAAzEDLgMvBAAMIIACAAAAAAAA+D8HAAAAPwAAAAAAAAAAAAAAAAcAAAAAAAAAAAAAAAAAAAAAAzMC8WjjiLX45D4DNAIAAAAAAADgPwIAAAAAAAAAQAM3AzgCMzMzMzMz0z8AkgI5ARgRAAEAAAABAAAA7QAAABUAAAABAAEAAAABAAAAAQEAAAAAAAAAAAAAAAEAAAAAAAAAAAABAAAAAAAAAAAAAAAAAAEAAAAAAAD9BQAAAOEAAAAhAAAAAQABAAECAQAAAA0AAwAABwAAAQgGMAE1+wIAAJUBAgC7FgECpAADAAAIEICfAAICpAIFAAAAQEBNAQJIBgAAAKQCCQAAIHCA+wUBAKQGCQAAIHCAjAkMAPsKAgAJCAkKuxgAA1IKAACkCQsAACgQgJ8JAgIJBwgJjAgDAIwLDAD7DAIACQoLDLsJAANSDAAApAsNAAAwEICfCwICCQkKC58GBAIJBAUGTQMEOw4AAAD7BgEATQUGOw4AAACMBwAA+wgCAIwJAABMNgACpAYQAAAg8ICfBgQCJgQFBp8CAwIwAgGFBwAAAIIAAQARAgAAAAAAgFZAAwsDOgQACBCAAzsEAABAQAM8AxoDFAQAIHCAAz0EACgQgAM+BAAwEIADEQMTBAAg8IAAsgI/ARgAAAAAAAABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAATMBAAAABAEEAAAAFPsBAAArAQEAggABAPsDAQBNAgPcAAAAAIcBAgArAQQA+wMBAE0CA9MBAAAAhwECAPsCAgBqAQIADgEEAPAAAwACAACA+wIDAJ8CAQGCAAEAAwNAA0EDQgDUAkMBGAAAAQMAAAAAAAAAAAEAAgEAAQADVQEAAAAKAgcAAAcEAAAFAgcBOA4BAQCCAAEA+wMAAPsFAQBNBAUNAAAAAIcCAwQrAgEAggABAE0EALMBAAAAhwMCBCsDAQCCAAEA+wUCAIcEBQNNBgD/AgAAAKQHBQAECDDA8QYCAAcAAACpBQABqQUBAA4EBwBNBgSsBgAAAG8IBwBSCQUAvAYGLggAAACfBgQB+wcDAE0GB9wJAAAAagUGA/sGBAArBgEAggABAPsIAwBNBwjcCQAAAIcGBwMrBgQA+wgDAE0HCNMKAAAAhwYHA/sHBQBqBgcDDgYEAPADAwALAACA+wcGAJ8HAQGCAAEADANEA0UDRgNHA0gEBAgwwANJA0oDJgNAA0EDQgDjAksBGA8BAwAAAAABAQMAAAEBAwABAAAAAAAAAAEBAAAAAAAAAwAAAN0AAQMAAAAAAAAAAAEAAgEAAQAcVQEAAAAFAgUAAAcEAAAFAg8BHfsCAAAOAgMA8AACAAAAAICCAAEA+wMBAE0CA9MBAAAAagECAPsCAgArAgEAggABAPsEAQBNAwTcAgAAAIcCAwArAgQA+wQBAE0DBNMBAAAAhwIDAPsDAwBqAgMADgIEAPAAAwAAAACA+wMEAJ8DAQGCAAEAAwNCA0EDQAD8AkwBGCgAAAABAwAAANQAAQMAAAAAAAAAAAEAAgEAAQAlVQEAAAAEAAYAAAAf+wAAAPsBAQAOAQMA8AACAAAAAICCAAEA+wICAE0BAtMBAAAAqQIBAGoCAQD7AQMAKwEBAIIAAQD7AwIATQID3AIAAACHAQIAKwEEAPsDAgBNAgPTAQAAAIcBAgD7AgQAagECAA4BBADwAAMAAAAAgPsCBQCfAgEBggABAAMDQgNBA0AAhgMAARgy9gAAAAEDAAAAANQAAQMAAAAAAAAAAAEAAgEAAQAqVQEAAAAEAAYAAAAf+wAAAPsBAQAOAQMA8AACAAAAAICCAAEA+wICAE0BAtMBAAAAqQIAAGoCAQD7AQMAKwEBAIIAAQD7AwIATQID3AIAAACHAQIAKwEEAPsDAgBNAgPTAQAAAIcBAgD7AgQAagECAA4BBADwAAMAAAAAgPsCBQCfAgEBggABAAMDQgNBA0AAigMAARg28gAAAAEDAAAAANQAAQMAAAAAAAAAAAEAAgEAAQAuVQEAAAAEAAYAAAAf+wAAAPsBAQAOAQMA8AACAAAAAICCAAEA+wICAE0BAtMBAAAAqQIAAGoCAQD7AQMAKwEBAIIAAQD7AwIATQID3AIAAACHAQIAKwEEAPsDAgBNAgPTAQAAAIcBAgD7AgQAagECAA4BBADwAAMAAAAAgPsCBQCfAgEBggABAAMDQgNBA0AAjgMAARg67gAAAAEDAAAAANQAAQMAAAAAAAAAAAEAAgEAAQAyVQEAAAAHAgYAAAcEAAAFAg8HMfsCAABNBAFhAAAAANkGAAASAAAAEgIBABICAgASAgMAEgIEABICBQC8BATHAQAAAJ8EAwC8AgJfAgAAAJ8CAAH7AgAATQQBMgMAAADZBgEAEgAAABICAQASAgIAEgIDABICBAASAgUAvAQExwEAAACfBAMAvAICXwIAAACfAgAB+wIAAE0EAd0EAAAA2QYCABIAAAASAgEAEgICABICAwASAgQAEgIFALwEBMcBAAAAnwQDALwCAl8CAAAAnwIAAYIAAQAFA00DTgMpA08DUAMLDA2FA1EBGAAAAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAAAAAOGAQAAAAEBAAAAAAGCAAEAAACWA1IBGACYAQAAAAgBCAAAAB9NAQC6AAAAAE0CAKwBAAAA+wMAAFIEAgD7BwEATQYHrAEAAABNBQY6AgAAAJ8DAwH7AwIAUgQCAPsFAwCfAwMB+wMEAPsFBQBSBgAAUgcBAJ8FAwC8AwNfAwAAAJ8DAAH7AwYAUgQBAFIFAgCfAwMB+wMHAGoAAwGCAAEABAMHA0kDUwMpAJoDVAEYAAABAAIAAAAAAAAAAQAAAAIAAAAAAAAAAQAAAAIAAZsBAAAAAgAHAAAAF6kAAADeAAAA+wABALwAADUAAAAAnwACAfsAAgC8AADxAQAAAJ8AAgH7AAMA+wEEADABACoCAAAA+wADAPsBBQAwAQCcAwAAAPsAAwD7AQYAMAEAYQQAAACCAAEABQNVA1YDVwNYA1kAsgNaARgAAAMAAAABAAAAAwAAAAEAAAABAAAAAbMBAAAABwEFAAAASU0BALoAAAAA8AFFAAEAAIBNAQAkAgAAAA4BQQBNAQAkAgAAAG8DAwC8AQHeBAAAAJ8BAwIOAToATQEAJAIAAABvAwUAvAEBEgYAAACfAQMCKwEzAE0BACQCAAAAbwMHALwBARIGAAAAnwEDAg4BLAD7BAAATQMEZQgAAACHAgMBDgInAE0CACQCAAAAbwQFAKkFAQC8AgIuCQAAAJ8CBAH7AgEAbwQKAFIFAQC8AgJrCwAAAJ8CBAH7AgIAbwMMAJ8CAgH7AgMATQQAJAIAAAC8AgJpDQAAAJ8CAwH7BAQATQMEmQ4AAABNAgN6DwAAAG8FEABSBgEAcwQFBrwCAgMRAAAAnwIDAg4CBQD7AwMAUgUCALwDA2kNAAAAnwMDAYIAAQASAwcDHgMiAycDWwNcA10DJQMsAyYDXgNfA2ADYQMgAyEDHQNiAMIDAAEYAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQAAAAAAAQAAAAAAAQAAAAAAAAEAAAAAAAEAAAIAAAAAAAEAAAAAAAAAAAAAAQEAAAAABMMBAAAAGQATAAAAhwKMAAAA+wEAAA4B/gD7BAEATQMEVwAAAAAOAwIAjAL//2UAAQCMAgAA+wUBAE0EBQsBAAAADgQCAIwDAQBlAAEAjAMAAEMBAgP7AgIADgIZAPsDAwAhAgMCbwMDAGADIAACAAAA+wQDAPsJAwB4CAkEuy8IAqQHBwAAGFCAnwcCAlsGBwQJBQYAQwMEBYwEAACMBWgBTC4AAqQCCQAAIFCAnwIEAt4CAwD7AgQAnwIBAWUACwANAQoACgAAAPsEAwCMB1oACQYHAQkFBgBDAwQFIQIDAt4CAwD7AgQAnwIBAfsEAwCVAwQLuxYDAqQCDQAAMFCAnwICAvsGAQBNBQZzDgAAAA4FAgCMBAEAZQABAIwEAAD7BwEATQYHHg8AAAAOBgIAjAX//2UAAQCMBQAAQwMEBfsHAQBNBgcFEAAAAA4GAgCMBQEAZQABAIwFAAD7CAEATQcIxhEAAAAOBwIAjAb//2UAAQCMBgAAQwQFBvsFBQAOBQIAjAMAAIwEAAD7BQYAuxgCA1IKAgCkCRMAAEhQgJ8JAgIJCAkDCQcIALsJAgNSCwIApAoVAABQUICfCgICCQkKBAkICQAmBgcIuxgCA1ILAgCkChMAAEhQgJ8KAgIJCQoECQgJALsJAgNSDAIApAsVAABQUICfCwICCQoLAwkJCgBDBwgJnwUDAfsGBwCkBxgAAFxggYwK/P/7CwgACQkKC/sLCQBNCguZGQAAAAkICQqMCQAAjAz8//sNCAAJCwwN+w0JAE0MDZgaAAAACQoLDJ8HBAIJBQYH+wYKAFIIBQC8BgbCGwAAAJ8GAwH7CQsACQgFCaQJHQAAcGCB+w0MAE0MDeweAAAATQsMeR8AAAC7FgsCpAoNAAAwUICfCgICjAsAAPsPDABNDg/sHgAAAE0NDnsgAAAAuxYNAqQMDQAAMFCAnwwCAp8JBAIJBwgJpAgYAABcYIGMCQAAbwwhAPsNCAAJCwwN+w4NAE0NDuweAAAATQwNeR8AAAAJCgsMjAsAAJ8IBAIJBgcI+wcOAE0IBjsiAAAAMAgHOyIAAAD7Bw8AMAYHhRYAAACkByQAAAAwQvsJCgBNCAmXJQAAALwICGgmAAAAnwgCAJ8HAAQXByQATQwLuicAAADwDCEAKAAAgG8OKQC8DAsDKgAAAJ8MAwIODBsATQwLvysAAABNDQv8KQAAAKQQHQAAcGCBjBEAAIwSAACMFSgA+xgQAE0XGOweAAAATRYXeR8AAAAJFBUWuxYUAqQTDQAAMFCAnxMCAp8QBAIJDwwQvBAM2iwAAACfEAICCQ4PEDAODe0tAAAAbgfb/wIAAAD7CBEATQcI/S4AAAC8Bwf3LwAAAJ8HAgJSAAcASAAA//sBEgBvAzAAvAEBazEAAACfAQMBggABADIDYwNkAgAAAAAAgHZAAvFo44i1+OQ+AgAAAAAAgGZAAwsDZQQAGFCAAzUEACBQgAIAAAAAAAAAAAIAAAAAAIBWQAM6BAAwUIADZgNnA2gDaQM9BABIUIADPgQAUFCAAxoDFAQAXGCBAzMDNAMbA2oEAHBggQNrAw4DEAIAAAAAAAASwAMRAy0EAAAwQgNsA20DBwNuA28DYgNwA3EDcgM3AzgDcwNfANMDAAEYAAEAAQAAAAAAAAAAAAAAAAAAAQABAAAAAAEAAAAAAAAAAAAAAAAAAAAAAQAAAgABAAAAAAAAAQACAAAAAAABAAAAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAAABAAEBAgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAAAAAAAAAAEAAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEAAAAAAQAAAQAAAAAAAAAAAAEAAAAAAAAAAAEAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP0ABgAAAAAAAOIiAAAAAAHUAQAAAAgAAwAAACP7AwAATQID3gAAAAD7BAEATQMEmgEAAACfAwECJgECA4ESAQQCAAAAbwICAKQABQAAEDCAnwADAvsEAgBNAwRQBgAAAE0CA0sHAAAATQECPAgAAABvAwkA+wYBAE0FBtkKAAAAUgYAAKkHAQCfBQMCvAMDjQsAAACfAwMCUgIDADACAfUMAAAAggABAA0DdAN1AgAAAAAAAAAAAwsDDwQAEDCAA3YDQgN3A3gDeQN6A3sA+wMAARgAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAAAAAAAAf0BAAAADgEFAAAATU0BADgAAAAAxgIAAMYDAABkAUEA+wYAALwGBn8BAAAAnwYCAk0IBr4CAAAATQcIAQMAAAD7CAEAUgoFALwICFYEAAAAnwgDAjAIB/UFAAAA+wgBAE0LBr4CAAAATQoLHgYAAABSCwUAvAgI9QcAAACfCAQB+wgBAE0KBq4IAAAAUgsFALwICCEJAAAAnwgEAfsIAQBSCgUAvAgIJQoAAACfCAMC8AgMAAsAAID7CgIATQkKeQwAAABSCgcAbwsNAOIMDwBvDRAAMA0MLA4AAACfCQQBZQALAPsKAgBNCQo/EQAAAFIKBwCfCQIB+wsDAE0KCxQSAAAAhwkKCDAJB3MTAAAA+woEAE0JCpgUAAAAMAkGJBUAAABuAb7/AgAAAPsBAAC8AQE1FgAAAJ8BAgGCAAEAFwN8A30DfgN/A4ABA3sDgQEDggEDIwMkA4MBA4QBA4UBA4YBA4cBBQEOApqZmZmZmdk/AwIDiAEDiQEDigEDIgNVAIIEiwEBGAAAAAAAAQAAAAIAAAABAAAAAAAAAgAAAAAAAAAAAQAAAAAAAAIAAAAAAQABAAAAAAAAAAAAAAIAAAAAAQAAAAAAAwAAAADvABUAAAABAwIAAAAvARgAAACABP8BAAAAAAAA+wMAAE0CA+8AAAAAnwIBAqkDAQD7BAEAvAQEOgEAAACfBAIC+wUCADAFBCQCAAAAUgcEALwFAl8DAAAAnwUDAfsFAwC8BQU6AQAAAJ8FAgL7BgIAMAYFJAIAAABSCAUAvAYCXwMAAACfBgMB+wcEAE0GB14EAAAAvAYGOgEAAACfBgICpAcGAAAAUEAwBwYkAgAAAFIJBgC8BwJfAwAAAJ8HAwFNBwadBwAAAG8KCAC8CAcSCQAAAJ8IAwIrCAMAvAgHUgoAAACfCAICbwsIAFIMCAC8CQcuCwAAAJ8JBAFNDAdjDQAAAE0LDC8OAAAATQoLeQ8AAAA+CQoM2QoAABIABgASAgQAEgAJABICBQASAgYAEgACANkLAQASAAAAEgAKAPsMBwBSDgcAbw8QALwMDPIRAAAAnwwEAaQMEwAAACBBvA0GRxQAAACfDQIAnwwABBcMCwBvExUAvBEQ3hYAAACfEQMCDhEGAPsRBwBSExAAbxQQALwREa4XAAAAnxEEAW4M9P8CAAAApAwZAAAAgIFvDRoAnwwCAqQNHgAdcLDBMA0MDR8AAABNDweXIAAAAE0OD8QhAAAATQ0OVCIAAAAwDQxrIwAAAIwOIE4JDQ4JMA0MMyQAAACMDcgAMA0M1CUAAACpDQAAMA0MwyYAAABNEAeXIAAAAE0PEMQhAAAATQ4PhScAAABNDQ47KAAAADANDDsoAAAATQ4HlyAAAABNDQ7EIQAAADANDCQCAAAApA0ZAAAAgIFvDikAnw0CAqQOKwAdqLDBMA4NDR8AAACkDi4ALbCwwTAODUYsAAAATRAHlyAAAABNDxDEIQAAAE0OD1QiAAAAMA4NayMAAABvDy8ACQ4PCTAODaMwAAAAjA7IADAODdQlAAAATRAHlyAAAABNDxDEIQAAAE0OD4UnAAAAMA4NhScAAABNDweXIAAAAE0OD8QhAAAAMA4NJAIAAABNDgeXIAAAAG8QMQC8Dg4SCQAAAJ8OAwIrDgkATQ8HlyAAAAC8Dw9SCgAAAJ8PAgK8Dw/aMgAAAJ8PAgIJDg8ITQ8HlyAAAABvETEAUhIOALwPDy4LAAAAnw8EAfsQCABNDxDvAAAAAG8QMwCfDwICbxA0ADAQD/w1AAAAbxA2ADAQDxA3AAAA4hA6AIwRAAAwERCZOAAAAIwRAAAwERCYOQAAAPsSCABNERLvAAAAAG8SOwCfEQICbxI0ADASEfw1AAAAbxI2ADASERA3AAAA2RICABIAEQCpEwAAqRQAANkVAwASABAAEgAPAPsXCABNFhfvAAAAAG8XMwCfFgICbxc8ADAXFvw1AAAAjBcBADAXFhA3AAAA2RcEABIBE/8SABYAEgARABIBFP8SABAAEgAVABICCQCkGgYAAABQQE0ZGkg9AAAATRgZKj4AAACkGwYAAABQQE0aG0g9AAAATRkanD8AAACkHAYAAABQQE0bHEg9AAAATRobYUAAAACkHAYAAABQQE0bHEg9AAAApBxCAEH4sMEwHBsqPgAAAKQcBgAAAFBATRscSD0AAACMHDwAMBwbYUAAAABNHAb7QwAAAE0bHIUnAAAApB0GAAAAUEBNHB1IPQAAAE0dBvtDAAAAMB0cnD8AAACMHAAA2R0FABIBHP8SABsAEgAJAFIeHQCfHgEB4h5IAKkfAAAwHx5zRAAAAKkfAAAwHx4eRQAAAKkfAAAwHx7GRgAAAKkfAAAwHx4FRwAAAOIfSwDiIEgAqSEAADAhIHNEAAAAqSEAADAhIB5FAAAAqSEAADAhIMZGAAAAqSEAADAhIAVHAAAAMCAf3EkAAADiIEgAqSEAADAhIHNEAAAAqSEAADAhIB5FAAAAqSEAADAhIMZGAAAAqSEAADAhIAVHAAAAMCAf00oAAAD/IAAAAAAAANkhBgASAQP/EgAfABIAHgASABcA2SIHABICCgASAgsAEgAgABIAHwASAQP/EgAeABIAFwDZIwgAEgET/xIAHwASAQP/EgAeABIAFwDZJAkAEgACABIBE/8SAB8AEgED/xIAHgASABcA+ygMAE0nKIJMAAAAUikiALwnJ8dNAAAAnycDALwlAl8DAAAAnyUAAfsoDABNJyivTgAAAFIpIgC8JyfHTQAAAJ8nAwC8JQJfAwAAAJ8lAAHAJU8A2SYLABICDQASAg4AEgIPABIAJQASAAIAEgIQABIAJAASACAAvCcEaFAAAACfJwIEZCcDAFIsJgBSLSsAnywCAW4n/P8CAAAAvCcFaFAAAACfJwIEZCcIAG8uUQC8LCv+UgAAAJ8sAwIrLAMAUiwmAFItKwCfLAIBbif3/wIAAADZJwwAEgED/xICEQASAAIAEgISABIAGAASABkAEgAaAFIoCwCfKAEBbyhTADAoESxUAAAATSsG8FUAAABNKissVgAAANksDQASAAAAEgITABICFAASAAIAEgIFALwqKsdNAAAAnyoDALwoAl8DAAAAnygAAaQoWQAAYHGF2SkOABIBA/8SAB4AEgEU/xIBHP8SAB0AEgET/xIAFQASAAgAEgAJABIAEAASAAcAEgAOABIADwASABYAEgAMABIADQASABEAEgIJABICEwCfKAIB+ysJAE0qK/1aAAAA2SwPABIAAAASAhUAEgICALwqKsdNAAAAnyoDALwoAl8DAAAAnygAAcAoWwASAhEAEgIGABICFgASAhcAEgICAMEDAACCJwMAXAMUAwEDIgMpA4wBAzsEAABQQAONAQOOAQNdA48BAyYCMzMzMzMzAEADBQMNAw4DkAEDkQEDLQQAACBBAwQDkgEDWwOTAQOUAQQAAICBA5UBA0cDlgEDlwEEHXCwwQNEA2wDmAEDmQEDmgEDmwEDnAEDnQEDGgMRA54BA58BBB2osMEDoAEDoQEELbCwwQIAAAAA0BJjQQOiAQOjAQNxBwAAAAAAAAAAAAAAAAAAAAACAAAAAAAABEADpAECAAAAAAAA0D8DpQEDMwM0BQI4OQcAAAA/AAAAAAAAAAAAAAAAAgAAAAAAAOA/AzwDVwNYA1kDpgEEQfiwwQOnAQNmA2cDaQNoBQRERUZHA0ADQQUCSUoDqAEDTgOpAQYPA20DqgEDBgcAAIA/AAAAAAAAAAAAAAAAAzEDqwEDrAEDLgOtAQQAYHGFAzcGFRECAwQFBgcICQoODxAREhMUFYQBrgEBBQAAAQAAAAIDAAAAAQAAAQAAAAIAAAABAAABAAAAAgAA8gAAAQAAAAIAAAACAAEAAAAAAAAAAQAAAAACAAAAAAD3AgAAAAAAADUAAAkAAAAAAAEAAAAAAAABAAAAAAEAAL8AAP4ABgAAAAEAAAABAAAAAAAAAAEAAAABAAABAAAB9AAAAAAAAAAAAQAAAAAAAgAAAAEAAAABAAAAAQAAAAD6AAABAAAAAQAAAQAAAAAAAAABAAAAAAACAAAAAAAAAPoAAAAAAAAAAQAAAAAAAAEAAAAAAQAAAQAAAQAAAAAA+wIAAAAAAQAAAQAAAgAEAQIAAAcAAAAAAQAAAQAAAQDpAAAAAAAWAAAAAAABAAAAAAABAAAAAAACAAAAAAAAAOYAAAAAAAABAAAAAQAAAAAAAAACAQAAAAQAAwEAAAEA8gEAAAEAAAMCAQAAAQAAAQAAAQAA/AAIAQAAAQAAAQDxAQAA/AAIAAIAAAAADwAAAAAAAAAZAAAAAAAJAAAAAMUADgAAAAAAAAAAAAEAAAAAAAAAAAACBAAAAAAAAAAA6wAAAAEAAP8ABAAAAAEAAAAAAQAA/gAHAAAAAAAAAA2lQwAAwAAAAAAAAAAAAAAAAAAAABEAAAAAAAAAAAAAAC8AAAAAAAAAAAAAKAAAAAAAAAAAAAAAAAcAAAAAABkAhgAAAA4AAAAJAAAAQQAAAAwAAAAGAAAABgAAAAUAAAAXAAAAGwAAAA4AAAAPAAAAOwAAACIAAABb////0QAAAAAqAAABAgD3A6MAAACkAAEAAAAAQG8CAgC8AAAWAwAAAJ8AAwKkAQEAAAAAQG8DBAC8AQEWAwAAAJ8BAwKkAgEAAAAAQG8EBQC8AgIWAwAAAJ8CAwKkAwEAAAAAQG8FBgC8AwMWAwAAAJ8DAwKkBAEAAAAAQG8GBwC8BAQWAwAAAJ8EAwKkBQkAAACAQE0HABIKAAAATQYH7wsAAACfBQICpAYJAAAAgEBNCgASCgAAAE0JChwMAAAATQgJGA0AAABNBwgiDgAAAJ8GAgKkBwkAAACAQE0JAE0PAAAATQgJWRAAAACfBwICpAgJAAAAgEBNDAASCgAAAE0LDBwMAAAATQoLGA0AAABNCQp2EQAAAJ8IAgKkCQkAAACAQE0NAE0PAAAATQwNHxIAAABNCwyhEwAAAE0KCxgUAAAAnwkCAqQKCQAAAIBATQ0ATQ8AAABNDA0fEgAAAE0LDJUVAAAAnwoCAqQLCQAAAIBATQ8AEgoAAABNDg8cDAAAAE0NDlIWAAAATQwN9hcAAACfCwICpAwJAAAAgEBNEQASCgAAAE0QERwMAAAATQ8QtRgAAABNDg+MGQAAAE0NDkoaAAAAnwwCAqQNCQAAAIBATREATQ8AAABNEBEfEgAAAE0PEKETAAAATQ4P7BsAAACfDQICpA4JAAAAgEBNEgBNDwAAAE0REh8SAAAATRARoRMAAABNDxDXHAAAAJ8OAgKkDwkAAACAQE0RABIKAAAATRAReB0AAACfDwICpBAJAAAAgEBNFAASCgAAAE0TFBwMAAAATRITQx4AAABNERIUHwAAAJ8QAgKkEQkAAACAQE0VABIKAAAATRQVoRMAAABNExQhIAAAAE0SE9AhAAAAnxECAqQSCQAAAIBATRUATQ8AAABNFBUfEgAAAE0TFB8iAAAAnxICAqQTCQAAAIBATRcATQ8AAABNFhccDAAAAE0VFkMeAAAATRQV/iMAAACfEwICpBQJAAAAgEBNGAASCgAAAE0XGBwMAAAATRYXGA0AAABNFRZCJAAAAJ8UAgKkFQkAAACAQE0YAE0PAAAATRcYHxIAAABNFhcjJQAAAJ8VAgKkFgkAAACAQE0ZABIKAAAATRgZoRMAAABNFxjoJgAAAJ8WAgKkFwkAAACAQE0ZABIKAAAATRgZBycAAACfFwICpBgJAAAAgEBNHABNDwAAAE0bHB8SAAAATRoboRMAAABNGRosKAAAAJ8YAgKkGioAAACQQk0ZGkgrAAAATRwAgS0AAABNGxzLLgAAAE0aG7wsAAAATRsEMS8AAABNHRuZMAAAAE0cHXoxAAAATR4cTjIAAABNHR68LAAAAE0eHVozAAAAxh8AADAfHiQ0AAAATR8dUDUAAADGIAAAMCAfJDQAAABNIR2YNgAAAE0gIfI3AAAAxiEAADAhICQ0AAAATSEU7zgAAADAIjkAEgAgAMAjOgASABYAnyEDAuIiPQD/IwQAAAAAAKQkQQBA/ODDbyVCAGolIySkJEQAQ/zgw28lRQBqJSMkpCRHAEb84MNvJUgAaiUjJKQkSgBJ/ODDbyVLAGolIySkJE0ATPzgw28lTgBqJSMkpCRQAE/84MNvJVEAaiUjJKQkUwBS/ODDbyVUAGolIyQwIyJjOwAAAP8jBAAAAAAApCRWAFX84MNvJUIAaiUjJKQkWABX/ODDbyVFAGolIySkJFoAWfzgw28lSABqJSMkpCRcAFv84MNvJUsAaiUjJKQkXgBd/ODDbyVOAGolIySkJGAAX/zgw28lUQBqJSMkpCRiAGH84MNvJVQAaiUjJDAjIt08AAAAUiMVAFIkIgDiJWMA4iZmAG8nZwAwJyapZAAAAOInPQDiKGkAjCm0ADApKDhoAAAAMCgnYzsAAADiKGkAjCkAADApKDhoAAAAMCgn3TwAAAAwJyYFZQAAADAmJXNCAAAA4iZmAG8nZwAwJyapZAAAAOInagDiKGkAjCkAADApKDhoAAAAMCgn3TwAAAAwJyYFZQAAADAmJR5FAAAA4iZmAG8nZwAwJyapZAAAAOInPQDiKGkAjClaADApKDhoAAAAMCgnYzsAAADiKGkAjCkAADApKDhoAAAAMCgn3TwAAAAwJyYFZQAAADAmJcZIAAAA4iZmAG8nZwAwJyapZAAAAOInPQDiKGkAjCmm/zApKDhoAAAAMCgnYzsAAADiKGkAjCkAADApKDhoAAAAMCgn3TwAAAAwJyYFZQAAADAmJQVLAAAA4iZmAG8nZwAwJyapZAAAAOInPQDiKGkAjClaADApKDhoAAAAMCgnYzsAAADiKGkAjCkAADApKDhoAAAAMCgn3TwAAAAwJyYFZQAAADAmJVdOAAAA4iZmAG8nZwAwJyapZAAAAOInPQDiKGkAjCmm/zApKDhoAAAAMCgnYzsAAADiKGkAjCkAADApKDhoAAAAMCgn3TwAAAAwJyYFZQAAADAmJQtRAAAA4iZmAG8nZwAwJyapZAAAAOInagDiKGkAjCkAADApKDhoAAAAMCgn3TwAAAAwJyYFZQAAADAmJUtUAAAAnyMDAsAkawASAAgAEgAeABIAHQASAB8AEgAaABIAGwASABEAEgAQABIABgASAAIAEgAiABIAEwASAAEAEgAOABIADwASAA0AEgAjABIAIQASABkAEgALABIAGAASAAwAEgAWABIAFwCCJAIAbAOvAQQAAABAA7ABA7EBA7IBA7MBA7QBA7UBA7YBBAAAgEADtwEDuAEDuQEDugEDuwEDvAEDvQEDvgEDvwEDwAEDwQEDwgEDwwEDxAEDxQEDxgEDxwEDyAEDyQEDygEDywEDzAEDzQEDzgEDzwED0AED0QED0gED0wED1AED1QEDOwQAAJBCAzwD1gED1wED2AED2QEDIAMhA9oBA9sBAyIDdgOKAQPcAQMUBgAGAQPdAQPeAQUCOzwDRwNFA98BBED84MMDZgPgAQRD/ODDA2cD4QEERvzgwwNpA+IBBEn84MMDaAPjAQRM/ODDA2MD5AEET/zgwwNkA+UBBFL84MMDQgPmAQRV/ODDA+cBBFf84MMD6AEEWfzgwwPpAQRb/ODDA+oBBF384MMD6wEEX/zgwwPsAQRh/ODDBQdCRUhLTlFUA+0BA+4BBQJkZQPvAQPwAQUBaAUBPAYWAwABFgEAAQEAAv4AAAAAAf8AAAAAAf8AAAAAAf8AAAAAAf8AAAAAAv4AAAAAAAAAAAAAAAAAAAAAAf8AAAAAAAAAAAAAAAAAAAAAAf8AAAAAAAAAAAAAAAAAAAAAAAAB/wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAB/wAAAAAAAAAAAAAAAAAAAAAAAAAAAf8AAAAAAAAAAAAAAAAAAAAAAf8AAAAAAAAAAAAAAAAAAAAAAAAB/wAAAAAAAAAAAAAAAAAAAAAAAAAAAf8AAAAAAAAAAAAAAAAAAAAAAf8AAAAAAAAAAAAAAAAAAAAAA/0AAAH/AAAAAAL+Af8AAAH/AAAC/gH/AAAAAAAAA/0AAAH/AAAAAAAAAAAJ9wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAH/AAAB/wAAAAAAAAAAAAAAAAAAAAAB/wAAAf8AAAAB/wL+AAb6AAAB/wAAAAAAAAAAAAAAAAAAAAAB/wAAAf8AAAAAAf8AAAAC/gL+AAj4AAAB/wAAAAAAAAAAAAAAAAAAAAAB/wAAAf8AAAAAAf8AAAAC/gL+AAj4AAAB/wAAAAAAAAAAAAA0zAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEAAAACAAAAAAAAAAAAAAABAAAAAAAAAAAAAAABAAAAAAAAAAAAAAABAAAAAAAAAAAAAAABAAAAAAAAAAAAAAACAAAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADAAAAAAAAAAEAAAAAAAAAAAAAAAIAAAABAAAAAAAAAAEAAAAAAAAAAgAAAAEAAAABAAAAAQAAAAAAAAADAAAAAAAAAAEAAAADAAAAAAAAAAIAAAD+////CgAAAAEAAAAAAAAAAQAAAAAAAAABAAAAAAAAAAEAAAAAAAAAAQAAAAAAAAABAAAAAAAAAAEAAAAAAAAA+f///woAAAABAAAAAAAAAAEAAAAAAAAAAQAAAAAAAAABAAAAAAAAAAEAAAAAAAAAAQAAAAAAAAABAAAAAAAAAPn///8MAAAAAAAAAAIAAAAAAAAAAgAAAAAAAAAAAAAAAQAAAAAAAAAAAAAA/v////7///8HAAAAAQAAAAEAAAABAAAAAAAAAP/////+////AAAAAAcAAAAAAAAAAgAAAAAAAAAAAAAAAQAAAAAAAAAAAAAA/v////7///8HAAAAAQAAAAEAAAABAAAAAAAAAAAAAAABAAAAAAAAAP7////+////AAAAAAkAAAAAAAAAAgAAAAAAAAAAAAAAAQAAAAAAAAAAAAAA/v////7///8HAAAAAQAAAAEAAAABAAAAAAAAAAAAAAABAAAAAAAAAP7////+////AAAAAAkAAAAAAAAAAgAAAAAAAAAAAAAA//////7////U////NAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAmgEAAAAX463pn+5eHIDRaYMLS0gaqZ+7yCw/Wz743BpYV8SSofE+B7XoK5a3pg==

local v1 = game:GetService("ReplicatedStorage")
local u2 = game:GetService("UserInputService")
local u3 = game:GetService("RunService")
game:GetService("TweenService")
local v4 = game:GetService("Players")
require(v1.Shared.Types)
local u5 = require(v1.Shared.Framework.Classes.Spring)
require(v1.Client.PlayerControls)
local u6 = require(v1.Shared.Framework.Classes.Maid)
require(v1.Client.Gui.Utils.SetCoreGuiEnabled)
require(v1.Client.Gui.GuiFrame)
local u7 = require(v1.Shared.Framework.Network.Remote)
local u8 = require(v1.Shared.Framework.Utilities.Math.Time)
local u9 = require(v1.Client.Gui.Utils.ClickableButton)
local u10 = require(v1.Client.Gui.Utils.AutoButtonColor)
local u11 = require(v1.Shared.Palette)
local u12 = require(v1.Shared.Framework.Services.CollisionGroup)
local u13 = require(v1.Shared.Utils.Stats.ItemUtil)
require(v1.Client.Gui.HUD)
local u14 = require(v1.Client.Framework.Services.InputMode)
local v15 = require(v1.Shared.Framework.Classes.Pool)
local v16 = require(v1.Client.Gui.CreateBindingMap)
local u17 = require(v1.Shared.Utils.AnimateColor)
local u18 = require(v1.Shared.Constants)
local u19 = require(v1.Client.Gui.Utils.PlayLocalSound)
local u20 = workspace.CurrentCamera
local u21 = v1.Assets.Minigames["Robot Claw"]
local u22 = v4.LocalPlayer
local u23 = u22.PlayerGui.ScreenGui.MinigameHUD["Robot Claw"]
local u24 = u23.Movement
u24.Parent = nil
local u25 = u23.Controls
u25.Parent = nil
local u26 = u23.CollectedItems.Template
u26.Parent = nil
local u28 = v15.new(function() --[[Anonymous function at line 48]]
    --[[
    Upvalues:
        [1] = u26
    --]]
    return u26:Clone()
end, function(p27) --[[Anonymous function at line 50]]
    --[[
    Upvalues:
        [1] = u17
    --]]
    u17.None(p27)
end)
local u29 = {
    ["Keyboard"] = {
        [Enum.KeyCode.W] = "Up",
        [Enum.KeyCode.S] = "Down",
        [Enum.KeyCode.A] = "Left",
        [Enum.KeyCode.D] = "Right",
        [Enum.KeyCode.Q] = "CameraLeft",
        [Enum.KeyCode.E] = "CameraRight",
        [Enum.KeyCode.F] = "Drop"
    },
    ["Gamepad"] = {
        [Enum.KeyCode.DPadUp] = "Up",
        [Enum.KeyCode.DPadDown] = "Down",
        [Enum.KeyCode.DPadLeft] = "Left",
        [Enum.KeyCode.DPadRight] = "Right",
        [Enum.KeyCode.ButtonL1] = "CameraLeft",
        [Enum.KeyCode.ButtonR1] = "CameraRight",
        [Enum.KeyCode.ButtonR2] = "Drop"
    }
}
local v30 = {}
local v31 = {
    ["Image"] = "rbxassetid://134873589669250"
}
local v32 = {
    ["Keyboard"] = {
        ["Rotation"] = 180
    },
    ["Gamepad"] = {
        ["Rotation"] = 0
    }
}
v31.Properties = v32
v30.Up = v31
local v33 = {
    ["Image"] = "rbxassetid://134873589669250"
}
local v34 = {
    ["Gamepad"] = {
        ["Rotation"] = 0
    }
}
v33.Properties = v34
v30.Down = v33
local v35 = {
    ["Image"] = "rbxassetid://134873589669250"
}
local v36 = {
    ["Keyboard"] = {
        ["Rotation"] = 90
    },
    ["Gamepad"] = {
        ["Rotation"] = 0
    }
}
v35.Properties = v36
v30.Left = v35
local v37 = {
    ["Image"] = "rbxassetid://134873589669250"
}
local v38 = {
    ["Keyboard"] = {
        ["Rotation"] = -90
    },
    ["Gamepad"] = {
        ["Rotation"] = 0
    }
}
v37.Properties = v38
v30.Right = v37
local v39 = {
    ["Image"] = "rbxassetid://134873589669250"
}
local v40 = {
    ["Keyboard"] = {
        ["Rotation"] = 90
    },
    ["Gamepad"] = {
        ["Rotation"] = 0
    }
}
v39.Properties = v40
v30.CameraLeft = v39
local v41 = {
    ["Image"] = "rbxassetid://134873589669250"
}
local v42 = {
    ["Keyboard"] = {
        ["Rotation"] = -90
    },
    ["Gamepad"] = {
        ["Rotation"] = 0
    }
}
v41.Properties = v42
v30.CameraRight = v41
local v43 = {
    ["Image"] = "rbxassetid://134873589669250"
}
local v44 = {
    ["Gamepad"] = {
        ["Rotation"] = 0
    }
}
v43.Properties = v44
v30.Drop = v43
local u45 = v16(u29, v30)
return function(u46) --[[Function name: run, line 132]]
    --[[
    Upvalues:
        [1] = u6
        [2] = u24
        [3] = u23
        [4] = u25
        [5] = u21
        [6] = u22
        [7] = u13
        [8] = u12
        [9] = u5
        [10] = u3
        [11] = u29
        [12] = u14
        [13] = u2
        [14] = u10
        [15] = u11
        [16] = u9
        [17] = u45
        [18] = u28
        [19] = u20
        [20] = u7
        [21] = u19
        [22] = u8
        [23] = u17
        [24] = u18
    --]]
    local u47 = u6.new()
    local v48 = u24:Clone()
    v48.Parent = u23
    u47:Add(v48)
    local v49 = u25:Clone()
    v49.Parent = u23
    u47:Add(v49)
    local u50 = u21.ClawMachine:Clone()
    u50.Parent = workspace
    u47:Add(u50)
    local u51 = u50.Claw
    local u52 = u51:GetAttribute("BasePivot") or u51:GetPivot()
    u51:SetAttribute("BasePivot", u52)
    local u53 = u51.BasePart.Size.X / 2.025
    local function u72(p54, p55) --[[Anonymous function at line 159]]
        --[[
        Upvalues:
            [1] = u50
            [2] = u21
            [3] = u53
            [4] = u22
            [5] = u13
            [6] = u47
        --]]
        local v56 = {}
        for _, v57 in ipairs(u50:GetDescendants()) do
            if v57:IsA("BasePart") and v57.Name == "SpawnPlatform" then
                table.insert(v56, v57)
            end
        end
        if #v56 ~= 0 then
            local v58 = v56[math.random(#v56)]
            local v59 = v58.Size
            local v60 = v59.X / 2 - 1.5
            local v61 = math.max(v60, 0.2)
            local v62 = v59.Z / 2 - 1.5
            local v63 = math.max(v62, 0.2)
            local v64 = (math.random() - 0.5) * 2 * v61
            local v65 = (math.random() - 0.5) * 2 * v63
            local v66 = v58.Position.Y + v59.Y / 2 + 1 + 3
            local v67 = v58.Position.X + v64
            local v68 = v58.Position.Z + v65
            local v69 = Vector3.new(v67, v66, v68)
            local v70 = u21.Capsule:Clone()
            v70.Color.Color = Color3.fromHSV(math.random(), 0.7, 0.6)
            v70:ScaleTo(u53)
            v70:PivotTo(CFrame.new(v69))
            local v71 = u21.ItemBillboardGui:Clone()
            v71.Name = "ClawItem" .. p54
            v71.Adornee = v70.HitBox
            v71.Parent = u22.PlayerGui.ScreenGui
            u13:UpdateIcon(v71.Icon, p55)
            v70:SetAttribute("ItemGUID", p54)
            v70:AddTag("ClawToyModel")
            v70.Parent = u50
            u47:Add(v71)
            u47:Add(v70)
            v71.Enabled = true
            return v70
        end
    end
    u12:AddModel(u51, "Ignore")
    local u73 = true
    local function v77() --[[Anonymous function at line 212]]
        --[[
        Upvalues:
            [1] = u46
            [2] = u72
        --]]
        local v74 = u46.BonusItems
        for v75, v76 in pairs(v74) do
            u72(v75, v76)
            task.wait(0.1)
        end
    end
    for _, v78 in pairs(u50:GetDescendants()) do
        if v78:HasTag("IgnoreCollision") then
            u12:AddBasePart(v78, "Ignore")
        end
    end
    local u79 = Instance.new("AlignPosition")
    u79.Mode = Enum.PositionAlignmentMode.OneAttachment
    u79.Attachment0 = u51.DisplayModel.Rod.Attach
    u79.MaxForce = 20000 * u53
    u79.Responsiveness = 200
    u79.ApplyAtCenterOfMass = false
    u79.Position = u51.DisplayModel.Rod.CFrame.Position
    u79.Parent = u51.DisplayModel.Rod
    local u80 = Instance.new("AlignOrientation")
    u80.Mode = Enum.OrientationAlignmentMode.OneAttachment
    u80.AlignType = Enum.AlignType.AllAxes
    u80.Attachment0 = u51.DisplayModel.Rod.Attach
    u80.MaxTorque = 10000000 * u53
    u80.Responsiveness = 200
    u80.CFrame = u51.DisplayModel.Rod.CFrame
    u80.Parent = u51.DisplayModel.Rod
    local u81 = u51.DisplayModel:GetAttribute("BaseOffset") or u51.DisplayModel:GetPivot():Inverse() * u52
    u51.DisplayModel:SetAttribute("BaseOffset", u81)
    local u82 = u5.new(Vector3.new(0, 0, 0))
    u82.Stiffness = 2.5
    u82.Friction = 0.25
    local u83 = {
        ["x"] = 0,
        ["y"] = 0
    }
    local u84 = u5.new(Vector3.new(0.5, 0, 0))
    u84.Stiffness = 2.5
    u84.Friction = 0.25
    local u85 = false
    local u86 = false
    local function u100(p87, p88) --[[Anonymous function at line 264]]
        --[[
        Upvalues:
            [1] = u83
            [2] = u82
        --]]
        local v89 = u83.x
        local v90 = u83.y
        local v91 = u83
        local v92 = u83.x + p87
        v91.x = math.clamp(v92, 0, 1)
        local v93 = u83
        local v94 = u83.y + p88
        v93.y = math.clamp(v94, 0, 1)
        local v95 = u82
        local v96 = u83.x - v89
        local v97 = math.clamp(v96, -0.2, 0.2)
        local v98 = u83.y - v90
        local v99 = math.clamp(v98, -0.2, 0.2)
        v95.Target = 900 * Vector3.new(v97, 0, v99)
    end
    local u101 = u5.new(Vector3.new(0, 0, 0))
    u101.Stiffness = 0.5
    u101.Friction = 1
    local function u104() --[[Anonymous function at line 274]]
        --[[
        Upvalues:
            [1] = u85
            [2] = u101
            [3] = u84
            [4] = u86
            [5] = u83
            [6] = u100
            [7] = u3
        --]]
        u85 = true
        u101.Target = Vector3.new(1, 0, 0)
        task.wait(1.5)
        u84.Target = Vector3.new(0.5, 0, 0)
        task.wait(1)
        u86 = true
        u101.Target = Vector3.new(0, 0, 0)
        task.wait(1)
        local v102 = 0
        while u83.x > 0.00001 or u83.y > 0.00001 do
            local v103 = (u83.x ^ 2 + u83.y ^ 2) ^ 0.5
            u100(-(u83.x / v103) * v102, -(u83.y / v103) * v102)
            v102 = u3.Heartbeat:Wait()
        end
        task.wait(0.3)
        u84.Target = Vector3.new(1, 0, 0)
        task.wait(0.5)
        u85 = false
        u86 = false
    end
    local u105 = workspace.CurrentCamera.CameraType
    local u106 = workspace.CurrentCamera.CameraSubject
    local u107 = workspace.CurrentCamera.FieldOfView
    workspace.CurrentCamera.CameraType = Enum.CameraType.Scriptable
    workspace.CurrentCamera.FieldOfView = 60
    local u108 = u50.CenterPart.CFrame
    workspace.CurrentCamera.CameraSubject = u50.CenterPart
    local u109 = 0
    local function u113() --[[Anonymous function at line 306]]
        --[[
        Upvalues:
            [1] = u109
            [2] = u108
            [3] = u53
        --]]
        local v110 = u109 + 90
        local v111 = math.rad(v110)
        local v112 = u53
        workspace.CurrentCamera.CFrame = CFrame.new((u108 * CFrame.new(12 * u53 * math.sin(v111), 3, 12 * u53 * math.cos(v111))).Position, u108.Position - Vector3.new(0, v112, 0))
    end
    u113()
    local u114 = {
        ["Up"] = false,
        ["Down"] = false,
        ["Left"] = false,
        ["Right"] = false
    }
    local u115 = {
        ["Input"] = {
            ["Up"] = false,
            ["Down"] = false,
            ["Left"] = false,
            ["Right"] = false
        },
        ["Buttons"] = {
            ["Up"] = false,
            ["Down"] = false,
            ["Left"] = false,
            ["Right"] = false
        }
    }
    local u116 = {}
    local function v124(p117, p118) --[[Anonymous function at line 355]]
        --[[
        Upvalues:
            [1] = u29
            [2] = u14
            [3] = u116
            [4] = u115
            [5] = u73
            [6] = u114
            [7] = u104
        --]]
        if p118 then
            return
        else
            local v119 = u29[u14.Mode]
            if v119 then
                local v120 = v119[p117.KeyCode]
                if v120 then
                    local v121 = u116[v120]
                    local v122 = p117.UserInputState == Enum.UserInputState.Begin
                    if v121 then
                        v121.Button:SetAttribute("Pressed", v122)
                    end
                    u115.Input[v120] = v122
                    if u73 then
                        local v123 = u115.Input[v120] or u115.Buttons[v120]
                        u114[v120] = v123
                        if v123 and v120 == "Drop" then
                            u104()
                        end
                    end
                else
                    return
                end
            else
                return
            end
        end
    end
    local function u133(u125, p126) --[[Anonymous function at line 389]]
        --[[
        Upvalues:
            [1] = u47
            [2] = u85
            [3] = u115
            [4] = u73
            [5] = u114
            [6] = u104
        --]]
        u47:Add(p126.MouseButton1Down:Connect(function() --[[Anonymous function at line 390]]
            --[[
            Upvalues:
                [1] = u125
                [2] = u85
                [3] = u115
                [4] = u73
                [5] = u114
                [6] = u104
            --]]
            local v127 = u125
            if u85 and v127 == "Drop" then
                return
            else
                u115.Buttons[v127] = true
                if u73 then
                    local v128 = u115.Input[v127] or u115.Buttons[v127]
                    u114[v127] = v128
                    if v128 and v127 == "Drop" then
                        u104()
                    end
                end
            end
        end))
        u47:Add(p126.MouseButton1Up:Connect(function() --[[Anonymous function at line 394]]
            --[[
            Upvalues:
                [1] = u125
                [2] = u85
                [3] = u115
                [4] = u73
                [5] = u114
                [6] = u104
            --]]
            local v129 = u125
            if u85 and v129 == "Drop" then
                return
            else
                u115.Buttons[v129] = false
                if u73 then
                    local v130 = u115.Input[v129] or u115.Buttons[v129]
                    u114[v129] = v130
                    if v130 and v129 == "Drop" then
                        u104()
                    end
                end
            end
        end))
        u47:Add(p126.MouseLeave:Connect(function() --[[Anonymous function at line 398]]
            --[[
            Upvalues:
                [1] = u125
                [2] = u85
                [3] = u115
                [4] = u73
                [5] = u114
                [6] = u104
            --]]
            local v131 = u125
            if u85 and v131 == "Drop" then
                return
            else
                u115.Buttons[v131] = false
                if u73 then
                    local v132 = u115.Input[v131] or u115.Buttons[v131]
                    u114[v131] = v132
                    if v132 and v131 == "Drop" then
                        u104()
                    end
                end
            end
        end))
    end
    u47:Add(u2.InputBegan:Connect(v124))
    u47:Add(u2.InputEnded:Connect(v124))
    local function u134(_) --[[Anonymous function at line 406]] end
    local function v138(p135) --[[Anonymous function at line 410]]
        --[[
        Upvalues:
            [1] = u10
            [2] = u11
            [3] = u9
            [4] = u134
            [5] = u47
            [6] = u45
            [7] = u133
            [8] = u116
        --]]
        local v136 = p135.Name
        local v137 = p135.Button
        u10(v137, u11.Button.Default)
        u9(v137, u134)
        u47:Add(u45(p135, v136))
        u133(v136, v137)
        u116[v136] = p135
    end
    local u139 = u85
    local u140 = u109
    local u141 = u86
    for _, v142 in v48:GetChildren() do
        v138(v142)
    end
    for _, v143 in v49:GetChildren() do
        if not v143:IsA("UIListLayout") then
            v138(v143)
        end
    end
    local function v144() --[[Anonymous function at line 434]]
        --[[
        Upvalues:
            [1] = u73
            [2] = u28
            [3] = u47
            [4] = u20
            [5] = u105
            [6] = u106
            [7] = u107
        --]]
        u73 = false
        u28:Done()
        u47:Cleanup()
        u20.CameraType = u105
        u20.CameraSubject = u106
        u20.FieldOfView = u107
    end
    v77()
    u84.Target = Vector3.new(1, 0, 0)
    u47:Add(u50.CollectPart.Touched:Connect(function(p145) --[[Anonymous function at line 450]]
        --[[
        Upvalues:
            [1] = u46
            [2] = u7
            [3] = u19
            [4] = u47
            [5] = u22
        --]]
        if p145.Name == "HitBox" and (p145.Parent and (p145.Parent:HasTag("ClawToyModel") and not p145.Parent:GetAttribute("wasCollected"))) then
            local v146 = p145.Parent:GetAttribute("ItemGUID")
            if v146 and u46.BonusItems[v146] then
                p145.Parent:SetAttribute("wasCollected", true)
                u7:FireServer("GrabMinigameItem", v146)
                u19("SmallReward")
                u47:Remove(p145.Parent)
                local v147 = u22.PlayerGui.ScreenGui:FindFirstChild("ClawItem" .. v146)
                if v147 then
                    u47:Remove(v147)
                end
            end
        end
    end))
    task.spawn(function() --[[Anonymous function at line 467]]
        --[[
        Upvalues:
            [1] = u73
            [2] = u114
            [3] = u141
            [4] = u140
            [5] = u113
            [6] = u139
            [7] = u100
            [8] = u52
            [9] = u53
            [10] = u83
            [11] = u51
            [12] = u81
            [13] = u82
            [14] = u101
            [15] = u79
            [16] = u80
            [17] = u84
            [18] = u3
            [19] = u7
        --]]
        local v148 = 0
        while u73 do
            local v149 = (u114.CameraLeft and -1 or 0) + (u114.CameraRight and 1 or 0)
            if u141 then
                if u140 % 360 > 0.00001 then
                    local v150 = u140
                    local v151 = u140 - 180
                    local v152 = v150 + math.sign(v151) * 180 * v148
                    u140 = math.clamp(v152, 0, 360)
                    u113()
                end
            elseif v149 ~= 0 then
                u140 = (u140 + 90 * v149 * v148) % 360
                u113()
            end
            local v153 = u140 + 90
            local v154 = math.rad(v153)
            local v155 = (u114.Up and 1 or 0) + (u114.Down and -1 or 0)
            local v156 = (u114.Right and 1 or 0) + (u114.Left and -1 or 0)
            if u139 then
                v155 = 0
                v156 = 0
            end
            u100(math.sin(v154) * v155 * v148 - math.cos(v154) * v156 * v148, math.sin(v154) * v156 * v148 + math.cos(v154) * v155 * v148)
            local v157 = u52 * CFrame.new(-4 * u53 * u83.x, 0, -4 * u53 * u83.y)
            u51:PivotTo(v157)
            local v158 = v157 * u81
            local v159 = CFrame.fromEulerAnglesXYZ
            local v160 = u82.Value.X
            local v161 = math.rad(v160)
            local v162 = u82.Value.Z
            local v163 = v158 * v159(v161, 0, (math.rad(v162))) * CFrame.new(0, -4.5 * u53 * u101.Value.X, 0)
            u79.Position = v163.Position
            u80.CFrame = v163
            for _, v164 in pairs(u51.DisplayModel:GetChildren()) do
                if v164.Name == "Grabber" and v164:FindFirstChild("Rod_Weld") then
                    local v165 = v164.PivotOffset
                    local v166 = v164.Rod_Weld
                    local v167 = CFrame.fromEulerAnglesXYZ
                    local v168 = 40 * u84.Value.X
                    v166.C0 = v165 * v167(0, 0, (math.rad(v168))) * v165:Inverse()
                end
            end
            v148 = u3.Heartbeat:Wait()
        end
        u7:FireServer("FinishMinigame")
    end)
    u47:Add(u3.Heartbeat:Connect(function() --[[Anonymous function at line 507]]
        --[[
        Upvalues:
            [1] = u46
            [2] = u8
            [3] = u23
        --]]
        local v169 = u46.FinishAt - u8.now()
        local v170 = math.max(v169, 0)
        u23.Controls.Drop.Timer.Text = ("\226\143\176 Time Left: %*"):format((u8.formatTime(v170, true)))
    end))
    return v144, function(p171) --[[Function name: stateChanged, line 514]]
        --[[
        Upvalues:
            [1] = u28
            [2] = u13
            [3] = u17
            [4] = u18
            [5] = u23
        --]]
        for _, v172 in p171.Items do
            local v173 = u28:Get()
            local v174 = v173.Content.ItemName
            v174.Text = u13:GetName(v172)
            u13:FormatAmount(v173.Content.ItemInfo, v172)
            u13:UpdateIcon(v173.Icon, v172)
            local v175 = u13:GetRarity(v172)
            if v175 == "Legendary" then
                u17.Cycle(v174, "Rainbow", {
                    ["Speed"] = 0.4
                })
            else
                u17.None(v174)
                v174.TextColor3 = u18.RarityColors[v175]
            end
            v173.Parent = u23.CollectedItems
        end
        u28:Done()
    end
end