--devbgascension

-- Bytecode (Base64):
-- BgM+DlNjcm9sbGluZ0ZyYW1lB0NvbnRlbnQETG9ncw5GaW5kRmlyc3RDaGlsZAVVRGltMgNuZXcEU2l6ZQFZBk9mZnNldAtHZXRDaGlsZHJlbgVGcmFtZQNJc0EETmFtZQdWaXNpYmxlBVRpdGxlB1VwZGF0ZXMER2xvdwZDb2xvcjMHZnJvbVJHQgtJbWFnZUNvbG9yMwZ1cGRhdGUTQWJzb2x1dGVDb250ZW50U2l6ZQdVSVNjYWxlBVNjYWxlCkxhc3RVcGRhdGUNU2hvdWxkRGlzcGxheQZVcGRhdGUFQ2xvc2UKX2NoYW5nZWxvZwRPcGVuBGdhbWUHUGxheWVycwpHZXRTZXJ2aWNlEVJlcGxpY2F0ZWRTdG9yYWdlB3JlcXVpcmUGQ2xpZW50CUZyYW1ld29yawlVdGlsaXRpZXMDR3VpEkhvb2tTY3JvbGxpbmdGcmFtZQZTaGFyZWQJQ29uc3RhbnRzBVV0aWxzD0F1dG9CdXR0b25Db2xvcgdQYWxldHRlD0NsaWNrYWJsZUJ1dHRvbghHdWlGcmFtZQhTZXJ2aWNlcwlMb2NhbERhdGELTG9jYWxQbGF5ZXIJUGxheWVyR3VpCVNjcmVlbkd1aQxVSUxpc3RMYXlvdXQYR2V0UHJvcGVydHlDaGFuZ2VkU2lnbmFsB0Nvbm5lY3QGQnV0dG9uEkNvbm5lY3REYXRhQ2hhbmdlZANSZWQIU2V0dGluZ3MHU2lkZWJhcgdCdXR0b25zCUNoYW5nZWxvZwAHDAECAAAGAwAABQEDdvsEAABNAwT+AAAAAE0CA74BAAAATQECaAIAAABSAwAAvAEBAwMAAACfAQMCDgEUAPsEAABNAwT+AAAAAE0CA74BAAAApAMGAAAUQICMBAEAjAUAAIwGAABNCgEvCAAAAE0JCngJAAAATQgJcAoAAACVBwgHnwMFAjADAi8IAAAA+wUAAE0EBf4AAAAATQMEvgEAAABNAgNoAgAAALwCAmgLAAAAnwICBGQCDQBvCQwAvAcG/g0AAACfBwMCDgcIAE0IBroOAAAA8QgCAAAAAACpBwABqQcBADAHBoAPAAAAbgLy/wIAAAD7BQAATQQF/gAAAABNAwS+AQAAAE0CA7oQAAAAvAICaAsAAACfAgIEZAINAG8JDAC8Bwb+DQAAAJ8HAwIOBwgATQgGug4AAADxCAIAAAAAAKkHAAGpBwEAMAcGgA8AAABuAvL/AgAAAPsDAABNAgMKEQAAALwCAmgLAAAAnwICBGQCFwBvCQwAvAcG/g0AAACfBwMCDgcSAE0HBiESAAAATQkGug4AAACaCQgAAAAAAKQIFQAAUDCBjAkAAIwK6gCMC/8AnwgEAisIAwCkCBYAABQwgZ8IAQIwCAcAFwAAAG4C6P8CAAAA3gABAIIAAQAYAwEDAgMDAwQDBQMGBAAUQIACAAAAAACAYUADBwMIAwkDCgMLAwwDDQMOAw8DEAMRAxIDEwQAUDCBBAAUMIEDFAAWFQEYAAAAAAAAAAAAAAABAQAAAAAAAAAAAAAAAAAAAAAAAAACAAAAAAAAAAAAAAEAAAAAAQAAAAAAAAD+AAUAAAAAAAAAAAAAAQAAAAABAAAAAAAAAP4ABQAAAAAAAAEAAAAAAQAAAAAAAAAAAAAAAAAAAAAA/gAFARcAAAAACgADAAAAFfsAAACkAQIAAAQAgIwCAQCMAwAAjAQAAPsIAQBNBwjGAwAAAE0GB3gEAAAA+wkCAE0ICSsFAAAATQcIhAYAAADsBQYHnwEFAjABAC8HAAAAggABAAgDBQMGBAAEAIADFgMIAxcDGAMHADAVARgAAAAAAAAAAAAAAAAAAAAAAAAAAAExAAAAAAMAAgAAAAb7AAAA+wIBAE0BAroAAAAAnwACAYIAAQABAw0AOgABGAAAAAAAATsAAAAABAECAAAAC00CAAQAAAAATQECRwEAAAAOAQUA+wEAAPsDAQBNAgMmAgAAAJ8BAgGCAAEAAwMZAxoDGwBBAAEYAAAAAAABAAAAAAJCAAAAAAIAAQAAAAX7AAAAvAAAYwAAAACfAAIBggABAAEDHABJAAEYAAAAAAFKAAAAAAMAAQAAAAb7AAAAbwIAALwAABYBAAAAnwADAYIAAQACAx0DHgBQAAEYAAAAAAABUQAAAAAdAAABAADZAaMAAACkAAEAAAAAQG8CAgC8AAAWAwAAAJ8AAwKkAQEAAAAAQG8DBAC8AQEWAwAAAJ8BAwKkAgYAAABQQE0HAU0HAAAATQYHHAgAAABNBQa1CQAAAE0EBR8KAAAATQMEPgsAAACfAgICpAMGAAAAUEBNBQESDAAAAE0EBQcNAAAAnwMCAqQEBgAAAFBATQgBTQcAAABNBwgfCgAAAE0GB6EOAAAATQUG1w8AAACfBAICpAUGAAAAUEBNBwESDAAAAE0GB3gQAAAAnwUCAqQGBgAAAFBATQoBTQcAAABNCQofCgAAAE0ICaEOAAAATQcI7BEAAACfBgICpAcGAAAAUEBNCgFNBwAAAE0JCh8KAAAATQgJlRIAAACfBwICpAgGAAAAUEBNDAFNBwAAAE0LDBwIAAAATQoLQxMAAABNCQpoFAAAAJ8IAgJNCQAxFQAAAE0LCZkWAAAATQoLehcAAABNDAqOGAAAAE0LDJ0ZAAAATQwDJhoAAADZDQAAEgALABIBDP9NEAv+GwAAAE0PEL4cAAAATQ4PaB0AAAC8Dg5oHgAAAJ8OAgRkDh8ATRMSNB8AAADZFAEAEgASABIAEwASAAoApBUiAACEAIKMFgEAjBcAAIwYAABNGxPGIwAAAE0aG3gkAAAATRwKKyUAAABNGxyEJgAAAOwZGhufFQUCMBUSLycAAABvFyMAvBUTlCgAAACfFQMCUhcUALwVFccpAAAAnxUDAW4O4P8CAAAATQ4LCioAAAC8Dg5oHgAAAJ8OAgRkDgwAbxUZALwTEv4rAAAAnxMDAg4TBwBSEwYATRQSrCwAAADZFQIAEgANABIAEgCfEwMBbg7z/wIAAABvEC0AwBEuABIADQASAAMAvA4IKC8AAACfDgQBUg4EAE0PC2MwAAAATREFrCwAAABNEBFvMQAAAJ8OAwFSDgYATQ8LYzAAAADAEDIAEgAHAJ8OAwFNEgrKMwAAAE0REp0ZAAAATRARDTQAAABNDxDTNQAAAE0OD0c2AAAAUg8GAE0QDqwsAAAAwBE3ABIABwCfDwMBUg8CAE0QCwoqAAAATRILCioAAABNERI0HwAAAJ8PAwFSDwIATRAL/hsAAABNEgv+GwAAAE0REjQfAAAAnw8DAf8PAAAAAAAAwQwAAIIPAgA4Ax8EAAAAQAMgAyEDIgMjBAAAUEADJAMlAyYDJwMoAykDKgMrAywDLQMuAy8DMAMxAzIDMwM0Ax0DCwMbAwEDAgMDAwoDNQMFAwYEAIQAggMWAwgDFwMYAwcDNgM3AxADDAM4AxkGAwM5AxwDOgYEAzsDPAM9Az4GBQYAAQIDBAUBAAEYAAIAAAAAAAEAAAAAAAIAAAAAAAAAAAAAAAABAAAAAAAAAQAAAAAAAAAAAAABAAAAAAAAAQAAAAAAAAAAAAABAAAAAAAAAAABAAAAAAAAAAAAAAMAAQAAAAEAAAADAAIAABgAAAAAAAAAAAABAAEAAAABAAAAAAAAAAAAAAAAAAAAAAMAAAAAAAAA+gAKAAAAAAABAAAAAAEAAAAAAAD+AAkAAAAAAAAHAAAAAAAAAAEAAAAAAAYAAAAAAAAAAAABAAAAAAAFAAAAAAAAAAEAAAAAAAAAAwAAAAEAAAAABuVAqderKfeC14TDQxH5P4llm113ldodzW89iejMJdJHn+6QPZNvTFA=

local v1 = game:GetService("Players")
local v2 = game:GetService("ReplicatedStorage")
local v3 = require(v2.Client.Framework.Utilities.Gui.HookScrollingFrame)
local u4 = require(v2.Shared.Constants)
local v5 = require(v2.Client.Gui.Utils.AutoButtonColor)
local v6 = require(v2.Shared.Palette)
local v7 = require(v2.Client.Gui.Utils.ClickableButton)
local u8 = require(v2.Client.Gui.GuiFrame)
local v9 = require(v2.Client.Framework.Services.LocalData)
local u10 = v1.LocalPlayer.PlayerGui.ScreenGui
local u11 = u10._changelog.Frame
local u12 = u4.Update
local function u18(p13) --[[Anonymous function at line 22]]
    --[[
    Upvalues:
        [1] = u11
        [2] = u12
    --]]
    local v14 = u11.ScrollingFrame.Content.Logs:FindFirstChild(p13)
    if v14 then
        u11.ScrollingFrame.Content.Size = UDim2.new(1, 0, 0, v14.Size.Y.Offset + 140)
    end
    for _, v15 in u11.ScrollingFrame.Content.Logs:GetChildren() do
        if v15:IsA("Frame") then
            v15.Visible = v15.Name == p13
        end
    end
    for _, v16 in u11.ScrollingFrame.Content.Title:GetChildren() do
        if v16:IsA("Frame") then
            v16.Visible = v16.Name == p13
        end
    end
    for _, v17 in u11.Updates:GetChildren() do
        if v17:IsA("Frame") then
            v17.Glow.ImageColor3 = v17.Name == p13 and Color3.fromRGB(0, 234, 255) or Color3.new()
        end
    end
    u12 = p13
end
for _, u19 in u11.ScrollingFrame.Content.Logs:GetChildren() do
    local u20 = u19.UIListLayout
    u19.Size = UDim2.new(1, 0, 0, u20.AbsoluteContentSize.Y / u10.UIScale.Scale)
    u20:GetPropertyChangedSignal("AbsoluteContentSize"):Connect(function() --[[Function name: update, line 48]]
        --[[
        Upvalues:
            [1] = u19
            [2] = u20
            [3] = u10
        --]]
        u19.Size = UDim2.new(1, 0, 0, u20.AbsoluteContentSize.Y / u10.UIScale.Scale)
    end)
end
for _, u21 in u11.Updates:GetChildren() do
    if u21:IsA("Frame") then
        v7(u21.Button, function() --[[Anonymous function at line 58]]
            --[[
            Upvalues:
                [1] = u18
                [2] = u21
            --]]
            u18(u21.Name)
        end)
    end
end
v9:ConnectDataChanged("LastUpdate", function(p22) --[[Anonymous function at line 65]]
    --[[
    Upvalues:
        [1] = u18
        [2] = u4
    --]]
    if p22.LastUpdate.ShouldDisplay then
        u18(u4.Update)
    end
end)
v5(u11.Close, v6.Button.Red)
v7(u11.Close, function() --[[Anonymous function at line 73]]
    --[[
    Upvalues:
        [1] = u8
    --]]
    u8:Close()
end)
v7(u10.Settings.Frame.Sidebar.Buttons.Changelog.Button, function() --[[Anonymous function at line 80]]
    --[[
    Upvalues:
        [1] = u8
    --]]
    u8:Open("_changelog")
end)
v3(u11.Updates, u11.Updates.UIListLayout)
v3(u11.ScrollingFrame, u11.ScrollingFrame.UIListLayout)
return {}