--devbgascension

-- Bytecode (Base64):
-- BgP/AQVDbG9uZQZQYXJlbnQHVmlzaWJsZQVWYWx1ZQRtYXRoA21pbgdHZXRUaWVyEEdldFBvaW50c0ZvclRpZXIDc2luEkFic29sdXRlV2luZG93U2l6ZQFZEkFic29sdXRlQ2FudmFzU2l6ZQVTY2FsZQdWZWN0b3IyA25ldw5DYW52YXNQb3NpdGlvbgZCdWJibGUFTGFiZWwEY2VpbARUZXh0BVVEaW0yCWZyb21TY2FsZQRTaXplCFRleHRTaXplCFBvc2l0aW9uB2FuaW1hdGUNQ2hhbGxlbmdlUGFzcwZQb2ludHMFdGFibGUEZmluZAdDbGFpbWVkA0hVRA1Ob3RpZmljYXRpb25zBUNsb3NlBEl0ZW0MR2V0QXR0cmlidXRlCkpTT05EZWNvZGUIZnJvbUl0ZW0DR2V0B1Jld2FyZHMEVHlwZQNQZXQYQ2hhbGxlbmdlUGFzc0NsYWltUmV3YXJkCkZpcmVTZXJ2ZXIVQ2hhbGxlbmdlUGFzc0ZyZWVTa2lwBFNob3cSVW5sb2NrQWxsUHJvZHVjdElkFVByb21wdFByb2R1Y3RQdXJjaGFzZQxQcmljZUluUm9idXgCX18GQnV0dG9uBCUqJSoMUm9idXhVbmljb2RlBmZvcm1hdA5SZXNldFByb2R1Y3RJZB5Zb3UgbmVlZCAlKiB0byByZXNldCB0aGUgcGFzcyEJR2VtUmVzZXRzDEdldFJlc2V0Q29zdAlDYW5BZmZvcmQNZnJvbU5vdEVub3VnaAVCdWlsZBJDaGFsbGVuZ2VQYXNzUmVzZXQEQ29zdApUZXh0Qm91bmRzAVgTdXBkYXRlUmVzZXRHZW1zU2l6ZRdTa2lwQ2hhbGxlbmdlc1Byb2R1Y3RJZAZpbnNlcnQVQ2hhbGxlbmdlUGFzc0NsYWltQWxsBE9wZW4ISXNBY3RpdmUDWmVuDUFyZWFzVW5sb2NrZWQGSXNPcGVuCkZpbmlzaFRpbWUNVW5peFRpbWVzdGFtcBBHZXRTZXJ2ZXJUaW1lTm93A21heA5mb3JtYXRSZWFsVGltZQR0YXNrBHdhaXQJRnJlZVNraXBzBkFtb3VudAklKiBTa2lwJSoAAXMPTGFzdEludml0ZUJvbnVzEUludml0ZUJvbnVzUGVyaW9kFkJhY2tncm91bmRUcmFuc3BhcmVuY3kIVUlTdHJva2UMVHJhbnNwYXJlbmN5EFRleHRUcmFuc3BhcmVuY3kGQWN0aXZlClNlbGVjdGFibGUG4o+zICUqCmZvcm1hdFRpbWUGSW52aXRlD3VwZGF0ZUZyZWVTa2lwcwhJbnN0YW5jZRdFeHBlcmllbmNlSW52aXRlT3B0aW9uczZFYXJuIGEgZnJlZSBza2lwIHdoZW4gYSBmcmllbmQgam9pbnMgZnJvbSB5b3VyIGludml0ZSENUHJvbXB0TWVzc2FnZRBQcm9tcHRHYW1lSW52aXRlE2J1YmJsZS1jaGFsbGVuZ2UtJSoIRmluZEJ5SWQFVGFza3MIUHJvZ3Jlc3MOR2V0UmVxdWlyZW1lbnQETmFtZQtMYXlvdXRPcmRlcglDb21wbGV0ZWQHQ29udGVudANCYXIERmlsbAQlKiUlCkZvcm1hdFRhc2sESWNvbgpVcGRhdGVJY29uBlJld2FyZAlHZXRBbW91bnQKZnJvbU9mZnNldARGb250C0dldFRleHRTaXplCkNoYWxsZW5nZXMETGlzdAREb25lDHVwZGF0ZVF1ZXN0cwZPcmFuZ2UJRmluYWxUaWVyCVR3ZWVuSW5mbwRFbnVtC0Vhc2luZ1N0eWxlBFNpbmUPRWFzaW5nRGlyZWN0aW9uA091dAZDcmVhdGUEUGxheQVDbG91ZAVDbGFpbQhGcmVlU2tpcAxGb3JtYXRBbW91bnQKSlNPTkVuY29kZQxTZXRBdHRyaWJ1dGULSW1hZ2VCdXR0b24FRnJhbWUVWW91IGhhdmUgJSogdG8gY2xhaW0hCWF1dG9Db2xvchFDaGFsbGVuZ2UgUmV3YXJkcwZZZWxsb3cFU291bmQSTm90aWZpY2F0aW9uU2Vhc29uASEIdG9zdHJpbmcGdXBkYXRlB0J1dHRvbnMJVW5sb2NrQWxsBkVmZmVjdANBZGQGUmVtb3ZlEUltYWdlVHJhbnNwYXJlbmN5BFRpbWUHRGVzdHJveQNQb3AIUm90YXRpb24EQmFjawVkZWxheQRnYW1lB1BsYXllcnMKR2V0U2VydmljZRFSZXBsaWNhdGVkU3RvcmFnZQpSdW5TZXJ2aWNlC1RleHRTZXJ2aWNlC0h0dHBTZXJ2aWNlDFR3ZWVuU2VydmljZRJNYXJrZXRwbGFjZVNlcnZpY2UJV29ya3NwYWNlDVNvY2lhbFNlcnZpY2UHcmVxdWlyZQZDbGllbnQJRnJhbWV3b3JrCFNlcnZpY2VzCUxvY2FsRGF0YQNHdWkFVXRpbHMSVXBkYXRlV2hpbGVHdWlPcGVuBlNoYXJlZAREYXRhD0F1dG9CdXR0b25Db2xvcgdQYWxldHRlD0NsaWNrYWJsZUJ1dHRvbhNDaGVja0ludmVudG9yeVNwYWNlB05ldHdvcmsGUmVtb3RlB0NsYXNzZXMEUG9vbAVTdGF0cwlRdWVzdFV0aWwJVXRpbGl0aWVzBlN0cmluZwxGb3JtYXRTdWZmaXgISXRlbVV0aWwKQW5pbWF0aW9ucwdTZXRGYWRlB1Rvb2x0aXAIQnVpbGRlcnMOVG9vbHRpcEJ1aWxkZXIMRm9ybWF0Q29tbWFzElByb2Nlc3NpbmdQdXJjaGFzZQhHdWlGcmFtZQ1Qcm9tcHRCdWlsZGVyBlByb21wdARNYXRoC1Byb2R1Y3RJbmZvCUNvbnN0YW50cxFTZXRDb3JlR3VpRW5hYmxlZA5QbGF5TG9jYWxTb3VuZAlTdGF0c1V0aWwMTm90aWZpY2F0aW9uCFJpY2hUZXh0BVNoaW55DklzVHJhZGluZ1BsYXphC0xvY2FsUGxheWVyCVBsYXllckd1aQlTY3JlZW5HdWkHVUlTY2FsZQ5TY3JvbGxpbmdGcmFtZQVEb2dneQhUZW1wbGF0ZQtOdW1iZXJWYWx1ZRhHZXRQcm9wZXJ0eUNoYW5nZWRTaWduYWwHQ29ubmVjdAlIZWFydGJlYXQMQmluZE9uT3BlbmVkEkNvbm5lY3REYXRhQ2hhbmdlZAxCaW5kT25DbG9zZWQDUmVkBkNsb3VkcwZUaWVyJSoFSG92ZXIHT25FbnRlcgVHcmVlbgZQdXJwbGUVQ29ubmVjdFByb2R1Y3RDaGFuZ2VkClJlc2V0Um9idXgJUmVzZXRHZW1zBFNraXAIQ2xhaW1BbGwETGVmdAhDdXJyZW5jeQVDb2lucwdCdW5kbGVzBXNwYXduBUV2ZW50BlF1ZXN0cw9RdWVzdHNDb21wbGV0ZWQAJQIAAQAAAAX7AAAAvAAAOgAAAACfAAIAggAAAAEDAQA7AAEYAAAAAAA8AAAAABICCQAABwQAAAUCAgGLAfsEAABNAwQkAAAAAE0CA4ABAAAAKwIBAIIAAQD7AgEAkAMAAkMCAgPeAgEA+wQCAE0DBOwDAAAA+wQDAJ4TAwMEAAAApAIGAAAUQICfAgMC+wMEAFIFAgC8AwMlBwAAAJ8DAwKMBAEAYAMCAAQAAACMAwEAlQQDCPsFBABSBwMAvAUF8gkAAACfBQMC+wYEAFIIBAC8BgbyCQAAAJ8GAwImCAIFJgkGBewHCAlDCgMHWwkKC3gICQqMCuf/+w8BAFsODw27GA4CpA0PAAA4QICfDQICWwwNDEMLCAyeEwoDCwAAAKQJBgAAFECAnwkDAg4BGQD7DAUATQsMxRAAAABNCgt4EQAAAPsNBQBNDA2tEgAAAE0LDHgRAAAA+w8GAE0OD4QTAAAACQ0IDkMMCw0+DgoUJg0MDvsOBQCkDxcAAFhQgYwQAABSEQ0Anw8DAjAPDpUYAAAA+wwCAE0LDOwDAAAA+wwDAOwKCwxvDBkAQwsMCvsOBwBNDQ4nGgAAAE0MDcMbAAAA+w0IALsHAgNSDwIApA4dAABwQICfDgICnw0CAjANDPUeAAAA+w0HAE0MDScaAAAApA0hAACA8IFSDgsAUg8LAJ8NAwIwDQwvIgAAAPsOBwBNDQ4nGgAAAE0MDcMbAAAAjA4tAIwQHgAJDxAKQw0ODzANDG4jAAAA+wwHAKQNJAAAWPCBjA4AAIwPFACMEAEAUhEJAJ8NBQIwDQw7JQAAAIIAAQAmAwIDAwIAAAAAAAAAAAMEAwUDBgQAFECAAwcCAAAAAAAA8D8DCAIAAAAAAABJQAIAAAAAAMBywAIAAAAAAAAkQAIAAAAAAAAIQAMJBAA4QIADCgMLAwwDDQIAAAAAAAAAQAMOAw8EAFhQgQMQAgAAAAAAAOg/AxEDEgMTBABwQIADFAMVAxYEAIDwgQMXAxgEAFjwgQMZAEgaARgAAAAAAAABAwAAAAIAAAAAAAAAAAEAAAAAAQAAAQMBAAAAAAEAAAAAAQAAAgAAAQAAAAAAAAAAAAAAAAACAQAAAAABAAAAAAIAAAAAAQACAAAAAAAAAAMAAAAAAQABAAAAAAAAAAAAAAAAAAEAAAAAAAAAAAABAAAAAAAAAAAAAAEAAAAAAAAAAAABSQAAAAADAAEAAAAF+wAAAIwBAACpAgAAnwADAYIAAQAAAG8AARgAAAAAAXAAAAAAAwABAAAABfsAAACMAQAAqQIBAJ8AAwGCAAEAAABzAAEYAAAAAAF0AAAAAAQBAQAAAAX7AQAAUgIAAKkDAACfAQMBggABAAAAdwABGAAAAAABeAAAAAADAAEAAAAF+wAAAIwBAACpAgEAnwADAYIAAQAAAHsAARgAAAAAAXwAAAAACQEDAAAAIowBAACMBAEA+wUAAE0IADAAAAAATQcILQEAAAC8BQUlAgAAAJ8FAwJSAgUAjAMBAKgCDACkBQUAABAwgE0HADAAAAAATQYH2gYAAABSBwQAnwUDAisFAgBSAQQAZQABAIsC9P/7AgEA8QEGAAIAAADeAQEA+wICAIwDAACpBAEAnwIDAYIAAQAHAxsDHAMHAx0DHgQAEDCAAx8AgwEAARgAAQAAAAAAAAAAAAAAAQAAAAAAAAAAAQH9BgAAAQEAAAAChAAAAAACAAIAAAAQ+wEAAE0AAR8AAAAAqQEAADABAIABAAAA+wEAAE0AATwCAAAAqQEAADABAIABAAAA+wABAKkBAACfAAIBggABAAMDIAMDAyEAkgEAARgAAAAAAAABAAAAAAABAAABkwAAAAACAAIAAAAQ+wEAAE0AAR8AAAAAqQEBADABAIABAAAA+wEAAE0AATwCAAAAqQEBADABAIABAAAA+wABAKkBAQCfAAIBggABAAMDIAMDAyEAmQEAARgAAAAAAAABAAAAAAABAAABmgAAAAACAAEAAAAF+wAAALwAAGMAAAAAnwACAYIAAQABAyIApAEAARgAAAAAAaUAAAAABAADAAAAFPsAAABvAgAAvAAAEgEAAACfAAMCKwABAIIAAQD7AQEAUgMAALwBAcsCAAAAnwEDAisBAQCCAAEA+wMCAE0CA2cDAAAAUgMBAJ8CAgCCAgAABAMjAyQDJQMmALsBAAEYAAAAAAABAQIAAAAAAQECAAAAAAC8AAAAAAUABAAAABv7AAAAvAAAfwAAAACfAAICKwABAIIAAQBNAwAwAQAAAE0CAxUCAAAA+wMBAIcBAgNNAgERAwAAAPACBgAEAACA+wICAFIDAACfAgICKwIBAIIAAQD7AgMAbwQFALwCAmsGAAAAnwIDAYIAAQAHAycDGwMoAykDKgMrAywAyAEAARgAAAAAAQEDAAAAAAABAAAAAAAAAAEDAAAAAAHJAAAAAAMAAQAAAAb7AAAAbwIAALwAAGsBAAAAnwADAYIAAQACAy0DLADYAQABGAAAAAAAAdkAAAAABQAEAAAADfsAAAC8AACYAAAAAJ8AAgH7AAEA+wICAPsEAwBNAwRKAQAAALwAAGkCAAAAnwAEAYIAAQADAy4DLwMwAOgBAAEYAAAAAAEAAAAAAAAAAekAAAAACAEDAAAAGw4ACABNAgAbAAAAAA4CBQD7AQAATQIAGwAAAACfAQICZQABAG8BAQD7BAEATQMErAIAAABNAgPDAwAAAG8EBAD7BwIATQYHOAUAAABSBwEAvAQEjQYAAACfBAQCUgMEADADAvUHAAAAggABAAgDMQMyAzMDEgM0AzUDNgMUAO0BAAEYAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAAB7gAAAAAFAAQAAAAN+wAAALwAAJgAAAAAnwACAfsAAQD7AgIA+wQDAE0DBOwBAAAAvAAAaQIAAACfAAQBggABAAMDLgM3AzAA+QEAARgAAAAAAQAAAAAAAAAB+gAAAAAIAQMAAAAbDgAIAE0CABsAAAAADgIFAPsBAABNAgAbAAAAAJ8BAgJlAAEAbwEBAPsEAQBNAwSsAgAAAE0CA8MDAAAAbwQEAPsHAgBNBgc4BQAAAFIHAQC8BASNBgAAAJ8EBAJSAwQAMAMC9QcAAACCAAEACAMxAzIDMwMSAzQDNQM2AxQA/gEAARgAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAH/AAAAAAUBAAAAAAdvAgAAUgQAALwCAo0BAAAAnwIDAlIBAgCCAQIAAgM4AzYAkgIAARgAAAAAAAAAEwEAAAAGAAYAAAAo+wAAALwAAH8AAAAAnwACAisAAQCCAAEA+wEBAE0EADABAAAATQMEuAIAAAC8AQHCAwAAAJ8BAwL7AgIAUgQAAFIFAQC8AgLPBAAAAJ8CBAIrAg0A+wMDAE0CAxgFAAAAUgMAAFIEAQDABQYAnwIEAvsDBAC8BAJPBwAAAJ8EAgCfAwAAggMAAPsCBQBvBAgAvAICawkAAACfAgMBggABAAoDJwMbAzkDOgM7AzwGEQM9Az4DLAERigIAARgAAAAAAQEDAAAAAAAAAAEAAAAAAAABAAAAAAAAAwAAAAAAAwAAAAABCwEAAAAHAAIAAAAe+wMAAE0CA6wAAAAATQECIwEAAABNAAHDAgAAAE0FAKEEAAAATQQFeQUAAAD7BgEATQUGhAYAAADsAwQFuwcDAqQCCQAAIHCAnwICApUBAgOkAgwAACyggIwDAABSBAEAjAUBAIwGAACfAgUCMAIALw0AAACCAAEADgMzAz8DEgIAAAAAAADwPwNAA0EDDQMFAxMEACBwgAMVAw8EACyggAMXAJwCQgEYAAAAAAAAAAEAAAAAAAAAAAAAAAABAAAAAAAAAAABHQEAAAAFAAQAAAAN+wAAALwAAJgAAAAAnwACAfsAAQD7AgIA+wQDAE0DBPUBAAAAvAAAaQIAAACfAAQBggABAAMDLgNDAzAArAIAARgAAAAAAQAAAAAAAAABLQEAAAAIAQMAAAAbDgAIAE0CABsAAAAADgIFAPsBAABNAgAbAAAAAJ8BAgJlAAEAbwEBAPsEAQBNAwSsAgAAAE0CA8MDAAAAbwQEAPsHAgBNBgc4BQAAAFIHAQC8BASNBgAAAJ8EBAJSAwQAMAMC9QcAAACCAAEACAMxAzIDMwMSAzQDNQM2AxQAsgIAARgAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAEzAQAAAAwABAAAAEP7AAAAvAAAfwAAAACfAAICKwABAIIAAQBNAQAwAQAAAPsCAQBNBAEtAgAAALwCAiUDAAAAnwIDAv8DAAAAAAAAjAYBAFIEAgCMBQEAqAQPAKQHBgAAFECATQgB2gcAAABSCQYAnwcDAisHBwCeNAMFBgAAAFIIAwBSCQYApAcJAAAgQICfBwMBiwTx/xwEAwANBAIACgAAgIIAAQCpBAAAUgUDAMYGAADGBwAAZAUJAE0LARULAAAAhwoLCU0LChEMAAAA8AsDAA0AAICpBAEAZQACAG4F9v8CAAAADgQFAPsFAgBSBgAAnwUCAisFAQCCAAEA+wUDAG8HDgC8BQVrDwAAAJ8FAwGCAAEAEAMnAxsDHAMHAx0DHgQAFECAAx8DRAQAIECAAgAAAAAAAAAAAygDKQMqA0UDLAC8AgABGAAAAAABAQMAAQAAAAAAAgABAAAAAQAAAAAAAAEAAAAAAAD+BQAAAQMBAAAAAQAAAQAAAAEB/AAHAAAAAAEDAAAAAAE9AQAAAAMAAQAAAAb7AAAAbwIAALwAABYBAAAAnwADAYIAAQACAxsDRgDtAgABGAAAAAAAAW4BAAAACAAGAAAAP/sAAAC8AAB2AAAAAJ8AAgL7AQEAvAEBfwEAAACfAQICDgEGAE0DATIDAAAATQIDQgIAAAArAgEAqQAAAPsCAgAwAAKABAAAAPsCAwBvBAUAvAICMQYAAACfAgMCDgIFACsABAD7AgMAvAICYwcAAACfAgIBjAMAAPsHAABNBgfZCAAAAE0FBrcJAAAA+wYEALwGBrcKAAAAnwYCAiYEBQaeEgMDBAAAAKQCDQAAMLCAnwIDAvsFAgBNBAWsDgAAAE0DBMMPAAAA+wUFAE0EBYIQAAAAUgUCAJ8EAgIwBAP1EQAAAKQDFAAATCCBjAQBAJ8DAgFIAML/ggABABUDRwMnA0gDSQMDAxsDSgMiA0sDTANNAwUDTgQAMLCAAzMDEgNPAxQDUANRBABMIIEA8QIAARgBAAAAAQAAAAEAAAAAAAECAAACAAAAAAAAAQAAAAMAAAAAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAACAAAA8RFyAQAAAA0ABgAAAHP7AAAAvAAAfwAAAACfAAICKwABAIIAAQBNAgAwAQAAAE0BAlECAAAA+wMBAE0CAysDAAAAbwQEAFIGAQANAQMABQAAgG8HBgBlAAEAbwcHALwEBI0IAAAAnwQEAlIDBAAwAwL1CQAAAPsCAgC8AgK3CgAAAJ8CAgJNBQAwAQAAAE0EBbUMAAAAkAMEC/sGAwBNBQaMDQAAAEMEAwUmBQQCjAcAALcHAgAFAAAAqQYAAakGAQD7BwQADgYCAG8IDgBlAAEAjAgAADAIBzoPAAAA+wgEAE0HCG0QAAAADgYCAG8IEQBlAAEAjAgAADAIB9kSAAAA+wgEAE0HCMMTAAAADgYCAG8IFABlAAEAjAgAADAIByQVAAAA+wkEAE0ICcMTAAAATQcIbRAAAAAOBgIAbwgRAGUAAQCMCAAAMAgH2RIAAAD7BwQAVggGADAIB4MWAAAA+wcEAFYIBgAwCAckFwAAAIwHAABgBxEABQAAAPsIBABNBwjDEwAAAG8JGAD7DAUATQsM2RkAAABSDAUAnwsCArwJCY0IAAAAnwkDAlIICQAwCAf1CQAAAIIAAQD7CAQATQcIwxMAAABvCBoAMAgH9QkAAACCAAEAGwMnAxsDUgNTA1QCAAAAAAAA8D8DVQNWAzYDFANNAgAAAAAAAAAAA1cDWAIAAAAAAADgPwNZA1oCAAAAAAAA6D8DWwMSAgAAAAAAANA/A1wDXQNeA18DYANhAI0DYgEYAAAAAAEBAwAAAAEAAAAAAAAAAAAAAAAAAAACAAAAAQAAAAABAAAAAgIAAAAAAQAAAAAAAAEAAAAAAAAAAAEAAAAAAAAAAAEAAAAAAAAAAAAAAQAAAAEAAAACAAABAAAAAAAAAAAAAAAAAAAAAgAAAAAAAo4BAAAAAwACAAAADvsAAABvAgAAvAAAMQEAAACfAAMCDgACAPsAAQCfAAEBpAAEAAAMIIBvAQUAnwACAUgA8/+CAAEABgMbA0oDUANRBAAMIIACAAAAAAAA4D8AqwMAARgBAAAAAAABAAIAAAD8BqwBAAAABAACAAAADaQAAgAABACAbwEDAJ8AAgJvAQQAMAEApgUAAAD7AQAA+wMBALwBAWIGAAAAnwEDAYIAAQAHA2MDDwQABACAA2QDZQNmA2cAuAMAARgAAAAAAQAAAgAAAAABuQEAAAAVAAcAAACaAfsAAAC8AAB/AAAAAJ8AAgIrAAEAggABAIwDAQCMAQMAjAIBAKgBiwBvBQEAUgcDALwFBY0CAAAAnwUDAlIEBQD7BQEAUgcAAFIIBAC8BQW5AwAAAJ8FBAIOBX0ATQcFRAQAAAATBgcATQgFFQUAAAATBwgATQkF5AYAAAATCAkA+woBAFIMBgC8Cgp/BwAAAJ8KAwLsCQgK+woCALwKCn8AAAAAnwoCAjAECroIAAAAMAMKAAkAAABNCwoYCgAAAE0NBdoMAAAAkAwNCzAMC4ANAAAATQ0Kvg4AAABNDA0/DwAAAE0LDG8QAAAApAwTAABIEIFSDQkAjA4AAIwPAQCMEAYAnwwFAjAMCy8UAAAATQ0Kvg4AAABNDA0/DwAAAE0LDMMVAAAAbw0WAFsQCRe7BxACpA8aAABkgIGfDwICvA0NjQIAAACfDQMCUgwNADAMC/UbAAAATQwKvg4AAABNCwzDFQAAAPsMAQBSDgYAvAwMvRwAAACfDAMCMAwL9RsAAAD7CwEATQ0Krh0AAABSDgUAvAsLIR4AAACfCwQBTQ0Kvg4AAABNDA0/HwAAAE0LDCsgAAAA+wwDAPsNBABSDwcAvA0NAiEAAACfDQMAnwwAAjAMC/UbAAAApAwjAACIEIH7DgUATRAL9RsAAABNEQtuJAAAAE0SCzklAAAApBMnAABIYIJvFCgAnxMCALwODropAAAAnw4AAk0NDnkqAAAAjA4eAJ8MAwIwDAsvFAAAAPsOBgBNDQ4BKwAAAE0MDessAAAAMAwKJC0AAACLAXX/+wECALwBATUuAAAAnwECAYIAAQAvAycDaAM2A2kDagMoA2sDbANtA24DbwEAAx8DAwNwA3EDcgMVAw8EAEgQgQMXAxIDcwIAAAAAAABZQAMFAxMEAGSAgQMUA3QDdQN2A3cDUwN4A3kEAIgQgQMYA3oDDgQASGCCAgAAAAAAAPB/A3sDQQN8A30DAgN+AMQDfwEYAAAAAAEBAgAAAAEAAAAAAAEAAAAAAAEDAAABAAABAAABAAAAAAACAAAAAQABAAEAAAAAAAABAAAAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAEAAAAAAAACAAAAAAABAAAAAAAAAAABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQAAAAAAAOkZAAAAAcUBAAAAAwABAAAABvsAAABvAgAAvAAAFgEAAACfAAMBggABAAIDGwNGAMYEAAEYAAAAAAABRwIAAAAGAQQAAAATTQEAwwAAAABvAgEAMAIB9QIAAAD7AQAAUgIAAPsFAQBNBAWsAwAAAE0DBG4EAAAAnwEDAfsBAgBSAgAAwAMFABICAwCfAQMBggABAAYDEgNGAxQDMwOAAQYdAR3DBDMBGAAAAAAAAQAAAAAAAAABAAAAAANEAgAAAB0AGQAAAI0D+wAAALwAAH8AAAAAnwACAisAAQCCAAEATQEAMAEAAAD7BAEATQMEJwIAAABNAgPDAwAAAPsDAgBNBAEtBAAAAIwFECefAwMCMAMC9QUAAACMAgAA+wMDAE0FAS0EAAAAvAMDJQYAAACfAwMCjAYBAFIEAwCMBQEAqAQKAKQHCQAAIHCATQgB2goAAABSCQYAnwcDAisHAgBSAgYAZQABAIsE9v/7BAQA+wcDAE0GB5MLAAAAtwMCAAYAAACpBQABqQUBADAFBIAMAAAAqQQAAPsGAwBNBQaTCwAAAH0FCwADAAAATQYB2goAAAAcBQYA+wcDAE0GB5MLAAAA8QUCAAYAAACpBAABqQQBAPsFBQAwBAWADAAAAPsFBgAwBAWADAAAAPsFAwBNBwG4DQAAALwFBcIOAAAAnwUDAvsJBgBNCAmsDwAAAE0HCCMQAAAATQYHwwMAAAD7BwIATQgFKxEAAACMCRAnnwcDAjAHBvUFAAAATQYBLQQAAAANAgwAEgAAAFIIBgD7CQMAUgsCALwJCfITAAAAnwkDAEwTAAKkBxYAAFRAgZ8HAAJSBgcA+wcHAPEGFQAHAAAApAcZAABgcIFvCBoApAkeAB1wsMGkCiEAIHywwZ8HBAL7CAgA+woJAFILBwDiDCMAMAYM7CIAAAC8CAiWJAAAAJ8IBQK8CAjuJQAAAJ8IAgHeBgcADQICABIAAACpBwABqQcBAPsIAwBNCgEtBAAAALwICCUGAAAAnwgDAvsJAwBSCwYAvAkJJQYAAACfCQMC+woKAMYLAADGDAAAZAqdAKQQCQAAIHCATREB2goAAABSEg0AnxADAkcQAgAAAACAqQ8AAakPAQDUDQIACAAAAKkQAAGpEAEATRIO1yYAAABNERIFJwAAADAQEYAMAAAATRMO1yYAAABNEhMFJwAAAE0REtoKAAAAMA8RgAwAAAC3CQIADQAAAKkRAAGpEQEATRQO1yYAAABNExQFJwAAAE0SE6wPAAAAVhMPADATEoAMAAAADhECAG8TKABlAAEAjBMAADATEjopAAAATRMSbSoAAAAOEQIAbxQaAGUAAQCMFAAAMBQT2SsAAABNExLDAwAAAA4RAgBvFCwAZQABAIwUAAAwFBMkLQAAAE0UEsMDAAAATRMUbSoAAAAOEQIAbxQaAGUAAQCMFAAAMBQT2SsAAABWExEAMBMSgy4AAABWExEAMBMSJC8AAACVFAgw8Q0CABQAAACpEwABqRMBAFIUEwAOFAcATRUBUTEAAACMFgAAtxYCABUAAACpFAABqRQBAE0WDtcmAAAATRUWHjIAAAAwFBWADAAAAE0WDtcmAAAATRUWwwMAAABWFhAADhYBAFYWFAAwFhWADAAAAE0WARUzAAAAhxUWDfsWCwBNGQ7XJgAAAE0YGco0AAAAUhkVALwWFiE1AAAAnxYEAfsWCwBNGg7XJgAAAE0ZGso0AAAATRgZKxEAAABSGRUAvBYW9TYAAACfFgQBbxg0APsZDABSGxUAvBkZnjcAAACfGQMAvBYOLjgAAACfFgAB+xYNAE0YDtcmAAAATRcYyjQAAAAODwIAbxg5AGUAAQCMGAAAxhkAAP8aAAACAAAAbxs6AG8cOwDFGhsDAQAAAJ8WBQFuCmL/AgAAAIwKAACMDQEAUgsIAIwMAQCoCwkApA4JAAAgcIBNDwHaCgAAAFIQDQCfDgMCKw4BAJUKCjCLC/f/+wsOAPEKIwALAAAA+wsOAA4LHwD7Cw4AYAsdAAoAAAD7Cw8Abw08APsQEABNDxDMPQAAAG8QPgD7ExEATRIT9QUAAABNERJ9PwAAAJ8PAwK8DQ2NQAAAAJ8NAwJSDA0A4g1CAG8OQwAwDg1uQQAAAMAORAASAhIAEgIRABICEwASAhQAMA4NrA8AAACfCwMB3goOAPsLFQCMDQAAtw0CAAoAAACpDAABqQwBADAMC4AMAAAA+wwVAE0LDMMDAAAAjA0JAGANAwAKAAAAbwxFAGUABQC7PwoDUg0KAKQMRwAAAGBEnwwCAjAMC/UFAAAA+wsWAIwNAQC3DQIACgAAAKkMAAGpDAEAMAwLgAwAAAD7CxcAnwsBAfsLGACfCwEBggABAEgDJwMbAxEDEgMcAxQDBwMdAx4EACBwgAMfA4EBAwMDOQM6AzMDPwNTAgAAAAAAAAAAAwgDBQMGBABUQIEDggEDDwQAYHCBAgAAAAAAAOg/A4MBA4QBA4UBBB1wsMEDhgEDhwEEIHywwQMEBQEiA4gBA4kBA4oBA4sBAgAAAAAAAOA/A1kDWgNbAgAAAAAAANA/A1wDXQNeAgAAAAAAAPA/A1IDjAEDKAMjA3YDjQEDjgEDjwECZmZmZmZm1j8DkAEDkQEDkgEDkwEDlAEDlQEDNgOWAQUCQQ8DlwEGHgOYAQOZAQQAAGBEAR7rA5oBARgAAAAAAQEDAAEAAAAAAAAAAAAAAAIBAAAAAAABAAAAAQAAAAAAAAEB/QcAAAAAAAAAAAACAAAAAAAAAAAAAAAAAAAAAQAAAQAAAgAAAAAAAQAAAAAAAAAAAAAAAAADAAEAAQAAAAAAAAAAAAADAAABAAAAAAAAAAEAAAAAAAAAAAAAAAICAAAAAgAAAAAAAQAAAAACAAAAAQAAAAAAAAAAAAEAAAACAAAAAAABAAAAAAAAAAIAAAABAAAAAAABAAABAAAAAAABAAAAAAAAAAEAAAAAAAAAAQAAAAAAAAAAAAEAAAEAAAIAAAAAAQAAAAAAAAAAAQAAAAAAAgAAAAAAAAAAAgAAAQAAAAAAAAAAAQAAAAAAAAAAAAABAAAAAAAAAAACAAAAAAAAAAAAAAAAAAAAAOQAIQEAAAABAAAAAAAAAf4GAAABAAAAAAEAAAAAAAAAAAAAAAAAAAAAAQAAAQAAAAAAAP4LAwAAAAAAAAABAAAAAAAAAAAAAAAAAAABAAAAAAAAAAMAAQAB7AEAAAAGAAIAAAAM+wAAAPsFAQBNBAXTAAAAAE0DBHUBAAAATQIDswIAAAC8AABfAwAAAJ8AAwGCAAEABAObAQOcAQOdAQOeAQDaBAABGAAAAAAAAAAAAAAAAVsCAAAABgACAAAADPsAAAD7BQEATQQF0wAAAABNAwR1AQAAAE0CA7MCAAAAvAAAaQMAAACfAAMBggABAAQDmwEDnAEDnQEDnwEA3QQAARgAAAAAAAAAAAAAAAFeAgAAAAYAAwAAABj7AAAA+wIBAPsDAgDiBAEAjAUBADAFBKMAAAAAvAAAlgIAAACfAAUCvAAA7gMAAACfAAIBpAAGAAAUQID7AgIATQECSgcAAACfAAIB+wABALwAAFAIAAAAnwACAYIAAQAJA6ABBQEAA4gBA4kBA1ADUQQAFECAA6EBA6IBAPcEAAEYAAAAAAAAAAAAAAAAAAEAAAAAAAEAAAABeAIAAAALAAMAAAB++wEAAE0AAScAAAAATQEAlAEAAAC8AQE6AgAAAJ8BAgKpAgEAMAIBgAMAAACMAgEAMAIBowQAAACkAgcAABhQgIwDMgCMBDIAnwIDAjACAS8IAAAAMAABJAkAAACkAgwAACyggG8DDQCkBBEAEDzgwJ8CAwL7AwEAbwQBAJ8DAgH7AwIA+wYAAE0FBsMSAAAAUgYCAOIHFACMCLQAMAgHOBMAAAC8AwOWFQAAAJ8DBQK8AwPuFgAAAJ8DAgH7AwIAUgUBAKQGDAAALKCAbwcNAKQIGAAXPODAnwYDAuIHGQCkCAcAABhQgIwJyACMCsgAnwgDAjAIBy8IAAAAbwgNADAIB6MEAAAAvAMDlhUAAACfAwUCvAMD7hYAAACfAwIBjAMBADADAKMEAAAATQMAwxIAAACpBAAAMAQDgAMAAACkAxwAAGyggW8EDQDZBQAAEgICABIAAQASAAIAnwMDAaQDHgAAdKCBjAQBAJ8DAgFNAwDDEgAAAKkEAQAwBAOAAwAAAPsDAgD7BgAATQUGwxIAAABSBgIA4gcUAIwIAAAwCAc4EwAAALwDA5YVAAAAnwMFArwDA+4WAAAAnwMCAfsDAgBSBQAAUgYCAOIHHwCMCAAAMAgHowQAAAC8AwOWFQAAAJ8DBQK8AwPuFgAAAJ8DAgGCAAEAIAMRA6MBAwEDAwOgAQMVA3kEABhQgAMXAwIDggEDDwQALKCAAgAAAAAAAOA/A4MBA4QBA4UBBBA84MADEgOkAQUBEwOIAQOJAQOlAQQXPODABQIIBANQA6YBBABsoIEDUQQAdKCBBQEEASLiBAABGAAAAAEAAAAAAQAAAQAAAQAAAAAAAAEAAwAAAAAAAgAAAQAAAAAAAAAAAAAAAAAAAQAAAAAAAAAAAQAAAAAAAAEAAP4AAAMAAAIAAAEAAAAAAgAAAAAAAAAGAAAAAgAAAAABAAAAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAWMCAAAATAAAAQAAywejAAAApAABAAAAAEBvAgIAvAAAFgMAAACfAAMCpAEBAAAAAEBvAwQAvAEBFgMAAACfAQMCpAIBAAAAAEBvBAUAvAICFgMAAACfAgMCpAMBAAAAAEBvBQYAvAMDFgMAAACfAwMCpAQBAAAAAEBvBgcAvAQEFgMAAACfBAMCpAUBAAAAAEBvBwgAvAUFFgMAAACfBQMCpAYBAAAAAEBvCAkAvAYGFgMAAACfBgMCpAcBAAAAAEBvCQoAvAcHFgMAAACfBwMCpAgBAAAAAEBvCgsAvAgIFgMAAACfCAMCpAkNAAAAwEBNDQFNDgAAAE0MDRwPAAAATQsMQxAAAABNCgtoEQAAAJ8JAgKkCg0AAADAQE0OAU0OAAAATQ0OHxIAAABNDA2hEwAAAE0LDI0UAAAAnwoCAqQLDQAAAMBATQ4BEhUAAABNDQ7GFgAAAE0MDTAXAAAAnwsCAqQMDQAAAMBATRABTQ4AAABNDxAfEgAAAE0OD6ETAAAATQ0O1xgAAACfDAICpA0NAAAAwEBNDwESFQAAAE0OD3gZAAAAnw0CAqQODQAAAMBATRIBTQ4AAABNERIfEgAAAE0QEaETAAAATQ8Q7BoAAACfDgICpA8NAAAAwEBNEwFNDgAAAE0SEx8SAAAATRESoRMAAABNEBFiGwAAAJ8PAgKkEA0AAADAQE0UARIVAAAATRMUHA8AAABNEhNSHAAAAE0REvYdAAAAnxACAqQRDQAAAMBATRUBEhUAAABNFBUcDwAAAE0TFBgeAAAATRITQh8AAACfEQICpBINAAAAwEBNFgESFQAAAE0VFqETAAAATRQVISAAAABNExRQIQAAAJ8SAgKkEw0AAADAQE0YARIVAAAATRcYHA8AAABNFhe1IgAAAE0VFqEjAAAATRQVxiQAAACfEwICpBQNAAAAwEBNGAESFQAAAE0XGKETAAAATRYXISAAAABNFRbQJQAAAJ8UAgKkFQ0AAADAQE0bAU0OAAAATRobHA8AAABNGRq1IgAAAE0YGR8SAAAATRcYRCYAAABNFhcEJwAAAJ8VAgKkFg0AAADAQE0ZAU0OAAAATRgZHxIAAABNFxh1KAAAAJ8WAgKkFw0AAADAQE0bARIVAAAATRobxhYAAABNGRq7KQAAAE0YGYYqAAAAnxcCAqQYDQAAAMBATR0BEhUAAABNHB0cDwAAAE0bHLUiAAAATRoboSMAAABNGRqaKwAAAJ8YAgKkGQ0AAADAQE0dAU0OAAAATRwdHxIAAABNGxxEJgAAAE0aG+osAAAAnxkCAqQaDQAAAMBATR0BTQ4AAABNHB0fEgAAAE0bHJUtAAAAnxoCAqQbDQAAAMBATR8BEhUAAABNHh/GFgAAAE0dHrspAAAATRwdRi4AAACfGwICpBwNAAAAwEBNHwFNDgAAAE0eHx8SAAAATR0efS8AAACfHAICpB0NAAAAwEBNIgESFQAAAE0hIhwPAAAATSAhtSIAAABNHyCMMAAAAE0eH0oxAAAAnx0CAqQeDQAAAMBATSIBEhUAAABNISIcDwAAAE0gIbUiAAAATR8gmTIAAACfHgICpB8NAAAAwEBNIQESFQAAAE0gIQczAAAAnx8CAqQgDQAAAMBATSQBTQ4AAABNIyQfEgAAAE0iI6ETAAAATSEiGDQAAACfIAICpCENAAAAwEBNJQFNDgAAAE0kJR8SAAAATSMkoRMAAABNIiMsNQAAAJ8hAgKkIg0AAADAQE0mARIVAAAATSUmoRMAAABNJCUhIAAAAE0jJBM2AAAAnyICAqQjDQAAAMBATScBTQ4AAABNJicfEgAAAE0lJqETAAAATSQlSTcAAACfIwICpCQNAAAAwEBNJwESFQAAAE0mJ6ETAAAATSUm0TgAAACfJAICpCUNAAAAwEBNKQFNDgAAAE0oKR8SAAAATScooRMAAABNJie0OQAAAJ8lAgKkJg0AAADAQE0pARIVAAAATSgpoRMAAABNJyh4OgAAAJ8mAgJNJwAxOwAAAE0pJ5k8AAAATSgpej0AAABNKSgrPgAAAE0rKDAXAAAATSornT8AAABNKyr+QAAAAE0sK0ZBAAAATS8qAUIAAABNLi/rQwAAAE0tLvJEAAAAxi4AADAuLSRFAAAATS4R70YAAADAL0cAEgAtAJ8uAgKkL0kAABiBhG8wSgCfLwICTTILk0sAAAC8MAvyTAAAAJ8wAwKMMQAA2TIBABIAKgASATH/EgAvABIAMAASAAsAEgArABIAKQASACwAEgAYAG81TQC8MymUTgAAAJ8zAwLANU8AEgAyALwzM8dQAAAAnzMDAW81UQC8My+UTgAAAJ8zAwLANVIAEgAyALwzM8dQAAAAnzMDAU0zAv1TAAAAwDVUABIAMgC8MzPHUAAAAJ8zAwFvNRcAwDZVABIAMgC8MxqqVgAAAJ8zBAHGMwAAbzYXANk3BgASAAsAEgEz/xIAMgC8NAkoVwAAAJ80BAFvNhcAwDdYABIAKAASACAAvDQaqlYAAACfNAQBbzYXAMA3WQASACgAEgAgALw0Gp9aAAAAnzQEAVI0DABNNiokRQAAAE01NmNbAAAATTcNrFwAAABNNjdvXQAAAJ80AwFSNA4ATTYqJEUAAABNNTZjWwAAAMA2XgASABoAnzQDAU01Kv5AAAAATTQ1j18AAABNNTTyRAAAAMY2AAAwNjUkRQAAAP82AAAAAAAAjDkBAE03C5NLAAAAjDgBAKg3bgC8OjU6YAAAAJ86AgJvPGEAUj45ALw8PI1iAAAAnzwDAlI7PAAwOzq6YwAAAE08C5NLAAAAJjs8OTA7OgBkAAAATTs612UAAACkPGcAABhhhow9AQBbQTlpuxhBAqRAbAAArKGGn0ACAls/QGh4Pj9obz9tAIxAAACfPAUCMDw7O24AAABSPTkAvDsL8kwAAACfOwMCTT0612UAAABNPD3DbwAAAFI9GABSPjsAnz0CAjA9PPVwAAAATUA612UAAABNP0DKcQAAAE0+P1ByAAAA2T8KABIAOgASAAQAEgAXALw8FoFzAAAAnzwEAVI8DABNPzrXZQAAAE0+PwV0AAAATT0+rFwAAABNPw2sXAAAAE0+P5t1AAAAnzwDAVI8DgBNPzrXZQAAAE0+PwV0AAAATT0+rFwAAADZPgsAEgAJABIAOQASAA8AEgAQAJ88AwFSPAwATT8612UAAABNPj8edgAAAE09PqxcAAAATT8NrFwAAABNPj9ndwAAAJ88AwFSPA4ATT8612UAAABNPj8edgAAAE09PqxcAAAAwD54ABIAEACfPAMBMDQ6JEUAAABqOjY5izeS/004KtN5AAAATTc4dXoAAABSOAwATTk3rFwAAABNOw2sXAAAAE06O257AAAAnzgDAVI4DgBNOTesXAAAAMA6fAASABkAEgAGABIAJwASAAsAnzgDAU06C0p9AAAAwDt+ABIAGAASADcAEgAfALw4Hm9/AAAAnzgEAU05KtN5AAAATTg54IAAAABSOQwATTo4rFwAAABNPA2sXAAAAE07PG57AAAAnzkDAVI5DgBNOjisXAAAAMA7gQASABkAEgAGABIAJwASAAsAnzkDAU07C+yCAAAAwDyDABIAGAASADgAEgAfALw5Hm9/AAAAnzkEAU06KtN5AAAATTk6cYQAAABSOgwATTs5rFwAAABNPQ2sXAAAAE08PWd3AAAAnzoDAVI6DgBNOzmsXAAAAMA8hQASAAkAEgALABIAFAASABsAEgAcABIAEACfOgMBwDqGABIAOQASACkATT05rFwAAABNPD0jhwAAAE07PMNvAAAAbz2IALw7O5ROAAAAnzsDAlI9OgC8OzvHUAAAAJ87AwFvPU0AvDsplE4AAACfOwMCUj06ALw7O8dQAAAAnzsDAU09OaxcAAAATTw9I4cAAABNOzzDbwAAAE1AO6GIAAAATT9AeYoAAABNQCmETQAAAOw+P0C7Bz4CpD2MAAAsooafPQIClTw9iaQ9ZwAAGGGGjD4AAFI/PACMQAEAjEEAAJ89BQIwPTsvjQAAAE08KgFCAAAATTs8EI4AAABSPAwATT07rFwAAABNPw2sXAAAAE0+P5t1AAAAnzwDAVI8DgBNPTusXAAAAMA+jwASABkAEgAGABIAJwASAAsAnzwDAU0+C/WQAAAAwD+RABIAGAASADsAEgAfALw8Hm9/AAAAnzwEAU09KtN5AAAATTw9bpIAAABSPQwATT48rFwAAABNQA2sXAAAAE0/QJt1AAAAnz0DAVI9DgBNPjysXAAAAMA/kwASAAkAEgALABIADwASABAAnz0DAU1CKB+UAAAATUFCxpUAAABNQEEJlgAAAE0/QIeXAAAATT4/spgAAABNPT4wFwAAAFI+JgCfPgECDj4HAKk+AAAwPj2AmQAAAP8+AAAAAAAAwTEAAII+AgBSPg4ATT89rFwAAADAQJoAEgAaAJ8+AwGkPp0AAHCyicA/ngASAAsAEgAJABIAPQASABoAEgAHABIAHQCfPgIBTT4qUZ8AAABNQD7ToAAAAE0/QKxcAAAAwEChABIACQASAD4AEgAHABIACwASAD8AEgAdAKRBnQAAcLKJwEKiABIAGgASAEAAn0ECAVJBDABSQj8ATUQNrFwAAABNQ0RndwAAAJ9BAwFSQQ4AUkI/AMBDowASAAgAEgAnAJ9BAwHAQaQAEgAJABIAEgASAC4AEgATABIAFAASAAMAEgAqAMZCAADGQwAATUsoH5QAAABNSkvGlQAAAE1JSgmWAAAATUhJh5cAAABNR0iymAAAAE1GRzAXAAAATUVGrFwAAABNREVJNwAAANlFHAASAAkAEgAsABIAEwASAAsAEgA3ABIAOAASADkAEgFC/xIABQASAC8AEgA2ABIAFAASAAQAEgAVABIBQ/8SACMAEgAkABIADQASAAwAEgAOABIAGgASAEQAEgA8ABIAQAASAEEAb0gXAMBJpQASACUAEgAqALxGGqpWAAAAn0YEAW9IFwDASaYAEgAlABIAKgC8RhqfWgAAAJ9GBAFNRhA2pwAAAG9HqACfRgICwEipABIALAASACEAEgAFALxGRsdQAAAAn0YDAf9IAAADAAAAb0kXAG9KqgBvS6sAxUhJBAEAAABSSUUAvEYJKFcAAACfRgQB/0YAAAAAAADBMQAAgkYCAKwBA6cBBAAAAEADqAEDqQEDqgEDqwEDrAEDrQEDrgEDrwEDsAEDsQEDsgEEAADAQAOzAQO0AQO1AQO2AQO3AQO4AQO5AQO6AQO7AQMbA7wBA70BA74BA78BA8ABA8EBA8IBA8MBA8QBA8UBA8YBA8cBA8gBA8kBA8oBA8sBA8wBA80BA84BA88BA9ABA9EBA9IBA9MBA9QBA6EBA9UBA9YBA9cBA9gBA9kBA9oBA9sBA9wBA90BA94BA98BA+ABA+EBA5EBA+IBA+MBA3wDfQPkAQMCAw8GAANjBAAYgYQD5QEDgQEDCAMNA+YBBgID5wEDBAYDA+gBBgQGBQPpAQPqAQYHBggD6wEDIgMzA+wBBgkD7QEDAQPuAQM2A20DbgOKAQMVBAAYYYYCAAAAAAAALkACAAAAAAAAAEADBQMJBACsoYYCAAAAAAAA4D8DGQMSAxQDIwPvAQPwAQOLAQPxAQOMAQPyAQYMA5sBA5wBA4ABBg0DLwYOA/MBA/QBBg8DNwYQA/UBBhIGEwM/A0ACAAAAAAAA8D8DQQMTBAAsooYDFwP2AQYUA0MGFQP3AQYWAyAD+AED+QED+gED+wEDAwYXA1AD/AEEAHCyiQYYA1IDYQYZBhoGGwYcBiAGIQP9AQM+BiMD/gED/wEgAAECAwQFBgcICQoLDA0ODxASExQVFhcYGRobHB8gISMBAAEHAAIAAAAAAAEAAAAAAAEAAAAAAAEAAAAAAAEAAAAAAAEAAAAAAAEAAAAAAAEAAAAAAAEAAAAAAAIAAAAAAAAAAAAAAQAAAAAAAAAAAAABAAAAAAAAAAABAAAAAAAAAAAAAAEAAAAAAAABAAAAAAAAAAAAAAEAAAAAAAAAAAAAAQDtAAAAAAAAAAABAAAAAAAAAAAAAAEAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAQAAAAAAAAAAAQAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAABAAAAAAAAAAABAAAAAPUAAAAAAAEAAAAAAAAAAAEAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAEAAAAAAAABAAAAAAAAAAAAAAEAAAAAAAAAAAAAAQAAAAAAAAAAAAABAAAAAAAAAAAAAAEAAAAAAAAAAAEAAAAAAAAAAAAAAQAAAAAAAAAAAwABAAAAAgAB7gAAAgABAAQAAAAAAAEAAAIAAAAABQAAAAEAAAAAAgUAAAAAAAAAAAAnAAAAAAAAAAAEAAAAAAAAAAAEAAAAAAAABAAAAAAABgIAAAAAAAAADwAAAAAAAAcAAAAAAAAKAAAAAAAAAAAAAQAAAAAAAAAHAAAAAgABAAACAAIAAAB/AQAAAQAAAAAAAAABAAAAAAEAAAAAAAAAAAAAAAAAAAAAAgAAAAEAAAAAAAAAAAIAAAAAAAAAAAAAAAAMAAAAAAAAAAAAAAABAAAAAAAAAAAAAAAADwAAAAAAAAAAAAAAAQAAAAAAAAAAAAUAAtMzAAAAAgAAAAAAAAABAAAAAMoAAAAFAAAAAAAAAAAJAAAAAgAAAAAAAAABAAAAAAAAAAAFAAAAAAAAAAAJAAAAAgAAAAAAAAABAAAAAAAAAAAAABIAAAYAAAAAAAAAAAAAAAAAAQAAAAAAAAD6AAAAAAABAAAAAAAAAAAAAAABAAAAAAAAAAAKAAAAAgAAAAAAvQABAAAAAAAAAAAGAAAAAAAAAAAHAAAAAgAAAAAAAAABAAAAAAAAAAAoAAAAAAAAAAAAAAACAAABAAABAAAABQAAAAAABAAAAAAAAAAAABkAAQAAAAIAAAAAAAAeAAAAAAAMAAAAAAAAAQAAAAAADAAAAAAAAAAjAQEAAAAAAABCAAAAAAAAAAACAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAG8AAAAAAAADAAAAAAAABQAAAAAAAAAAAAAjAAAAAAAAAAAAAAQAAAABAAAAEwAAAAsAAAASAAAAgQAAADYAAABDAAAAvgAAAAAkbhtfURDSYfpc3zXFPZcOxiBgM1sVr0gk0oXCg8OlYwhQiZS2ZZ8S/g==

local v1 = game:GetService("Players")
local v2 = game:GetService("ReplicatedStorage")
local v3 = game:GetService("RunService")
local u4 = game:GetService("TextService")
local u5 = game:GetService("HttpService")
local u6 = game:GetService("TweenService")
local u7 = game:GetService("MarketplaceService")
local u8 = game:GetService("Workspace")
local u9 = game:GetService("SocialService")
local u10 = require(v2.Client.Framework.Services.LocalData)
require(v2.Client.Gui.Utils.UpdateWhileGuiOpen)
local u11 = require(v2.Shared.Data.ChallengePass)
local u12 = require(v2.Client.Gui.Utils.AutoButtonColor)
local u13 = require(v2.Shared.Palette)
local u14 = require(v2.Client.Gui.Utils.ClickableButton)
local u15 = require(v2.Client.Gui.Utils.CheckInventorySpace)
local u16 = require(v2.Shared.Framework.Network.Remote)
local v17 = require(v2.Shared.Framework.Classes.Pool)
local u18 = require(v2.Shared.Utils.Stats.QuestUtil)
local u19 = require(v2.Shared.Framework.Utilities.String.FormatSuffix)
local u20 = require(v2.Shared.Utils.Stats.ItemUtil)
local u21 = require(v2.Client.Framework.Utilities.Gui.Animations.SetFade)
local v22 = require(v2.Client.Gui.Tooltip)
local u23 = require(v2.Shared.Data.Builders.TooltipBuilder)
local u24 = require(v2.Shared.Framework.Utilities.String.FormatCommas)
local u25 = require(v2.Client.Gui.Animations.ProcessingPurchase)
local u26 = require(v2.Client.Gui.GuiFrame)
local u27 = require(v2.Shared.Data.Builders.PromptBuilder)
local u28 = require(v2.Client.Gui.Prompt)
local u29 = require(v2.Shared.Framework.Utilities.Math.Time)
local v30 = require(v2.Shared.Framework.Utilities.ProductInfo)
local u31 = require(v2.Shared.Constants)
local u32 = require(v2.Client.Gui.Utils.SetCoreGuiEnabled)
local u33 = require(v2.Client.Gui.Utils.PlayLocalSound)
require(v2.Shared.Utils.Stats.StatsUtil)
local u34 = require(v2.Client.Gui.Utils.Notification)
local u35 = require(v2.Shared.Utils.RichText)
local u36 = require(v2.Client.Gui.Utils.Shiny)
local v37 = require(v2.Shared.Utils.IsTradingPlaza)
local u38 = v1.LocalPlayer
local u39 = u38.PlayerGui.ScreenGui
local u40 = u39.UIScale
local u41 = u39.ChallengePass.Frame
local u42 = u41.ScrollingFrame
local u43 = u42.Doggy
local u44 = u41.Challenges.List.Template
u44.Parent = nil
local u45 = v17.new(function() --[[Anonymous function at line 59]]
    --[[
    Upvalues:
        [1] = u44
    --]]
    return u44:Clone()
end)
local u46 = Instance.new("NumberValue")
local u47 = u11:GetPointsForTier(u11.FinalTier)
local u48 = 0
local function u67(p49, p50) --[[Anonymous function at line 72]]
    --[[
    Upvalues:
        [1] = u41
        [2] = u48
        [3] = u46
        [4] = u47
        [5] = u11
        [6] = u42
        [7] = u40
        [8] = u43
        [9] = u24
    --]]
    if u41.Parent.Visible then
        u48 = u48 + (p49 or 0)
        local v51 = u46.Value
        local v52 = u47
        local v53 = math.min(v51, v52)
        local v54 = u11:GetTier(v53)
        local v55 = v54 < 1 and 1 or v54
        local v56 = v55 + 1
        local v57 = u11:GetPointsForTier(v55)
        local v58 = u11:GetPointsForTier(v56)
        local v59 = (v55 + (v53 - v57) / (v58 - v57)) * -300 - 50
        local v60 = u48 * 3
        local v61 = v59 + math.sin(v60) * 10
        local v62 = math.min(-25, v61)
        if p50 then
            local v63 = u42.AbsoluteWindowSize.Y
            local v64 = u42.AbsoluteCanvasSize.Y + v59 * u40.Scale - v63 / 2
            u42.CanvasPosition = Vector2.new(0, v64)
        end
        local v65 = u46.Value / u47
        local v66 = 0.75 + v65
        u43.Bubble.Label.Text = u24((math.ceil(v53)))
        u43.Bubble.Size = UDim2.fromScale(v66, v66)
        u43.Bubble.Label.TextSize = 45 + 30 * v65
        u43.Position = UDim2.new(0, 20, 1, v62)
    end
end
u40:GetPropertyChangedSignal("Scale"):Connect(function() --[[Anonymous function at line 111]]
    --[[
    Upvalues:
        [1] = u67
    --]]
    u67(0, false)
end)
u46:GetPropertyChangedSignal("Value"):Connect(function() --[[Anonymous function at line 115]]
    --[[
    Upvalues:
        [1] = u67
    --]]
    u67(0, true)
end)
v3.Heartbeat:Connect(function(p68) --[[Anonymous function at line 119]]
    --[[
    Upvalues:
        [1] = u67
    --]]
    u67(p68, false)
end)
u26:BindOnOpened("ChallengePass", function() --[[Anonymous function at line 123]]
    --[[
    Upvalues:
        [1] = u67
    --]]
    u67(0, true)
end)
local u69 = nil
u10:ConnectDataChanged("ChallengePass", function(p70) --[[Anonymous function at line 131]]
    --[[
    Upvalues:
        [1] = u11
        [2] = u69
        [3] = u67
    --]]
    local v71 = 0
    for v72 = 1, u11:GetTier(p70.ChallengePass.Points) do
        if not table.find(p70.ChallengePass.Claimed, v72) then
            v71 = v72
            break
        end
    end
    if v71 ~= u69 then
        u69 = v71
        u67(0, true)
    end
end)
u26:BindOnOpened("ChallengePass", function() --[[Anonymous function at line 146]]
    --[[
    Upvalues:
        [1] = u39
        [2] = u32
    --]]
    u39.HUD.Visible = false
    u39.Notifications.Visible = false
    u32(false)
end)
u26:BindOnClosed("ChallengePass", function() --[[Anonymous function at line 153]]
    --[[
    Upvalues:
        [1] = u39
        [2] = u32
    --]]
    u39.HUD.Visible = true
    u39.Notifications.Visible = true
    u32(true)
end)
u12(u41.Parent.Close, u13.Button.Red)
u14(u41.Parent.Close, function() --[[Anonymous function at line 164]]
    --[[
    Upvalues:
        [1] = u26
    --]]
    u26:Close()
end)
local v73 = u41.ScrollingFrame.Clouds
local v74 = v73.Template
v74.Parent = nil
local u75 = {}
for u76 = 1, u11.FinalTier do
    local u77 = v74:Clone()
    u77.Name = ("Tier%*"):format(u76)
    u77.LayoutOrder = u11.FinalTier - u76
    local v78 = u77.Cloud
    local v79 = UDim2.new
    local v80 = u76 * 2
    v78.Position = v79(1, math.sin(v80) * 15 - 15, 0.5, 0)
    local v81 = u11:GetPointsForTier(u76)
    u77.Cloud.Label.Text = u24(v81)
    v22:OnEnter(u77.Cloud.Item.Hover, function() --[[Anonymous function at line 187]]
        --[[
        Upvalues:
            [1] = u77
            [2] = u5
            [3] = u23
        --]]
        local v82 = u77:GetAttribute("Item")
        if v82 then
            local v83 = u5:JSONDecode(v82)
            if v83 then
                return u23.fromItem(v83)
            end
        end
    end)
    u12(u77.Cloud.Claim.Button, u13.Button.Green)
    u14(u77.Cloud.Claim.Button, function() --[[Anonymous function at line 200]]
        --[[
        Upvalues:
            [1] = u10
            [2] = u76
            [3] = u15
            [4] = u16
        --]]
        local v84 = u10:Get()
        if v84 then
            if v84.ChallengePass.Rewards[u76].Type ~= "Pet" or u15(v84) then
                u16:FireServer("ChallengePassClaimReward")
            end
        else
            return
        end
    end)
    u12(u77.Cloud.FreeSkip.Button, u13.Button.Purple)
    u14(u77.Cloud.FreeSkip.Button, function() --[[Anonymous function at line 216]]
        --[[
        Upvalues:
            [1] = u16
        --]]
        u16:FireServer("ChallengePassFreeSkip")
    end)
    u77.Parent = v73
    u75[u76] = u77
end
local u85 = u41.Buttons.UnlockAll
u12(u85.Button, u13.Button.Orange)
u14(u85.Button, function() --[[Anonymous function at line 232]]
    --[[
    Upvalues:
        [1] = u25
        [2] = u7
        [3] = u38
        [4] = u11
    --]]
    u25:Show()
    u7:PromptProductPurchase(u38, u11.UnlockAllProductId)
end)
v30:ConnectProductChanged(u11.UnlockAllProductId, function(p86) --[[Anonymous function at line 237]]
    --[[
    Upvalues:
        [1] = u24
        [2] = u85
        [3] = u31
    --]]
    local v87 = not (p86 and p86.PriceInRobux) and "__" or u24(p86.PriceInRobux)
    u85.Button.Label.Text = ("%*%*"):format(u31.RobuxUnicode, v87)
end)
local u88 = u41.Buttons.ResetRobux
u12(u88.Button, u13.Button.Orange)
u14(u88.Button, function() --[[Anonymous function at line 249]]
    --[[
    Upvalues:
        [1] = u25
        [2] = u7
        [3] = u38
        [4] = u11
    --]]
    u25:Show()
    u7:PromptProductPurchase(u38, u11.ResetProductId)
end)
v30:ConnectProductChanged(u11.ResetProductId, function(p89) --[[Anonymous function at line 254]]
    --[[
    Upvalues:
        [1] = u24
        [2] = u88
        [3] = u31
    --]]
    local v90 = not (p89 and p89.PriceInRobux) and "__" or u24(p89.PriceInRobux)
    u88.Button.Label.Text = ("%*%*"):format(u31.RobuxUnicode, v90)
end)
local u91 = u41.Buttons.ResetGems
u12(u91.Button, u13.Button.Purple)
u14(u91.Button, function() --[[Anonymous function at line 266]]
    --[[
    Upvalues:
        [1] = u10
        [2] = u11
        [3] = u20
        [4] = u27
        [5] = u28
        [6] = u16
    --]]
    local v92 = u10:Get()
    if v92 then
        local v93 = u11:GetResetCost(v92.ChallengePass.GemResets)
        if not u20:CanAfford(v92, v93) then
            return u28(u27.fromNotEnough(v92, v93, function(p94) --[[Anonymous function at line 274]]
                return ("You need %* to reset the pass!"):format(p94)
            end):Build())
        end
        u16:FireServer("ChallengePassReset")
    end
end)
local function v98() --[[Anonymous function at line 284]]
    --[[
    Upvalues:
        [1] = u91
        [2] = u40
    --]]
    local v95 = u91.Button.Cost.Label
    local v96 = v95.TextBounds.X / u40.Scale
    local v97 = math.ceil(v96) + 1
    v95.Size = UDim2.new(0, v97, 1, 0)
end
u91.Button.Cost.Label:GetPropertyChangedSignal("TextBounds"):Connect(v98)
u40:GetPropertyChangedSignal("Scale"):Connect(v98)
local v99 = u91.Button.Cost.Label
local v100 = v99.TextBounds.X / u40.Scale
local v101 = math.ceil(v100) + 1
v99.Size = UDim2.new(0, v101, 1, 0)
local u102 = u41.Challenges.Skip
u12(u102.Button, u13.Button.Green)
u14(u102.Button, function() --[[Anonymous function at line 300]]
    --[[
    Upvalues:
        [1] = u25
        [2] = u7
        [3] = u38
        [4] = u11
    --]]
    u25:Show()
    u7:PromptProductPurchase(u38, u11.SkipChallengesProductId)
end)
v30:ConnectProductChanged(u11.SkipChallengesProductId, function(p103) --[[Anonymous function at line 306]]
    --[[
    Upvalues:
        [1] = u24
        [2] = u102
        [3] = u31
    --]]
    local v104 = not (p103 and p103.PriceInRobux) and "__" or u24(p103.PriceInRobux)
    u102.Button.Label.Text = ("%*%*"):format(u31.RobuxUnicode, v104)
end)
local u105 = u41.Buttons.ClaimAll
u12(u105.Button, u13.Button.Green)
u14(u105.Button, function() --[[Anonymous function at line 316]]
    --[[
    Upvalues:
        [1] = u10
        [2] = u11
        [3] = u15
        [4] = u16
    --]]
    local v106 = u10:Get()
    if not v106 then
        return
    end
    local v107 = v106.ChallengePass
    local v108 = {}
    for v109 = 1, u11:GetTier(v107.Points) do
        if not table.find(v107.Claimed, v109) then
            table.insert(v108, v109)
        end
    end
    if #v108 == 0 then
        return
    end
    local v110 = false
    for _, v111 in v108 do
        if v107.Rewards[v111].Type == "Pet" then
            v110 = true
            break
        end
    end
    if not v110 or u15(v106) then
        u16:FireServer("ChallengePassClaimAll")
    end
end)
local u112 = u39.HUD.Left.Currency.Coins.Bundles.ChallengePass
if v37() then
    u112.Visible = false
    return {}
end
u14(u112.Button, function() --[[Anonymous function at line 365]]
    --[[
    Upvalues:
        [1] = u26
    --]]
    u26:Open("ChallengePass")
end)
task.spawn(function() --[[Anonymous function at line 369]]
    --[[
    Upvalues:
        [1] = u11
        [2] = u10
        [3] = u112
        [4] = u26
        [5] = u8
        [6] = u29
    --]]
    while true do
        local v113 = u11:IsActive()
        local v114 = u10:Get()
        if v114 and not v114.AreasUnlocked.Zen then
            v113 = false
        end
        u112.Visible = v113
        if u26:IsOpen("ChallengePass") and not v113 then
            u26:Close()
        end
        local v115 = u11.FinishTime.UnixTimestamp - u8:GetServerTimeNow()
        local v116 = math.max(0, v115)
        u112.Button.Label.Text = u29.formatRealTime(v116)
        task.wait(1)
    end
end)
local u117 = u41.FreeSkips
local u118 = u117.Invite.Button
local function u124() --[[Anonymous function at line 397]]
    --[[
    Upvalues:
        [1] = u10
        [2] = u117
        [3] = u8
        [4] = u11
        [5] = u118
        [6] = u29
    --]]
    local v119 = u10:Get()
    if v119 then
        local v120 = v119.ChallengePass.FreeSkips
        u117.Amount.Text = ("%* Skip%*"):format(v120, v120 == 1 and "" or "s")
        local v121 = u8:GetServerTimeNow()
        local v122 = (v119.ChallengePass.LastInviteBonus or 0) + u11.InviteBonusPeriod - v121
        local v123 = v122 > 0
        u118.BackgroundTransparency = v123 and 0.5 or 0
        u118.UIStroke.Transparency = v123 and 0.75 or 0
        u118.Label.TextTransparency = v123 and 0.25 or 0
        u118.Label.UIStroke.Transparency = v123 and 0.75 or 0
        u118.Active = not v123
        u118.Selectable = not v123
        if v122 > 0 then
            u118.Label.Text = ("\226\143\179 %*"):format((u29.formatTime(v122)))
        else
            u118.Label.Text = "Invite"
        end
    else
        return
    end
end
task.spawn(function() --[[Anonymous function at line 427]]
    --[[
    Upvalues:
        [1] = u26
        [2] = u124
    --]]
    while true do
        if u26:IsOpen("ChallengePass") then
            u124()
        end
        task.wait(0.5)
    end
end)
u12(u118, u13.Button.Purple)
u14(u118, function() --[[Anonymous function at line 440]]
    --[[
    Upvalues:
        [1] = u9
        [2] = u38
    --]]
    Instance.new("ExperienceInviteOptions").PromptMessage = "Earn a free skip when a friend joins from your invite!"
    u9:PromptGameInvite(u38)
end)
local function u136() --[[Anonymous function at line 452]]
    --[[
    Upvalues:
        [1] = u10
        [2] = u18
        [3] = u45
        [4] = u19
        [5] = u20
        [6] = u4
        [7] = u41
    --]]
    local v125 = u10:Get()
    if v125 then
        for v126 = 1, 3 do
            local v127 = ("bubble-challenge-%*"):format(v126)
            local v128 = u18:FindById(v125, v127)
            if v128 then
                local v129 = v128.Tasks[1]
                local v130 = v128.Rewards[1]
                local v131 = v128.Progress[1] / u18:GetRequirement(v129)
                local v132 = u45:Get()
                v132.Name = v127
                v132.LayoutOrder = v126
                v132.Completed.Visible = v128.Claimed or false
                v132.Content.Bar.Fill.Size = UDim2.new(v131, 0, 1, 6)
                local v133 = v132.Content.Bar.Label
                local v134 = v131 * 100
                v133.Text = ("%*%%"):format((math.ceil(v134)))
                v132.Content.Label.Text = u18:FormatTask(v129)
                u18:UpdateIcon(v132.Icon, v128)
                local v135 = v132.Content.Reward.Amount
                v135.Text = u19(u20:GetAmount(v130))
                v135.Size = UDim2.fromOffset(u4:GetTextSize(v135.Text, v135.TextSize, v135.Font, Vector2.new((1 / 0))).X, 30)
                v132.Parent = u41.Challenges.List
            end
        end
        u45:Done()
    end
end
local u137 = nil
local u138 = nil
local u139 = u39.HUD.Left.Currency.Coins.Bundles.ChallengePass.Button.Notification
local function v165() --[[Anonymous function at line 491]]
    --[[
    Upvalues:
        [1] = u10
        [2] = u43
        [3] = u19
        [4] = u11
        [5] = u85
        [6] = u88
        [7] = u91
        [8] = u137
        [9] = u6
        [10] = u46
        [11] = u75
        [12] = u20
        [13] = u5
        [14] = u21
        [15] = u138
        [16] = u34
        [17] = u35
        [18] = u13
        [19] = u12
        [20] = u14
        [21] = u26
        [22] = u139
        [23] = u105
        [24] = u124
        [25] = u136
    --]]
    local v140 = u10:Get()
    if not v140 then
        return
    end
    local v141 = v140.ChallengePass
    u43.Bubble.Label.Text = u19(v141.Points, 10000)
    local v142 = u11:GetTier(v141.Points)
    local v143 = 0
    for v144 = 1, v142 do
        if not table.find(v141.Claimed, v144) then
            v143 = v144
            break
        end
    end
    u85.Visible = v142 < u11.FinalTier
    local v145
    if u11.FinalTier <= v142 then
        v145 = #v141.Claimed == u11.FinalTier
    else
        v145 = false
    end
    u88.Visible = v145
    u91.Visible = v145
    local v146 = u11:GetResetCost(v141.GemResets)
    u91.Button.Cost.Label.Text = u19(v146.Amount, 10000)
    local v147 = v141.Points
    if v143 ~= 0 then
        local v148 = u11
        v147 = math.min(v147, v148:GetPointsForTier(v143))
    end
    if v147 ~= u137 then
        u6:Create(u46, TweenInfo.new(0.75, Enum.EasingStyle.Sine, Enum.EasingDirection.Out), {
            ["Value"] = v147
        }):Play()
    end
    u137 = v147
    local _ = v143 == 0
    local v149 = u11:GetTier(v141.Points)
    local v150 = u11:GetTier(v147)
    for v151, v152 in u75 do
        local v153 = table.find(v141.Claimed, v151) ~= nil
        local v154 = v151 <= v149
        v152.Cloud.Claim.Visible = v154
        v152.Cloud.Claim.Claimed.Visible = v153
        local v155 = v150 < v151
        local v156 = v152.Cloud.Claim.Button
        v156.Visible = not v153
        v156.BackgroundTransparency = v155 and 0.5 or 0
        v156.UIStroke.Transparency = v155 and 0.75 or 0
        v156.Label.TextTransparency = v155 and 0.25 or 0
        v156.Label.UIStroke.Transparency = v155 and 0.75 or 0
        v156.Active = not v155
        v156.Selectable = not v155
        local v157 = v151 == v149 + 1
        if v157 then
            v157 = v141.FreeSkips > 0
        end
        v152.Cloud.FreeSkip.Visible = v157
        local v158 = v152.Cloud.Label
        local v159 = not v154
        if v159 then
            v159 = not v157
        end
        v158.Visible = v159
        local v160 = v141.Rewards[v151]
        u20:UpdateIcon(v152.Cloud.Item, v160)
        u20:FormatAmount(v152.Cloud.Item.Amount, v160)
        v152:SetAttribute("Item", u5:JSONEncode(v160))
        u21(v152.Cloud.Item, v153 and 0.35 or 0, nil, { "ImageButton", "Frame" })
    end
    local v161 = 0
    for v162 = 1, v149 do
        if not table.find(v141.Claimed, v162) then
            v161 = v161 + 1
        end
    end
    if v161 ~= u138 then
        if u138 and u138 < v161 then
            local v164 = {
                ["Sound"] = "NotificationSeason",
                ["Button"] = function(p163) --[[Function name: Button, line 579]]
                    --[[
                    Upvalues:
                        [1] = u12
                        [2] = u13
                        [3] = u14
                        [4] = u26
                    --]]
                    p163.Label.Text = "Open"
                    u12(p163, u13.Button.Orange)
                    u14(p163, function() --[[Anonymous function at line 582]]
                        --[[
                        Upvalues:
                            [1] = u26
                        --]]
                        u26:Open("ChallengePass")
                    end)
                end
            }
            u34(("You have %* to claim!"):format((u35.autoColor("Challenge Rewards", u13.Text.Yellow))), v164)
        end
        u138 = v161
    end
    u139.Visible = v161 > 0
    u139.Label.Text = v161 > 9 and "!" or tostring(v161)
    u105.Visible = v161 > 1
    u124()
    u136()
end
u26:BindOnOpened("ChallengePass", function() --[[Anonymous function at line 602]]
    --[[
    Upvalues:
        [1] = u36
        [2] = u41
    --]]
    u36:Add(u41.Buttons.UnlockAll.Effect)
end)
u26:BindOnClosed("ChallengePass", function() --[[Anonymous function at line 605]]
    --[[
    Upvalues:
        [1] = u36
        [2] = u41
    --]]
    u36:Remove(u41.Buttons.UnlockAll.Effect)
end)
u16.Event("ChallengePassReset"):Connect(function() --[[Anonymous function at line 610]]
    --[[
    Upvalues:
        [1] = u43
        [2] = u33
        [3] = u6
    --]]
    local v166 = u43.Bubble
    local u167 = v166.Pop:Clone()
    u167.Visible = true
    u167.ImageTransparency = 1
    u167.Size = UDim2.fromOffset(50, 50)
    u167.Parent = v166
    local u168 = TweenInfo.new(0.5, Enum.EasingStyle.Sine)
    u33("Pop")
    u6:Create(u43.Label, u168, {
        ["Rotation"] = 180
    }):Play()
    u6:Create(u167, TweenInfo.new(0.5, Enum.EasingStyle.Back), {
        ["Size"] = UDim2.fromOffset(200, 200),
        ["ImageTransparency"] = 0.5
    }):Play()
    v166.ImageTransparency = 1
    v166.Label.Visible = false
    task.delay(0.5, function() --[[Anonymous function at line 631]]
        --[[
        Upvalues:
            [1] = u6
            [2] = u167
            [3] = u168
        --]]
        u6:Create(u167, u168, {
            ["ImageTransparency"] = 1
        }):Play()
        task.wait(u168.Time)
        u167:Destroy()
    end)
    task.wait(1)
    v166.Label.Visible = true
    u6:Create(u43.Label, u168, {
        ["Rotation"] = 0
    }):Play()
    u6:Create(v166, u168, {
        ["ImageTransparency"] = 0
    }):Play()
end)
u10:ConnectDataChanged({ "ChallengePass", "Quests", "QuestsCompleted" }, v165)
return {}