--devbgascension

-- Bytecode (Base64):
-- BgOGAgxWaWV3cG9ydFNpemUBeARtYXRoBWZsb29yBWNsYW1wBVNjYWxlBnVwZGF0ZQdVSVNjYWxlDHVwZGF0ZVNjYWxlcxFJbWFnZVRyYW5zcGFyZW5jeQdjbGVhbnVwC0dldENoaWxkcmVuA0lzQQdEZXN0cm95EWNsZWFudXBQcml6ZUVudHJ5BFR5cGUIQ3VycmVuY3kFSW1hZ2UHUG93ZXJ1cAROYW1lBEljb24GUG90aW9uA25ldwVwcmludBh1bmtub3duIHByaXplIGVudHJ5IHR5cGUPc2V0dXBQcml6ZUVudHJ5A0dldAlHZXRQcml6ZXMFSW5uZXIKVXBkYXRlSWNvbgVUaXRsZQdHZXROYW1lBFRleHQFdGFibGUFY2xvbmUVR2V0Q3VycmVuY3lNdWx0aXBsaWVyBkFtb3VudARjZWlsDEZvcm1hdEFtb3VudAlHZXRSYXJpdHkJTGVnZW5kYXJ5BUN5Y2xlB1JhaW5ib3cFU3BlZWQETm9uZQxSYXJpdHlDb2xvcnMKVGV4dENvbG9yMwx1cGRhdGVQcml6ZXMLUHJpemVTY29yZXMNUmVmcmVzaFBlcmlvZAlEb2dneUp1bXAHQ2xhaW1lZAZQYXJlbnQFTGFiZWwlV2luIHVwIHRvICUqIHByaXplcyBldmVyeSAlKiBtaW51dGVzIQZmb3JtYXQDbm93BUJlZ2FuA21heBtNb3JlIHByaXplcyBhdmFpbGFibGUgaW4gJSoOZm9ybWF0UmVhbFRpbWULdXBkYXRlVGltZXIGSXNPcGVuBHRhc2sEd2FpdApsYXN0U291bmRzBHRpY2sBdAlwbGF5U291bmQLb2JqZWN0VHlwZXMGcmFuZG9tAXcBaAhJbnN0YW5jZQpJbWFnZUxhYmVsFkJhY2tncm91bmRUcmFuc3BhcmVuY3kERW51bQpCb3JkZXJNb2RlBUluc2V0AWkHVmVjdG9yMgtBbmNob3JQb2ludAVVRGltMgpmcm9tT2Zmc2V0BFNpemUIUG9zaXRpb24GWkluZGV4B29iamVjdHMBZgFwAW0BeQZpbnNlcnQJbmV3T2JqZWN0BXNjb3JlB1Zpc2libGUFU2NvcmUKJSolKiBTY29yZQTinIUgAB11cGRhdGVUb3BSaWdodFByaXplc0Zyb21TY29yZQlTUEVFRF9NSU4TU1BFRURfSU5DUkVBU0VfUkFURQlTUEVFRF9NQVgFc3BlZWQRUE9JTlRTX1BFUl9TRUNPTkQJU2NvcmU6ICVpFk9CSkVDVFNfUEVSX1NFQ09ORF9NSU4gT0JKRUNUU19QRVJfU0VDT05EX0lOQ1JFQVNFX1JBVEUWT0JKRUNUU19QRVJfU0VDT05EX01BWANtaW4KbGFzdE9iamVjdAZsYXllcnMFcGFpcnMORmluZEZpcnN0Q2hpbGQGRnJhbWUxBkZyYW1lMgF2BWRvZ2d5AWoHR1JBVklUWQNzaW4DYWJzCFJvdGF0aW9uBHNpZ24GcmVtb3ZlBmlwYWlycwhzdGVwR2FtZQRQbGF5EHVwZGF0ZUNvbm5lY3Rpb24KRGlzY29ubmVjdA9pbnB1dENvbm5lY3Rpb24HT3ZlcmxheQZSZXN1bHQFSW5wdXQFZGVsYXkMRG9nZ3lKdW1wV2luCkZpcmVTZXJ2ZXIFRXh0cmEcTW9yZSBwcml6ZXMgYXZhaWxhYmxlIGxhdGVyIQZQcml6ZXMhR2V0IGEgaGlnaGVyIHNjb3JlIHRvIHdpbiBwcml6ZXMhJkdldCBhIGhpZ2hlciBzY29yZSB0byB3aW4gbW9yZSBwcml6ZXMhCFN1YnRpdGxlB3J1bm5pbmcIc3RvcEdhbWUSVU5USUxfRklSU1RfT0JKRUNUCWZyb21TY2FsZQlyZXNldEdhbWUXcmJ4YXNzZXRpZDovLzQ4NTM5MzA3MjcIU2V0VHJhY2sNVXNlcklucHV0VHlwZQxNb3VzZUJ1dHRvbjEFVG91Y2gHS2V5Q29kZQdCdXR0b25ZCkpVTVBfU1BFRUQGU3ByaW5nBXNwYXduCUhlYXJ0YmVhdAdDb25uZWN0CklucHV0QmVnYW4Jc3RhcnRHYW1lA0hVRAVDbG9zZQRBcmVhBE1haW4IS2V5Ym9hcmQHR2FtZXBhZAZCdXR0b24LR2FtZXBhZEljb24OQ2xpY2sgdG8ganVtcCEMVGFwIHRvIGp1bXAhDm9uSW5wdXRDaGFuZ2VkBFN0b3AJSXNQbGF5aW5nBE9wZW4EZ2FtZQdQbGF5ZXJzCkdldFNlcnZpY2UJV29ya3NwYWNlClJ1blNlcnZpY2UQVXNlcklucHV0U2VydmljZRFSZXBsaWNhdGVkU3RvcmFnZQdyZXF1aXJlBkNsaWVudANHdWkFVXRpbHMPQXV0b0J1dHRvbkNvbG9yD0NsaWNrYWJsZUJ1dHRvbghHdWlGcmFtZQZTaGFyZWQHUGFsZXR0ZQ1Eb2dneUp1bXBVdGlsCUZyYW1ld29yawhTZXJ2aWNlcwlMb2NhbERhdGEJQ29uc3RhbnRzCVV0aWxpdGllcwRNYXRoBFRpbWUJSXRlbUZyYW1lBVN0YXRzCEl0ZW1VdGlsClBvdGlvbkljb24FVHlwZXMERGF0YQhQb3dlcnVwcwdOZXR3b3JrBlJlbW90ZQ5QbGF5TG9jYWxTb3VuZAVNdXNpYwpBY3RpdmF0aW9uCUlucHV0TW9kZQZTdHJpbmcMRm9ybWF0Q29tbWFzCkFuaW1hdGlvbnMHU2V0RmFkZQxBbmltYXRlQ29sb3IJU3RhdHNVdGlsDEN1cnJlbmN5VXRpbAtMb2NhbFBsYXllcglQbGF5ZXJHdWkJU2NyZWVuR3VpBUZyYW1lBkxheWVycwdPYmplY3RzBURvZ2d5C091dGVyIFNwYWNlDVRoZSBPdmVyd29ybGQJd29ya3NwYWNlBldvcmxkcwdJc2xhbmRzBklzbGFuZA1DdXJyZW50Q2FtZXJhGEdldFByb3BlcnR5Q2hhbmdlZFNpZ25hbA9Qb2ludHNQZXJTZWNvbmQDU2t5B0Nsb3VkczEJTW91bnRhaW5zB0Nsb3VkczIGR3JvdW5kHHJieGFzc2V0aWQ6Ly8xMzM0MjkzMjIzNzQ2MjcccmJ4YXNzZXRpZDovLzEzNTE5MDM5NjIyNDU5MAdDb250ZW50CFRlbXBsYXRlBUNsb25lC0xheW91dE9yZGVyB1ByaXplJSoWQ3VycmVuY3lNdWx0VXBkYXRlS2V5cxJDb25uZWN0RGF0YUNoYW5nZWQGU3F1ZWFrC0ltYWdlQnV0dG9uDEJpbmRPbk9wZW5lZAxCaW5kT25DbG9zZWQDVG9wA1JlZAZQdXJwbGUSR2V0SW1hZ2VGb3JLZXlDb2RlB0NoYW5nZWQETW9kZQRCaW5kAB0FAAIAAAAZ+wMAAE0CA7ABAAAATQECmQIAAAA+AAEAWwIAA7sMAgKkAQYAABRAgJ8BAgI+AAEDbwMHAIwEAgA0LgAEAwQAAFICAACkAQkAACBAgJ8BBAJSAAEA+wEBADAAAYQKAAAAggABAAsCAAAAAADAgkADAQMCAgAAAAAAABRAAwMDBAQAFECAApqZmZmZmek/AwUEACBAgAMGADwHARgAAAAAAAABAAAAAAAEAAAAAAAAAAACAAABPQAAAAADAAIAAAAK+wIAAE0BAoQBAAAA2AAAAfsCAQBNAQIrAgAAADAAAYQBAAAAggABAAMCAAAAAAAA8D8DBgMIAKUBCQEYAAAAAAIAAAAAAaYAAAAACQEBAAAAF4wBAAAwAQCjAAAAAPsCAABNAQKRAQAAAFICAACfAQIBvAEAaAIAAACfAQIEZAEIAG8IAwC8BgX+BAAAAJ8GAwIrBgMAvAYFUAUAAACfBgIBbgH3/wIAAACCAAEABgMKAwsDDAMIAw0DDgCwAQ8BGAAAAAEAAAAAAQAAAAEAAAAAAQAA/gAFsQAAAAAGAgMAAAAvTQIBEQAAAADwAgoAAQAAgPsEAABNBQEJAQAAAIcDBAVNAgOpAgAAADACAKkCAAAAggABAE0CAREAAAAA8AIKAAMAAID7BAEATQUBugQAAACHAwQFTQIDrgUAAAAwAgCpAgAAAIIAAQBNAgERAAAAAPACDAAGAACAjAIBADACAKMHAAAA+wMCAE0CA+8IAAAAUgMAAFIEAQBvBQkAnwIEAYIAAQCkAgsAAACgQG8DDABSBAEAnwIDAYIAAQANAxADEQMSAxMDFAMVAxYDCgMXApqZmZmZmfE/AxgEAACgQAMZALsBGgEYAAAAAAEAAAAAAAAAAAEAAAABAAAAAAAAAAABAAAAAQAAAQAAAAAAAAACAAAAAAK8AAAAAA4ACQAAAIQB+wAAALwAAH8AAAAAnwACAisAAQCCAAEA+wEBAPsDAgBSBAAAvAEBCAEAAACfAQQCUgIBAMYDAADGBAAAZAJxAPsIAwCHBwgF+wgEAE0LBywCAAAATQoLrgMAAABSCwYAvAgIIQQAAACfCAQBTQkHLAIAAABNCAm6BQAAAPsJBABSCwYAvAkJVgYAAACfCQMCMAkI9QcAAABNCAYRCAAAAPAIFwAJAACApAgMAAAsoIBSCQYAnwgCAvsJBQBSCwAATQwGCQkAAACpDQEAvAkJhw0AAACfCQUCTQwIKw4AAAAJCwwJuwcLAqQKEQAAQPCAnwoCAjAKCCsOAAAAUgYIAPsIBABNDAcsAgAAAE0LDK4DAAAATQoLKw4AAABSCwYAvAgI9RIAAACfCAQB+wgEAFIKBgC8CAglEwAAAJ8IAwLwCA8AFAAAgPsKBgBNCQp5FQAAAE0LBywCAAAATQoLugUAAABvCxYA4gwYAG8NGQAwDQwsFwAAAJ8JBAFlABIA+woGAE0JCj8aAAAATQsHLAIAAABNCgu6BQAAAJ8JAgFNCgcsAgAAAE0JCroFAAAA+wwHAE0LDBQbAAAAhwoLCDAKCXMcAAAA+woIAIcJCgX7CgQAUgwJAFINBgC8CgohBAAAAJ8KBAH7CgQATQwJKw4AAABSDQYAvAoK9RIAAACfCgQBbgKO/wIAAACCAAEAHQMbAxwDHQMVAx4DHwMgAyEDEAMRAyIDIwQALKCAAyQDJQMDAyYEAEDwgAMnAygDKQMqAysDLAUBFwKamZmZmZnZPwMtAy4DLwDKATABGAAAAAABAQMAAAAAAAEAAAABAAEAAAAAAAAAAAEAAAAAAAAAAAAAAgAAAAEAAAABAAAAAAAAAAEAAAAAAAAAAAECAAAAAAAAAAAAAAIAAAAAAQABAAAAAAAAAAAAAAAAAAIAAAAAAAAAAQAAAAAAAAAAAAMAAQAAAAAAAQAAAAAAAOkAGcsAAAAADAAEAAAASPsAAAC8AAB/AAAAAJ8AAgIrAAEAggABAPsDAQBNAgPwAQAAABwBAgD7AwEATQID3QIAAABNBAASAwAAAE0DBNoEAAAAYAMSAAEAAAD7BgIATQUGJAUAAABNBAUkBQAAAE0DBMMGAAAAbwUHAFIHAQC2CAIIvAUFjQkAAACfBQQCUgQFADAEA/UKAAAAggABAPsEAwBNAwSaCwAAAJ8DAQJNBgASAwAAAE0FBoQMAAAAQwQFAowGAQAmBwQDnhIGAwcAAACkBQ8AADjQgJ8FAwL7CQIATQgJJAUAAABNBwgkBQAAAE0GB8MGAAAAbwgQAPsLAwBNCguCEQAAAFILBQCfCgICvAgIjQkAAACfCAMCUgcIADAHBvUKAAAAggABABIDGwMxAzIDMwM0AzUDNgM3AgAAAAAAAE5AAzgDIQM5AzoDAwM7BAA40IADPAM9APABPgEYAAAAAAEBAwAAAAEAAAIAAAAAAAEAAAAAAAAAAAAAAAAAAAAAAgAAAAEAAAAAAQAAAAAAAAEAAAAAAAAAAAAAAAAAAAAAAAAC8QAAAAADAAIAAAAO+wAAAG8CAAC8AAAxAQAAAJ8AAwIOAAIA+wABAJ8AAQGkAAQAAAwggG8BBQCfAAIBSADz/4IAAQAGAzMDPwNAA0EEAAwggAIAAAAAAADgPwCFAgABGAEAAAAAAAEAAgAAAPwGBgEAAAABAAIAAAAF+wAAAJ8AAQH7AAEAnwABAYIAAQAAAJACAAEYAAABAAERAQAAAAcDAgAAABn7BQAATQQFPgAAAACHAwQBDgMKAKQFAgAAABBAnwUBAk0GA5UDAAAAJgQFBk0FA5QEAAAAYAQCAAUAAACCAAEApAQCAAAAEECfBAECMAQDlQMAAAD7BAEAUgUBAJ8EAgGCAAEABQNCA0MEAAAQQANEAzsAsQJFARgAAAAAAQAAAAAAAAAAAAAAAgAAAAACAAABMgEAAAAPAQIAAABcTQEAkgAAAACkAwMAAAgQgIwEAgCfAwIChwIBA00DApYEAAAATQQCiQUAAACkBQgAABxggG8GCQCfBQICjAYBADAGBToKAAAApAYOAA0wsMAwBgVjDAAAAE0GAogPAAAAMAYFqRAAAACkBhIAABwQgW8HEwCMCAEAnwYDAjAGBegUAAAApAYXAABYUIFSBwMAUggEAJ8GAwIwBgUvGAAAAKQGGQAAHFCBjAdkAIwIAACMCQAAjAoAAJ8GBQIwBgU7GgAAAPsIAABNBwgNHAAAAHgGBxswBgUNHAAAAPsGAQAwBgUkHQAAAE0HADgeAAAA4ggiADAFCIcfAAAApAkSAAAcEIGMDCwBQwsMA6QMAwAACBCAjA0AAIwOVQCfDAMCQwoLDE0LApgjAAAAnwkDAjAJCJEgAAAAMAMIlgQAAAAwBAiJBQAAAE0JAowhAAAAMAkIjCEAAACeNAcDCAAAAKQGJgAAlECCnwYDAYIAAQAnA0YDAwNHBAAIEIADSANJA0oDFwQAHGCAA0sDTANNA04DTwQNMLDAA1ADEgNRBAAcEIECAAAAAAAA4D8DUgNTA1QEAFhQgQNVBAAcUIEDVgIAAAAAAADwPwNXAzUDWANZA1oDWwUFHyAEBSEDXAMiA10EAJRAggC8Al4BGAAAAQAAAAADAAEAAgAAAAEAAAEAAAABAAAAAQAAAAAAAAEAAAAAAAABAAAAAAAAAAABAAAAAAABAAACAAABAAEAAAAAAAAAAAAAAAAAAAEAAQABAAAAAAD7AAAHPQEAAAATAAcAAABF+wAAALwAAH8AAAAAnwACAg4ABQBNAgASAQAAAE0BAtoCAAAAZQABAIwBAAD7BQEATQIF8AMAAADGAwAAxgQAAGQCMQD7CgIATQkKwgUAAACQCAkE1AYCAAgAAACpBwABqQcBANQFAgABAAAAqQgAAakIAQD7CgMAhwkKBU0KCdoCAAAAMAgKgAYAAAD7CgQATQsJLAcAAAAOCAIAbwwIAGUAAQCMDAAAxg0AAPsOBQCfCgUBTQsJLAcAAABNCgsiCQAAAG8MCgAOBwIAbw4LAGUAAQBvDgwA+w8GAPsSAQBNERLwAwAAAIcQEQWfDwICvAwMjQ0AAACfDAQCUgsMADALCvUOAAAAbgLO/wIAAACCAAEADwMbAzMDNAMxAgAAAAAAAAAAA18DYAMdAgAAAAAAAOA/A2EDYgNjA2QDOAMhANoCZQEYAAAAAAIAAAAAAAADAAAAAAABAAAAAAAAAAEAAAACAAEAAAACAAAAAAAAAAAAAgAAAAAAAAAAAAAAAAAAAAAAAAAA9wAMWwEAAAAaAgQAAAsEAAEFAgQCAwYjAuYCTQMAlQAAAABDAgMBMAIAlQAAAABNBQCpAQAAAE0HADQCAAAACQYCB0MEBQZNBQCpAQAAAE0GAMMDAAAATC4AAqQDBgAAFECAnwMEAjADAMwHAAAATQYA7QgAAAAJBQYCuwwFAqQECgAAJECAnwQCAjAEAMILAAAA+wYAAE0FBiIMAAAAbwYNAFIIBAC8BgaNDgAAAJ8GAwIwBgX1DwAAAPsFAQCfBQEBTQYApxAAAABNCAA8EQAAAAkHCAJDBQYHTQgASRIAAACeEwUECAAAAFIHBQCkBhQAAExAgJ8GAwJSBQYA2AYVBU0HAFsWAAAATQkAWxYAAAAmCAIJYAYHAAgAAAC8CAB7FwAAAJ8IAgFDCAcGMAgAWxYAAABNCABZGAAAAKQJGgAAAJBBUgoIAJ8JAgQXCScA+w4CAFIQDAC8Dg4DGwAAAJ8OAwJNDw4hHAAAAE0QDh4dAAAATRINkR4AAABNFQ2XHwAAAAkUARU5FQMACRMUFUMREhMhEhEgeBMSIDARDZEeAAAApBQjAACIEIKMFQAAUhYSAIwXAACMGAAAnxQFAjAUDzskAAAApBQjAACIEIKMFQAAUhYTAIwXAACMGAAAnxQFAjAUEDskAAAAbgnY/wIAAABNCQCmJQAAAE0KCZcfAAAATQsJkR4AAABNDAmLJgAAAA4MIQBNDAmXHwAAAE0OAOInAAAACQ0OASYKDA1NDAmRHgAAAAkNCgFDCwwNTQwLmCgAAACMDQQAfQwPAA0AAACkDCoAAIiQgk0NC5krAAAAjA4AAJ8MAwJSCwwApAwqAACIkIKfDAECUgoMAKkMAAAwDAmLJgAAADALCZEeAAAAMAoJlx8AAABNDAuYKAAAAA0MMgAsAACA+wwDAKQNIwAAiBCCjA4AAE0PC5krAAAAjBABAFsUAi67GBQCpBMwAAC8QICfEwICuwITAqQSMgAAxECAnxICAlsREi2fDQUCMA0MOyQAAAAmDwIBWw4PLrsYDgKkDTAAALxAgJ8NAgJbDA0zWw8CLrsYDwKkDjAAALxAgJ8OAgJbDQ4z+w4DADANDjg0AAAAuy8MA1IPDACkDjYAANRAgJ8OAgK7Lw0DUhANAKQPNgAA1ECAnw8CAvEOHQAPAAAAZQAbAPsMAwCkDSMAAIgQgowOAABNDwuZKwAAAIwQAQBNEguYKAAAADkREgCfDQUCMA0MOyQAAACMDWgB+xADAE0PEDg0AAAAWxABN0MODxCeEw0DDgAAAKQMFAAATECAnwwDAvsNAwAwDA04NAAAAE0MADg4AAAAHA8MAIwNAQCMDv//qA0pAIcQDA9NERCHOQAAAE0TEJEeAAAApBQqAACIkII5FgMACRUBFowWAACfFAMCQxITFE0TEpkrAAAAjBT2/30TCgAUAAAAvBMRUDoAAACfEwIBpBM9AADwsINSFAwAUhUPAJ8TAwFlAA4AMBIQkR4AAACkEyMAAIgQgowUAABNFRKZKwAAAIwWAQBNGBKYKAAAADkXGACfEwUCMBMROyQAAACLDdf/TQ4JkR4AAACkDyoAAIiQgowQAACMERAAnw8DAkMNDg+kDyoAAIiQgk0QCZY/AAAATREJiUAAAACfDwMCWw4PPqQPQgAAABBEUhAMAJ8PAgRRDy0ATRUTkR4AAACkFioAAIiQgowXAABNGROJQAAAAFsYGT6fFgMCQxQVFqQXKgAAiJCCTRgTlj8AAABNGROJQAAAAJ8XAwJbFhc+TRcTjEMAAAAmFRYXJhYUDUMXDhVNGRaZKwAAALsCGQKkGDIAAMRAgJ8YAgJNGReZKwAAAGAYDQAZAAAATRkWmCgAAAC7AhkCpBgyAADEQICfGAICTRkXmCgAAABgGAMAGQAAAKkYAQCCGAIAbg/S/wIAAICpDwAAgg8CAEQDRANmA2cDaAMDAwUEABRAgANpA2oDBAQAJECAA18DYQNrAzgDIQNsA20DbgNvBABMQIACAAAAAAAA8D8DcANeA3EDcgQAAJBBA3MDdAN1A1oDdgIAAAAAAMByQANTAxcEAIgQggNWA3cDeAN5A1wDUQQAiJCCAwICAAAAAAAAAAACzczMzMzMEMACAAAAAAAAIkADegQAvECAA3sEAMRAgAIAAAAAAAAIQAN8A30EANRAgAIAAAAAAMCHQANYA1kDDgMiA34EAPCwgwIAAAAAAADgPwNIA0kDfwQAABBEA1sA8gKAAQEYAAAAAQAEAAAAAAAAAAAAAAAAAAEABAAAAAAAAAEAAQAAAAAAAAAAAAQABAAAAAAAAQAAAAAAAAAAAgEAAQAAAAABAAABAAAFAAEAAAAAAQAAAAACAAEAAgAAAAAAAAABAQEAAgAAAAAAAAAAAQAAAAAAAAAA9AARAAEAAQACAAABAAAAAAABAAAAAQAAAAABAAAAAAAAAQAAAAEAAAMAAQADAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAACAAAAAAAAAQAAAAAAAQAAAgAAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAACAAAAAAAAAAAAAAEAAAUAAQAAAAEBAAIAAAAAAAAAAAEAAAAAAQAAAQAAAAABAwABAAAAAAAAAAAAAAD0EQAAAAAAAAABAAAAAAAAAAIAAAAAAQAAAAAAAAAAAAEAAAAAAAAAAAAAAgECAAAAAAAAAAAAAAAAAAAAAAAAAAEA+AAMAHQBAAAAAgABAAAAB/sBAABNAAHuAAAAAKkBAQAwAQCAAQAAAIIAAQACA4EBA2AAigQAARgAAAAAAAABCwIAAAAQAgYAAADEAU0CAD8AAAAADgIIAE0CAD8AAAAAvAICGgEAAACfAgIBxgIAADACAD8AAAAATQIABwIAAAAOAggATQIABwIAAAC8AgIaAQAAAJ8CAgHGAgAAMAIABwIAAAD7AwAATQIDQAMAAABNAwIOBAAAAIwEAAD7BQEAvAUFfwUAAACfBQICDgUEAE0GBRIGAAAATQQG2gcAAAD7BwIATQYH3AgAAACpBwAAMAcGgAkAAABNBgLuCgAAAKkHAAAwBwaACQAAAKQGDAAAALBAbwcNANkIAAASAAIAnwYDASsBBACpBgAAMAYDgAkAAABlAIIAjAYAAPsKAwBNBwrwDgAAAMYIAADGCQAAZAcFAH0LBAABAAAAYAQCAAoAAABSBgoAbgf6/wIAAAD7CgMATQkK8A4AAAAcCAkA1AgCAAQAAACpBwABqQcBAIwJAAC3CQIABgAAAKkIAAGpCAEADggGAPsJBABvCw8AUgwGALwJCWsQAAAAnwkEAQ4HEABNCQOUEQAAAKkKAQAwCgmACQAAAE0JA5QRAAAAbwoSADAKCfUTAAAATQkDSBQAAACpCgAAMAoJgAkAAABlAEQA+wsDAE0KC/AOAAAAEwkKAGABEQAJAAAATQkDlBEAAACpCgEAMAoJgAkAAABNCQOUEQAAAG8KFQAwCgn1EwAAAE0JA0gUAAAAqQoAADAKCYAJAAAAZQAuACsIEABNCQOUEQAAAKkKAQAwCgmACQAAAE0JA5QRAAAAbwoWADAKCfUTAAAATQkDSBQAAACpCgAAMAoJgAkAAABlAB0ATQkDlBEAAACpCgAAMAoJgAkAAABNCQNIFAAAAKkKAQAwCgmACQAAAPsMAwBNCQzwDgAAAMYKAADGCwAAZAkLAPsPBQCHDg8MqQ8AAH0NBQABAAAAtwQCAAwAAACpDwABqQ8BADAPDoAJAAAAbgn0/wIAAABNCQPxFwAAAE0LA0gUAAAATQoLgAkAAAAwCgmACQAAAKkJAQAwCQOACQAAAKkGAQAwBgKACQAAAKkGAAAwBgDJGAAAAIIAAQAZA4IBA4MBA4QBA4UBA4YBAxsDMwM0A4cBA2ADgQEDiAEEAACwQAIAAAAAAADgPwMxA4kBA4oBA4sBA4wBAyEDjQEDjgEDjwEDkAEDkQEBDPIDkgEBGAAAAAEAAAAAAQAAAwAAAQAAAAABAAAEAAABAAMBAAAAAQEAAAADAAAAAAABAAAAAAEAAAAAAAQBAAAAAwEAAAAAAAEAAAAB/gAGAAAAAAAAAAIAAAAAAQEAAAAAAAMBAAAAAAEAAAAAAQAAAAAAAgAAAAAAAQAAAAABAAAAAAEAAAAAAAIBAAAAAAEAAAAAAQAAAAAAAwAAAAABAAAAAAIAAAAAAAEAAAAAAAAAAAAA/wAFAAAAAAAAAAIAAAMAAAMAAAHzAQAAAA0BBAAABwAAAQMCGQJ5jAEAADABAJUAAAAATQEAqQEAAAAwAQDMAgAAAIwBAAAwAQDCAwAAAE0CAF0EAAAATQMApwUAAAAmAQIDMAEAWwYAAACpAQAAMAEAyQcAAAD7AgAATQECIggAAABvAgkAjAQAALwCAo0KAAAAnwIDAjACAfULAAAA+wEBAJ8BAQFNAQA4DAAAAKQCDgAAANBAUgMBAJ8CAgRRAggAhwgBBU0HCIcPAAAAvAcHUBAAAACfBwIBxgcAAGoHAQVuAvf/AQAAgE0CAFkRAAAApAMTAAAAIEFSBAIAnwMCBBcDGgCMCAAAMAgHkRQAAAD7CAIAUgoGALwICAMVAAAAnwgDAk0JCCEWAAAApAoZAABgcIGMCwAAjAwAAJ8KAwIwCgk7GgAAAE0JCB4bAAAApAoZAABgcIGMCwEAjAwAAJ8KAwIwCgk7GgAAAG4D5f8CAAAATQMAphwAAACkBB8AAHjQgYwFKACMBgAAnwQDAjAEA5EUAAAApAQfAAB40IGMBQAAjAYAAJ8EAwIwBAOXIAAAAKkEAAAwBAOLIQAAAPsEAwCkBSIAAHhwgYwGAABNCAORFAAAAE0HCJkjAAAAjAgBAIwJAACfBQUCMAUEOxoAAAD7BAMAjAUAADAFBDgkAAAAggABACUDRANmA2kDXwOTAQNsA3ADkQEDYQNrAzgDIQNYA38EAADQQANZAw4DcQNyBAAAIEEDWgNzA3QDUwOUAQQAYHCBA1YDdQN3A1EDFwQAeNCBA3YDeAQAeHCBAwIDfADGBJUBARgAAAABAAAAAQAAAQAAAAAAAAEAAAIAAAAAAAAAAAABAAIAAQAAAAABAAAAAAABAP4ABQABAAAAAAEAAAIAAAAAAQAAAAAAAAAAAQAAAAAAAAAA+wAIAAEAAAAAAAABAAAAAAAAAQAAAgAAAAAAAAAAAAAAAAEAAAABRwIAAAADAAEAAAAG+wAAAG8CAAC8AAD5AQAAAJ8AAwGCAAEAAgOWAQOXAQDsBAABGAAAAAAAAW0CAAAABgECAAAAGfsBAABDAQEA3gEAAPsBAABvAgAAfQISAAEAAAD7AQEAbwMAALwBARsBAAAAnwEDAg4BBwD7AgEA+wUBAE0EBcICAAAAvAICpwMAAACfAgMB+wIAAHgCAgDeAgAASADr/4IAAQAEAhEREREREZE/A4ABA18DkgEA8QQAARgAAAABAAAAAQAAAAABAQAAAAAAAAIAAPsHcgIAAAAGAQIAAAAlTQEAwgAAAACkAgMAAgAQwPEBCwACAAAApAIFAAQAEMDxAQcAAgAAAE0CALMGAAAApAMIAAcYEMCaAhUAAwAAAPsDAABNAgOLCQAAACsCEAD7AgAAqQMBADADAosJAAAA+wIAAPsEAQBNAwSrCgAAADADApcLAAAA+wIBAG8EDABvBQ0AvAIClw4AAACfAgQBggABAA8DmAEDTQOZAQQCABDAA5oBBAQAEMADmwEDnAEEBxgQwAN4A50BA3YDngECmpmZmZmZ6T8DRQD/BAABGAAAAQAAAAAAAAAAAAAAAAABAAAAAQAAAAEAAAAAAAEAAAAAAAOAAgAAAAcCBQAAADK8AgBpAAAAAJ8CAgGkAgIAAAAQQMADAwASAgAAnwICAYwCAAD7BAEATQME/QQAAADZBQEAEgEC/xIAAAC8AwPHBQAAAJ8DAwIwAwA/BgAAAE0DAKYHAAAA+wUCAE0EBYIIAAAA2QYCABIAAwASAAAAvAQExwUAAACfBAMCMAQABwkAAAD7BQMATQQF3AoAAACpBQEAMAUEgAsAAAD7BQQATQQFQAwAAACpBQAAMAUEgAsAAACpBAEAMAQAyQ0AAADBAgAAggABAA4DlQEDnwEEAAAQQAYPA6ABA6EBA4IBA3cDogEDhAEDhwEDYAOFAQORAQMPEBHpBKMBARgAAAACAAAAAAQBAAAAAAAAAAAAAAwAAgAAAAAAAAAAAAALAAAAAAABAAAAAAABAAABAGoCAAAAAgABAAAAB/sBAABNAAEfAAAAAKkBAAAwAQCAAQAAAIIAAQACA6QBA2AAlgUAARgAAAAAAAABlwIAAAADAAIAAAAM+wAAAMYCAAC8AACnAAAAAJ8AAwH7AQEATQABHwEAAACpAQEAMAEAgAIAAACCAAEAAwOSAQOkAQNgAJ0FAAEYAAAAAAABAAAAAAABngIAAAACAAEAAAAF+wAAALwAAGMAAAAAnwACAYIAAQABA6UBAKgFAAEYAAAAAAKpAgAAAAIAAQAAAAr7AQAATQAByQAAAAAOAAEAggABAPsAAAC8AAANAQAAAJ8AAgGCAAEAAgORAQOjAQCwBQABGAAAAAABAgAAAAGxAgAAAAcCAwAAACErAQoA+wIAAG8EAAC8AgIxAQAAAJ8CAwIOAgQA+wMBAE0CA8kCAAAADgIBAIIAAQBNAgCzAwAAAKQDBgAFDEDAmgIPAAMAAAD7BgIATQUGTwcAAABNBAVACAAAAE0DBO4JAAAATQIDgAoAAAAOAgQA+wIBALwCAg0LAAAAnwICAYIAAQAMAzMDPwORAQObAQNNA5wBBAUMQMADpgEDhQEDgQEDYAOjAQC3BQABGAAAAAAAAAAAAAAAAQEAAAAAAAEAAAAAAAAAAAABAAAAA7gCAAAABwECAAAAQPsDAABNAgPcAAAAAE0BAloBAAAAqQIBAPAABQACAAAA8AACAAMAAACpAgABqQIBADACAYAEAAAA+wMAAE0CA9wAAAAATQEC3QUAAADwAAIABQAAAKkCAAGpAgEAMAIBgAQAAAD7BgEATQUGTwYAAABNBAVABwAAAE0DBO4IAAAATQIDrAkAAABNAQIICgAAAPAAAgAFAAAAqQIAAakCAQAwAgGABAAAAPAACgACAACA+wMAAE0CA9wAAAAATQECWgEAAABvAgsAMAIB9QwAAACCAAEA8AAJAAMAAID7AwAATQID3AAAAABNAQJaAQAAAG8CDQAwAgH1DAAAAIIAAQAOA4cBA6cBA6gBA5oBA2ADqQEDpgEDhQEDgQEDqgEDqwEDrAEDIQOtAQDFBa4BARgAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAACAAEAAAAAAAAAAAEAAQAAAAAAAAACxgIAAAAEAQEAAAAK+wEAAMYDAAC8AQGnAAAAAJ8BAwH7AQAAvAEBaQEAAACfAQIBggABAAIDkgEDlQEA1gWvAQEYAAAAAAABAAAAAdcCAAAABAEBAAAACPsDAABNAgPJAAAAACoCAgABAAAAqQEAAakBAQCCAQIAAQORAQDbBbABARgAAAAAAAAAANwCAAAAAwABAAAABvsAAABvAgAAvAAAFgEAAACfAAMBggABAAIDMwOxAQDiBQABGAAAAAAAAeMCAAAAQAAAAQAAqQejAAAApAABAAAAAEBvAgIAvAAAFgMAAACfAAMCpAEBAAAAAEBvAwQAvAEBFgMAAACfAQMCpAIBAAAAAEBvBAUAvAICFgMAAACfAgMCpAMBAAAAAEBvBQYAvAMDFgMAAACfAwMCpAQBAAAAAEBvBgcAvAQEFgMAAACfBAMCpAUJAAAAgEBNCQRNCgAAAE0ICR8LAAAATQcIoQwAAABNBgfXDQAAAJ8FAgKkBgkAAACAQE0KBE0KAAAATQkKHwsAAABNCAmhDAAAAE0HCOwOAAAAnwYCAqQHCQAAAIBATQoETQoAAABNCQofCwAAAE0ICZUPAAAAnwcCAqQICQAAAIBATQoEEhAAAABNCQp4EQAAAJ8IAgKkCQkAAACAQE0MBBIQAAAATQsMoQwAAABNCgu+EgAAAJ8JAgKkCgkAAACAQE0OBE0KAAAATQ0OHBMAAABNDA1DFAAAAE0LDGgVAAAAnwoCAqQLCQAAAIBATQ0EEhAAAABNDA0HFgAAAJ8LAgKkDAkAAACAQE0RBBIQAAAATRARHBMAAABNDxC1FwAAAE0OD4wYAAAATQ0OShkAAACfDAICpA0JAAAAgEBNEQRNCgAAAE0QER8LAAAATQ8QoQwAAABNDg/DGgAAAJ8NAgKkDgkAAACAQE0TBBIQAAAATRIToQwAAABNERIhGwAAAE0QEdAcAAAATQ8Qwh0AAACfDgICpA8JAAAAgEBNEQQSEAAAAE0QEe8eAAAAnw8CAqQQCQAAAIBATRMEEhAAAABNEhPGHwAAAE0REgkgAAAAnxACAqQRCQAAAIBATRQEEhAAAABNExTGHwAAAE0SE8AhAAAAnxECAqQSCQAAAIBATRYEEhAAAABNFRYcEwAAAE0UFVIiAAAATRMU9iMAAACfEgICpBMJAAAAgEBNFwRNCgAAAE0WFx8LAAAATRUWoQwAAABNFBUsJAAAAJ8TAgKkFAkAAACAQE0WBE0KAAAATRUWfSUAAACfFAICpBUJAAAAgEBNFwRNCgAAAE0WF88mAAAAnxUCAqQWCQAAAIBATRoETQoAAABNGRocEwAAAE0YGUMUAAAATRcY/icAAACfFgICpBcJAAAAgEBNGwQSEAAAAE0aG6EMAAAATRkaIRsAAABNGBnQHAAAAJ8XAgKkGAkAAACAQE0dBBIQAAAATRwdHBMAAABNGxy1FwAAAE0aG6EoAAAATRkamikAAACfGAICpBkJAAAAgEBNHwRNCgAAAE0eHxwTAAAATR0etRcAAABNHB0fCwAAAE0bHEQqAAAATRobBCsAAACfGQICpBoJAAAAgEBNHQQSEAAAAE0cHaEMAAAATRsc6CwAAACfGgICpBsJAAAAgEBNHwQSEAAAAE0eH6EMAAAATR0eIRsAAABNHB0TLQAAAJ8bAgKkHAkAAACAQE0fBBIQAAAATR4foQwAAABNHR58LgAAAJ8cAgL/HQYAAAAAAE0eADEvAAAATSAemTAAAABNHyB6MQAAAE0hHxIyAAAATSAhnTMAAABNJB8SMgAAAE0jJJ0zAAAATSIjLDQAAABNISJaNQAAAE0iIU82AAAATSMieTcAAABNJCJYOAAAAE0mICw0AAAATSUmSDkAAABNJiRGOgAAAKQuPgAAANBDTS0u2D8AAABNLC07PAAAAE0rLCdAAAAATSor4TsAAABNKSq5QQAAAE0oKRIyAAAATScozyYAAABNKh8SMgAAAE0pKp0zAAAATSgpK0IAAABNKQFIQwAAAMAqRAASACkAEgAoAG8tRQC8KymURgAAAJ8rAwJSLSoAvCsrx0cAAACfKwMBTS0psEUAAABNLC2ZSQAAAD4rLEhbLStKuwwtAqQsTQAAMLGEnywCAj4rLEpvLk4AjC8CADQuKwQuLwAAUi0rAKQsUAAAPLGEnywEAlIrLAAwKyiEUQAAAKQrVAAATCGFjCwAAIwtJgKfKwMCMCsdq1UAAACkK1QAAEwhhYwsAACMLWwHnysDAjArHeJWAAAAjCsYATArHalXAAAAjCs0AzArHcNYAAAAjCsLADArHTRZAAAAbytaADArHadbAAAAbytcADArHUldAAAAbyteADArHTxfAAAAjCsBADArHV1gAAAATSsJ8mEAAAAwKx3tYgAAAP8rBAAAAAAA4ixlAIwtAAAwLSyRYwAAAIwtAAAwLSyXZAAAADAsK7pmAAAA4ixlAIwtAAAwLSyRYwAAAG8tZwAwLSyXZAAAADAsK5JoAAAA4ixlAIwtAAAwLSyRYwAAAG8taQAwLSyXZAAAADAsK4lqAAAA4ixlAIwtAAAwLSyRYwAAAG8tawAwLSyXZAAAADAsK9lsAAAA4ixlAIwtAAAwLSyRYwAAAIwtAQAwLSyXZAAAADAsK25tAAAAMCsdWW4AAAD/LAAAAgAAAOItdABvLnUAMC4tiG8AAACMLj4AMC4tlnAAAACMLiQAMC4tiXEAAACMLv3/MC4tmHIAAACkLlQAAEwhhYwvBwCMMAMAny4DAjAuLYxzAAAA4i50AG8vdgAwLy6IbwAAAIwvNwAwLy6WcAAAAIwvIwAwLy6JcQAAAIwv/f8wLy6YcgAAAKQvVAAATCGFjDAFAIwxBACfLwMCMC8ujHMAAADFLC0DAQAAADAsHZJ3AAAATS0lvngAAABNLi3yeQAAAMYvAAAwLy4kegAAAE0yIU82AAAATTEyQHsAAABNMDEOfAAAAE0vMEg5AAAATTAv8nkAAADGMQAAMDEwJHoAAAD/MQAAAAAAAP8yAAAAAAAAjDUBAE02CfB9AAAAHDM2AIw0AQCoMzMAvDYuOn4AAACfNgICMDU2AH8AAABvOIAAUjo1ALw4OI2BAAAAnzgDAlI3OAAwNza6ggAAADAtNiR6AAAAajYxNbw3MDp+AAAAnzcCAjA1NwB/AAAAbzmAAFI7NQC8OTmNgQAAAJ85AwJSODkAMDg3uoIAAAAwLzckegAAAGo3MjXZOAEAEgAoABIANwBvO1EAvDkolEYAAACfOQMCUjs4ALw5OcdHAAAAnzkDAU06KIRRAAAA2DmDOk06NytCAAAAMDk6hFEAAACLM83/wDOEABIADgDANIUAEgAQABIAEQASAA4AwDWGABIACgASAAkAEgAeABIAMQASABcAEgAbABIAGgASAAsAEgAyAE04HCaHAAAAUjk1ALw2CiiIAAAAnzYEAcA2iQASAAoAEgAJABIAIQASAAwApDeMAAAsoojAOI0AEgAHABIANgCfNwIBbzkyAMA6jgASADUAEgA2ALw3CiiIAAAAnzcEAak3AAAwNx3JjwAAAMY3AAAwNx2VkAAAAMY3AAAwNx3MkQAAAMY3AAAwNx3CkgAAAMY3AAAwNx1bkwAAAMY3AAAwNx0/lAAAAMY3AAAwNx0HlQAAAP83AAAAAAAAMDcdOJYAAAD/NwAAAAAAADA3HaaXAAAATTcdppcAAACMOBYAMDg3lnAAAABNNx2mlwAAAIw4FgAwODeJcQAAAP83AAAAAAAAMDcdPpgAAABNNx0+mAAAAOI4mgCMOQAAMDk4lZAAAABvOZsAMDk4lJkAAAAwODf2nAAAAE03HT6YAAAA4jiaAIw5AAAwOTiVkAAAAG85mwAwOTiUmQAAADA4NyKdAAAAwDeeABIAHQASABMAMDcdl58AAADAN6AAEgAmABIAJAAwNx17oQAAAP83AAACAAAAbzgzAG85ogDFNzgDAQAAAMA4owASAAoAEgAJABIAHQASADEAEgAZABIANwASABgAbzsyAFI8OAC8OQooiAAAAJ85BAHAOaQAEgAiABIAOAASACMAEgAmADA5HRulAAAAwDmmABIAIgASAAoAEgAgABIACQASABIAEgAyADA5HaenAAAAwDmoABIAIgASADgAEgAjABIAJgAwOR1pqQAAAMA5qgASABQAEgACABIAAwASACAAEgAiADA5HQ2rAAAAbzsyAMA8rAASAB8AvDkHqq0AAACfOQQBbzsyAMA8rgASAB0AEgAfALw5B5+vAAAAnzkEAVI5BQBNPiEkegAAAE09PiR6AAAATTw9mLAAAABNOzxjsQAAAE06O6yyAAAATTwIrLIAAABNOzxvswAAAJ85AwFSOQYATT4hJHoAAABNPT4kegAAAE08PZiwAAAATTs8Y7EAAABNOjussgAAAMA7tAASAAcAnzkDAVI5BQBNPSFPNgAAAE08PUB7AAAATTs87rUAAABNOjussgAAAE08CKyyAAAATTs8Z7YAAACfOQMBUjkGAE09IU82AAAATTw9QHsAAABNOzzutQAAAE06O6yyAAAAwDu3ABIAHQCfOQMBTTkDgrgAAADAO7kAEgAHABIAHQASACEAvDk5x0cAAACfOQMBTTsg3LoAAABNOjvduwAAAE05Oq68AAAApDzAAL/40su8OgPYwQAAAJ86AwIwOjmpwgAAAE09IU82AAAATTw9QHsAAABNOzzutQAAAE06O6yyAAAATTk6CMMAAACkPMAAv/jSy7w6A9jBAAAAnzoDAjA6OanCAAAAwDnEABIAIAASACEATToWhcUAAABSPDkAvDo6x0cAAACfOgMBTToWDcYAAABNPCDcugAAAE07PFo1AAAAqTwBAPA6BQDHAAAA8DoCAMgAAACpPAABqTwBADA8O4DJAAAATTwg3LoAAABNOzzduwAAAPA6AgC7AAAAqTwAAak8AQAwPDuAyQAAAE0/IU82AAAATT4/QHsAAABNPT7utQAAAE08PayyAAAATTs8CMMAAADwOgIAuwAAAKk8AAGpPAEAMDw7gMkAAADwOgkAxwAAgE08INy6AAAATTs8WjUAAABvPMoAMDw79csAAABlAAkA8DoIAMgAAIBNPCDcugAAAE07PFo1AAAAbzzMADA8O/XLAAAAwDrNABIAHQAwOh36zgAAAMA6zwASAB0AMDodnNAAAAC8Oh36zgAAAJ86AgFSPCcAwD3RABIABwC8OhWK0gAAAJ86BAGCHQIA0wEDsgEEAAAAQAOzAQO0AQO1AQO2AQO3AQO4AQO5AQQAAIBAA7oBA7sBA7wBA70BA74BA78BA8ABA8EBA8IBA8MBA8QBA8UBA8YBA8cBA8gBA8kBA8oBA8sBA8wBA80BA84BA88BAxED0AED0QED0gED0wED1AED1QED1gED1wED2AED2QED2gED2wED3AED3QED3gED3wED4AEDMwPhAQMdA6cBA6YBA+IBA+MBA40BA+QBA+UBA+YBA+cBBAAA0EMD6AED6QED6gEDCAPrAQYAAwED7AEDoQECAAAAAADAgkADAgIAAAAAAAAUQAMDAwQEADCxhAKamZmZmZnpPwMFBAA8sYQDBgNRAxcEAEwhhQOdAQN5A2YDaANnAs3MzMzMzOw/A2wCzczMzMzM9D8DbgJ7FK5H4XqEPwNtA5MBA+0BA2oDWgN2BQJjZAPuAQIK16NwPQrHPwPvAQKamZmZmZnJPwPwAQK4HoXrUbjOPwPxAQPyAQNxA1ADSANJA1wDWwUFb3BxcnMD8wED9AEDRgP1AQP2AQM1A4UBA4YBAzED9wED+AED+QEDOAMUAgAAAAAAAPA/BgIGAwYEA/oBA/sBBgUDQAOfAQQALKKIBgYGBwORAQNEA2kDXwNwA4IBA4QBA1gDdwNCAzsFApABmQECAAAAAAAA0D8D/AEDngEGCANFBgkDXgP9AQYKBgsDgAEGDQOSAQYOA5UBBhIDowEGEwP+AQYUA/8BA4ACA6UBA6oBA4ECBhUDgQEDggIGFgOiAQYXA4cBA6kBAxUDTQObAQOcAQS/+NLLA4MCAxIDqwEGGAOEAgOFAgOoAQOaAQNgA6wBAyEDrQEGGQOvAQYaA7ABBhsDhgIYAAECAwQFBgcICQoLDQ4SExQVFhcYGRobAQABBAACAAAAAAABAAAAAAABAAD8AAABAAAAAAABAAAAAAAC/AAAAAAAAAAAAAEAAAAAAP8AAAAAAQAAAAAAAAAAAQD+AAAAAAEAAAAAAAAAAAEA/gAAAAAAAAAAAQAAAAAAAP8AAAAAAAAAAAAAAAABAAD/AAAAAAAAAAEAAAAAAAAA/wAAAAABAAAAAAAAAQAAAP4AAAAAAQAAAAAAAAAAAQD+AAAAAAAAAAABAAAAAAAA/wAAAAEAAAAAAAABAAAAAP4AAQAAAAAAAAAAAAABAAD+AAAAAAAAAAEAAAAAAAAA/wAAAAABAAAAAAAAAAAAAP8AAAABAAAAAAAAAAABAAD+AAAAAAAAAAEAAAAAAAAA/wMABQABAAAAAgAAAAIAAPMAAAAAAQACAAEAAQAAAAH6AgAAAAAAAAAAAAAAAAAA/gQAAAAAAAEAAgAACwAAAPgAAAD2AAAAAAEAAAAAAAT7AAAAAAAAAAIACQAAAAAA9QEAAAAAAAACAAABAAABAPsCAAABAAABAAABAAACAAD5BAABAAAAAAAAAAABAAAA+gAAAAABAAAAAAAAAAABAP4AAAAAAAABAAAAAAAAAAD/AAMAAQYAAAEAAAEAAAEA8wEAAAAAAAACBgAAAQAAAfUAAQAAAQAAAAAAAAAABAD6AAEAAQAAAgAAAAAAAAAB+wEAAAQAAQADAAAAAAABAPYBAAEAAAAAAAAAAQADAgD4AQABAAAAAAAAAAEAAQIA+gYAAAAAAAAA+wAAAgAAAP0aAAsAAAAPAAAAAAAAAADMIwAAAAAAAwAAAAAVAAAAxQALAAAAAAAACgAAAgAAAegAAQAAAQAAAgAAAQAAAgD5AAIAAAABAAAAAAEAAAAA/AAAAAEAAAAAAAAAAAAAAf4AAAAAAAAAAAACAAAAAAvzAAAAHQAAAAAAAQAAAAAA4gAUAAAAAAQAAAAAAACAAGgAAAAAAABUAAAAAAAAIwCJAAAAAAAtAAAAAAAHAAAAzAAACQAAAAAAAAAAAAAAAPcAAAIAAAAAAAAAAAAAAAD+BgAAAAAAAAAAAAAAAAAC+AAAAAAAAAAAAAAHAAAAAPkAAAALAAAAAAAAAAAAAAD1AQAAAAAAAAAAAAAAAAAA/wACAAAMAAAAAAABAPQAAP0AAAAAAAAAAAABAAAAAAD/AAAAAQAAAAAAAAAAAAAA/wAAAAIAAQAAAAAAAAABAPwAAAAAAAAJAAAABQAAAATuAAMAAAAAAAoBAAAABAAAAAQAAAABAAAAAgAAAAIAAAACAAAAAQAAAAEAAAACAAAAAgAAAAEAAAACAAAAAgAAAAEAAAABAAAAAgAAAAEAAAANAAAABgAAAAIAAAAIAAAABQAAAAsAAAAFAAAABwAAAAYAAAACAAAAAwAAAA0AAAALAAAADAAAAAUAAAAKAAAACAAAAAYAAADx////NAAAADsAAAAYAAAABwAAAAkAAAACAAAADQAAAB4AAACYAAAAdwAAADQAAAAJAAAAAgAAAAgAAAAHAAAACwAAAAEAAAADAAAAAQAAAAEAAAAFAAAAEgAAAAAccF9xOlieJQpCmxuuJNGw1rwC05Y+ZC5i1KFRkgwFvMnlhkjLaf5oOQ==

local v1 = game:GetService("Players")
local v2 = game:GetService("Workspace")
local u3 = game:GetService("RunService")
local u4 = game:GetService("UserInputService")
local v5 = game:GetService("ReplicatedStorage")
local v6 = require(v5.Client.Gui.Utils.AutoButtonColor)
local v7 = require(v5.Client.Gui.Utils.ClickableButton)
local u8 = require(v5.Client.Gui.GuiFrame)
local v9 = require(v5.Shared.Palette)
local u10 = require(v5.Shared.Utils.DoggyJumpUtil)
local u11 = require(v5.Client.Framework.Services.LocalData)
local u12 = require(v5.Shared.Constants)
local u13 = require(v5.Shared.Framework.Utilities.Math.Time)
require(v5.Client.Gui.Utils.ItemFrame)
local _ = require(v5.Shared.Utils.Stats.ItemUtil.PotionIcon)
require(v5.Shared.Types)
local _ = require(v5.Shared.Data.Currency)
local _ = require(v5.Shared.Data.Powerups)
local u14 = require(v5.Shared.Framework.Network.Remote)
local u15 = require(v5.Client.Gui.Utils.PlayLocalSound)
local u16 = require(v5.Client.Music)
local v17 = require(v5.Client.Activation)
local v18 = require(v5.Client.Framework.Services.InputMode)
local u19 = require(v5.Shared.Utils.Stats.ItemUtil)
local u20 = require(v5.Shared.Framework.Utilities.String.FormatCommas)
local u21 = require(v5.Client.Framework.Utilities.Gui.Animations.SetFade)
local u22 = require(v5.Shared.Utils.AnimateColor)
local u23 = require(v5.Shared.Utils.Stats.StatsUtil)
local v24 = require(v5.Shared.Utils.CurrencyUtil)
local u25 = {}
local u26 = v1.LocalPlayer
local u27 = u26.PlayerGui.ScreenGui
local u28 = u27.DoggyJump.Frame
local u29 = u27.DoggyJump.Frame.Inner.Main
local u30 = u29.Area
local u31 = u30.Layers
local u32 = u30.Objects
local v33 = u28.Inner.Prizes
local u34 = u32.Doggy
local v35 = workspace.Worlds["The Overworld"].Islands["Outer Space"].Island.DoggyJump.Activation
local u36 = u27.DoggyJump.Frame.UIScale
local u37 = v2.CurrentCamera
u37:GetPropertyChangedSignal("ViewportSize"):Connect(function() --[[Function name: update, line 60]]
    --[[
    Upvalues:
        [1] = u37
        [2] = u36
    --]]
    local v38 = u37.ViewportSize.x / 600 * 5
    local v39 = math.floor(v38) / 5
    u36.Scale = math.clamp(v39, 0.8, 2)
end)
local v40 = u37.ViewportSize.x / 600 * 5
local v41 = math.floor(v40) / 5
u36.Scale = math.clamp(v41, 0.8, 2)
u25.JUMP_SPEED = Vector2.new(0, 550)
u25.GRAVITY = Vector2.new(0, 1900)
u25.SPEED_MIN = 280
u25.SPEED_MAX = 820
u25.SPEED_INCREASE_RATE = 11
u25.OBJECTS_PER_SECOND_MIN = 0.9
u25.OBJECTS_PER_SECOND_MAX = 1.3
u25.OBJECTS_PER_SECOND_INCREASE_RATE = 0.01
u25.UNTIL_FIRST_OBJECT = 1
u25.POINTS_PER_SECOND = u10.PointsPerSecond
u25.layers = {
    ["Sky"] = {
        ["p"] = 0,
        ["v"] = 0
    },
    ["Clouds1"] = {
        ["p"] = 0,
        ["v"] = 0.18
    },
    ["Mountains"] = {
        ["p"] = 0,
        ["v"] = 0.2
    },
    ["Clouds2"] = {
        ["p"] = 0,
        ["v"] = 0.24
    },
    ["Ground"] = {
        ["p"] = 0,
        ["v"] = 1
    }
}
u25.objectTypes = {
    {
        ["i"] = "rbxassetid://133429322374627",
        ["w"] = 62,
        ["h"] = 36,
        ["y"] = -3,
        ["m"] = Vector2.new(7, 3)
    },
    {
        ["i"] = "rbxassetid://135190396224590",
        ["w"] = 55,
        ["h"] = 35,
        ["y"] = -3,
        ["m"] = Vector2.new(5, 4)
    }
}
local v42 = v33.Content
local v43 = v42.Template
v43.Parent = nil
local v44 = u29.Area.Overlay.Result.Prizes
local v45 = v44.Template
v45.Parent = nil
local u46 = {}
local u47 = {}
for v48 = 1, #u10.PrizeScores do
    local v49 = v43:Clone()
    v49.LayoutOrder = v48
    v49.Name = ("Prize%*"):format(v48)
    v49.Parent = v42
    u46[v48] = v49
    local u50 = v45:Clone()
    u50.LayoutOrder = v48
    u50.Name = ("Prize%*"):format(v48)
    u50.Parent = v44
    u47[v48] = u50
    u36:GetPropertyChangedSignal("Scale"):Connect(function() --[[Function name: updateScales, line 165]]
        --[[
        Upvalues:
            [1] = u36
            [2] = u50
        --]]
        local v51 = 1 / u36.Scale
        u50.UIScale.Scale = v51
    end)
    local v52 = 1 / u36.Scale
    u50.UIScale.Scale = v52
end
local function u62() --[[Anonymous function at line 202]]
    --[[
    Upvalues:
        [1] = u11
        [2] = u10
        [3] = u26
        [4] = u46
        [5] = u19
        [6] = u23
        [7] = u22
        [8] = u12
        [9] = u47
    --]]
    local v53 = u11:Get()
    if v53 then
        for v54, v55 in u10:GetPrizes(u26, v53) do
            local v56 = u46[v54]
            u19:UpdateIcon(v56.Inner.Icon, v55)
            v56.Inner.Title.Text = u19:GetName(v55)
            local v57
            if v55.Type == "Currency" then
                v57 = table.clone(v55)
                local v58 = u23:GetCurrencyMultiplier(v53, v55.Currency, true)
                local v59 = v57.Amount * v58
                v57.Amount = math.ceil(v59)
            else
                v57 = v55
            end
            u19:FormatAmount(v56.Inner.Icon.Amount, v57)
            local v60 = u19:GetRarity(v57)
            if v60 == "Legendary" then
                u22.Cycle(v56.Inner.Title, "Rainbow", {
                    ["Speed"] = 0.4
                })
            else
                u22.None(v56.Inner.Title)
                v56.Inner.Title.TextColor3 = u12.RarityColors[v60]
            end
            local v61 = u47[v54]
            u19:UpdateIcon(v61, v57)
            u19:FormatAmount(v61.Amount, v57)
        end
    end
end
u11:ConnectDataChanged(v24.CurrencyMultUpdateKeys, u62)
local function u69() --[[Anonymous function at line 240]]
    --[[
    Upvalues:
        [1] = u11
        [2] = u10
        [3] = u29
        [4] = u13
    --]]
    local v63 = u11:Get()
    if v63 then
        local v64 = #u10.PrizeScores
        local v65 = u10.RefreshPeriod
        if v63.DoggyJump.Claimed < v64 then
            u29.Parent.Parent.Label.Text = ("Win up to %* prizes every %* minutes!"):format(v64, v65 // 60)
        else
            local v66 = u13.now()
            local v67 = v63.DoggyJump.Began + v65 - v66
            local v68 = math.max(1, v67)
            u29.Parent.Parent.Label.Text = ("More prizes available in %*"):format((u13.formatRealTime(v68)))
        end
    else
        return
    end
end
task.spawn(function() --[[Anonymous function at line 261]]
    --[[
    Upvalues:
        [1] = u8
        [2] = u69
    --]]
    while true do
        if u8:IsOpen("DoggyJump") then
            u69()
        end
        task.wait(0.5)
    end
end)
u11:ConnectDataChanged("DoggyJump", function() --[[Anonymous function at line 272]]
    --[[
    Upvalues:
        [1] = u62
        [2] = u69
    --]]
    u62()
    u69()
end)
u25.running = false
u25.t = nil
u25.speed = nil
u25.score = nil
u25.lastObject = nil
u25.updateConnection = nil
u25.inputConnection = nil
u25.objects = {}
u25.doggy = {}
u25.doggy.w = 22
u25.doggy.h = 22
u25.lastSounds = {}
u25.lastSounds.Squeak = {
    ["t"] = 0,
    ["max"] = 0.25
}
u25.lastSounds.Spring = {
    ["t"] = 0,
    ["max"] = 0.25
}
function u25.playSound(_, p70, _) --[[Anonymous function at line 305]]
    --[[
    Upvalues:
        [1] = u25
        [2] = u15
    --]]
    local v71 = u25.lastSounds[p70]
    if v71 and tick() - v71.t >= v71.max then
        v71.t = tick()
        u15(p70)
    end
end
function u25.newObject(p72) --[[Anonymous function at line 316]]
    --[[
    Upvalues:
        [1] = u34
        [2] = u32
    --]]
    local v73 = p72.objectTypes[math.random(2)]
    local v74 = v73.w
    local v75 = v73.h
    local v76 = Instance.new("ImageLabel")
    v76.BackgroundTransparency = 1
    v76.BorderMode = Enum.BorderMode.Inset
    v76.Image = v73.i
    v76.AnchorPoint = Vector2.new(0.5, 1)
    v76.Size = UDim2.fromOffset(v74, v75)
    v76.Position = UDim2.new(100, 0, 0, 0)
    v76.ZIndex = u34.ZIndex - 1
    v76.Parent = u32
    local v77 = p72.objects
    local v78 = {
        ["f"] = v76,
        ["p"] = Vector2.new(300 + v74 + math.random(0, 85), v73.y),
        ["w"] = v74,
        ["h"] = v75,
        ["m"] = v73.m
    }
    table.insert(v77, v78)
end
local u79 = { "Frame", "ImageButton" }
local function u87() --[[Anonymous function at line 346]]
    --[[
    Upvalues:
        [1] = u11
        [2] = u10
        [3] = u25
        [4] = u46
        [5] = u21
        [6] = u79
        [7] = u20
    --]]
    local v80 = u11:Get()
    local v81 = not v80 and 0 or v80.DoggyJump.Claimed
    for v82, v83 in u10.PrizeScores do
        local v84 = v83 <= (u25.score or 0)
        local v85 = v82 <= v81
        local v86 = u46[v82]
        v86.Claimed.Visible = v85
        u21(v86.Inner, v85 and 0.5 or 0, nil, u79)
        v86.Inner.Score.Text = ("%*%* Score"):format(v84 and "\226\156\133 " or "", (u20(u10.PrizeScores[v82])))
    end
end
u11:ConnectDataChanged("DoggyJump", u87)
function u25.stepGame(p88, p89) --[[Anonymous function at line 370]]
    --[[
    Upvalues:
        [1] = u30
        [2] = u87
        [3] = u31
        [4] = u34
    --]]
    local v90 = p88.t + p89
    p88.t = v90
    local v91 = p88.SPEED_MIN + v90 * p88.SPEED_INCREASE_RATE
    local v92 = p88.SPEED_MIN
    local v93 = p88.SPEED_MAX
    local v94 = math.clamp(v91, v92, v93)
    p88.speed = v94
    local v95 = p88.POINTS_PER_SECOND * v90
    local v96 = math.floor(v95)
    p88.score = v96
    u30.Score.Text = ("Score: %i"):format(v96)
    u87()
    local v97 = p88.OBJECTS_PER_SECOND_MIN + p88.OBJECTS_PER_SECOND_INCREASE_RATE * v90
    local v98 = p88.OBJECTS_PER_SECOND_MAX
    local v99 = 1 / math.min(v97, v98)
    local v100 = p88.lastObject
    if v99 < v90 - p88.lastObject then
        p88:newObject()
        p88.lastObject = v100 + v99
    end
    local v101 = p88.layers
    for v102, v103 in pairs(v101) do
        local v104 = u31:FindFirstChild(v102)
        local v105 = v104.Frame1
        local v106 = v104.Frame2
        local v107 = v103.p + p89 * v103.v * -v94
        local v108 = v107 % 300
        local v109 = v108 - 300
        v103.p = v107
        v105.Position = UDim2.new(0, v108, 0, 0)
        v106.Position = UDim2.new(0, v109, 0, 0)
    end
    local v110 = p88.doggy
    local _ = v110.v
    local v111 = v110.p
    if v110.j then
        local v112 = v110.v - p88.GRAVITY * p89
        v111 = v110.p + v112 * p89
        if v111.y <= 4 then
            v111 = Vector2.new(v111.x, 0)
            v112 = Vector2.new()
            v110.j = false
        end
        v110.p = v111
        v110.v = v112
    end
    if v111.y == 0 then
        local v113 = u34
        local v114 = UDim2.new
        local v115 = v111.x
        local v116 = v90 * 9
        local v117 = math.sin(v116)
        v113.Position = v114(0, v115, 1, math.abs(v117) * -4.2)
        local v118 = (v90 - p89) * 9
        local v119 = math.sin(v118) * 3
        local v120 = v90 * 9
        local v121 = math.sin(v120) * 3
        u34.Rotation = v121
        local _ = math.sign(v119) == math.sign(v121)
    else
        u34.Position = UDim2.new(0, v111.x, 1, -v111.y)
        local v122 = u34.Rotation + p89 * 760
        u34.Rotation = math.min(360, v122)
    end
    local v123 = p88.objects
    for v124 = #v123, 1, -1 do
        local v125 = v123[v124]
        local v126 = v125.f
        local v127 = v125.p + Vector2.new(p89 * -v94, 0)
        if v127.x <= -10 then
            v126:Destroy()
            table.remove(v123, v124)
        else
            v125.p = v127
            v126.Position = UDim2.new(0, v127.x, 1, -v127.y)
        end
    end
    local v128 = v110.p + Vector2.new(0, 16)
    local v129 = Vector2.new(v110.w, v110.h) * 0.5
    for _, v130 in ipairs(v123) do
        local v131 = v130.p + Vector2.new(0, v130.h * 0.5)
        local v132 = Vector2.new(v130.w, v130.h) * 0.5 - v130.m
        local v133 = v131 - v128
        local v134 = v129 + v132
        local v135 = v133.x
        if math.abs(v135) < v134.x then
            local v136 = v133.y
            if math.abs(v136) < v134.y then
                return true
            end
        end
    end
    return false
end
function u25.stopGame(p137, p138) --[[Anonymous function at line 498]]
    --[[
    Upvalues:
        [1] = u30
        [2] = u11
        [3] = u28
        [4] = u10
        [5] = u14
        [6] = u47
    --]]
    if p137.updateConnection then
        p137.updateConnection:Disconnect()
        p137.updateConnection = nil
    end
    if p137.inputConnection then
        p137.inputConnection:Disconnect()
        p137.inputConnection = nil
    end
    local u139 = u30.Overlay
    local v140 = u139.Result
    local v141 = u11:Get()
    local v142 = not v141 and 0 or v141.DoggyJump.Claimed
    u28.Input.Visible = false
    u139.Play.Visible = false
    delay(0.5, function() --[[Anonymous function at line 522]]
        --[[
        Upvalues:
            [1] = u139
        --]]
        u139.Play.Visible = true
    end)
    if p138 then
        local v143 = 0
        for v144, v145 in u10.PrizeScores do
            if v145 <= p138 and v142 < v144 then
                v143 = v144
            end
        end
        local v146 = #u10.PrizeScores <= v142
        local v147 = v143 > 0
        if v147 then
            u14:FireServer("DoggyJumpWin", v143)
        end
        if v146 then
            v140.Extra.Visible = true
            v140.Extra.Text = "More prizes available later!"
            v140.Prizes.Visible = false
        elseif p138 < u10.PrizeScores[1] then
            v140.Extra.Visible = true
            v140.Extra.Text = "Get a higher score to win prizes!"
            v140.Prizes.Visible = false
        elseif v147 then
            v140.Extra.Visible = false
            v140.Prizes.Visible = true
            for v148, v149 in u10.PrizeScores do
                local v150 = u47[v148]
                local v151
                if v149 <= p138 then
                    v151 = v142 < v148
                else
                    v151 = false
                end
                v150.Visible = v151
            end
        else
            v140.Extra.Visible = true
            v140.Extra.Text = "Get a higher score to win more prizes!"
            v140.Prizes.Visible = false
        end
        v140.Subtitle.Visible = v140.Prizes.Visible
        v140.Visible = true
    else
        v140.Visible = false
    end
    u139.Visible = true
    p137.running = false
end
function u25.resetGame(p152) --[[Anonymous function at line 582]]
    --[[
    Upvalues:
        [1] = u30
        [2] = u87
        [3] = u31
        [4] = u34
    --]]
    p152.t = 0
    p152.speed = p152.SPEED_MIN
    p152.score = 0
    p152.lastObject = p152.UNTIL_FIRST_OBJECT - p152.OBJECTS_PER_SECOND_MIN
    p152.running = false
    u30.Score.Text = ("Score: %i"):format(0)
    u87()
    local v153 = p152.objects
    for v154 in ipairs(v153) do
        v153[v154].f:Destroy()
        v153[v154] = nil
    end
    local v155 = p152.layers
    for v156, v157 in pairs(v155) do
        v157.p = 0
        local v158 = u31:FindFirstChild(v156)
        v158.Frame1.Position = UDim2.fromScale(0, 0)
        v158.Frame2.Position = UDim2.fromScale(1, 0)
    end
    local v159 = p152.doggy
    v159.p = Vector2.new(40, 0)
    v159.v = Vector2.new(0, 0)
    v159.j = false
    u34.Position = UDim2.new(0, v159.p.x, 1, 0)
    u34.Rotation = 0
end
function u25.startGame(u160, _) --[[Anonymous function at line 617]]
    --[[
    Upvalues:
        [1] = u16
        [2] = u3
        [3] = u4
        [4] = u28
        [5] = u30
    --]]
    u160:resetGame()
    spawn(function() --[[Anonymous function at line 620]]
        --[[
        Upvalues:
            [1] = u16
        --]]
        u16:SetTrack("rbxassetid://4853930727")
    end)
    local u161 = 0
    u160.updateConnection = u3.Heartbeat:Connect(function(p162) --[[Anonymous function at line 625]]
        --[[
        Upvalues:
            [1] = u161
            [2] = u160
        --]]
        u161 = u161 + p162
        while u161 >= 0.016666666666666666 do
            if u160:stepGame(0.016666666666666666) then
                u160:stopGame(u160.score)
            end
            u161 = u161 - 0.016666666666666666
        end
    end)
    local u163 = u160.doggy
    u160.inputConnection = u4.InputBegan:Connect(function(p164) --[[Anonymous function at line 639]]
        --[[
        Upvalues:
            [1] = u163
            [2] = u160
        --]]
        local v165 = p164.UserInputType
        if (v165 == Enum.UserInputType.MouseButton1 or (v165 == Enum.UserInputType.Touch or p164.KeyCode == Enum.KeyCode.ButtonY)) and not u163.j then
            u163.j = true
            u163.v = u160.JUMP_SPEED
            u160:playSound("Spring", 0.8)
        end
    end)
    u28.Input.Visible = true
    u30.Overlay.Visible = false
    u160.running = true
end
u8:BindOnOpened("DoggyJump", function() --[[Anonymous function at line 662]]
    --[[
    Upvalues:
        [1] = u27
    --]]
    u27.HUD.Visible = false
end)
u8:BindOnClosed("DoggyJump", function() --[[Anonymous function at line 669]]
    --[[
    Upvalues:
        [1] = u25
        [2] = u27
    --]]
    u25:stopGame(nil)
    u27.HUD.Visible = true
end)
v6(u29.Parent.Parent.Top.Close.Button, v9.Button.Red)
v7(u29.Parent.Parent.Top.Close.Button, function() --[[Anonymous function at line 680]]
    --[[
    Upvalues:
        [1] = u8
    --]]
    u8:Close()
end)
v6(u29.Area.Overlay.Play.Button, v9.Button.Purple)
v7(u29.Area.Overlay.Play.Button, function() --[[Anonymous function at line 688]]
    --[[
    Upvalues:
        [1] = u25
    --]]
    if not u25.running then
        u25:startGame()
    end
end)
u4.InputBegan:Connect(function(p166, p167) --[[Anonymous function at line 695]]
    --[[
    Upvalues:
        [1] = u8
        [2] = u25
        [3] = u29
    --]]
    if not p167 and (u8:IsOpen("DoggyJump") and not u25.running) then
        if p166.KeyCode == Enum.KeyCode.ButtonY and u29.Area.Overlay.Play.Visible then
            u25:startGame()
        end
    end
end)
u28.Input.Gamepad.Icon.Image = u4:GetImageForKeyCode(Enum.KeyCode.ButtonY)
u29.Area.Overlay.Play.Button.GamepadIcon.Image = u4:GetImageForKeyCode(Enum.KeyCode.ButtonY)
v18.Changed:Connect(function(p168) --[[Function name: onInputChanged, line 709]]
    --[[
    Upvalues:
        [1] = u28
        [2] = u29
    --]]
    u28.Input.Main.Visible = p168 == "Keyboard" and true or p168 == "Touch"
    u28.Input.Gamepad.Visible = p168 == "Gamepad"
    u29.Area.Overlay.Play.Button.GamepadIcon.Visible = p168 == "Gamepad"
    if p168 == "Keyboard" then
        u28.Input.Main.Text = "Click to jump!"
    elseif p168 == "Touch" then
        u28.Input.Main.Text = "Tap to jump!"
    end
end)
local v169 = v18.Mode
u28.Input.Main.Visible = v169 == "Keyboard" and true or v169 == "Touch"
u28.Input.Gamepad.Visible = v169 == "Gamepad"
u29.Area.Overlay.Play.Button.GamepadIcon.Visible = v169 == "Gamepad"
if v169 == "Keyboard" then
    u28.Input.Main.Text = "Click to jump!"
elseif v169 == "Touch" then
    u28.Input.Main.Text = "Tap to jump!"
end
function u25.Stop(_) --[[Anonymous function at line 726]]
    --[[
    Upvalues:
        [1] = u25
    --]]
    u25:stopGame(nil)
    u25:resetGame()
end
function u25.IsPlaying(_) --[[Anonymous function at line 731]]
    --[[
    Upvalues:
        [1] = u25
    --]]
    return u25.running == true
end
u25:Stop()
v17:Bind(v35, function() --[[Anonymous function at line 738]]
    --[[
    Upvalues:
        [1] = u8
    --]]
    u8:Open("DoggyJump")
end)
return u25