--devbgascension

-- Bytecode (Base64):
-- BgPJAQJJZA5wYXNzTmFtZUZyb21JZARBcmVhDldvcmxkc1VubG9ja2VkDUFyZWFzVW5sb2NrZWQKaXNVbmxvY2tlZAVPcmRlcgdJc2xhbmRzBE5hbWUNZ2V0V29ybGRPcmRlcgVJbWFnZQRDb3N0CFVubG9ja2VkA0dldAVDbG9uZQZCdXR0b24GdHlwZW9mBm51bWJlcglHZXRBbW91bnQDR3VtBXRhYmxlBmluc2VydARzb3J0DEluZmluaXR5IEd1bQdWSVAgR3VtClZJUCBGbGF2b3IIZ2V0U3RvcmUHR3VtU2hvcAhDbGVhckFsbAlCbHVlYmVycnkHRmxhdm9ycwRLaW5kBFRyYXkDQWRkBUxhYmVsBFRleHQGQWN0aW9uDkZpbmRGaXJzdENoaWxkDFN0cmV0Y2h5IEd1bRN1cGRhdGVUdXRvcmlhbEFycm93BVVEaW0yCmZyb21PZmZzZXQKVGV4dEJvdW5kcwFYB1VJU2NhbGUFU2NhbGUEU2l6ZQVHcmVlbgpUZXh0Q29sb3IzBFR5cGUIQ3VycmVuY3kFQ29sb3IGQ29sb3IzA25ldwdWaXNpYmxlBEljb24KVXBkYXRlSWNvbgZQYXNzZXMGQnViYmxlBkZsYXZvcgVPd25lZAZMb2NrZWQRVW5sb2NrIHRoaXMgaW4gJSoJYXV0b0NvbG9yBE5vbmUGWWVsbG93BmZvcm1hdAZSZW1vdmUFRXF1aXAEUGluawQlKiUqDFJvYnV4VW5pY29kZQJfXwZPcmFuZ2UDQnV5DkdldE93bmVkQW1vdW50A1JlZAtHZXRDaGlsZHJlbgVGcmFtZQNJc0EHRGVmYXVsdAtMYXlvdXRPcmRlcgRTdGF0EUluZmluaXRlIFN0b3JhZ2UhCiUqIFN0b3JhZ2UHU3RvcmFnZQsrJSogQnViYmxlcwdCdWJibGVzDFVJR3JpZExheW91dAhDZWxsU2l6ZQZPZmZzZXQEbWF0aAVmbG9vcglUd2VlbkluZm8ERW51bQtFYXNpbmdTdHlsZQVRdWludA5DYW52YXNQb3NpdGlvbgdWZWN0b3IyBkNyZWF0ZQRQbGF5BHRhc2sFZGVmZXIJQ29zdFRpdGxlDHNldFNlbGVjdGlvbglHdWlPYmplY3QDPz8/CEVxdWlwcGVkC0ltYWdlQ29sb3IzBnVwZGF0ZQZaSW5kZXgGUGFyZW50CVVJUGFkZGluZwRVRGltDFBhZGRpbmdSaWdodApKU09ORW5jb2RlDFNldEF0dHJpYnV0ZQRCbHVlCEluYWN0aXZlBVRpdGxlCUhpZ2hsaWdodApCdWJibGUgR3VtCUJhc2ljIEd1bQREb25lBG9wZW4Lc2V0VHV0b3JpYWwMUHJpY2VJblJvYnV4IFlvdSBuZWVkICUqIHRvIHB1cmNoYXNlIHRoaXMgJSohBFNob3cWUHJvbXB0R2FtZVBhc3NQdXJjaGFzZQ1mcm9tTm90RW5vdWdoCEdhbWVwYXNzBUJ1aWxkBWRlbGF5DkN1cnJlbmN5UGlja3VwBkd1bUJ1eQ9HdW1TaG9wUHVyY2hhc2UKRmlyZVNlcnZlcg1VcGRhdGVTdG9yYWdlDFVwZGF0ZUZsYXZvcgVDbG9zZQhTaG9wT3BlbgRnYW1lB1BsYXllcnMKR2V0U2VydmljZRFSZXBsaWNhdGVkU3RvcmFnZQtIdHRwU2VydmljZRJNYXJrZXRwbGFjZVNlcnZpY2UMVHdlZW5TZXJ2aWNlB3JlcXVpcmUGU2hhcmVkBVR5cGVzBERhdGEJRnJhbWV3b3JrB0NsYXNzZXMEUG9vbAZDbGllbnQIU2VydmljZXMJTG9jYWxEYXRhA0d1aQVVdGlscw9BdXRvQnV0dG9uQ29sb3IHUGFsZXR0ZQlVdGlsaXRpZXMGU3RyaW5nDEZvcm1hdFN1ZmZpeBJIb29rU2Nyb2xsaW5nRnJhbWUPQ2xpY2thYmxlQnV0dG9uB05ldHdvcmsGUmVtb3RlCEd1aUZyYW1lBVN0YXRzCEl0ZW1VdGlsBE1haWQIR3VpQXJyb3cJUXVlc3RVdGlsElVwZGF0ZVdoaWxlR3VpT3BlbgxDdXJyZW5jeVV0aWwGV29ybGRzCFJpY2hUZXh0BlByb21wdAhCdWlsZGVycw1Qcm9tcHRCdWlsZGVyC1Byb2R1Y3RJbmZvCUNvbnN0YW50cwVTaGlueQpBbmltYXRpb25zElByb2Nlc3NpbmdQdXJjaGFzZQpHYW1lcGFzc2VzDlBsYXlMb2NhbFNvdW5kC0xvY2FsUGxheWVyCVBsYXllckd1aQlTY3JlZW5HdWkFSXRlbXMFSW5uZXIETGlzdAhTZWxlY3RlZAhUZW1wbGF0ZQtHZXREYXRhS2V5cxZDb25uZWN0R2FtZXBhc3NDaGFuZ2VkDEJpbmRPbk9wZW5lZAAVBwEBAAAGAwAABQECDfsBAADGAgAAxgMAAGQBBQBNBgWUAAAAAJoGAgAAAAAAggQCAG4B+v8CAAAAxgEAAIIBAgABAwEATwIBGAAAAAABAAAAAf4ABQBQAAAAAAYCAQAABwQAAAUCDwQhKwACAKkCAACCAgIATQIBTwAAAAArAgIAqQIBAIICAgD7AwAATQQBTwAAAACHAgMEDgIKAE0EAPEBAAAATQUBTwAAAACHAwQFRwMCAAAAAICpAgABqQIBAIICAgBNBAAyAgAAAE0FAU8AAAAAhwMEBUcDAgAAAACAqQIAAakCAQCCAgIAAwMDAwQDBQBYBgEYAAEAAQAAAQABAAAAAAEAAAAAAAAAAAACAAAAAAAAAAAAWQAAAAAMAQEAAAYDAAAFAYMeKwACAIwBAACCAQIA+wEAAMYCAADGAwAAZAETAJoEBAAAAAAATQYFZAAAAACCBgIATQYFJwEAAADGBwAAxggAAGQGBwBNCwq6AgAAAJoLBAAAAAAATQsFZAAAAACCCwIAbgb4/wIAAABuAez/AgAAAIwBAACCAQIAAwMHAwgDCQBjCgEYAAEAAgAAAAEAAQAAAgAAAAABAAAAAQAA/gD8AAoAZAAAAAAIAAYAAABE+wEAAPsDAQBNAgO6AAAAAIcAAQIrAAUA+wECAPsDAQBNAgO6AAAAAIcAAQIrAAEAggABAPsBAwDiAgQA+wQBAE0DBLoAAAAAMAMCugAAAABNAwCpAQAAADADAqkBAAAATQMAIwIAAAAwAwIjAgAAAPsEBAC8BAR/BQAAAJ8EAgIrBAIAqQMAAGUAHQBNBQBPBgAAACsFAgCpAwEAZQAYAPsGBQBNBwBPBgAAAIcFBgcOBQoATQYE8QcAAABNBwBPBgAAAIcFBgdHBQIAAAAAgKkDAAGpAwEAZQAJAE0GBDIIAAAATQcATwYAAACHBQYHRwUCAAAAAICpAwABqQMBADADAtYDAAAAnwECAYIAAQAJAwkDCwMMAw0FBAABAgMDDgMDAwQDBQB3AAEYHwAAAAAAAAAAAAABAQIAAQAAAAABAAAAAQAAAAEAAADZAQABAAABAAEAAAAAAQAAAAAAAAAAAAIAAAAAAAAAACAA/AZZAAAAAAQABwAAABD7AAAAvAAAOgAAAACfAAIC+wEBAE0CAKwBAAAA2QMAABICAgASAAAAEgIDABICBAASAgUAEgIGAJ8BAwGCAAIAAgMPAxABA3QAARgAAAAAAgAAAAAAAAAAAAANdQAAAAALAgMAAABY+wIAAPsFAQBNBgC6AAAAAIcEBQZNAwRPAQAAAJ8CAgL7AwAA+wYBAE0HAboAAAAAhwUGB00EBU8BAAAAnwMCAvECBgADAAAAtwICAAMAAACpBAABqQQBAIIEAgBNBgAjAgAAALssBgKkBQQAAAAwQJ8FAgLwBQIABQAAAKkEAAGpBAEATQcBIwIAAAC7LAcCpAYEAAAAMECfBgIC8AYCAAUAAACpBQABqQUBAPEEAgAFAAAAggQCAE0HACMCAAAAuywHAqQGBAAAADBAnwYCAvAGGgAFAAAATQcBIwIAAAC7LAcCpAYEAAAAMECfBgIC8AYSAAUAAAD7BwIATQkAIwIAAAC8BwcCBgAAAJ8HAwL7CAIATQoBIwIAAAC8CAgCBgAAAJ8IAwK3BwIACAAAAKkGAAGpBgEAggYCAE0HACMCAAAATQgBIwIAAAC3BwIACAAAAKkGAAGpBgEAggYCAAcDCQMDAwwDEQQAADBAAxIDEwCZAQABGAAAAAAAAAAAAQAAAAAAAAABAAEAAAAAAwAAAAAAAAAAAAEAAAAAAAAAAAACAAEBAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAACAAAAAAAAAACaAAAAABECBgAABwQAAAUCgw+jAfsCAAC8AgJ/AAAAAJ8CAgL/AwAAAAAAAPABAwABAACA+wQBACsEAQD7BAIAUgUEAMYGAADGBwAAZAU7AE0LCSMCAAAAuywLAqQKBAAAADBAnwoCAvAKNAAFAAAA4gwJADAIDLoGAAAATQ0JIwIAAAAwDQwjAgAAAE0NCakHAAAAMA0MqQcAAAArAgIAqQ0AAGUAHQBNDglPCgAAACsOAgCpDQEAZQAYAPsPAwBNEAlPCgAAAIcODxAODgoATQ8C8QsAAABNEAlPCgAAAIcODxBHDgIAAAAAgKkNAAGpDQEAZQAJAE0PAjIMAAAATRAJTwoAAACHDg8QRw4CAAAAAICpDQABqQ0BADANDNYIAAAAnjQDBAwAAABSCwMApAoPAAA40ICfCgMBbgXE/wIAAACkBREAAEDQgFIGAwDZBwAAEgIEABIABAASAgUAnwUDAfABNAABAACA+wYBAE0FBmkSAAAAjAgHAOIJCQBvChIAMAoJugYAAABNCgUjAgAAADAKCSMCAAAATQoFqQcAAAAwCgmpBwAAAKkKAQAwCgnWCAAAADQ0AwQICQAAUgcDAKQGDwAAONCAnwYEAfsHAQBNBgewEwAAAIwJAwDiCgkAbwsTADALCroGAAAATQsGIwIAAAAwCwojAgAAAE0LBqkHAAAAMAsKqQcAAACpCwEAMAsK1ggAAAA0NAMECQoAAFIIAwCkBw8AADjQgJ8HBAGCAwIA+wYCAE0FBvwUAAAAjAgDAOIJCQBvChQAMAoJugYAAABNCgUjAgAAADAKCSMCAAAATQoFqQcAAAAwCgmpBwAAAKkKAQAwCgnWCAAAADQ0AwQICQAAUgcDAKQGDwAAONCAnwYEAYIDAgAVAw4DFAMMAxEEAAAwQAMSAwkDCwMNBQQGAgcIAwMDBAMFAxUDFgQAONCAAxcEAEDQgAMYAxkDGgEFiAEbARgwAAAAAQABAAAAAAIAAAABAAAAAAAAAAMBAAEAAAABAAAAxQEAAQAAAQABAAAAAAEAAAAAAAAAAAACAAAAAAAAAAA1AAAAAPwAAPwADAAAAAAAAAASAAEAAAEAAQAAAQAAAAEAAAABAAAAAAD8AAAHAAABAAEAAAEAAAABAAAAAQAAAAAA/AAAAAcAAAEAAQAAAQAAAAEAAAABAAAAAAD8AAAIWQAAAAAHAAcAAAB4+wAAACsAAQCCAAEA+wABALwAAH8AAAAAnwACAisAAQCCAAEA+wECAG8DAQC8AQFLAgAAAJ8BAwFNAgAOBAAAAE0BAlcDAAAAKwEwAPsCAwBNAQJ9BQAAAPABDQAEAAAA+wECAPsFBABNBAWiBgAAAE0DBA4EAAAAxgQAAG8FAQC8AQFfBwAAAJ8BBQGCAAEA+wMFAE0CA8MIAAAATQEC9QkAAADwAQsAAwAAgPsBAgD7BAUATQMEAgoAAADGBAAAbwUBALwBAV8HAAAAnwEFAYIAAQD7AQYAbwMDALwBAQMLAAAAnwEDAg4BPAD7AgIAUgQBAIwFmwBvBgEAvAICXwcAAACfAgUBggABAE0CABYNAAAATQECQAwAAAArAS8A+wIDAE0BAn0FAAAA8AENAA0AAAD7AQIA+wUEAE0EBaIGAAAATQMEFg0AAADGBAAAbwUBALwBAV8HAAAAnwEFAYIAAQD7AwUATQIDwwgAAABNAQL1CQAAAPABCwAMAACA+wECAPsEBQBNAwQCCgAAAMYEAABvBQEAvAEBXwcAAACfAQUBggABAPsBBgBvAwwAvAEBAwsAAACfAQMCDgEHAPsCAgBSBAEAjAWbAG8GAQC8AgJfBwAAAJ8CBQGCAAEADgMOAxwDHQMeAx8DIAMhAyIDIwMkAyUDJgMnAxQAygEoARgAAAECAAAAAQECAAAAAAIAAAAAAQAAAAABAAAAAAAAAAAAAAABAAAAAAAAAQAAAAAAAAAAAAIAAAAAAQEAAAAAAAAAAwAAAAABAAAAAAEAAAAAAAAAAAAAAAEAAAAAAAABAAAAAAAAAAAAAgAAAAABAQAAAAAAAATLAAAAAAgAAgAAABv7AgAATQECIwAAAABNAAHDAQAAAKQBBAAADCCA+wcAAE0GByMAAAAATQUGwwEAAABNBAWhBQAAAE0DBHkGAAAA+wYBAE0FBisHAAAATQQFhAgAAADsAgMEjAMyAJ8BAwIwAQAvCQAAAIIAAQAKAwwDIwMpAyoEAAwggAMrAywDLQMuAy8A2gIAARgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAFbAQAAABQBFQAADgMAAgUBBA8DHQIPBSQCiQX7AQAAvAEBfwAAAACfAQICKwEBAIIAAQBNAwAjAQAAALssAwKkAgMAAAAgQJ8CAgLwAg4ABAAAgPsEAQBNAwQjAQAAAE0CA8MFAAAA+wUCAE0EBfUGAAAATQMEmwcAAAAwAwJzCAAAAGUAIwBNAwAjAQAAAE0CAxEJAAAA8AIRAAoAAID7AwMATQUAIwEAAABNBAUJCgAAAIcCAwT7BQEATQQFIwEAAABNAwTDBQAAAE0EAqQLAAAAMAQDcwgAAABlAA0A+wQBAE0DBCMBAAAATQIDwwUAAACkAw4AADTAgIwEAQCMBQEAjAYBAJ8DBAIwAwJzCAAAAE0DACMBAAAAuywDAqQCAwAAACBAnwICAvACCAAEAACA+wMBAE0CAyMBAAAAqQMAADADAoAPAAAAZQAhAPsDAQBNAgMjAQAAAKkDAQAwAwKADwAAAPsEAQBNAwQjAQAAAE0CA8MFAAAA+wMEAPsEBQBNBgAjAQAAALwEBAIQAAAAnwQDAm8FEQCfAwMCMAMC9QYAAAD7AgUA+wYBAE0FBiMBAAAATQQFrhIAAABNBQAjAQAAALwCAiETAAAAnwIEAfsDAQBNAgOuEgAAAE0DAKkUAAAAMAMCqRQAAAD7AwEATQIDwwUAAABNAwC6FQAAADADAvUGAAAATQQBFhYAAABNBQC6FQAAAIcDBAUrAwUATQQBDhcAAABNBQC6FQAAAIcDBAVHAwIAAAAAgKkCAAGpAgEATQQAIwEAAAC7LAQCpAMDAAAAIECfAwIC8AMWAAQAAIBNBAAjAQAAAPsFBgDGBgAAxgcAAGQFBgBNCgmUGAAAAJoKAwAEAAAAUgMIAGUAAwBuBfn/AgAAAMYDAAAOAwUATQUBORkAAACHBAUDDgQBAKkCAQCpAwEATQUBJxoAAABNBAUWFgAAAE0FALoVAAAA8QQLAAUAAABNBQEnGgAAAE0EBfcbAAAATQUAuhUAAADxBAIABQAAAKkDAAGpAwEA+wUBAE0EBSMBAAAAVgUCADAFBIAPAAAA+wUBAE0EBYQcAAAAUgUCAA4FAQBWBQMAMAUEgA8AAAD7BgEATQUGAh0AAABNBAWsHgAAAFYFAwArBQEAVgUCADAFBIAPAAAA+wYHAE0FBn0fAAAA8AUDABYAAID7BAgAKwQBAPsECQBNBgC6FQAAAIcFBAb7CAoATQcIrCAAAABNBgfDBQAAAG8IIQD7CwsATQoLzCIAAABNDAVPJAAAAJALDCP7DgIATQ0O9QYAAABNDA19JQAAAJ8KAwK8CAiNJgAAAJ8IAwJSBwgAMAcG9QYAAAD7BwoATQYHrCAAAABNCADWJwAAAFYHCAAwBwaADwAAAE0HACMBAAAAuywHAqQGAwAAACBAnwYCAvAGawAEAACATQcAIwEAAAD7CAYAxgkAAMYKAABkCAYATQ0MlBgAAACaDQMABwAAAFIGCwBlAAMAbgj5/wIAAADGBgAADgYGAKkHAQBNCQE5GQAAAIcICQYqCAIAAQAAAKkHAAAOByAA+wgMAPsMAQBNCwwCHQAAAE0KC6weAAAAvAgIaSgAAACfCAMB+wsBAE0KCwIdAAAATQkKrB4AAABNCAnDBQAAAG8JKQAwCQj1BgAAAPsIDQD7CwEATQoLAh0AAABNCQqsHgAAAPsMAgBNCwysHgAAAE0KC9cqAAAAnwgDAWUAKwD7CAwA+wwBAE0LDAIdAAAATQoLrB4AAAC8CAhfKwAAAJ8IAwH7CwEATQoLAh0AAABNCQqsHgAAAE0ICcMFAAAAbwosAPsNDgBNDA04LQAAAPsPDwBNEAAjAQAAAIcODxCQDQ4uvAoKjSYAAACfCgQCUgkKADAJCPUGAAAA+wgNAPsLAQBNCgsCHQAAAE0JCqweAAAA+wwCAE0LDKweAAAATQoLbi8AAACfCAMB+wkBAE0ICSMBAAAAqQkAADAJCIAPAAAAZQBWACsCNQD7BgwA+woBAE0JCgIdAAAATQgJrB4AAAC8BgZpKAAAAJ8GAwH7CQEATQgJAh0AAABNBwisHgAAAE0GB8MFAAAAbwcwADAHBvUGAAAA+wYNAPsJAQBNCAkCHQAAAE0HCKweAAAA+wkFAFILAQBNDAAjAQAAALwJCe8xAAAAnwkEAvsKBQBNDAAjAQAAALwKCgIQAAAAnwoDAmAJBwAKAAAA+woCAE0JCqweAAAATQgJbzIAAAArCAUA+woCAE0JCqweAAAATQgJmwcAAACfBgMBZQAgACsDHwD7CQEATQgJAh0AAABNBwisHgAAAE0GB8MFAAAAbwcpADAHBvUGAAAA+wYMAPsKAQBNCQoCHQAAAE0ICaweAAAAvAYGaSgAAACfBgMB+wYNAPsJAQBNCAkCHQAAAE0HCKweAAAA+woCAE0JCqweAAAATQgJ1yoAAACfBgMBjAYBAPsHEAC8BwdoMwAAAJ8HAgRkB0MAbw40ALwMC/41AAAAnwwDAg4MPgD7DQgATQ4LuhUAAACHDA0OKwwEAPsNCQBNDgu6FQAAAIcMDQ77DwIATQ4PrB4AAABNDQ46NgAAAKkOAABNDwu6FQAAAE0QALoVAAAAmg8JABAAAABNBgsANwAAAPsQAgBNDxCsHgAAAE0ND5sHAAAAZQAOAE0QDCMBAAAAuywQAqQPAwAAACBAnw8CAvAPBwAEAACA+xACAE0PEKweAAAATQ0Pbi8AAACpDgEADg4HAPsPDABNEQusHgAAALwPD18rAAAAnw8DAWUABgD7DwwATRELrB4AAAC8Dw9pKAAAAJ8PAwH7Dw0ATRALrB4AAABSEQ0Anw8DAW4HvP8CAAAATQcAuhUAAADwBwgAOAAAgPsIAQBNBwhuOQAAAG8IOgAwCAf1BgAAAGUALAD7CAcATQcIfR8AAADwBxUAFgAAgPsIAQBNBwhuOQAAAG8JOwD7CwQA+w4IAE0PALoVAAAAhw0OD00MDYo8AAAAbw09AJ8LAwK8CQmNJgAAAJ8JAwJSCAkAMAgH9QYAAABlABMA+wgBAE0HCG45AAAAbwk+APsLBAD7DgkATQ8AuhUAAACHDQ4PTQwNpD8AAABvDT0AnwsDArwJCY0mAAAAnwkDAlIICQAwCAf1BgAAAPsLEABNCgvZQAAAAE0JCppBAAAATQgJeUIAAABNBwhwQwAAAHgMBkU+CwxEuwwLAqQKSAAAHGGEnwoCAgkJBwo+CgdJJggJCvsJEQD7CxAApAxLAAA0oIRvDUwApA5QAE840cSfDAMC4g1SAKQOVAAANDCFjA8AAPsTEgBNEhMrVQAAAE0REoRWAAAACRAIEZ8OAwIwDg2VUQAAALwJCZZXAAAAnwkFArwJCe5YAAAAnwkCAaQJWwAAaJGFwApcABICAQASAhIAnwkCAfsKAQBNCQqBXQAAAPsMAQBNCwwjAQAAAE0KC4APAAAAMAoJgA8AAADeABMA+wkUAJ8JAQGCAAEAXgMOAwwDEQQAACBAAxIDIwMkAzADMQMyAzMDNAM1AzYEADTAgAM3AxMCAAAAAICELkEDOAM5AwsDCQMUAx8DAQM6AzsDPAM9AyUDEAMgAz4DPwNAA0EDAwNCA0MDDQNEA0UDRgMiA0cDSANJA0oDSwNMA00DTgNPA1ADUQNSAxgDUwNUA1UDVgIAAAAAgIQeQQNXA1gDWQNaAywDWwIAAAAAAAAIQAIAAAAAAADwPwNcA10EABxhhAIAAAAAAAAAQANeBAA0oIQCMzMzMzMz0z8DXwNgA2EETzjRxANiBQFRA2MEADQwhQMtAy4DZANlA2YDZwQAaJGFBggDaAEI7gFpAQmfAAAAAQEDAAAAAAAAAAEAAAAAAAAAAAAAAAABAAAAAAABAAAAAAABAAAAAAAAAAAAAgAAAAAAAAAAAAAAAAMAAAAAAAAAAQAAAAAAAAIAAAAAAAEAAAAAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAMAAAAAAAABAAAAAAAAAwAAAAAAAAAAAAAAAAAAAQAAAAAAAAABAEUAAAABAAAAAQD+AAW3AAAAAAEEAAAAAAAAAAAAAAAAAAAAAAAAAQAAAAAAAQAAAAAAAAABAAAAAAAAAAAAAgAAAAAAAAABAAABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABAAAAAAAAAAIAAAAAAAAAAQA0AAAAAQAAAAEA/gAFyAAAAAAAAAABAQAAAAAAAAAAAQAAAAAAAAAAAAEAAAAAAAAAAAAAAAACAAAAAAAAAAABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAgAAAAAAAAIBAAAAAAAAAAABAAAAAAAAAAAAAQAAAAAAAQAAAAAAAAAAAAAAAAAAAQAAAAAAAQAAAAD9AAUBAAAAAAAAAAAAAQAAAAAAAAAAAQAAAAAAAAAAAAAABAEAAAAAAQAAAAABAAAAAAAAAAABAAAAAAEBAAAAAAABAAEAAAAAAAEAAAAAAAAAAQAAAAABAgEAABcAAAACAAAAAAACAAAAAO8AFQAAAAEAAAAAAAABAAAAAAEAAAAAAAAAAAAAAAAAAAAAAAAAAgAAAAAAAAAAAAAAAAAAAAAAAAMAAAAAAAAAAAEAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIAAAAAAAQAAAAAAAAAAAACAQABUAAAAOkAAAAAEgANAAANAAACDw3mAQIPD+0BAocC+wAAALwAAH8AAAAAnwACAisAAQCCAAEA+wMBAE0CA30BAAAA8AIDAAIAAID7AQIAKwEBAPsBAwD7AgQAvAICaAMAAACfAgIEZALqAG8JBAC8Bwb+BQAAAJ8HAwIOB+UATQgGugYAAACHBwEIKwACAKkIAABlAB0ATQkHTwcAAAArCQIAqQgBAGUAGAD7CgUATQsHTwcAAACHCQoLDgkKAE0KAPEIAAAATQsHTwcAAACHCQoLRwkCAAAAAICpCAABqQgBAGUACQBNCgAyCQAAAE0LB08HAAAAhwkKC0cJAgAAAACAqQgAAakIAQBNCwAWAgAAAE0MBroGAAAAhwoLDCsKBQBNCwAOCgAAAE0MBroGAAAAhwoLDEcKAgAAAACAqQkAAakJAQBNCwcjCwAAALssCwKkCg0AAADAQJ8KAgLwChYADgAAgE0LByMLAAAA+wwGAMYNAADGDgAAZAwGAE0REJQPAAAAmhEDAAsAAABSCg8AZQADAG4M+f8CAAAAxgoAAA4KBQBNDAA5EAAAAIcLDAoOCwEAqQkBAKkKAQBNDAAnEQAAAE0LDPcSAAAATQwGugYAAADxCwsADAAAAE0MACcRAAAATQsMFgIAAABNDAa6BgAAAPELAgAMAAAAqQoAAakKAQBNDAasEwAAAE0LDMMUAAAADggDAE0MBroGAAAAKwwBAG8MFQAwDAv1FgAAAE0MBqwTAAAATQsMIwsAAABWDQkA5wwNCDAMC4AXAAAATQwGrBMAAABNCwwOGAAAAOcMCggwDAuAFwAAAE0MBqwTAAAATQsMhBkAAABSDAkADgwDAFYMCgAODAEAUgwIADAMC4AXAAAATQwGrBMAAABNCwysGgAAAFYMCAAwDAuAFwAAAE0MBqwTAAAATQsMrhsAAAAOCAcApAweAAB0wIGMDQEAjA4BAIwPAQCfDAQCKwwDAKQMHgAAdMCBnwwBAjAMCwAfAAAATQ0GrBMAAABNDA0jCwAAAE0LDMMUAAAATQ0HIwsAAAC7LA0CpAwNAAAAwECfDAIC8AwJAA4AAID7DgcATQ0O9RYAAABNDA2bIAAAADAMC3MhAAAAZQAwAPsMCABSDgAATQ8HIwsAAAC8DAzvIgAAAJ8MBAL7DQgATQ8HIwsAAAC8DQ0CIwAAAJ8NAwJgDAkADQAAAPsOBwBNDQ6kJAAAAE0MDW8lAAAAMAwLcyEAAABlABkATQ0HIwsAAABNDA0RJgAAAPAMDAAnAACA+w0JAE0PByMLAAAATQ4PCScAAACHDA0OTQ0MpCQAAAAwDQtzIQAAAGUACACkDB4AAHTAgYwNAQCMDgEAjA8BAJ8MBAIwDAtzIQAAAG4CFf8CAAAA+wIKAA4CAwD7AgsA+wMKAJ8CAgH7AgwAnwIBAYIAAQAoAw4DIAMUA04DagNQAwkDAwMEAwUDHwMMAxEEAADAQAMSAwEDOgM7AzwDEAMjA2sDJAM3A2wDPQM+AzgDNQM2BAB0wIEDbQMwAzEDTAMTAzQDTQMyAzMA5QJuAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAGYBAAAAAAAAAAAAAAAAAAABAAAAAQAAAAMAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgAAAAAAAAAAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAOf+//8BAAAAAAAAAAEAAAAAAAAAAAAAAAEAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAFAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABAAAAAAAAANr+//8AAAAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAD+////AAAAAAUAAAAiAQAAAAAAAAAAAAAAAAAAAAAAAAEAAAAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAAAAAAAAgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADf////AAAAACcAAAAAAAAAAQAAAAAAAAAAAAAAAwAAAAAAAAABAAAAAAkAAgAAAB/7AwAATQIDrAAAAABNAQIjAQAAAE0AAcMCAAAApAEFAAAQMID7CAAATQcIrAAAAABNBgcjAQAAAE0FBsMCAAAATQQFoQYAAABNAwR5BwAAAPsGAQBNBQYrCAAAAE0EBYQJAAAA7AIDBIwDHgCfAQMCMAEALwoAAACCAAEACwMQAwwDIwMpAyoEABAwgAMrAywDLQMuAy8AugMAARgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABuwEAAAATAhQAAAcEAAAFAoMPzAL7AgAAvAICfwAAAACfAgICKwIBAIIAAQD7AwEAUgQAAFIFAQCfAwMCUgQDAMYFAADGBgAAZASgAPsJAgC8CQl/AAAAAJ8JAgJNCgi6AQAAADAKCboBAAAATQsJrAIAAABNCguuAwAAAE0LCKkEAAAAMAsKqQQAAAAwBwkABQAAAPUKBgcwCgkNBwAAAPsKAwAwCgkkCAAAAE0LCCMJAAAAuywLAqQKCwAAAKBAnwoCAvAKNAAMAACATQwJrAIAAABNCwwjCQAAAE0KC2INAAAApAsQAAA84ICfCwECMAsKvhEAAABNDAmsAgAAAE0LDCMJAAAATQoLrgMAAACpCwAAMAsKgBIAAABNDAmsAgAAAE0LDCMJAAAATQoLwxMAAABvDBQA+w8EAE0ODzgVAAAA+xEFAE0SCCMJAAAAhxAREpAPEBa8DAyNFwAAAJ8MBAJSCwwAMAsK9RgAAAD7CgYATQsJrAIAAAD7DgcATQ0OrAIAAABNDA1uGQAAAJ8KAwFlAEcA+woIAE0MCCMJAAAAvAoKAhoAAACfCgMCTQ0JrAIAAABNDA0jCQAAAE0LDK4DAAAAqQwBADAMC4ASAAAATQ0JrAIAAABNDA0jCQAAAE0LDMMTAAAA+wwJAFINCgBvDhsAnwwDAjAMC/UYAAAATQ0JrAIAAABNDA0jCQAAAE0LDGINAAAApAwQAAA84ICMDQAAjA4SAJ8MAwIwDAu+EQAAAG8NCQD7DgoATRAIIwkAAAC8Dg6eHAAAAJ8OAwC8CwkuHQAAAJ8LAAH7CwgATQ8JrAIAAABNDg8jCQAAAE0NDq4DAAAATQ4IIwkAAAC8CwshHgAAAJ8LBAH7CwYATQwJrAIAAAD7DwcATQ4PrAIAAABNDQ46HwAAAJ8LAwGkCiIAAIQAgtkLAAASAAkAEgILAJ8KAgFuBF//AgAAAPABBgAjAACATQUCJyQAAABNBAUWIwAAACsEBABNBQInJAAAAE0EBfclAAAA+wYMAIcFBgQrBQIA+wYNAIcFBgQOBTIApAYiAACEAIL7Bw4A4ggnADAECLoBAAAATQkFIwkAAAAwCQgjCQAAAE0JBakEAAAAMAkIqQQAAAArAgIAqQkAAGUAHQBNCgVPKAAAACsKAgCpCQEAZQAYAPsLDwBNDAVPKAAAAIcKCwwOCgoATQsC8SkAAABNDAVPKAAAAIcKCwxHCgIAAAAAgKkJAAGpCQEAZQAJAE0LAjIqAAAATQwFTygAAACHCgsMRwoCAAAAAICpCQABqQkBADAJCNYmAAAAnwYDAWUABwATBgMADgYFAKQGIgAAhACC+wcOABMIAwCfBgMB+wcQAE0GB6IrAAAAvAYGaCwAAACfBgIEZAYYAG8NLQC8Cwr+LgAAAJ8LAwIOCxMA+wsGAE0MCqwCAAAATQ4KugEAAACaDgcAAQAAAPsPBwBNDg+sAgAAAE0NDtIvAAAAKw0FAPsPBwBNDg+sAgAAAE0NDrkwAAAAnwsDAW4G5/8CAAAA+wgQAE0HCLoxAAAATQYHwxMAAAAwAQb1GAAAAPsJEABNCAm6MQAAAE0HCMMTAAAATQYHAjIAAAAwAQb1GAAAAPsIEABNBwi6MQAAAE0GB64DAAAA8AEHADMAAID7CQ0ATQgJ2zQAAABNBwipBAAAACsHBQD7CQwATQgJ0zUAAABNBwipBAAAADAHBqkEAAAA+wYRADABBn02AAAA3gASAPsGAgC8BgY1NwAAAJ8GAgGkBiIAAIQAgvsHEwCfBgIBggABADgDDgMJAxADOAMLA1ICAAAAAAAAWUADbwNwAwwDEQQAAKBAAxIDcQNyAzYEADzggANzAzcDIwNHA0gDSQNDAyQDSgMTAgAAAACAhC5BA3QDdQM5A1EDZgNnBACEAIIDFAM7AzwDDQUEAQkEJgMDAwQDBQMhA04DTwNQA3YDdwN4A3kDHwN6A3sDIAN8AQucA30BAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAnQEAAAAAAAAAAAAAAAAAAAEAAAABAAAAAwAAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAABAAAAAAAAAAAAAAABAAAAAAAAAAAAAAACAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA6f///wAAAAAcAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAAAAAAAAQAAAAEAAAAAAAAAAAAAAAAAAAABAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAAAAlP7//wEAAAAAAAAAAQAAAAAAAAAAAAAAAQAAAAAAAAABAAAAAAAAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABmAQAAAAAAAPz///8AAAAABgAAAAAAAAABAAAAAAAAAAAAAAAAAAAAAAAAAAMAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD+////AAAAAAgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAD+////AAAAAAQAAAAAAAAAAAAAAAEAAAABAAAAAAAAAAAAAAAAAAAAAgAAAAAAAAAAAAAAAAAAAAEAAAAAAwEDAAAGAwAABQEBC/sBAADxAQgAAAAAAN4AAAD7AQEAvAEBSwAAAACfAQIB+wECAJ8BAQGCAAEAAQMdAOIDfgEYAAAAAQEAAAABAALjAQAAAAQAAwAAAAf7AAAA+wEBAPsDAgBNAgO6AAAAAJ8AAwGCAAEAAQMJAPQDAAEYAAAAAAAAAfUBAAAABAECAAAADA4ACgBNAQAbAAAAAA4BBwD7AQAA+wMBAE0CAyMBAAAATQMAGwAAAABqAwECggABAAIDfwMMAP0DAAEYAAAAAAEAAAAAAAAC/gEAAAAIAQEAAAARbwIAAFIEAAD7BwAATQYHfQEAAADwBgMAAgAAgG8FAwBlAAMA+wYAAE0FBn0BAAAAvAICjQQAAACfAgQCUgECAIIBAgAFA4ABAyADHwM8A0MAnAQAARgAAAAAAAAAAAAAAAAAAAAAAB0CAAAACwAOAAAAogH7AAAAvAAAfwAAAACfAAICKwABAIIAAQD7AwEATQIDwwEAAABNAQL1AgAAAPsDAgCHAgMBKwICAPsDAwCHAgMBKwIBAIIAAQBNBAIjAwAAALssBAKkAwUAAABAQJ8DAgLwAyIABgAAgE0EAiMDAAAA+wUEAMYGAADGBwAAZAUGAE0KCZQHAAAAmgoDAAQAAABSAwgAZQADAG4F+f8CAAAAxgMAAA4DQwBNBQA5CAAAAIcEBQMrBD8A+wQFALwEBJgJAAAAnwQCAfsEBgD7BgcATQcCIwMAAAC8BATjCgAAAJ8EBACCBAAAZQAyAPsHAQBNBgcCCwAAAE0FBqwMAAAATQQFwwEAAABNAwT1AgAAAPADKAANAACA+wMIAFIFAABNBgIjAwAAALwDA+8OAAAAnwMEAvsECABNBgIjAwAAALwEBAIPAAAAnwQDAmADGQAEAAAA+wQJAE0DBBgQAAAAUgQAAE0FAiMDAAAAwAYRABICCgCfAwQC+wUKAE0EBX0SAAAA8AQFABMAAIBvBhQAvAQDvRUAAACfBAMB+wQLALwFA08WAAAAnwUCAJ8EAACCBAAA+wcBAE0GBwILAAAATQUGrAwAAABNBAXDAQAAAE0DBPUCAAAA8AMXAA0AAICkAxkAAGBwgYwEAAD7BQwAbwYaAJ8DBAGkAxkAAGBwgW8EGwD7BQwAbwYaAJ8DBAH7AwwAbwQcAJ8DAgH7Aw0AbwUdAFIGAQC8AwNrHgAAAJ8DBAGCAAEA+wQCAIcDBAEOAwcA+wMNAG8FHwBSBgEAvAMDax4AAACfAwQBggABAPsEAwCHAwQBDgMGAPsDDQBvBSAAUgYBALwDA2seAAAAnwMEAYIAAQAhAw4DIwMkAwwDEQQAAEBAAxIDAQM6A4EBA4IBAyUDEANLA0wDEwODAQYQAyADFAMYA4QBA4UBA2YDhgEEAGBwgQOHAQKSJEmSJEnCPwOIAQOJAQOKAQOLAQOMAQEQiAQAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAJAgAAAAAAAAAAAAAAAAAAAQAAAAEAAAADAAAAAAAAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAAAAAAAAQAAAAEAAAADAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEAAAAAAAAAO/7//wAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAABAAAAAAAAAP7///8AAAAABQAAAMEBAAAAAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAwAAAAAAAAAAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAAAAAgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACAAAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIAAAAAAgABAAAABfsAAAC8AABjAAAAAJ8AAgGCAAEAAQONAQC1BAABGAAAAAABNgIAAAACAAEAAAAE+wAAAG8BAACfAAIBggABAAEDjgEAugQAARgAAAABOwIAAABGAAABAADGBKMAAACkAAEAAAAAQG8CAgC8AAAWAwAAAJ8AAwKkAQEAAAAAQG8DBAC8AQEWAwAAAJ8BAwKkAgEAAAAAQG8EBQC8AgIWAwAAAJ8CAwKkAwEAAAAAQG8FBgC8AwMWAwAAAJ8DAwKkBAEAAAAAQG8GBwC8BAQWAwAAAJ8EAwKkBQkAAACAQE0HARIKAAAATQYH7wsAAACfBQICpAYJAAAAgEBNCQESCgAAAE0ICcYMAAAATQcIDg0AAACfBgICpAcJAAAAgEBNCgESCgAAAE0JCsYMAAAATQgJFg4AAACfBwICpAgJAAAAgEBNDAESCgAAAE0LDBwPAAAATQoLGBAAAABNCQpCEQAAAJ8IAgKkCQkAAACAQE0NAU0SAAAATQwNHA8AAABNCwxDEwAAAE0KC2gUAAAAnwkCAqQKCQAAAIBATQ4BTRIAAABNDQ4fFQAAAE0MDaEWAAAATQsM1xcAAACfCgICpAsJAAAAgEBNDQESCgAAAE0MDXgYAAAAnwsCAqQMCQAAAIBATQ8BEgoAAABNDg/GDAAAAE0NDgkZAAAAnwwCAqQNCQAAAIBATRIBEgoAAABNERIcDwAAAE0QEbUaAAAATQ8QoRsAAABNDg/GHAAAAJ8NAgKkDgkAAACAQE0TAU0SAAAATRITHA8AAABNERK1GgAAAE0QER8VAAAATQ8QPh0AAACfDgICpA8JAAAAgEBNEwFNEgAAAE0SEx8VAAAATRESoRYAAABNEBHsHgAAAJ8PAgKkEAkAAACAQE0UARIKAAAATRMUHA8AAABNEhNSHwAAAE0REvYgAAAAnxACAqQRCQAAAIBATRQBTRIAAABNExQfFQAAAE0SE5UhAAAAnxECAqQSCQAAAIBATRYBEgoAAABNFRahFgAAAE0UFSEiAAAATRMU0CMAAACfEgICpBMJAAAAgEBNFwESCgAAAE0WFxwPAAAATRUWGBAAAABNFBV2JAAAAJ8TAgKkFAkAAACAQE0YAU0SAAAATRcYHxUAAABNFhehFgAAAE0VFpolAAAAnxQCAqQVCQAAAIBATRkBEgoAAABNGBmhFgAAAE0XGCEiAAAATRYXUCYAAACfFQICpBYJAAAAgEBNGgFNEgAAAE0ZGh8VAAAATRgZoRYAAABNFxiNJwAAAJ8WAgKkFwkAAACAQE0aARIKAAAATRkaoRYAAABNGBl8KAAAAJ8XAgKkGAkAAACAQE0bARIKAAAATRobxgwAAABNGRrYKQAAAJ8YAgKkGQkAAACAQE0cARIKAAAATRscoRYAAABNGhvRKgAAAJ8ZAgKkGgkAAACAQE0dAU0SAAAATRwdHxUAAABNGxx9KwAAAJ8aAgKkGwkAAACAQE0fARIKAAAATR4fxgwAAABNHR67LAAAAE0cHUYtAAAAnxsCAqQcCQAAAIBATSABEgoAAABNHyAcDwAAAE0eH7UaAAAATR0emS4AAACfHAICpB0JAAAAgEBNHwESCgAAAE0eHwcvAAAAnx0CAqQeCQAAAIBATSIBTRIAAABNISIfFQAAAE0gIaEWAAAATR8gtDAAAACfHgICpB8JAAAAgEBNIwFNEgAAAE0iIx8VAAAATSEiRDEAAABNICHqMgAAAJ8fAgKkIAkAAACAQE0jARIKAAAATSIjxgwAAABNISI8MwAAAJ8gAgKkIQkAAACAQE0lAU0SAAAATSQlHxUAAABNIyShFgAAAE0iIyw0AAAAnyECAk0iADE1AAAATSQimTYAAABNIyR6NwAAAE0lIyU4AAAATSQlnTkAAABNJyQ4OgAAAE0mJyw7AAAATSUm6zwAAABNJiRtPQAAAE0nJfI+AAAAxigAADAoJyQ/AAAA4ihBAG8pDQAwKSh9QAAAAMYpAADGKgAAxisAAKksAAD/LQAAAAAAAMAuQgASACAAwC9DABIAGADAMEQAEgAYAE0xCO9FAAAA2TIDABIAJwASAA8AEgAHABIABgASASv/EgAJABIAGACfMQICwDJGABIACQASAAcAEgAGABIAGAASADAAEgASANkzBQASASz/EgAJABIAFAASACgAEgAkABIAJgASACUA2SsGABIACQASACYAEgALABIADAASAA0AEgASABIAIAASACgAEgAHABIABgASACQAEgAZABIAHgASAAoAEgAdABIALQASACUAEgAEABIAIwASASr/EgAzANk0BwASAAkAEgAoABIABwASAAYAEgAlABIAGAASACAAEgALABIAEgASAAwAEgEq/xIBK/8SADMA2TUIABIACQASADIAEgAxABIAJQASAB0AEgAtABIACgASAAsAEgASABIADQASAAIAEgAjABIABwASAAYAEgEr/xIAGAASACQAEgAoABIBKf8SADQA2TYJABIBLP8SABQAEgA0AP83AAAEAAAAbzhHAG85DQBvOg4AbztIAMU3OAUBAAAAvDgXX0kAAACfOAIEZDgHAJ40NwU8AAAAUj43AFI/PACkPUwAACyhhJ89AwFuOPj/AgAAAFI4FgBvOTgAUjo3AFI7NACfOAQBTTgkok0AAAC8ODhoTgAAAJ84AgRkOA0Abz85ALw9PP5PAAAAnz0DAg49CABSPQ8ATT48rFAAAADZPwoAEgA1ABIBKf8SADwAnz0DAW448v8CAAAA/zgAAAIAAABSOwcAUjwGAMU4OwMBAAAAxjkAAMY6AABkOBYAUj08AMY+AADGPwAAZD0QAE1DQSNRAAAAuyxDAqRCUwAAACBFn0ICAvBCCQBUAACATURBI1EAAADZRQsAEgAtABIAQQC8Qhz2VQAAAJ9CBAFuPe//AgAAAG446f8CAAAAUjgOAFI5JQBNOiXZVgAAAJ84AwFSOA8ATTomAlcAAABNOTqsUAAAAMA6WAASAAkAEgAmABIABwASAAYAEgAgABIAHwASAAMAEgAiABIAEgASABsAEgAoABIAGgASACEAEgAQAJ84AwFSOAoATTkkY1kAAABNOwusUAAAAE06O29aAAAAnzgDAVI4DwBNOSRjWQAAAMA6WwASABEAnzgDAW86OADAO1wAEgAhALw4EapdAAAAnzgEATA1KHZeAAAAMDYoW18AAADBKQAAgigCAGADjwEEAAAAQAOQAQORAQOSAQOTAQOUAQOVAQOWAQQAAIBAA5cBA5gBA5kBAx8DFAOaAQObAQOcAQOdAQOeAQOfAQOgAQOhAQOiAQOjAQMzA6QBA6UBA6YBA6cBA6gBA6kBA6oBA6sBA6wBA60BA64BA68BA7ABA7EBA7IBA7MBA7QBA7UBA7YBA7cBA7gBA7kBA7oBA7sBA7wBA70BA74BA78BA8ABA8EBAxwDTwPCAQPDAQPEAQPFAQPGAQNwAyAFAUAGAAYBBgIDNgYGAzsDOgPHAQMVAxYEACyhhAMhA04DUAMQAwwDEQQAACBFAxIDyAEDWQMlBhEDjQEDTQYSBhMDyQEDfQN+DwABAgQGBwkKDA0ODxESEwEAAQUAAgAAAAAAAQAAAAAAAQAAAAAAAQAAAAAAAQAAAAAAAvgAAAAAAAEAAAAAAAAAAAEAAAAAAAAAAAEAAAAAAAAA/QAAAQAAAAAAAAAAAAABAAAAAAAAAAAAAAEAAAAAAAD9AAAAAAAAAAABAAAAAAAAAAAAAAAAAQAAAAAAAAAAAP4AAAEAAAAAAAAAAAAAAQAAAAAAAAAAAAABAAAAAAAA/QABAAAAAAAAAAAAAAEAAAAAAAAAAAAAAQAAAAAAAAD9AAABAAAAAAAAAAAAAAEAAAAAAAAAAAAAAQAAAAAAAP0AAQAAAAAAAAAAAQAAAAAAAAAAAQAAAAAAAAAAAQAA/AAAAAAAAAABAAAAAAAAAAAAAAEAAAAAAAABAAAAAAD9AAAAAAEAAAAAAAAAAAAAAQAAAAAAAAAAAQAAAAAAAP0AAAADAAEAAAABAAAAAgAAAAAAAQACAAEAABEBAAAD4AMBAgADAAkACwARAAAAAAAAAAAAABQAAAAAAABCAAB8AAAAACQAAAAAAAAAAAAAAAAAAAAAAAAAAAB3AAAAAGUAAAAAAAAAADcAAAAAAAAAAAAAAAAAAAAAAAAAAEYAgwAJAAAAAAAAAAEAAAABAAAAAAAA/wADAAAAAAMAAADwAAEAAAAAAQAAAAAAAAD+AAgAAAAAAAAAAAEAAAABAPgAAAAAAAEAAAAAAAAA/gD/AA0AAAAAAQAAAAAAAAAA8gAAAAAAAAAAAAAALAAAAAAAAAABAAAAAAAFAAAAAADOAAEAAgABAAAACAAAAAMAAAAEAAAAAgAAAAMAAAADAAAAAwAAAAQAAAADAAAAAwAAACEAAACEAAAAmwAAAH0AAAAQAAAACAAAAA4AAAA2AAAAABS+5j29qe8UJ4wiVynO7y/5YvA6hT3j4/DtDJDnvpE0ryyupEWFRA+T

local v1 = game:GetService("Players")
local v2 = game:GetService("ReplicatedStorage")
local u3 = game:GetService("HttpService")
local u4 = game:GetService("MarketplaceService")
local u5 = game:GetService("TweenService")
require(v2.Shared.Types)
local u6 = require(v2.Shared.Data.Flavors)
local u7 = require(v2.Shared.Data.Gum)
local v8 = require(v2.Shared.Framework.Classes.Pool)
local u9 = require(v2.Client.Framework.Services.LocalData)
local u10 = require(v2.Client.Gui.Utils.AutoButtonColor)
local u11 = require(v2.Shared.Palette)
local u12 = require(v2.Shared.Data.Currency)
local u13 = require(v2.Shared.Framework.Utilities.String.FormatSuffix)
local v14 = require(v2.Client.Framework.Utilities.Gui.HookScrollingFrame)
local u15 = require(v2.Client.Gui.Utils.ClickableButton)
local u16 = require(v2.Shared.Framework.Network.Remote)
local u17 = require(v2.Client.Gui.GuiFrame)
local u18 = require(v2.Shared.Utils.Stats.ItemUtil)
require(v2.Shared.Framework.Classes.Maid)
local u19 = require(v2.Client.Gui.Utils.GuiArrow)
require(v2.Shared.Utils.Stats.QuestUtil)
local v20 = require(v2.Client.Gui.Utils.UpdateWhileGuiOpen)
local v21 = require(v2.Shared.Utils.CurrencyUtil)
local u22 = require(v2.Shared.Data.Worlds)
local u23 = require(v2.Shared.Utils.RichText)
local u24 = require(v2.Client.Gui.Prompt)
local u25 = require(v2.Shared.Data.Builders.PromptBuilder)
local v26 = require(v2.Shared.Framework.Utilities.ProductInfo)
local u27 = require(v2.Shared.Constants)
local u28 = require(v2.Client.Gui.Utils.Shiny)
local u29 = require(v2.Client.Gui.Animations.ProcessingPurchase)
local u30 = require(v2.Shared.Data.Gamepasses)
local u31 = require(v2.Client.Gui.Utils.PlayLocalSound)
local u32 = v1.LocalPlayer
local u33 = u32.PlayerGui.ScreenGui
local u34 = u33.GumShop.Frame
local u35 = u34.Items.Inner.List
local u36 = u34.Selected
local u37 = u35.Template
u37.Parent = nil
local u38 = {
    ["Kind"] = "Flavors"
}
local u39 = nil
local u40 = nil
local u41 = nil
local u42 = false
local u43 = {}
local function u48(p44) --[[Anonymous function at line 99]]
    --[[
    Upvalues:
        [1] = u22
    --]]
    if not p44 then
        return 0
    end
    for v45, v46 in u22 do
        if v45 == p44 then
            return v46.Order
        end
        for _, v47 in v46.Islands do
            if v47.Name == p44 then
                return v46.Order
            end
        end
    end
    return 0
end
local u55 = v8.new(function() --[[Anonymous function at line 116]]
    --[[
    Upvalues:
        [1] = u37
        [2] = u15
        [3] = u7
        [4] = u6
        [5] = u41
        [6] = u9
        [7] = u22
    --]]
    local u49 = u37:Clone()
    u15(u49.Button, function() --[[Anonymous function at line 119]]
        --[[
        Upvalues:
            [1] = u7
            [2] = u49
            [3] = u6
            [4] = u41
            [5] = u9
            [6] = u22
        --]]
        local v50 = u7[u49.Name] or u6[u49.Name]
        if v50 then
            local v51 = u41
            local v52 = {
                ["Name"] = u49.Name,
                ["Image"] = v50.Image,
                ["Cost"] = v50.Cost
            }
            local v53 = u9:Get()
            local v54
            if v53 then
                if v50.Area then
                    if u22[v50.Area] then
                        v54 = v53.WorldsUnlocked[v50.Area] ~= nil
                    else
                        v54 = v53.AreasUnlocked[v50.Area] ~= nil
                    end
                else
                    v54 = true
                end
            else
                v54 = false
            end
            v52.Unlocked = v54
            v51(v52)
        end
    end)
    return u49
end)
local function u80(_, p56) --[[Anonymous function at line 136]]
    --[[
    Upvalues:
        [1] = u9
        [2] = u7
        [3] = u6
        [4] = u22
        [5] = u48
        [6] = u18
    --]]
    local v57 = u9:Get()
    local u58 = p56 == "Gum" and u7 or u6
    local v59 = {}
    for v60, v61 in u58 do
        local v62 = v61.Cost
        if typeof(v62) ~= "number" then
            local v63 = {
                ["Name"] = v60,
                ["Cost"] = v61.Cost,
                ["Image"] = v61.Image
            }
            local v64
            if v57 then
                if v61.Area then
                    if u22[v61.Area] then
                        v64 = v57.WorldsUnlocked[v61.Area] ~= nil
                    else
                        v64 = v57.AreasUnlocked[v61.Area] ~= nil
                    end
                else
                    v64 = true
                end
            else
                v64 = false
            end
            v63.Unlocked = v64
            table.insert(v59, v63)
        end
    end
    table.sort(v59, function(p65, p66) --[[Anonymous function at line 153]]
        --[[
        Upvalues:
            [1] = u48
            [2] = u58
            [3] = u18
        --]]
        local v67 = u48(u58[p65.Name].Area)
        local v68 = u48(u58[p66.Name].Area)
        if v67 ~= v68 then
            return v67 < v68
        end
        local v69 = p65.Cost
        local v70 = typeof(v69) == "number"
        local v71 = p66.Cost
        if v70 ~= (typeof(v71) == "number") then
            return v70
        end
        local v72 = p65.Cost
        if typeof(v72) ~= "number" then
            local v73 = p66.Cost
            if typeof(v73) ~= "number" then
                return u18:GetAmount(p65.Cost) < u18:GetAmount(p66.Cost)
            end
        end
        return p65.Cost < p66.Cost
    end)
    if p56 ~= "Gum" then
        local v74 = u6["VIP Flavor"]
        local v75 = {
            ["Name"] = "VIP Flavor",
            ["Cost"] = v74.Cost,
            ["Image"] = v74.Image,
            ["Unlocked"] = true
        }
        table.insert(v59, 3, v75)
        return v59
    end
    local v76 = u7["Infinity Gum"]
    local v77 = {
        ["Name"] = "Infinity Gum",
        ["Cost"] = v76.Cost,
        ["Image"] = v76.Image,
        ["Unlocked"] = true
    }
    table.insert(v59, 7, v77)
    local v78 = u7["VIP Gum"]
    local v79 = {
        ["Name"] = "VIP Gum",
        ["Cost"] = v78.Cost,
        ["Image"] = v78.Image,
        ["Unlocked"] = true
    }
    table.insert(v59, 3, v79)
    return v59
end
local function u84() --[[Anonymous function at line 202]]
    --[[
    Upvalues:
        [1] = u42
        [2] = u9
        [3] = u19
        [4] = u38
        [5] = u34
        [6] = u36
        [7] = u35
    --]]
    if u42 then
        local v81 = u9:Get()
        if v81 then
            u19:ClearAll("GumShop")
            if v81.Flavors.Blueberry then
                if not v81.Gum["Stretchy Gum"] then
                    if u38.Kind ~= "Gum" then
                        u19:Add(u34.Tray.Gum, nil, "GumShop")
                        return
                    end
                    if u36.Label.Text == "Stretchy Gum" then
                        u19:Add(u36.Action, nil, "GumShop")
                        return
                    end
                    local v82 = u35:FindFirstChild("Stretchy Gum")
                    if v82 then
                        u19:Add(v82, 155, "GumShop")
                    end
                end
            else
                if u38.Kind ~= "Flavors" then
                    u19:Add(u34.Tray.Flavors, nil, "GumShop")
                    return
                end
                if u36.Label.Text == "Blueberry" then
                    u19:Add(u36.Action, nil, "GumShop")
                    return
                end
                local v83 = u35:FindFirstChild("Blueberry")
                if v83 then
                    u19:Add(v83, 155, "GumShop")
                    return
                end
            end
        end
    else
        return
    end
end
u41 = function(p85) --[[Function name: setSelection, line 238]]
    --[[
    Upvalues:
        [1] = u9
        [2] = u36
        [3] = u11
        [4] = u12
        [5] = u13
        [6] = u18
        [7] = u30
        [8] = u38
        [9] = u7
        [10] = u6
        [11] = u34
        [12] = u23
        [13] = u28
        [14] = u10
        [15] = u27
        [16] = u43
        [17] = u35
        [18] = u5
        [19] = u33
        [20] = u40
        [21] = u84
    --]]
    local v86 = u9:Get()
    if not v86 then
        return
    end
    local v87 = p85.Cost
    if typeof(v87) == "number" then
        u36.Cost.Label.TextColor3 = u11.Text.Green
    elseif p85.Cost.Type == "Currency" then
        local v88 = u12[p85.Cost.Currency]
        u36.Cost.Label.TextColor3 = v88.Color
    else
        u36.Cost.Label.TextColor3 = Color3.new(1, 1, 1)
    end
    local v89 = p85.Cost
    if typeof(v89) == "number" then
        u36.Cost.Visible = false
    else
        u36.Cost.Visible = true
        u36.Cost.Label.Text = u13(u18:GetAmount(p85.Cost), 1000000)
        u18:UpdateIcon(u36.Cost.Icon, p85.Cost)
    end
    u36.Icon.Image = p85.Image
    u36.Label.Text = p85.Name
    local v90 = (v86.Gum[p85.Name] or v86.Flavors[p85.Name]) ~= nil
    local v91 = p85.Cost
    if typeof(v91) == "number" then
        local v92 = p85.Cost
        for v95, v94 in u30 do
            if v94.Id == v92 then
                goto l21
            end
        end
        local v95 = nil
        ::l21::
        if v95 and v86.Passes[v95] then
            v90 = true
        end
    end
    local v96 = v86.Bubble.Gum == p85.Name and true or v86.Bubble.Flavor == p85.Name
    u36.Cost.Visible = not v90
    local v97 = u36.Owned
    local v98
    if v90 then
        v98 = not v96
    else
        v98 = v90
    end
    v97.Visible = v98
    u36.Action.Button.Visible = not (v96 and v90)
    local v99 = (u38.Kind == "Gum" and u7 or u6)[p85.Name]
    u34.Locked.Label.Text = ("Unlock this in %*"):format((u23.autoColor(v99.Area or "None", u11.Text.Yellow)))
    u34.Locked.Visible = not p85.Unlocked
    local v100 = p85.Cost
    if typeof(v100) ~= "number" then
        if v90 then
            if not v96 then
                u36.Action.Button.Label.Text = "Equip"
                u28:Remove(u36.Action.Button)
                u10(u36.Action.Button, u11.Button.Pink)
            end
        else
            u28:Remove(u36.Action.Button)
            u36.Action.Button.Label.Text = "Buy"
            u10(u36.Action.Button, u18:GetOwnedAmount(v86, p85.Cost) < u18:GetAmount(p85.Cost) and u11.Button.Red or u11.Button.Green)
        end
        goto l49
    end
    local v101 = p85.Cost
    for v113, v103 in u30 do
        if v103.Id == v101 then
            ::l41::
            if v113 and v86.Passes[v113] == true and true or false then
                u28:Remove(u36.Action.Button)
                u36.Action.Button.Label.Text = "Equip"
                u10(u36.Action.Button, u11.Button.Pink)
            else
                u28:Add(u36.Action.Button)
                u36.Action.Button.Label.Text = ("%*%*"):format(u27.RobuxUnicode, u43[p85.Cost] or "__")
                u10(u36.Action.Button, u11.Button.Orange)
            end
            u36.Cost.Visible = false
            ::l49::
            local v104 = 1
            for _, v105 in u35:GetChildren() do
                if v105:IsA("Frame") then
                    local v106 = u7[v105.Name] or u6[v105.Name]
                    local v107 = u11.Button.Default
                    local v108 = false
                    if v105.Name == p85.Name then
                        v104 = v105.LayoutOrder
                        v107 = u11.Button.Green
                    else
                        local v109 = v106.Cost
                        if typeof(v109) == "number" then
                            v107 = u11.Button.Orange
                            v108 = true
                        end
                    end
                    if v108 then
                        u28:Add(v105.Button)
                    else
                        u28:Remove(v105.Button)
                    end
                    u10(v105.Button, v107)
                end
            end
            if p85.Name == "Infinity Gum" then
                u36.Stat.Text = "Infinite Storage!"
            elseif u38.Kind == "Gum" then
                u36.Stat.Text = ("%* Storage"):format((u13(u7[p85.Name].Storage, 500000)))
            else
                u36.Stat.Text = ("+%* Bubbles"):format((u13(u6[p85.Name].Bubbles, 500000)))
            end
            local v110 = u35.UIGridLayout.CellSize.X.Offset
            local v111 = (v104 - 1) / 3
            local v112 = v110 * math.floor(v111) - v110 / 2
            u5:Create(u35, TweenInfo.new(0.3, Enum.EasingStyle.Quint), {
                ["CanvasPosition"] = Vector2.new(0, v112 * u33.UIScale.Scale)
            }):Play()
            task.defer(function() --[[Anonymous function at line 346]]
                --[[
                Upvalues:
                    [1] = u36
                    [2] = u33
                --]]
                u36.Cost.Label.Size = UDim2.fromOffset(u36.Cost.Label.TextBounds.X / u33.UIScale.Scale, 50)
            end)
            u36.CostTitle.Visible = u36.Cost.Visible
            u40 = p85
            u84()
            return
        end
    end
    local v113 = nil
    goto l41
end
local function u129() --[[Anonymous function at line 357]]
    --[[
    Upvalues:
        [1] = u9
        [2] = u38
        [3] = u7
        [4] = u6
        [5] = u35
        [6] = u22
        [7] = u30
        [8] = u11
        [9] = u18
        [10] = u12
        [11] = u40
        [12] = u41
        [13] = u84
    --]]
    local v114 = u9:Get()
    if not v114 then
        return
    end
    local v115 = u38.Kind == "Gum" and u7 or u6
    for _, v116 in u35:GetChildren() do
        if v116:IsA("GuiObject") then
            local v117 = v115[v116.Name]
            local v118
            if v114 then
                if v117.Area then
                    if u22[v117.Area] then
                        v118 = v114.WorldsUnlocked[v117.Area] ~= nil
                    else
                        v118 = v114.AreasUnlocked[v117.Area] ~= nil
                    end
                else
                    v118 = true
                end
            else
                v118 = false
            end
            local v119 = (v114.Gum[v116.Name] or v114.Flavors[v116.Name]) ~= nil
            local v120 = v117.Cost
            if typeof(v120) == "number" then
                local v121 = v117.Cost
                for v124, v123 in u30 do
                    if v123.Id == v121 then
                        goto l31
                    end
                end
                local v124 = nil
                ::l31::
                if v124 and v114.Passes[v124] then
                    v119 = true
                end
            end
            local v125 = v114.Bubble.Flavor == v116.Name and true or v114.Bubble.Gum == v116.Name
            v116.Button.Label.Text = v118 and (v116.Name or "???") or "???"
            v116.Button.Cost.Visible = not v119 and v118
            v116.Button.Equipped.Visible = v125 and v118
            local v126 = v116.Button.Owned
            if v119 then
                v119 = not v125
                if v119 then
                    v119 = v118
                end
            end
            v126.Visible = v119
            v116.Button.Locked.Visible = not v118
            v116.Button.Icon.ImageColor3 = v118 and Color3.new(1, 1, 1) or Color3.new()
            local v127 = v116.Button.Cost.Label
            local v128 = v117.Cost
            if typeof(v128) == "number" then
                v127.TextColor3 = u11.Text.Green
            elseif u18:GetOwnedAmount(v114, v117.Cost) < u18:GetAmount(v117.Cost) then
                v127.TextColor3 = u11.Color.Red
            elseif v117.Cost.Type == "Currency" then
                v127.TextColor3 = u12[v117.Cost.Currency].Color
            else
                v127.TextColor3 = Color3.new(1, 1, 1)
            end
        end
    end
    if u40 then
        u41(u40)
    end
    u84()
end
local function u146(p130, p131) --[[Anonymous function at line 412]]
    --[[
    Upvalues:
        [1] = u9
        [2] = u80
        [3] = u55
        [4] = u35
        [5] = u27
        [6] = u43
        [7] = u10
        [8] = u11
        [9] = u18
        [10] = u13
        [11] = u3
        [12] = u33
        [13] = u7
        [14] = u6
        [15] = u41
        [16] = u22
        [17] = u34
        [18] = u38
        [19] = u39
        [20] = u129
    --]]
    local v132 = u9:Get()
    if v132 then
        local v133 = u80(p130, p131)
        for v134, v135 in v133 do
            local u136 = u55:Get()
            u136.Name = v135.Name
            u136.Button.Icon.Image = v135.Image
            u136.LayoutOrder = v134
            u136.ZIndex = 100 - v134
            u136.Parent = u35
            local v137 = v135.Cost
            if typeof(v137) == "number" then
                u136.Button.Cost.UIPadding.PaddingRight = UDim.new()
                u136.Button.Cost.Icon.Visible = false
                u136.Button.Cost.Label.Text = ("%*%*"):format(u27.RobuxUnicode, u43[v135.Cost] or "__")
                u10(u136.Button, u11.Button.Orange)
            else
                local v138 = u18:GetAmount(v135.Cost)
                u136.Button.Cost.Icon.Visible = true
                u136.Button.Cost.Label.Text = u13(v138, 1000000)
                u136.Button.Cost.UIPadding.PaddingRight = UDim.new(0, 18)
                u136:SetAttribute("Cost", u3:JSONEncode(v135.Cost))
                u18:UpdateIcon(u136.Button.Cost.Icon, v135.Cost)
                u10(u136.Button, u11.Button.Default)
            end
            task.defer(function() --[[Anonymous function at line 442]]
                --[[
                Upvalues:
                    [1] = u136
                    [2] = u33
                --]]
                u136.Button.Cost.Label.Size = UDim2.fromOffset(u136.Button.Cost.Label.TextBounds.X / u33.UIScale.Scale, 30)
            end)
        end
        local v139 = p131 == "Gum" and v132.Bubble.Gum or v132.Bubble.Flavor
        local v140 = u7[v139] or u6[v139]
        if v140 then
            local v141 = task.defer
            local v142 = u41
            local v143 = {
                ["Name"] = v139,
                ["Cost"] = v140.Cost,
                ["Image"] = v140.Image
            }
            local v144
            if v132 then
                if v140.Area then
                    if u22[v140.Area] then
                        v144 = v132.WorldsUnlocked[v140.Area] ~= nil
                    else
                        v144 = v132.AreasUnlocked[v140.Area] ~= nil
                    end
                else
                    v144 = true
                end
            else
                v144 = false
            end
            v143.Unlocked = v144
            v141(v142, v143)
        elseif v133[1] then
            task.defer(u41, v133[1])
        end
        for _, v145 in u34.Tray:GetChildren() do
            if v145:IsA("Frame") then
                u10(v145.Button, v145.Name == p131 and u11.Button.Blue or u11.Button.Inactive)
            end
        end
        u34.Title.Label.Text = p131
        u34.Title.Label.Highlight.Text = p131
        u34.Title.Icon.Image = p131 == "Flavors" and u6["Bubble Gum"].Image or u7["Basic Gum"].Image
        u38.Kind = p131
        u39 = p130
        u55:Done()
        task.defer(u129)
    end
end
local function v148(p147) --[[Anonymous function at line 482]]
    --[[
    Upvalues:
        [1] = u42
        [2] = u19
        [3] = u129
    --]]
    if u42 ~= p147 then
        u42 = p147
        u19:ClearAll()
        u129()
    end
end
local u149 = u39
local v150 = {
    "Bubble",
    "Flavors",
    "Gum",
    "Passes"
}
for _, v151 in v21:GetDataKeys() do
    table.insert(v150, v151)
end
v20("GumShop", v150, u129)
for _, u152 in u34.Tray:GetChildren() do
    if u152:IsA("Frame") then
        u15(u152.Button, function() --[[Anonymous function at line 500]]
            --[[
            Upvalues:
                [1] = u146
                [2] = u149
                [3] = u152
            --]]
            u146(u149, u152.Name)
        end)
    end
end
for _, v153 in { u7, u6 } do
    for _, u154 in v153 do
        local v155 = u154.Cost
        if typeof(v155) == "number" then
            v26:ConnectGamepassChanged(u154.Cost, function(p156) --[[Anonymous function at line 509]]
                --[[
                Upvalues:
                    [1] = u43
                    [2] = u154
                --]]
                if p156 and p156.PriceInRobux then
                    u43[u154.Cost] = p156.PriceInRobux
                end
            end)
        end
    end
end
v14(u35, u35.UIGridLayout)
u15(u36.Action.Button, function() --[[Anonymous function at line 520]]
    --[[
    Upvalues:
        [1] = u9
        [2] = u36
        [3] = u7
        [4] = u6
        [5] = u30
        [6] = u29
        [7] = u4
        [8] = u32
        [9] = u18
        [10] = u25
        [11] = u38
        [12] = u24
        [13] = u31
        [14] = u16
    --]]
    local v157 = u9:Get()
    if not v157 then
        return
    end
    local v158 = u36.Label.Text
    local v159 = u7[v158] or u6[v158]
    if not v159 then
        return
    end
    local v160 = v159.Cost
    if typeof(v160) ~= "number" then
        if u36.Action.Button.Label.Text == "Buy" and u18:GetOwnedAmount(v157, v159.Cost) < u18:GetAmount(v159.Cost) then
            local v162 = u25.fromNotEnough(v157, v159.Cost, function(p161) --[[Anonymous function at line 540]]
                --[[
                Upvalues:
                    [1] = u38
                --]]
                return ("You need %* to purchase this %*!"):format(p161, u38.Kind == "Flavors" and "Flavor" or u38.Kind)
            end)
            if u38.Kind == "Gum" then
                v162:Gamepass("Infinity Gum")
            end
            return u24(v162:Build())
        end
        goto l15
    end
    local v163 = v159.Cost
    for v166, v165 in u30 do
        if v165.Id == v163 then
            ::l12::
            if v166 and not v157.Passes[v166] then
                u29:Show()
                return u4:PromptGamePassPurchase(u32, v159.Cost)
            end
            ::l15::
            if u36.Action.Button.Label.Text == "Buy" then
                task.delay(0, u31, "CurrencyPickup")
                task.delay(0.14285714285714285, u31, "CurrencyPickup")
                u31("GumBuy")
                u16:FireServer("GumShopPurchase", v158)
                return
            elseif u7[v158] then
                u16:FireServer("UpdateStorage", v158)
            elseif u6[v158] then
                u16:FireServer("UpdateFlavor", v158)
            end
        end
    end
    local v166 = nil
    goto l12
end)
u10(u34.Close, u11.Button.Red)
u15(u34.Close, function() --[[Anonymous function at line 565]]
    --[[
    Upvalues:
        [1] = u17
    --]]
    u17:Close()
end)
u17:BindOnOpened("GumShop", function() --[[Anonymous function at line 570]]
    --[[
    Upvalues:
        [1] = u31
    --]]
    u31("ShopOpen")
end)
u38.open = u146
u38.setTutorial = v148
return u38