--devbgascension

-- Bytecode (Base64):
-- BgOKAgVWYWx1ZQRtYXRoA3JhZAFYBk9mZnNldAFZA2NvcwNzaW4FVURpbTIDbmV3BVNjYWxlD2dldFJvdGF0ZWRVRGltMgNkZWcGcmFuZG9tEWdldEFuZ2xlRnJvbUluZGV4B0Rlc3Ryb3kKQWN0aXZhdGlvbgRCZWFtBkNvbG9yMwdmcm9tUkdCBUNvbG9yBkFzc2V0cwlQYXJ0aWNsZXMIQ29uZmV0dGkLR2V0Q2hpbGRyZW4ETmFtZQRHbG93BUNsb25lBEVudW0ITm9ybWFsSWQETGVmdBFFbWlzc2lvbkRpcmVjdGlvbgxBY2NlbGVyYXRpb24HRW5hYmxlZARSb290BlBhcmVudARFbWl0BHRhc2sFZGVsYXkITGlmZXRpbWUDTWF4BEl0ZW0TQ2xhaW1XaGVlbFNwaW5RdWV1ZQpGaXJlU2VydmVyBUZhZGVkBE1haW4EU3BpbgdWaXNpYmxlBFNraXAKZmluaXNoU3BpbgpEaXNjb25uZWN0BE5vbmUESWNvbglMZWdlbmRhcnkFY2xvc2UTQ2FuUHJvbXB0T3B0SW5Bc3luYwRUeXBlA1BldApVcGRhdGVJY29uBXBjYWxsBUN5Y2xlB1JhaW5ib3cFU3BlZWQMcHJvbXB0Tm90aWZ5E0ZyZWVOb3RpZnlMZWdlbmRhcnkLUHJvbXB0T3B0SW4FU3RhdHMKV2hlZWxTcGlucwNHZXQOR2V0T3duZWRBbW91bnQEU2hvdwZzcGluLTEJUHJvZHVjdElkFVByb21wdFByb2R1Y3RQdXJjaGFzZQlXaGVlbFNwaW4MSW52b2tlU2VydmVyBkNyZWF0ZQRQbGF5BHdhaXQEVGltZQhwbGF5U3BpbgVDbGljawdTcGlubmVyBlRpY2tlcglUd2VlbkluZm8LRWFzaW5nU3R5bGUFUXVpbnQIUm90YXRpb24MdXBkYXRlVGlja2VyBXJvdW5kBWZsb29yCFBvc2l0aW9uBUxhYmVsE3VwZGF0ZUl0ZW1Qb3NpdGlvbnMPTWFzdGVyeVVwZ3JhZGVzDUF1dG9DbGFpbVNwaW4SQ2xhaW1GcmVlV2hlZWxTcGluDHRyeUF1dG9DbGFpbQ1OZXh0V2hlZWxTcGluA25vdwNtYXgkWW91IGhhdmUgYSAlKiB3YWl0aW5nIHRvIGJlIGNsYWltZWQhCWF1dG9Db2xvcglGcmVlIFNwaW4EVGV4dARDeWFuBmZvcm1hdApUZWxlcG9ydElkBVNvdW5kC0dldEZ1bGxOYW1lEE5vdGlmaWNhdGlvblJpZnQFVGl0bGUFQ2xhaW0JRlJFRSBTUElODEJpbGxib2FyZEd1aQtEZXNjcmlwdGlvbhVDbGFpbSB5b3VyIEZSRUUgc3BpbiEDQWRkDEZyZWUgc3BpbiBpbgZSZW1vdmUFRnJhbWUKSW1hZ2VMYWJlbApmb3JtYXRUaW1lD0ZyZWUgc3BpbiBpbiAlKhF1cGRhdGVDbGFpbUJ1dHRvbgZCdXR0b24EQ29zdAZCZWZvcmUKZnJvbU9mZnNldApUZXh0Qm91bmRzB1VJU2NhbGUEU2l6ZQdzcGluLSUqB0J1dHRvbnMORmluZEZpcnN0Q2hpbGQJR2V0QW1vdW50BCUqJSoMUm9idXhVbmljb2RlAl9fBWRlZmVyBnVwZGF0ZQxQcmljZUluUm9idXgFSXRlbXMJSXNBbnlPcGVuCGZyb21JdGVtBEZyZWUIRnJlZUl0ZW0JRXhwbG9zaW9uBE9wZW4DUmVkClRleHRDb2xvcjMIQ3VycmVuY3kGQW1vdW50FUdldEN1cnJlbmN5TXVsdGlwbGllcgRjZWlsDEZvcm1hdEFtb3VudAVDbG9zZQZzcGluLTMGRWZmZWN0BGdhbWUHUGxheWVycwpHZXRTZXJ2aWNlEVJlcGxpY2F0ZWRTdG9yYWdlClJ1blNlcnZpY2UMVHdlZW5TZXJ2aWNlEk1hcmtldHBsYWNlU2VydmljZR1FeHBlcmllbmNlTm90aWZpY2F0aW9uU2VydmljZQdyZXF1aXJlBlNoYXJlZAREYXRhBkNsaWVudAlGcmFtZXdvcmsIU2VydmljZXMJTG9jYWxEYXRhBVV0aWxzCEl0ZW1VdGlsCVV0aWxpdGllcwZTdHJpbmcMRm9ybWF0U3VmZml4A0d1aQ9DbGlja2FibGVCdXR0b24HTmV0d29yawZSZW1vdGUIR3VpRnJhbWUFVHlwZXMSR2V0U2NyZWVuR3VpSG9sZGVyD0F1dG9CdXR0b25Db2xvcgdQYWxldHRlB1Rvb2x0aXAIQnVpbGRlcnMOVG9vbHRpcEJ1aWxkZXIJSXRlbUZyYW1lEkhvb2tTY3JvbGxpbmdGcmFtZQxBbmltYXRlQ29sb3IJQ29uc3RhbnRzDlBsYXlMb2NhbFNvdW5kBVNoaW55BWV2ZXJ5BE1hdGgKQW5pbWF0aW9ucwdTZXRGYWRlCEd1aUFycm93DE5vdGlmaWNhdGlvbghSaWNoVGV4dAhJdGVtRmFsbAdFZmZlY3RzBkJ1YmJsZRJQcm9jZXNzaW5nUHVyY2hhc2UIUHJvZHVjdHMLUHJvZHVjdEluZm8JU3RhdHNVdGlsC0xvY2FsUGxheWVyCVBsYXllckd1aQlTY3JlZW5HdWkPRmxvYXRpbmcgSXNsYW5kDVRoZSBPdmVyd29ybGQJd29ya3NwYWNlBldvcmxkcwdJc2xhbmRzBklzbGFuZAdEaXNwbGF5ClN1cmZhY2VHdWkHQWRvcm5lZQlmcm9tU2NhbGUISW5zdGFuY2ULTnVtYmVyVmFsdWUHUG93ZXJ1cAtTcGluIFRpY2tldAhDaXJjdWxhcgNIVUQKTm90aWZ5R2FtZQ1FbWVyYWxkIEdvbGVtDkluZmVybm8gRHJhZ29uDUx1bmFyIFNlcnBlbnQRT3B0SW5Qcm9tcHRDbG9zZWQHQ29ubmVjdANUb3AISW5hY3RpdmUGTm90aWZ5BUdyZWVuEkNvbm5lY3REYXRhQ2hhbmdlZAtTcGluIHRvIFdpbghXb3JsZE1hcApBY3Rpdml0aWVzBVRpbWVyFUNvbm5lY3RQcm9kdWN0Q2hhbmdlZAQlKiUlBkNoYW5jZQlHZXRSYXJpdHkFSW5uZXIGU2VjcmV0DFJhcml0eUNvbG9ycwdPbkVudGVyA0lzQQRQaW5rBk9yYW5nZQRCaW5kCFBvd2VydXBzBlBhc3NlcwxUZWFtRXF1aXBwZWQFVGVhbXMNQWN0aXZlUG90aW9ucwtBY3RpdmVCdWZmcxhHZXRQcm9wZXJ0eUNoYW5nZWRTaWduYWwMQmluZE9uT3BlbmVkDEJpbmRPbkNsb3NlZAAfDwECAAAGAwAABQEHQ/sDAABNAgPsAAAAALsWAgKkAQMAAAgQgJ8BAgJNBAB5BAAAAE0DBHAFAAAA+wYBAE0FBnkEAAAATQQFcAUAAAAmAgMETQUAeAYAAABNBAVwBQAAAPsHAQBNBgd4BgAAAE0FBnAFAAAAJgMEBbsJAQNSBQEApAQIAAAcEICfBAICuxgBA1IGAQCkBQoAACQQgJ8FAgKkBg0AADCwgE0IAHkEAAAATQcIhA4AAAAJCgIECQsDBSYJCgv7DAEATQsMeQQAAABNCgtwBQAAAEMICQpNCgB4BgAAAE0JCoQOAAAACQwCBQkNAwRDCwwN+w4BAE0NDngGAAAATQwNcAUAAABDCgsMnwYFAIIGAAAPAwEDAgMDBAAIEIADBAMFAwYDBwQAHBCAAwgEACQQgAMJAwoEADCwgAMLAEYMARgAAAAAAAAAAQAAAAAAAAAAAAEAAAAAAAAAAAABAAAAAAEAAAAAAQABAAAAAQAAAAAAAAAAAQAAAAEAAAAAAAAAAPwARwAAAAAIAQAAAAYDAAAFAQIQeAIAAVsBAgB4BQECuwoFAqQEBQAAEDCAnwQCAjkDBACMBSgApAcIAAAcMICfBwECeAYHBgkEBQZDAgMEggICAAkCGC1EVPsh6T8CAAAAAAAA8D8CGC1EVPsh2T8DAgMNBAAQMIACAAAAAAAA4D8DDgQAHDCAAFQPARgAAAEAAAAAAAAAAAAAAAAAVQAAAAACAAEAAAAF+wAAALwAAFAAAAAAnwACAYIAAQABAxAAaAABGAAAAAABaQAAAAALAQkAAAYDAAAFAQFmDgBQAPsBAAD7BAEATQMEzwAAAAC8AQGaAQAAAJ8BAwKkAgQAAAwggIwDJwCMBO0AjAX/AJ8CBAIwAgGkBQAAAPsIAgBNBwiBBgAAAE0GB64HAAAATQUGrAgAAAC8BQVoCQAAAJ8FAgJSAgUAxgMAAMYEAABkAiUATQcGugoAAADwByIACwAAALwHBjoMAAAAnwcCAqQIEAAPONDAMAgH+BEAAABvCBIAMAgHMRMAAACpCAAAMAgH8BQAAAD7CgEATQkKzwAAAABNCAl0FQAAADAIByQWAAAAjAoUALwIB1YXAAAAnwgDAaQIGgAAZICBTQoHyxsAAABNCQq0HAAAANkKAAASAAcAnwgDAW4C2v8CAAAA+wIDAPsFBAD7BgUAhwQFBk0DBModAAAAnwICAfsCBgBvBB4AvAICax8AAACfAgMB+wEHAKkCAAAwAgHnIAAAAPsDCABNAgNaIQAAAE0BAkEiAAAAqQIBADACAYAjAAAA+wMIAE0CA1ohAAAATQECECQAAACpAgAAMAIBgCMAAACCAAEAJQMRAxIDEwMUBAAMIIADFQMWAxcDGAMZAxoDGwMcAx0DHgMfBA840MADIAcAAIDAAAAAAAAAAAAAAAAAAyEDIgMjAyQDJQMmAycEAGSAgQMoAykDKgMrAywDLQMuAy8DMAMxAQJZMgEYAAEAAAAAAAABAAAAAAAAAAIAAAAAAAAAAAAAAAAAAQAAAAMAAAEAAAABAAABAAABAAAAAAAAAQAAAAEAAAAAAAAAAPYADwAAAAAAAAEAAAAAAwAAAAEAAAAAAAAAAQAAAAAAAAABWgAAAAAFAAMAAAAa+wAAAA4ABgD7AAAAvAAAGgAAAACfAAIBxgAAAN4AAAD7AQEATQABJAEAAACpAQAAMAEAgAIAAAD7AQIATQABPwMAAAD7BAEATQMEWgQAAABNAgOuBQAAAE0BArkGAAAAnwACAYIAAQAHAzMDJAMwAzQDLgM1AzYAfTcBGAAAAQAAAAEAAgAAAAAAAQAAAAAAAAAAAAABfgAAAAACAAEAAAAF+wAAALwAAMgAAAAAnwACAoIAAgABAzgAhwEAARgAAAAAAIgAAAAABwAEAAAAGvsDAACVAgMA+wQBABwDBADPAQIDlQABAN4AAAD7AAIA+wQDAE0DBFoBAAAATQIDrgIAAADiAwUAbwQGADAEAxEDAAAA+wUBAPsGAACHBAUGMAQDugQAAAC8AAAhBwAAAJ8ABAGCAAEACAIAAAAAAADwPwMuAzUDOQMaBQIDBAM6AzsAjQEAARgAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAAAAY4AAAAACAAHAAAAKaQAAQAAAABAwAECABICAACfAAIDDgAiAA4BIQCMAgAA+wMCAG8EAwDZBQEAEgEC/xICAwASAgQAEgIFAJ8DAwLeAwEA+wQGAE0DBHkEAAAA+wcFAE0GB1oFAAAATQUGrgYAAABNBAW5BwAAAG8FCADiBgoAbwcLADAHBiwJAAAAnwMEAfsEBQBNAwQkDAAAAKkEAQAwBAOADQAAAMECAACCAAEADgM8BAAAAEAGBQKamZmZmZnJPwM9Ay4DNQM2Az4DPwUBCQKamZmZmZnZPwMkAzACBQaGAUABGAAAAAAABAABAQAAAAAAAAAABAAAAAAAAAAAAAAAAAAAAAEAAAAAAAAChwAAAAADAAEAAAAG+wAAAG8CAAC8AABrAQAAAJ8AAwGCAAEAAgNBAywAlgEAARgAAAAAAAGXAAAAAAUABAAAAB77AAAADgAGAPsAAAC8AAAaAAAAAJ8AAgHGAAAA3gAAAPsBAQBNAAEkAQAAAKkBAAAwAQCAAgAAAPsBAgBNAAE/AwAAAPsEAQBNAwRaBAAAAE0CA64FAAAATQECuQYAAACfAAIB+wADALwAAEQHAAAAnwACAYIAAQAIAzMDJAMwAzQDLgM1AzYDQgChAQABGAAAAQAAAAEAAgAAAAAAAQAAAAAAAAAAAAAgAAAAAX4AAAAABQECAAAAE00CACEAAAAATQECBQEAAAD7AgAA8QIMAAEAAAANAQkAAgAAgPsCAABHAgYAAAAAAKQCBQAAEDCAjAMCAPsEAQCfAgMB3gEAAIIAAQAGA0MDRAIAAAAAAADwPwMmAycEABAwgACnAQABGAAAAAABAAABAAAAAAEAAAAAAgKoAAAAAAsAEgAAAHb7AAAAvAAAfwAAAACfAAICKwABAIIAAQD7AQEAUgMAAPsEAgC8AQHvAQAAAJ8BBAINARAAAgAAgPsCAwC8AgKYAwAAAJ8CAgH7AgQA+wQFAPsHBgBNBgcYBAAAAE0FBgsFAAAAvAICaQYAAACfAgQBggABAPsEBwBNAwRaBwAAAE0CA0EIAAAAqQMAADADAoAJAAAA+wQHAE0DBFoHAAAATQIDEAoAAACpAwEAMAMCgAkAAAD7AggAqQMBADADAucLAAAA+wIJAG8EDAC8AgI5DQAAAJ8CAwIOAjgA+wQKAIcDBAJ4BgIPWwUGDngIBRC7CggCpAcTAABIEIGfBwICOQYHAIwIKACkChYAAFQQgZ8KAQJ4CQoUCQcICUMEBgfeAgsAeAUEF94FDAD7BQ0AjAYAADAGBewYAAAA+wUOAPsHDQD7CA8A4gkZAPsKDAAwCgnsGAAAALwFBZYaAAAAnwUFArwFBe4bAAAAnwUCAfsGEACVBQYP3gUQAKQGHgAAdMCB+wgPAE0HCEofAAAAnwYCAfsGEADxBQIABgAAAIIAAQD7Bg0ATQcG7BgAAAAhBwcgMAcG7BgAAAD7AxEARwICAAAAAICpBAABqQQBAJ8DAgGCAAEAIQNFA0YCAAAAAAAAAAADRwNIA0kDSgMuAy8DMAMxAy0DSwNMAhgtRFT7Iek/AgAAAAAAAPA/AhgtRFT7Idk/AwIDDQQASBCBAgAAAAAAAOA/Aw4EAFQQgQIAAAAAAICWQAMBBQEYA00DTgMmA08EAHTAgQNQAgAAAAAAgHZAALUBUQEYYQAAAAEBAgAAAAAAAQABAAAAAQAAAAAAAAAAAAEDAAAAAAAAAAEAAAAAAAAAAQAAAAIAAAAAAQEAjgABAAAAAAAAAAAAAAAAcwEAAQAAAAEAAAAAAAAAAAAAAAACAAECAAAAAAABAAABAwAAAAAAAwAAAAAAAVUAAAAABwAEAAAAPfsBAACVAAEA3gAAAPsBAQBvAgEAnwECAfsBAgD7BgMATQUGWgIAAABNBAViAwAAAE0DBI0EAAAApAQHAAAYUIBvBQgApAYMAAsokMCfBAMC4gUOAIwGHgAwBgU4DQAAALwBAZYPAAAAnwEFArwBAe4QAAAAnwECAaQBEwAASBCBbwIIAJ8BAgH7AQAA8QACAAEAAACCAAEA+wECAPsGAwBNBQZaAgAAAE0EBWIDAAAATQMEjQQAAACkBAcAABhQgG8FFACfBAIC4gUOAIwGAAAwBgU4DQAAALwBAZYPAAAAnwEFArwBAe4QAAAAnwECAYIAAQAVAgAAAAAAAPA/A1IDLgNTA1QDVQMKBAAYUIACmpmZmZmZuT8DHQNWA1cECyiQwANYBQENA00DTgMmA08EAEgQgQIzMzMzMzPTPwDdAVkBGAAAAQIAAAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEAAAABAAABAgAAAAAAAAAAAAAAAAAAAAAAAAAAAAHeAAAAAAsABwAAAEj7AwAATQID7AIAAAAhAQIBPgABAHgDAAO7MAMCpAIGAAAUQICfAgICuwwCAqQBCAAAHECAnwECAvsCAQBHAgMAAAAAgN4BAQBlAAYA+wIBAPECBAABAAAA3gEBAPsCAgCfAgEB+wUAAE0EBewCAAAAIQMEAT4CAwB4BQIDuzAFAqQEBgAAFECAnwQCArsMBAKkAwgAABxAgJ8DAgL7BAMAxgUAAMYGAABkBAYA+wkEAE0KCDsJAAAAnwkCAjAJBzsJAAAAbgT5/wIAAAD7BQUATQQFYgoAAAD7BgAATQUG7AIAAAAwBQQ4CwAAAPsHBgBNBgdaDAAAAE0FBmIKAAAATQQFww0AAAD7BgAATQUG7AIAAAAwBQQ4CwAAAIIAAQAOAgAAAAAAgEZAAgAAAAAAgHZAAwECAAAAAACANkADAgNaBAAUQIADWwQAHECAA1wDUwNYAy4DXQDrAV4BGAAAAAAAAQAAAAAAAAAAAQAAAQABAAABAQADAAAAAAEAAAAAAAAAAAEAAAABAAAAAAD/AAMAAAAAAAAAAQAAAAAAAAAAAAAAAewAAAAACAEBAAAAFakBAABNAgDDAAAAAMYDAADGBAAAZAIGAE0HBhEBAAAA8AcDAAIAAICpAQEAZQACAG4C+f8CAAAADgEFAPsCAABvBAMAvAICawQAAACfAgMBggECAAUDXwM5A2ADYQMsAIICYgEYAAEAAAAAAQAAAAEB/QAGAQAAAAACAwEAAAAMAAwAAADHAfsAAAC8AAB/AAAAAJ8AAgIrAAEAggABAIwCAABNBADfAQAAAPsGAQBNBQaaAgAAAJ8FAQImAwQFnhICAwMAAACkAQUAABAwgJ8BAwINAQIABgAAAKkCAAGpAgEA+wMCAPEDggACAAAA+wMCAEcDNwAAAAAADgI1AKkEAABNBQDDBwAAAMYGAADGBwAAZAUGAE0KCREIAAAA8AoDAAkAAICpBAEAZQACAG4F+f8CAAAADgQFAPsFAwBvBwoAvAUFawsAAACfBQMBUgMEACsDHwD7AwQAbwUMAPsIBQBNBwjMDQAAAG8IDgD7CwYATQoL9Q8AAABNCQqjEAAAAJ8HAwK8BQWNEQAAAJ8FAwJSBAUA4gUUAPsIBwBNBwjPFQAAAE0GB3QWAAAAvAYGshcAAACfBgICMAYFbBIAAABvBhgAMAYFbhMAAACfAwMBDgIgAPsECABNAwS6GQAAAG8EGgAwBAP1DwAAAPsECABNAwTDGwAAAG8EHAAwBAP1DwAAAPsHBwBNBgfPFQAAAE0FBnQWAAAATQQFZx0AAABNAwTiHgAAAG8EHwAwBAP1DwAAAPsDCQD7BggATQUGJCAAAAC8AwNfIQAAAJ8DAwFlAA0A+wQIAE0DBLoZAAAAbwQiADAEA/UPAAAA+wMJAPsGCABNBQYkIAAAALwDA2kjAAAAnwMDAfsDCgD7BQgATQQFJCAAAAAOAgIAjAUAAGUAAQBvBSQApAYnAACYUIJvBygApAgsACuokMKfBgMC/wcAAAIAAABvCC0AbwkuAMUHCAMBAAAAnwMFAd4CAgD7AwsAVgQCADAEA4AvAAAA+wUIAE0EBboZAAAATQME9Q8AAADwAyUAGgAAAPsEAQBNAwTZMAAAAFIEAQCfAwIC+wUIAE0EBcMbAAAAMAME9Q8AAAD7BAsA+wYBAE0FBtkwAAAAUgYBAKkHAQCfBQMCMAUE9Q8AAAD7CAcATQcIzxUAAABNBgd0FgAAAE0FBmcdAAAATQQF4h4AAABvBjEAUggDALwGBo0RAAAAnwYDAlIFBgAwBQT1DwAAAIIAAQAyA0UDYwNkAwIDZQQAEDCAAgAAAAAAAAAAA18DOQNgA2EDLANmA2cDaANpA2oDawNsA20FAhITAxEDIwNuA28DcANxA10DcgNzA3QDdQMkA3YDdwN4AgAAAAAAANA/A1UDCgQAmFCCApqZmZmZmck/Ax0DVgNXBCuokMIDeQN6AzADewN8AJMCfQEYEQAAAAEBAgAAAAAAAAAAAAAAAAEAAAABAAABAAAA6AEAAAAAAQAAAAEB/QAGAQAAAAACABAAAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAEAAP4HAQAAAAAAAQAAAAAAAQAAAAAAAAAAAAAAAQAAAAAAAAACAAAAAAABAAAAAAAAAgEAAAEAAAAAAAAAAAABAAAAAAD9BQEAAAACAAAAAAAAAQAAAAABAAAAAAEAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAAAAgMBAAAACQACAAAAH/sDAABNAgOsAAAAAE0BAiMBAAAATQABCAIAAACkAQUAABAwgPsIAABNBwisAAAAAE0GByMBAAAATQUGCAIAAABNBAWhBgAAAE0DBHkHAAAA+wYBAE0FBisIAAAATQQFhAkAAADsAgMEjAMeAJ8BAwIwAQAvCgAAAIIAAQALA34DfwOAAQMJA4EBBAAQMIADggEDBAODAQMLA4QBANICAAEYAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAVMBAAAADwAGAAAAVIwCAQCMAAMAjAEBAKgATwBvBAAAUgYCALwEBI0BAAAAnwQDAlIDBAD7BQAAhwQFA/sGAQCHBQYDTQYFEQIAAADwBkEAAwAAgPsIAgBNBwhaBAAAAE0GB9MFAAAAUggDALwGBgMGAAAAnwYDAg4GNgANAiQABwAAgPsHAwBNCQXKAwAAALwHBwIIAAAAnwcDAvsJAABNCAkYCQAAAE0LBqwKAAAATQoLIwsAAABNCQoIDAAAAG8LDQD7DgQATQ0OOA4AAAAOCAIACQ4IBysOAQBvDg8AvAsLjQEAAACfCwQCUgoLADAKCfUQAAAApAkTAABIEIHZCgAAEgAGABICBQCfCQIBTQkGrAoAAABNCAkjCwAAAE0HCMMUAAAAbwkNAPsMBABNCww4DgAAAJAMBA+8CQmNAQAAAJ8JBAJSCAkAMAgH9RAAAACLALH/ggABABUDhQEDawM5AyoDLgOGAQOHAQIAAAAAAAAIQAOIAQNIA34DfwOAAQOJAQOKAQOLAQNpAyYDjAEEAEgQgQNdARDCAo0BARgAAAAAAQAAAAAAAQABAAEAAAADAAAAAAAAAAABAwABAAAAAAABAAABAAAAAAAAAAAAAAAAAAAAAAAAAAEAAAAAAAQAAAAAAAAAAAAAAAAAAAAA7RVDAQAAAAQBAwAAAAwOAAgATQEAGwAAAAAOAQUA+wEAAPsCAQBNAwAbAAAAAGoDAQL7AQIAnwEBAYIAAQABA44BANwCAAEYAAAAAAEAAAAAAgABXQEAAAADAAUAAAAW+wEAAE0AASQAAAAA+wIBAE0BAjgBAAAAmgAHAAEAAAD7AAIAvAAA/AIAAACfAAICDgABAIIAAQD7AQMATQABZwMAAAD7AgQATQECygQAAACfAAIAggAAAAUDJAOPAQOQAQORAQMqAP8CAAEYAAAAAAAAAAAAAAAAAAECAAAAAAAAAIABAAAABQAJAAAAMvsAAAAOAAEAggABAPsBAQBNAAG6AAAAAPAAEgABAACA+wACAG8BAgCfAAIB+wADAG8CAwC8AABrBAAAAJ8AAwH7AAQA+wMEAE0CA5YFAAAAjAMKALwAAFYGAAAAnwAEAWUAEAD7AQUA+wMBAE0CA7oAAAAAhwABAvsBBgC8AQGYBwAAAJ8BAgH7AQcA+wMIAE0EAAsIAAAAvAEBaQkAAACfAQQBqQABAN4AAACkAAwAACyggG8BDQCfAAIBqQAAAN4AAACCAAEADgMaA5IBA5MBA2EDLAOUAQMlA0cDSQNKAyYDTwQALKCAApqZmZmZmck/AJgDAAEYAAABAgAAAAABAAABAAAAAAEAAAAAAAAAAAIAAAAAAQAAAAEAAAAAAAACAAEAAAABAAGZAQAAAAUAAQAAABP7AQAATQABugAAAADwAAMAAQAAAKkAAQCCAAIA+wQAAE0DBKwCAAAATQIDugMAAABNAQL1BAAAAPABAgAFAAAAqQAAAakAAQCCAAIABgMaA5IBA34DcANpA3EAqAMAARgAAAAAAAEAAgAAAAAAAAAAAAAAqQEAAAADAAEAAAAG+wAAAG8CAAC8AAAWAQAAAJ8AAwGCAAEAAgNLA5UBALEDAAEYAAAAAAABsgEAAAAIAQkAAABh+wEAAFIDAAD7BAEAvAEB7wAAAACfAQQC+wICAIwEAABgBAgAAQAAAKQDAwAACBCAjAQBAIwFAQCMBgEAnwMEAisDBQD7BQMATQQF9QQAAABNAwRvBQAAADADAnMGAAAA+wICAPsDBABSBAEAnwMCAjADAvUEAAAA+wYFAE0FBloHAAAATQQFQQgAAABNAwSsCQAAAE0CA7oKAAAAjAQAALcEAgABAAAAqQMAAakDAQAwAwKACwAAAPsCBgD7BgUATQUGWgcAAABNBAVBCAAAAE0DBKwJAAAAjAUAAGAFAwABAAAAjAQAAGUAAQBvBAwApAUOAAAI0IBvBg8ApAcTABJEAMGfBQMC/wYAAAEAAABvBxQAxQYHAgEAAACfAgUBDQEMABUAAID7AgcA+wYFAE0FBloHAAAATQQFQQgAAACMBS0AvAICXxYAAACfAgQBZQAJAPsCBwD7BgUATQUGWgcAAABNBAVBCAAAALwCAmkXAAAAnwIDAfsCCACfAgEBggABABgDRgMTAwoEAAgQgANpA5YBA5cBAy4DLwN+A3ADMAJmZmZmZmbWPwNVBAAI0IACmpmZmZmZyT8DHQNWA1cEEkQAwQN5AgAAAAAAAPA/A3YDeAC4AwABGAAAAAAAAAEAAAAAAAAAAAAAAAAAAAAAAAEAAAAAAAEAAAAAAAAAAAAAAAAAAAACAQAAAAAAAAEAAAAAAAAAAAAAAAEAAAAA/QYAAQAAAAAAAAAAAAACAAAAAAAAAAADAAG5AQAAAA4BAwAAEwAABA8HBgIPCQwCDw0SAg8MKAI0+wEAAMYCAADGAwAAZAEtAE0HBcoAAAAATQYHEQEAAADwBigAAgAAgE0JBcoAAAAATQgJKwMAAAD7CQEAUgsAAE0NBcoAAAAATQwNCQIAAACpDQEAvAkJhwQAAACfCQUCCQcICbsHBwKkBgcAABhQgJ8GAgL7BwIATQoErAgAAABNCQorAwAAAOIKCQBvCwIAMAsKEQEAAABNDAXKAAAAAE0LDAkCAAAAMAsKCQIAAAAwBgorAwAAALwHB/UKAAAAnwcEAW4B0v8CAAAAggABAAsDKgM5A5gBA5kBA5oBAwIDmwEEABhQgAN+BQMBAgMDnAEAzgMAARgAAAAAAQAAAAAAAwAAAAAAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAAAAAAA+wAHzwEAAAAIAAIAAAAV+wAAAKQBAgAABACAjAIAAPsGAABNBQahAwAAAE0EBXkEAAAA+wcBAE0GBysFAAAATQUGhAYAAADsAwQFjAQBAIwFAACfAQUCMAEALwcAAACCAAEACAMJAwoEAAQAgAOCAQMEA4MBAwsDhAEA2QMAARgAAAAAAAAAAAAAAAAAAAAAAAAAAAHaAQAAAAYABQAAABv7AAAAlQAAAN4AAAD7AAEA+wECADABAOwBAAAA+wADAPsCAQCkAwQAAAwggG8EBQCfAwIC4gQGAPsFAgAwBQTsAQAAALwAAJYHAAAAnwAFArwAAO4IAAAAnwACAfsABACpAQEAnwACAYIAAQAJAgAAAAAAAPA/AwEDVQMKBAAMIIACexSuR+F6hD8FAQEDTQNOAOEDAAEYAAAAAQAAAAEAAAAAAAAAAAAAAAAAAAABAAAB4gEAAAACAAEAAAAF+wAAALwAAGMAAAAAnwACAYIAAQABA50BAOkDAAEYAAAAAAHqAQAAAAcAAwAAABz7AQAATQABeQAAAAD7AwEATQIDWgEAAABNAQK6AgAAAG8CAwDiAwUAbwQGADAEAywEAAAAnwAEAfsAAgD7BgEATQUGWgEAAABNBAXTCAAAAE0DBBQHAAAATQIDswkAAAC8AABfCgAAAJ8AAwGCAAEACwM9Ay4DcAM+Az8FAQQCAAAAAAAA4D8DngEDhgEDnwEDdgD0AwABGAAAAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAH1AQAAAAcAAwAAABf7AQAATQABPwAAAAD7AwEATQIDWgEAAABNAQK6AgAAAJ8AAgH7AAIA+wYBAE0FBloBAAAATQQF0wQAAABNAwQUAwAAAE0CA7MFAAAAvAAAaQYAAACfAAMBggABAAcDNAMuA3ADngEDhgEDnwEDeAD5AwABGAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAB+gEAAABUAAABAAC7CKMAAACkAAEAAAAAQG8CAgC8AAAWAwAAAJ8AAwKkAQEAAAAAQG8DBAC8AQEWAwAAAJ8BAwKkAgEAAAAAQG8EBQC8AgIWAwAAAJ8CAwKkAwEAAAAAQG8FBgC8AwMWAwAAAJ8DAwKkBAEAAAAAQG8GBwC8BAQWAwAAAJ8EAwKkBQEAAAAAQG8HCAC8BQUWAwAAAJ8FAwKkBgoAAACQQE0JARILAAAATQgJxgwAAABNBwgnDQAAAJ8GAgKkBwoAAACQQE0LAU0OAAAATQoLHA8AAABNCQpDEAAAAE0ICWgRAAAAnwcCAqQICgAAAJBATQwBEgsAAABNCwyhEgAAAE0KCyETAAAATQkK0BQAAACfCAICpAkKAAAAkEBNDgESCwAAAE0NDhwPAAAATQwNtRUAAABNCwyhFgAAAE0KC8YXAAAAnwkCAqQKCgAAAJBATQ4BTQ4AAABNDQ4fGAAAAE0MDaESAAAATQsM7BkAAACfCgICpAsKAAAAkEBNDwESCwAAAE0ODxwPAAAATQ0OUhoAAABNDA32GwAAAJ8LAgKkDAoAAACQQE0PAU0OAAAATQ4PHxgAAABNDQ6VHAAAAJ8MAgKkDQoAAACQQE0PARILAAAATQ4P7x0AAACfDQICpA4KAAAAkEBNEQFNDgAAAE0QER8YAAAATQ8QSx4AAACfDgICpA8KAAAAkEBNEwFNDgAAAE0SEx8YAAAATRESoRIAAABNEBHXHwAAAJ8PAgKkEAoAAACQQE0SARILAAAATRESeCAAAACfEAICpBEKAAAAkEBNEwFNDgAAAE0SE88hAAAAnxECAqQSCgAAAJBATRUBTQ4AAABNFBUfGAAAAE0TFHUiAAAAnxICAqQTCgAAAJBATRcBEgsAAABNFhfGDAAAAE0VFrsjAAAATRQVhiQAAACfEwICpBQKAAAAkEBNGAFNDgAAAE0XGB8YAAAATRYXoRIAAABNFRbDJQAAAJ8UAgKkFQoAAACQQE0aAU0OAAAATRkaHA8AAABNGBm1FQAAAE0XGB8YAAAATRYXPiYAAACfFQICpBYKAAAAkEBNGQESCwAAAE0YGaESAAAATRcY6CcAAACfFgICpBcKAAAAkEBNGQESCwAAAE0YGQcoAAAAnxcCAqQYCgAAAJBATRwBTQ4AAABNGxwfGAAAAE0aG6ESAAAATRkaLCkAAACfGAICpBkKAAAAkEBNHQFNDgAAAE0cHR8YAAAATRscoRIAAABNGhu0KgAAAJ8ZAgKkGgoAAACQQE0eARILAAAATR0eHA8AAABNHB21FQAAAE0bHMQrAAAAnxoCAqQbCgAAAJBATSABEgsAAABNHyAcDwAAAE0eH7UVAAAATR0ejCwAAABNHB1KLQAAAJ8bAgKkHAoAAACQQE0iAU0OAAAATSEiHA8AAABNICG1FQAAAE0fIB8YAAAATR4fRC4AAABNHR4ELwAAAJ8cAgKkHQoAAACQQE0hAU0OAAAATSAhHxgAAABNHyChEgAAAE0eH5owAAAAnx0CAqQeCgAAAJBATSMBTQ4AAABNIiMcDwAAAE0hIrUVAAAATSAhHxgAAABNHyCsMQAAAJ8eAgKkHwoAAACQQE0jAU0OAAAATSIjHxgAAABNISKhEgAAAE0gIUkyAAAAnx8CAqQgCgAAAJBATSMBEgsAAABNIiOhEgAAAE0hItEzAAAAnyACAqQhCgAAAJBATSUBTQ4AAABNJCUfGAAAAE0jJEQuAAAATSIjDjQAAACfIQICpCIKAAAAkEBNJQFNDgAAAE0kJZc1AAAATSMkJzYAAACfIgICpCMKAAAAkEBNJwFNDgAAAE0mJx8YAAAATSUmRC4AAABNJCXqNwAAAJ8jAgKkJAoAAACQQE0nARILAAAATSYnxgwAAABNJSZBOAAAAJ8kAgKkJQoAAACQQE0pARILAAAATSgpHA8AAABNJyi1FQAAAE0mJ5k5AAAAnyUCAqQmCgAAAJBATSoBEgsAAABNKSqhEgAAAE0oKSETAAAATScoEzoAAACfJgICTScAMTsAAABNKSeZPAAAAE0oKXo9AAAATSooJw0AAABNKSqdPgAAAKQwQgAAABBETS8w2EMAAABNLi87QAAAAE0tLidEAAAATSwtIz8AAABNKyy5RQAAAE0qKycNAAAATSwqPEYAAABNKywnRwAAAFIsDgCfLAECMCwrJEgAAABNLCo8RgAAADAsKxRJAAAApCxMAAAsoYRvLU0Aby5NAJ8sAwKkLVAAADzhhG8uUQCfLQIC/y4AAAAAAADiL1UAbzBWADAwLxFSAAAAbzBXADAwL7pTAAAAjDABADAwLytUAAAApDBZAAA8gYWMMQYApDJdAFxsocWfMAMCjDEBAIwyAADAM14AEgAtABIALADANF8A2TUCABIAEQASACoAEgABABIAIQASAAYAEgEx/xIACwASACIAEgApAMY2AABNOSgfYAAAAE04OZVhAAAATTc4nT4AAADGOAAA/zkAAAMAAABvOmIAbztjAG88ZADFOToEAQAAANk6AwASATj/EgA3ABIAFgDZNgQAEgAFABIBOP8SABoAEgA5ABIACAASADcAEgAWAE07BYNlAAAAwD1mABIACwC8OzvHZwAAAJ87AwFSOw8ATT43mGgAAABNPT5jaQAAAE08PaxqAAAATT4QrGoAAABNPT5vawAAAJ87AwFSOwoATT43mGgAAABNPT5jaQAAAE08PaxqAAAAUj06AJ87AwFSOw8ATT83WmwAAABNPj/TbQAAAE09PmNpAAAATTw9rGoAAABNPhCsagAAAE09PrluAAAAnzsDAVI7CgBNPzdabAAAAE0+P9NtAAAATT0+Y2kAAABNPD2sagAAAFI9OgCfOwMBUjsPAE0/N1psAAAATT4/020AAABNPT5DbwAAAE08PaxqAAAATT4QrGoAAABNPT6bcAAAAJ87AwFSOwoATT83WmwAAABNPj/TbQAAAE09PkNvAAAATTw9rGoAAADZPQYAEgE4/xIANwASABYAEgAFAJ87AwHGOwAAbz4TANk/BwASATv/EgE2/7w8ByhxAAAAnzwEAcE4AACMNwAA2TgIABIABwASAAgAEgAvABIAIwASAAQAEgAnABIAJAASACkAEgAiABIACwASAAYAEgEx/xIBMv8SAC0AEgADABIAMAASATf/EgA1AIw5AADZOgkAEgE5/xIAGAASAAMAEgApAMY7AADZPAoAEgAtABIBO/8SADoAEgAuABIAMwASACsAEgApAMY9AABNQSlabAAAAE1AQdNtAAAATT9Ag3IAAABNPj+sagAAAE1GKFt0AAAATUVG2EMAAABNREU7QAAAAE1DRCdEAAAATUJDIz8AAABNQUIydQAAAE1AQY1zAAAATT9APHYAAADAQHcAEgALAG9DeABSREAAvEEHKHEAAACfQQQB2UEMABIABwASABsAEgE9/xIACwASAB8AEgAgABIAEAASACoAEgA+ABIAHQASABwAEgA/AP9CAAAAAAAAwEN5ABIAQgASACQAEgApABIACAASABcAEgAoAIxGAQCMRAMAjEUBAKhEEQBvSHoAUkpGALxISI17AAAAn0gDAlJHSACHSyRHTUpLC3wAAADZSw4AEgBCABIARwASAEMAvEglb30AAACfSAQBi0Tv/1JCBgDGQwAAxkQAAGRCkwD/RwAAAgAAAE1KKzh+AAAAb01/AFJORQBzTE1OvEpKA4AAAACfSgMCTU0pWmwAAABNTE1igQAAAE1LTDh+AAAAb05/AFJPRQBzTU5PvEtLA4AAAACfSwMCxUdKAwEAAADGSAAAxkkAAGRHdgAOS3UATU5Gyn8AAAC8TAgCggAAAJ9MAwJNUEusagAAAE1PUCtUAAAATVBGyn8AAAC8TQj1gwAAAJ9NBAFNTkusagAAAE1NTsOEAAAAb0+FAE1RRoyGAAAAvE9PjXsAAACfTwMCUk5PADBOTfWHAAAATVBLrGoAAABNT1CuiAAAAE1QRsp/AAAAvE0IIYkAAACfTQQBTU9Gyn8AAAC8TQgligAAAJ9NAwJSThQATU9Gyn8AAACfTgICTVFOrGoAAABNUFEsiwAAAE1PUMOEAAAAqVAAADBQT4CMAAAATVFOrGoAAABNUFEsiwAAAE1PUGeNAAAAqVAAADBQT4CMAAAApE9MAAAsoYSMUAEAjFEBAJ9PAwIwT04vjgAAAPBNAwCPAAAA8E0OAI0AAIBNTxZ5kAAAAE1RS6xqAAAATVBRw4QAAABvUZEA4lKTAG9TTQAwU1IskgAAAJ9PBAFlAAkATVBLrGoAAABNT1DDhAAAAE1RFxSUAAAAh1BRTTBQT3OVAAAATVFLrGoAAADZUg8AEgBLABIAKwASAAwAEgATABIARgC8TxKBlgAAAJ9PBAHiT5gATVBGyn8AAAAwUE/KfwAAAE1QSzuXAAAAMFBPO5cAAABqTy5LbkeJ/wIAAABuQmz/AgAAAE1DKVpsAAAATUJD020AAAC8QkJomQAAAJ9CAgRkQjkAb0k+ALxHRv6aAAAAn0cDAg5HNABNR0a6UwAAAPBHCgByAACAUkcPAE1IRqxqAAAATUoQrGoAAABNSUrXmwAAAJ9HAwFlABUATUdGulMAAADwRwoAnAAAgFJHDwBNSEasagAAAE1KEKxqAAAATUlKbp0AAACfRwMBZQAIAFJHDwBNSEasagAAAE1KEKxqAAAATUlKm3AAAACfRwMBqUcAAFJICgBNSUasagAAANlKEAASAUf/EgBGABIAGAASAAsAEgAeABIAJAASACMAEgAEABIAJwDZSxEAEgBGAJ9IBAHBRwAAbkLG/wIAAABNRCrPIQAAAMBFngASAAwAvEIRip8AAACfQgQBTUYpWmwAAABNRUZBoAAAAE1ERaxqAAAATUNEK1QAAABNQkPDhAAAAP9FAAACAAAAb0ahAG9HogDFRUYDAQAAAMBGowASAAgAEgAvABIAQgASABAAEgAJABIAKQASABwAEgAdABIAQQC8QwcocQAAAJ9DBAH/RQAABgAAAG9GpABvR6UAb0imAG9JeABvSqcAb0uoAMVFRgcBAAAAwEapABIALgASACYAEgAIALxDByhxAAAAn0MEAW9FqgC8Q0KUqwAAAJ9DAwLARawAEgBCABIAKAC8Q0PHZwAAAJ9DAwFSQw8ATUYpWmwAAABNRUZBoAAAAE1ERaxqAAAATUYQrGoAAABNRUabcAAAAJ9DAwFSQwoATUYpWmwAAABNRUZBoAAAAE1ERaxqAAAAUkU4AJ9DAwFSQw8ATUYpWmwAAABNRUYQrQAAAE1ERaxqAAAATUYQrGoAAABNRUbXmwAAAJ9DAwFSQwoATUYpWmwAAABNRUYQrQAAAE1ERaxqAAAA2UUWABIBN/8SAC0AEgEy/xIAAwASADUAn0MDAVJDDwBNRimYaAAAAE1FRmNpAAAATURFrGoAAABNRhCsagAAAE1FRm9rAAAAn0MDAVJDCgBNRimYaAAAAE1FRmNpAAAATURFrGoAAADARa4AEgAMAJ9DAwFSQxoAb0RNAFJFQQCfQwMBjEMKADBDLeyvAAAATUQpWmwAAABNQ0QQrQAAAKlEAAAwREOAjAAAAG9FrwC8Qy2UqwAAAJ9DAwJSRTwAvENDx2cAAACfQwMBUkM8AJ9DAQFvRQ0AwEawABIAFgASACkAEgAZALxDDKqxAAAAn0MEAW9FDQDARrIAEgAWABIAKQASABkAvEMMn7MAAACfQwQB/0MAAAAAAADBMQAAgkMCALQBA6ABBAAAAEADoQEDogEDowEDpAEDpQEDpgEDpwEDqAEEAACQQAOpAQOqAQNLA6sBA6wBA60BA64BA68BA0MDsAEDsQEDsgEDswEDtAEDtQEDtgEDtwEDuAEDuQEDugEDuwEDvAEDEQO9AQO+AQO/AQPAAQPBAQPCAQPDAQPEAQPFAQPGAQPHAQNQA8gBA8kBA8oBAxgDywEDzAEDzQEDzgEDzwED0AED0QED0gED0wED1AED1QED1gEDeQPXAQPYAQPZAQQAABBEA9oBA9sBA9wBA90BA94BAyQD3wEDCQPgAQQALKGEAgAAAAAAAOA/A+EBAwoEADzhhAPiAQM5AxoDmQEFA1JTVAPjAQPkAQNVBAA8gYUDHQNWA+UBBFxsocUGAAYBA+YBA+cBA+gBA+kBA+oBA+sBBggD7AED7QEDnQEDfgOWAQMuA4YBA+4BA+8BA/ABA/EBA5IBA/IBA/MBA/QBA/UBBg4DXwYRA4UBA2sDSQP2AQOPAQMqA4cBA1MDiAEDnAEDXQP3AQP4AQNpAzUDOwP5AQP6AQMwA/sBA4QBAzYDPQM+Az8FAZIBA/wBA5cBA/0BA1wFAn+XAQMZA/4BA/8BA54BA4ACBhYDgQIDLwNjA4ICBhcDgwIDhAIDhQIDhgIDhwIGGAOCAQOIAgYZAzEGGwMBBhwDiQIGHQOKAhoAAQMEBwgJCgsMDQ4PERITFBUWFxgZGhscHQEAAQgAAgAAAAAAAQAAAAAAAQAAAAAAAQAAAAAAAQAAAAAAAQAAAAAAAgAAAAAAAAAAAQAAAAAAAAAAAAABAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAEAAAAAAAAAAAAAAQAAAAAAAAAAAQAAAAAAAAEAAAAAAAAAAAEAAAAAAAAAAAAAAQAAAAAAAAEAAAAAAAABAAAAAAAAAAABAAAAAAAAAAAAAAEAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAEAAAAAAAAAAAEAAAAAAAABAAAAAAAAAAAAAAEAAAAAAAAAAAAAAQAAAAAAAAAAAAABAAAAAAAAAAAA4gAAAQAAAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAABAAAAAAAAAAABAAAAAAAAAAAAAAEAAAAAAAAAAAEAAAAAAAAAAAAAAQAAAAAAAAAAAQAAAAAAAAAAAAABAAAAAAAAAAAAAAMAAQAAAAEAAAACAAAAAAAAAAAAAAAAAAEAAAABAAAAAQAAAAIAAAAAAQAAAAcAAgAAAAAAAAAAAAIAAAAAAAEBAgAADgUAAAAAAAAAAAAeAQAAAAAAAQIAAAAAAAACAAAACQAAAAAAAAAQAAAAAAAABAAAAAAAAAAAAAAAAQAAAAAAAIQAAgAAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAIAAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAAABQEAAAAAAAAADQEAAAAAAAAAAAAAAAAAAAAAAAAnAQAAAAANAQAAAAAAAAATAQAAAAAAAAABAAAAAAAAAAAAAAAAAAAAAgAOAAAAAAMAAAAAAAAAAAAAAAAtAAIAAAAAAAAYAAAAAQAAAAAAAQAAAAAAAAAAAP4MAAAAAQABAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAAAAgMAAAAAAQAAAAAAAAAAAQAAAAAAAAAAAAAAAAEAAAAAAAAAAAIAAAAAAQAAAAEAAAA1AAAAAAEAAAAAAAAAAAEAAAAAAAACAAAAAQAAAAAAAAAAAAAAAAIAAAAAAAAAAAMAAAAAAAAAAAAABwEAAAABAAAA/uEA/wAoAAAAAAAAAAEAAAAAAQAAAAEAAAAAAAAAAAEAAAABAAAAAAAAAAACAAAAAAAAAAIBAAAAAAAAAAAAAAAAEADwAPYAIwAAAAAAAAUAAAAAAAAAAAACAAAAAAAAAAAAAAAAAAAAAAAAFgAAAAAAAAAAAAAAAAAAAAALAAAAAAAAAAAABAAAAAAAAAAAAAAAAQAAAAAAAAAAAgAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAAHAAAAAAAAfgAAAAABAAAAAAAAAAAABAAAAAIAAAEAAAAAAAABAAAAAAAAAAEAAgAAAAAAAAAFAAAAAAAAAAUAAAABAAAAHgAAAHwAAADLAAAAggAAAAAeZlD2pGnjxSpUlJwwnASoL8Ngl7vdmKstUzoXf9Pi6Zaqhst1C9Y+oQ==

local v1 = game:GetService("Players")
local u2 = game:GetService("ReplicatedStorage")
game:GetService("RunService")
local u3 = game:GetService("TweenService")
local u4 = game:GetService("MarketplaceService")
local u5 = game:GetService("ExperienceNotificationService")
local u6 = require(u2.Shared.Data.WheelSpin)
local u7 = require(u2.Client.Framework.Services.LocalData)
local u8 = require(u2.Shared.Utils.Stats.ItemUtil)
local u9 = require(u2.Shared.Framework.Utilities.String.FormatSuffix)
local v10 = require(u2.Client.Gui.Utils.ClickableButton)
local u11 = require(u2.Shared.Framework.Network.Remote)
local u12 = require(u2.Client.Gui.GuiFrame)
require(u2.Shared.Types)
local v13 = require(u2.Client.Gui.GetScreenGuiHolder)
local v14 = require(u2.Client.Gui.Utils.AutoButtonColor)
local u15 = require(u2.Shared.Palette)
local u16 = require(u2.Client.Activation)
local v17 = require(u2.Client.Gui.Tooltip)
local u18 = require(u2.Shared.Data.Builders.TooltipBuilder)
local v19 = require(u2.Client.Gui.Utils.ItemFrame)
require(u2.Client.Framework.Utilities.Gui.HookScrollingFrame)
local u20 = require(u2.Shared.Utils.AnimateColor)
local u21 = require(u2.Shared.Constants)
local u22 = require(u2.Client.Gui.Utils.PlayLocalSound)
local u23 = require(u2.Client.Gui.Utils.Shiny)
local u24 = require(u2.Shared.Framework.Utilities.every)
local u25 = require(u2.Shared.Framework.Utilities.Math.Time)
local u26 = require(u2.Client.Framework.Utilities.Gui.Animations.SetFade)
local u27 = require(u2.Client.Gui.Utils.GuiArrow)
local u28 = require(u2.Client.Framework.Utilities.Gui.Confetti)
local u29 = require(u2.Client.Gui.Utils.Notification)
local u30 = require(u2.Shared.Utils.RichText)
local u31 = require(u2.Client.Gui.Animations.ItemFall)
local u32 = require(u2.Client.Effects.Bubble)
local u33 = require(u2.Client.Gui.Animations.ProcessingPurchase)
local u34 = require(u2.Shared.Data.Products)
local v35 = require(u2.Shared.Framework.Utilities.ProductInfo)
local u36 = require(u2.Shared.Utils.Stats.StatsUtil)
local u37 = v1.LocalPlayer
local u38 = u37.PlayerGui.ScreenGui
local u39 = u38.WheelSpin.Frame
local u40 = workspace.Worlds["The Overworld"].Islands["Floating Island"].Island.WheelSpin
local u41 = u40.Display.SurfaceGui
u41.Parent = v13()
u41.Adornee = u40.Display
local u42 = UDim2.fromScale(0.5, 0.5)
local u43 = Instance.new("NumberValue")
local u44 = {}
local u45 = {
    ["Type"] = "Powerup",
    ["Name"] = "Spin Ticket",
    ["Amount"] = 1
}
local u46 = TweenInfo.new(6, Enum.EasingStyle.Circular)
local u47 = 1
local u48 = 0
local function u56(p49) --[[Anonymous function at line 70]]
    --[[
    Upvalues:
        [1] = u43
        [2] = u42
    --]]
    local v50 = u43.Value
    local v51 = math.rad(v50)
    local v52 = p49.X.Offset - u42.X.Offset
    local v53 = p49.Y.Offset - u42.Y.Offset
    local v54 = math.cos(v51)
    local v55 = math.sin(v51)
    return UDim2.new(p49.X.Scale, v52 * v54 - v53 * v55 + u42.X.Offset, p49.Y.Scale, v52 * v55 + v53 * v54 + u42.Y.Offset)
end
local function u60(p57) --[[Anonymous function at line 89]]
    --[[
    Upvalues:
        [1] = u16
        [2] = u40
        [3] = u2
        [4] = u31
        [5] = u6
        [6] = u47
        [7] = u11
        [8] = u32
        [9] = u39
    --]]
    if p57 then
        u16:Beam(u40.Activation).Color = Color3.fromRGB(39, 237, 255)
        for _, v58 in u2.Assets.Particles.Confetti:GetChildren() do
            if v58.Name ~= "Glow" then
                local u59 = v58:Clone()
                u59.EmissionDirection = Enum.NormalId.Left
                u59.Acceleration = Vector3.new(-4, 0, 0)
                u59.Enabled = false
                u59.Parent = u40.Activation.Root
                u59:Emit(20)
                task.delay(u59.Lifetime.Max, function() --[[Anonymous function at line 104]]
                    --[[
                    Upvalues:
                        [1] = u59
                    --]]
                    u59:Destroy()
                end)
            end
        end
        u31(u6[u47].Item)
        u11:FireServer("ClaimWheelSpinQueue")
    end
    u32.Faded = false
    u39.Main.Spin.Visible = true
    u39.Main.Skip.Visible = false
end
local u61 = u38.HUD.NotifyGame.Frame
local u62 = nil
local u63 = { "Emerald Golem", "Inferno Dragon", "Lunar Serpent" }
local function v64() --[[Anonymous function at line 125]]
    --[[
    Upvalues:
        [1] = u62
        [2] = u61
        [3] = u20
    --]]
    if u62 then
        u62:Disconnect()
        u62 = nil
    end
    u61.Parent.Visible = false
    u20.None(u61.Main.Icon.Legendary)
end
local function u68() --[[Anonymous function at line 134]]
    --[[
    Upvalues:
        [1] = u5
        [2] = u62
        [3] = u24
        [4] = u63
        [5] = u8
        [6] = u61
        [7] = u20
    --]]
    local v65, v66 = pcall(function() --[[Anonymous function at line 135]]
        --[[
        Upvalues:
            [1] = u5
        --]]
        return u5:CanPromptOptInAsync()
    end)
    if v65 and v66 then
        local u67 = 0
        u62 = u24(0.2, function() --[[Anonymous function at line 141]]
            --[[
            Upvalues:
                [1] = u67
                [2] = u63
                [3] = u8
                [4] = u61
            --]]
            u67 = (u67 + 1) % #u63 + 1
            u8:UpdateIcon(u61.Main.Icon, {
                ["Type"] = "Pet",
                ["Name"] = u63[u67]
            })
        end)
        u20.Cycle(u61.Main.Icon.Legendary, "Rainbow", {
            ["Speed"] = 0.4
        })
        u61.Parent.Visible = true
    end
end
u5.OptInPromptClosed:Connect(function() --[[Anonymous function at line 150]]
    --[[
    Upvalues:
        [1] = u11
    --]]
    u11:FireServer("FreeNotifyLegendary")
end)
v14(u61.Top.Close.Button, u15.Button.Red)
v10(u61.Top.Close.Button, v64)
v14(u61.Main.Buttons.Close.Button, u15.Button.Inactive)
v10(u61.Main.Buttons.Close.Button, v64)
v14(u61.Main.Buttons.Notify.Button, u15.Button.Green)
v10(u61.Main.Buttons.Notify.Button, function() --[[Anonymous function at line 161]]
    --[[
    Upvalues:
        [1] = u62
        [2] = u61
        [3] = u20
        [4] = u5
    --]]
    if u62 then
        u62:Disconnect()
        u62 = nil
    end
    u61.Parent.Visible = false
    u20.None(u61.Main.Icon.Legendary)
    u5:PromptOptIn()
end)
local u69 = nil
u7:ConnectDataChanged("Stats", function(p70) --[[Anonymous function at line 167]]
    --[[
    Upvalues:
        [1] = u69
        [2] = u68
    --]]
    local v71 = p70.Stats.WheelSpins
    if u69 ~= v71 then
        if v71 == 1 and u69 ~= nil then
            task.delay(2, u68)
        end
        u69 = v71
    end
end)
local u72 = 0
local function v79() --[[Anonymous function at line 181]]
    --[[
    Upvalues:
        [1] = u7
        [2] = u8
        [3] = u45
        [4] = u33
        [5] = u4
        [6] = u37
        [7] = u34
        [8] = u39
        [9] = u32
        [10] = u11
        [11] = u6
        [12] = u47
        [13] = u48
        [14] = u43
        [15] = u3
        [16] = u46
        [17] = u72
        [18] = u60
    --]]
    local v73 = u7:Get()
    if v73 then
        if u8:GetOwnedAmount(v73, u45) == 0 then
            u33:Show()
            u4:PromptProductPurchase(u37, u34["spin-1"].ProductId)
        else
            u39.Main.Spin.Visible = false
            u39.Main.Skip.Visible = true
            u32.Faded = true
            local v74 = u11:InvokeServer("WheelSpin")
            if v74 then
                local _ = u6[v74]
                local v75 = (v74 - 1) * 0.7853981633974483 - 0.39269908169872414
                local v76 = -math.deg(v75) + 40 * (math.random() - 0.5)
                u47 = v74
                u48 = v76 - 1440
                u43.Value = 0
                u3:Create(u43, u46, {
                    ["Value"] = u48
                }):Play()
                local v77 = u72 + 1
                u72 = v77
                task.wait(u46.Time)
                if v77 ~= u72 then
                    return
                end
                local v78 = u43
                v78.Value = v78.Value % 360
            end
            u60(v74 ~= nil)
        end
    else
        return
    end
end
local u80 = 0
local function u82() --[[Anonymous function at line 221]]
    --[[
    Upvalues:
        [1] = u80
        [2] = u22
        [3] = u3
        [4] = u39
    --]]
    local v81 = u80 + 1
    u80 = v81
    u22("Click")
    u3:Create(u39.Main.Spinner.Ticker, TweenInfo.new(0.1, Enum.EasingStyle.Quint), {
        ["Rotation"] = 30
    }):Play()
    task.wait(0.1)
    if v81 == u80 then
        u3:Create(u39.Main.Spinner.Ticker, TweenInfo.new(0.3), {
            ["Rotation"] = 0
        }):Play()
    end
end
local u83 = nil
local function v91() --[[Anonymous function at line 235]]
    --[[
    Upvalues:
        [1] = u43
        [2] = u83
        [3] = u82
        [4] = u44
        [5] = u56
        [6] = u41
        [7] = u39
    --]]
    local v84 = u43.Value % 360 / 45 - 22.5
    local v85 = math.round(v84)
    local v86 = math.floor(v85)
    if u83 == nil then
        u83 = v86
    elseif u83 ~= v86 then
        u83 = v86
        u82()
    end
    local v87 = u43.Value % 360 / 45 - 22.5
    local v88 = math.round(v87)
    math.floor(v88)
    for v89, v90 in u44 do
        v89.Position = u56(v90.Position)
    end
    u41.Spinner.Rotation = u43.Value
    u39.Main.Spinner.Label.Rotation = u43.Value
end
local u92 = nil
local u93 = u39.Main.Buttons.Free.Button
local u94 = u38.WorldMap.Worlds["The Overworld"].Islands["Floating Island"].Activities["Spin to Win"].Timer
u7:ConnectDataChanged("MasteryUpgrades", function(p95) --[[Function name: tryAutoClaim, line 258]]
    --[[
    Upvalues:
        [1] = u11
    --]]
    local v96 = false
    for _, v97 in p95.MasteryUpgrades do
        if v97.Type == "AutoClaimSpin" then
            v96 = true
            break
        end
    end
    if v96 then
        u11:FireServer("ClaimFreeWheelSpin")
    end
    return v96
end)
local function u105() --[[Anonymous function at line 275]]
    --[[
    Upvalues:
        [1] = u7
        [2] = u25
        [3] = u92
        [4] = u11
        [5] = u29
        [6] = u30
        [7] = u15
        [8] = u40
        [9] = u93
        [10] = u27
        [11] = u26
        [12] = u94
    --]]
    local v98 = u7:Get()
    if not v98 then
        return
    end
    local v99 = v98.NextWheelSpin - u25.now()
    local v100 = math.max(0, v99)
    local v101 = v100 == 0
    if u92 ~= v101 then
        if u92 ~= nil and v101 then
            local v102 = false
            for _, v103 in v98.MasteryUpgrades do
                if v103.Type == "AutoClaimSpin" then
                    v102 = true
                    break
                end
            end
            if v102 then
                u11:FireServer("ClaimFreeWheelSpin")
            end
            if not v102 then
                u29(("You have a %* waiting to be claimed!"):format((u30.autoColor("Free Spin", u15.Text.Cyan))), {
                    ["TeleportId"] = u40.Activation.Root:GetFullName(),
                    ["Sound"] = "NotificationRift"
                })
            end
        end
        if v101 then
            u93.Title.Text = "Claim"
            u93.Label.Text = "FREE SPIN"
            u40.Activation.Root.BillboardGui.Description.Text = "Claim your FREE spin!"
            u27:Add(u93.Parent)
        else
            u93.Title.Text = "Free spin in"
            u27:Remove(u93.Parent)
        end
        u26(u93.Parent, v101 and 0 or 0.25, TweenInfo.new(0.2, Enum.EasingStyle.Quint), { "Frame", "ImageLabel" })
        u92 = v101
        u94.Visible = not v101
    end
    if u93.Title.Text ~= "Claim" then
        local v104 = u25.formatTime(v100)
        u93.Label.Text = v104
        u94.Text = u25.formatTime(v100, true)
        u40.Activation.Root.BillboardGui.Description.Text = ("Free spin in %*"):format(v104)
    end
end
local u106 = {}
local u107 = u72
local u108 = u48
local function u116() --[[Anonymous function at line 322]]
    --[[
    Upvalues:
        [1] = u106
        [2] = u34
        [3] = u39
        [4] = u8
        [5] = u21
        [6] = u38
    --]]
    for v109 = 1, 3 do
        local v110 = ("spin-%*"):format(v109)
        local v111 = u106[v110]
        local v112 = u34[v110]
        if v112.Type == "Item" then
            local u113 = u39.Main.Buttons:FindFirstChild(v110)
            if u113 then
                if v109 == 3 then
                    local v114 = u8:GetAmount(v112.Item)
                    local v115 = u106["spin-1"]
                    u113.Button.Cost.Before.Text = ("%*%*"):format(u21.RobuxUnicode, v115 and v115 * v114 or "__")
                    task.defer(function() --[[Anonymous function at line 338]]
                        --[[
                        Upvalues:
                            [1] = u113
                            [2] = u38
                        --]]
                        u113.Button.Cost.Before.Size = UDim2.fromOffset(u113.Button.Cost.Before.TextBounds.X / u38.UIScale.Scale, 30)
                    end)
                end
                u113.Button.Cost.Label.Text = ("%*%*"):format(u21.RobuxUnicode, v111 or "__")
            end
        end
    end
end
for v117 = 1, 3 do
    local u118 = ("spin-%*"):format(v117)
    v35:ConnectProductChanged(u34[u118].ProductId, function(p119) --[[Anonymous function at line 348]]
        --[[
        Upvalues:
            [1] = u106
            [2] = u118
            [3] = u116
        --]]
        if p119 and p119.PriceInRobux then
            u106[u118] = p119.PriceInRobux
        end
        u116()
    end)
end
for v120, u121 in u6 do
    for _, u122 in { u41.Items:FindFirstChild("Item" .. v120), (u39.Main.Spinner.Items:FindFirstChild("Item" .. v120)) } do
        if u122 then
            u8:GetAmount(u121.Item)
            u8:FormatAmount(u122.Button.Amount, u121.Item)
            u122.Button.Label.Text = ("%*%%"):format(u121.Chance)
            u8:UpdateIcon(u122.Button.Icon, u121.Item)
            local v123 = u8:GetRarity(u121.Item)
            local v124 = v19(u121.Item)
            v124.Button.Inner.Label.Visible = false
            v124.Button.Inner.Secret.Visible = false
            v124.Size = UDim2.fromScale(1, 1)
            if v123 == "Legendary" or v123 == "Secret" then
                u20.Cycle(u122.Button.Label, "Rainbow", {
                    ["Speed"] = 0.5
                })
            else
                u122.Button.Label.TextColor3 = u21.RarityColors[v123]
            end
            v17:OnEnter(u122.Button, function() --[[Anonymous function at line 383]]
                --[[
                Upvalues:
                    [1] = u122
                    [2] = u41
                    [3] = u12
                    [4] = u18
                    [5] = u121
                --]]
                if u122.Parent ~= u41.Items or not u12:IsAnyOpen() then
                    return u18.fromItem(u121.Item)
                end
            end)
            u44[u122] = {
                ["Item"] = u121.Item,
                ["Position"] = u122.Position
            }
        end
    end
end
for _, u125 in u39.Main.Buttons:GetChildren() do
    if u125:IsA("Frame") then
        if u125.Name == "Free" then
            v14(u125.Button, u15.Button.Pink)
        elseif u125.Name == "spin-3" then
            v14(u125.Button, u15.Button.Orange)
        else
            v14(u125.Button, u15.Button.Green)
        end
        local u126 = false
        v10(u125.Button, function() --[[Anonymous function at line 408]]
            --[[
            Upvalues:
                [1] = u126
                [2] = u125
                [3] = u22
                [4] = u11
                [5] = u28
                [6] = u34
                [7] = u33
                [8] = u4
                [9] = u37
            --]]
            if not u126 then
                if u125.Name == "Free" then
                    u22("FreeItem")
                    u11:FireServer("ClaimFreeWheelSpin")
                    u28:Emit(u28.Explosion, 10)
                else
                    local v127 = u34[u125.Name]
                    u33:Show()
                    u4:PromptProductPurchase(u37, v127.ProductId)
                end
                u126 = true
                task.wait(0.2)
                u126 = false
            end
        end, function() --[[Anonymous function at line 424]]
            --[[
            Upvalues:
                [1] = u125
            --]]
            return u125.Name ~= "Free" and true or u125.Button.Title.Text == "Claim"
        end)
    end
end
u16:Bind(u40.Activation, function() --[[Anonymous function at line 433]]
    --[[
    Upvalues:
        [1] = u12
    --]]
    u12:Open("WheelSpin")
end)
local u128 = u39.Main.Spin.Button.Amount.Label
u7:ConnectDataChanged({ "NextWheelSpin", "Powerups" }, function(p129) --[[Anonymous function at line 440]]
    --[[
    Upvalues:
        [1] = u8
        [2] = u45
        [3] = u128
        [4] = u15
        [5] = u9
        [6] = u39
        [7] = u26
        [8] = u27
        [9] = u105
    --]]
    local v130 = u8:GetOwnedAmount(p129, u45)
    u128.TextColor3 = v130 > 0 and Color3.new(1, 1, 1) or u15.Text.Red
    u128.Text = u9(v130)
    u39.Main.Spin.Button.Title.Visible = v130 > 0
    u26(u39.Main.Spin.Button, v130 > 0 and 0 or 0.35, TweenInfo.new(0.2, Enum.EasingStyle.Quint), { "Frame" })
    if v130 == 1 then
        u27:Add(u39.Main.Spin, 45)
    else
        u27:Remove(u39.Main.Spin)
    end
    u105()
end)
u7:ConnectDataChanged({
    "Passes",
    "TeamEquipped",
    "Teams",
    "MasteryUpgrades",
    "ActivePotions",
    "ActiveBuffs"
}, function(p131) --[[Anonymous function at line 462]]
    --[[
    Upvalues:
        [1] = u44
        [2] = u36
        [3] = u8
    --]]
    for v132, v133 in u44 do
        if v133.Item.Type == "Currency" then
            local v134 = v133.Item.Amount * u36:GetCurrencyMultiplier(p131, v133.Item.Currency, true)
            local v135 = math.ceil(v134)
            u8:FormatAmount(v132.Button.Amount, {
                ["Type"] = "Currency",
                ["Currency"] = v133.Item.Currency,
                ["Amount"] = v135
            })
        end
    end
end)
u128:GetPropertyChangedSignal("TextBounds"):Connect(function() --[[Anonymous function at line 473]]
    --[[
    Upvalues:
        [1] = u128
        [2] = u38
    --]]
    u128.Size = UDim2.new(0, u128.TextBounds.X / u38.UIScale.Scale, 1, 0)
end)
v14(u39.Main.Spin.Button, u15.Button.Green)
v10(u39.Main.Spin.Button, v79)
v14(u39.Main.Skip.Button, u15.Button.Pink)
v10(u39.Main.Skip.Button, function() --[[Anonymous function at line 481]]
    --[[
    Upvalues:
        [1] = u107
        [2] = u43
        [3] = u108
        [4] = u3
        [5] = u60
    --]]
    u107 = u107 + 1
    u43.Value = u108
    local v136 = {
        ["Value"] = u108
    }
    u3:Create(u43, TweenInfo.new(0.01), v136):Play()
    u60(true)
end)
v14(u39.Top.Close.Button, u15.Button.Red)
v10(u39.Top.Close.Button, function() --[[Anonymous function at line 489]]
    --[[
    Upvalues:
        [1] = u12
    --]]
    u12:Close()
end)
u24(0.5, u105)
u43.Value = 10
u39.Main.Skip.Visible = false
u43:GetPropertyChangedSignal("Value"):Connect(v91)
v91()
u12:BindOnOpened("WheelSpin", function() --[[Anonymous function at line 500]]
    --[[
    Upvalues:
        [1] = u20
        [2] = u39
        [3] = u23
    --]]
    u20.Cycle(u39.Main.Title, "Rainbow", {
        ["Speed"] = 0.5
    })
    u23:Add(u39.Main.Buttons["spin-3"].Effect)
end)
u12:BindOnClosed("WheelSpin", function() --[[Anonymous function at line 505]]
    --[[
    Upvalues:
        [1] = u20
        [2] = u39
        [3] = u23
    --]]
    u20.None(u39.Main.Title)
    u23:Remove(u39.Main.Buttons["spin-3"].Effect)
end)
return {}