--devbgascension

-- Bytecode (Base64):
-- BgMqCFVJU3Ryb2tlFUZpbmRGaXJzdENoaWxkT2ZDbGFzcwROb25lB0Rlc3Ryb3kFQ2xvbmUFVURpbTIJZnJvbVNjYWxlBFNpemUJVGhpY2tuZXNzDFRyYW5zcGFyZW5jeQZDcmVhdGUEUGxheQNuZXcEdGFzawVkZWxheQRUaW1lDE91dGxpbmVQdWxzZQRnYW1lDFR3ZWVuU2VydmljZQpHZXRTZXJ2aWNlEVJlcGxpY2F0ZWRTdG9yYWdlB3JlcXVpcmUGU2hhcmVkBVV0aWxzDEFuaW1hdGVDb2xvcghJbnN0YW5jZQVGcmFtZQhQb3NpdGlvbgdWZWN0b3IyA29uZQtBbmNob3JQb2ludBZCYWNrZ3JvdW5kVHJhbnNwYXJlbmN5CFVJQ29ybmVyBFVEaW0MQ29ybmVyUmFkaXVzBlBhcmVudAZDb2xvcjMFQ29sb3IJVHdlZW5JbmZvBEVudW0LRWFzaW5nU3R5bGUEU2luZQADBAACAAAAEvsAAABvAgAAvAAAuAEAAACfAAMCDgAHAPsCAQBNAQI/AgAAAPsDAABNAgNtAAAAAJ8BAgH7AQAAvAEBUAMAAACfAQIBggABAAQDAQMCAwMDBAAqAAEYAAAAAAABAQAAAAAAAAIAAAABKwAAAAAMAQQAAAYDAAAFAYU9+wEAALwBAToAAAAAnwECAqQCAwAACBCAjAMBAIwEAQCfAgMCMAIBLwQAAAAOAAMAUgIAAFIDAQCfAgIB+wIBAE0EAW0FAAAA+wUCAOIGCACMBwAAMAcGGAYAAACMBwEAMAcG2QcAAAC8AgKWCQAAAJ8CBQK8AgLuCgAAAJ8CAgH7AgEAUgQBAPsFAgDiBgsApAcNAAAwEICMCAEAjAkoAIwKAQCMCygAnwcFAjAHBi8EAAAAvAIClgkAAACfAgUCvAIC7goAAACfAgIBpAIQAAA84ID7BAIATQMEShEAAADZBAAAEgABABICAwCfAgMBggECABIDBQMGAwcEAAgQgAMIAwEDCQMKBQIGBwMLAwwFAQQDDQQAMBCAAw4DDwQAPOCAAxABAB4RARgAAAAAAQAAAAAAAAEBAAADAAAAAAEAAAEAAP4AAAMAAAEAAAAAAAAAAAAAAAAAAAAAAAABAAAAAAAAAAAIHwAAAAAKAAABAgBaowAAAKQAAQAAAABAbwICALwAABYDAAAAnwADAqQBAQAAAABAbwMEALwBARYDAAAAnwEDAqQCBgAAAFBATQUBEgcAAABNBAWhCAAAAE0DBOgJAAAAnwICAqQDDAAALKCAbwQNAJ8DAgKkBBAAADzggIwFAQCMBgEAnwQDAjAEAy8RAAAApAQQAAA84IBvBRIAbwYSAJ8EAwIwBAM7EwAAAKQFFwAAWFCBPgQFFDAEA+gYAAAAjAQBADAEAzoZAAAApAQMAAAsoIBvBRoAnwQCAqQFHAAALLCBjAYAAIwHCACfBQMCMAUETx0AAAAwAwQkHgAAAKQFDAAALKCAbwYfAJ8FAgKkBiEAACwAgowHAQCMCAEAjAkBAJ8GBAIwBgWkIgAAAIwGAwAwBgUYIwAAADADBSQeAAAApAYlAAAsQIJvByYApAgqACmgcMKfBgMCwAcrABIAAwASAAAAEgAGABIAAgCCBwIALAMSBAAAAEADEwMUAxUDFgQAAFBAAxcDGAMZAxoDDQQALKCAAxsDBgMHBAA84IADCAIAAAAAAADgPwMcAgAAAAAAAABAAx0DHgQAWFCBAx8DIAMhAyIEACywgQMjAyQDAQMlBAAsAIIDJgMJAycEACxAggIzMzMzMzPrPwMoAykDKgQpoHDCBgEBAQEAARgAAgAAAAAAAQAAAAAAAgAAAAAAAAAAAgAAAAEAAAAAAAABAAAAAAAAAQAAAAABAAACAAAAAQAAAAAAAAEAAgAAAAEAAAAAAAAAAQAAAQAHAAAAAAACAAAAABgBAAAAAALJdDMW8wP98PuwWYLvLzu8HOmpB/R3QUvrJnNobvkK69583nsRTjV8

local u1 = game:GetService("TweenService")
local v2 = game:GetService("ReplicatedStorage")
local u3 = require(v2.Shared.Utils.AnimateColor)
local u4 = Instance.new("Frame")
u4.Size = UDim2.fromScale(1, 1)
u4.Position = UDim2.fromScale(0.5, 0.5)
u4.AnchorPoint = Vector2.one / 2
u4.BackgroundTransparency = 1
local v5 = Instance.new("UICorner")
v5.CornerRadius = UDim.new(0, 8)
v5.Parent = u4
local v6 = Instance.new("UIStroke")
v6.Color = Color3.new(1, 1, 1)
v6.Thickness = 3
v6.Parent = u4
local u7 = TweenInfo.new(0.85, Enum.EasingStyle.Sine)
return function(p8) --[[Function name: OutlinePulse, line 30]]
    --[[
    Upvalues:
        [1] = u4
        [2] = u1
        [3] = u7
        [4] = u3
    --]]
    local u9 = u4:Clone()
    u9.Size = UDim2.fromScale(1, 1)
    if p8 then
        p8(u9)
    end
    u1:Create(u9.UIStroke, u7, {
        ["Thickness"] = 0,
        ["Transparency"] = 1
    }):Play()
    u1:Create(u9, u7, {
        ["Size"] = UDim2.new(1, 40, 1, 40)
    }):Play()
    task.delay(u7.Time, function() --[[Anonymous function at line 42]]
        --[[
        Upvalues:
            [1] = u9
            [2] = u3
        --]]
        if u9:FindFirstChildOfClass("UIStroke") then
            u3.None(u9.UIStroke)
        end
        u9:Destroy()
    end)
    return u9
end