--devbgascension

-- Bytecode (Base64):
-- BgMjBGdhbWURUmVwbGljYXRlZFN0b3JhZ2UKR2V0U2VydmljZQdyZXF1aXJlBkNsaWVudANHdWkFVXRpbHMPQXV0b0J1dHRvbkNvbG9yDUNvbG9yU2VxdWVuY2UDbmV3BkNvbG9yMwdmcm9tUkdCBkJ1dHRvbgVDb2xvcgRUZXh0B0RlZmF1bHQFTGlnaHQFRW1wdHkGQWN0aXZlCEluYWN0aXZlA1JlZAZPcmFuZ2UFR3JlZW4EQmx1ZQZQdXJwbGUEUGluawRDeWFuA0dlbQRHb2xkBUVudGVyBVByZXNzBlN0cm9rZQdmcm9tSGV4ByMwMDI5NUUGWWVsbG93AAEMAAABAgCQBqMAAACkAAEAAAAAQG8CAgC8AAAWAwAAAJ8AAwKkAQUAAABAQE0FAE0GAAAATQQFHwcAAABNAwShCAAAAE0CA9cJAAAAnwECAqQCDAAALKCApAMPAAA40ICMBOwAjAXsAIwGNACfAwQCpAQPAAA40ICMBdkAjAamAIwHPwCfBAQAnwIAAuIDEwDiBCIA4gUlAKQGDAAALKCApAcPAAA40ICMCBsAjAmtAIwK7ACfBwQCpAgPAAA40ICMCSEAjAp6AIwL2QCfCAQAnwYAAjAGBaQRAAAApAYMAAAsoICkBw8AADjQgIwITQCMCdwAjArsAJ8HBAKkCA8AADjQgIwJLwCMCp0AjAvZAJ8IBACfBgACMAYFGCMAAAAwAgXrJAAAADAFBDoUAAAA4gUnAKQGDAAALKCApAcPAAA40ICMCLcAjAnyAIwK/wCfBwQCpAgPAAA40ICMCXMAjAqmAIwL8wCfCAQAnwYAAjAGBaQRAAAApAYMAAAsoICkBw8AADjQgIwI1ACMCfUAjAr/AJ8HBAKkCA8AADjQgIwJmQCMCswAjAvzAJ8IBACfBgACMAYFGCMAAACkBg8AADjQgIwHVwCMCGYAjAnHAJ8GBAIwBgWlJgAAADACBeskAAAAMAUEDxUAAADiBSUApAYMAAAsoICkBygAACzQgIwIAQCMCQEAjAoBAJ8HBACfBgACMAYFpBEAAACkBgwAACyggKQHKAAALNCAjAgBAIwJAQCMCgEAnwcEAJ8GAAIwBgUYIwAAAKQGDAAALKCApAcoAAAs0ICMCAEAjAkBAIwKAQCfBwQAnwYAAjAGBeskAAAAMAUEjRYAAADiBSkApAYMAAAsoICkBw8AADjQgIwI7ACMCewAjAo0AJ8HBAKkCA8AADjQgIwJ2QCMCqYAjAs/AJ8IBACfBgACMAYFpBEAAACkBgwAACyggKQHDwAAONCAjAjsAIwJ7ACMCjQAnwcEAqQIDwAAONCAjAnZAIwKpgCMCz8AnwgEAJ8GAAIwBgUYIwAAAKQGDAAALKCApAcPAAA40ICMCOwAjAm9AIwKMACfBwQCpAgPAAA40ICMCccAjAp6AIwLIgCfCAQAnwYAAjAGBeskAAAApAYPAAA40ICMB4sAjAhIAIwJDgCfBgQCMAYFpSYAAAAwBQSDFwAAAOIFJwCkBgwAACyggKQHDwAAONCAjAigAIwJsACMCrwAnwcEAqQIDwAAONCAjAl2AIwKgwCMC5UAnwgEAJ8GAAIwBgWkEQAAAKQGDAAALKCApAcPAAA40ICMCLYAjAnJAIwK1gCfBwQCpAgPAAA40ICMCaAAjAqwAIwLvACfCAQAnwYAAjAGBRgjAAAApAYPAAA40ICMB0oAjAhKAIwJSgCfBgQCMAYFpSYAAAAwAgXrJAAAADAFBLkYAAAA4gUnAKQGDAAALKCApAcPAAA40ICMCP8AjAlGAIwKRgCfBwQCpAgPAAA40ICMCbgAjAoHAIwLTgCfCAQAnwYAAjAGBaQRAAAApAYMAAAsoICkBw8AADjQgIwI/wCMCWMAjApYAJ8HBAKkCA8AADjQgIwJuACMCiMAjAteAJ8IBACfBgACMAYFGCMAAACkBg8AADjQgIwHiACMCAAAjAkAAJ8GBAIwBgWlJgAAADACBeskAAAAMAUEbxkAAADiBScApAYMAAAsoICkBw8AADjQgIwI/wCMCdMAjAolAJ8HBAKkCA8AADjQgIwJ/wCMCn4AjAszAJ8IBACfBgACMAYFpBEAAACkBgwAACyggKQHDwAAONCAjAj/AIwJ9ACMClUAnwcEAqQIDwAAONCAjAn/AIwKrwCMC0AAnwgEAJ8GAAIwBgUYIwAAAKQGDwAAONCAjAeLAIwISACMCQ4AnwYEAjAGBaUmAAAAMAIF6yQAAAAwBQRuGgAAAOIFJwCkBgwAACyggKQHDwAAONCAjAjQAIwJ/wCMCgAAnwcEAqQIDwAAONCAjAkmAIwK5gCMCyYAnwgEAJ8GAAIwBgWkEQAAAKQGDAAALKCApAcPAAA40ICMCNsAjAn/AIwKWACfBwQCpAgPAAA40ICMCUEAjAr/AIwLTgCfCAQAnwYAAjAGBRgjAAAApAYPAAA40ICMBykAjAiLAIwJBgCfBgQCMAYFpSYAAAAwAgXrJAAAADAFBJsbAAAA4gUlAKQGDAAALKCApAcPAAA40ICMCAAAjAnYAIwK7ACfBwQCpAgPAAA40ICMCQcAjAqHAIwL/wCfCAQAnwYAAjAGBaQRAAAApAYMAAAsoICkBw8AADjQgIwIHwCMCekAjArsAJ8HBAKkCA8AADjQgIwJNACMCoUAjAv/AJ8IBACfBgACMAYFGCMAAAAwAgXrJAAAADAFBNIcAAAA4gUnAKQGDAAALKCApAcPAAA40ICMCPsAjAl5AIwK/wCfBwQCpAgPAAA40ICMCakAjAprAIwL/wCfCAQAnwYAAjAGBaQRAAAApAYMAAAsoICkBw8AADjQgIwItgCMCWUAjArfAJ8HBAKkCA8AADjQgIwJfQCMClYAjAvfAJ8IBACfBgACMAYFGCMAAACkBg8AADjQgIwHbwCMCCkAjAmhAJ8GBAIwBgWlJgAAADACBeskAAAAMAUEZx0AAADiBScApAYMAAAsoICkBw8AADjQgIwI/wCMCYMAjAruAJ8HBAKkCA8AADjQgIwJ0QCMCjYAjAu/AJ8IBACfBgACMAYFpBEAAACkBgwAACyggKQHDwAAONCAjAj/AIwJqwCMCvsAnwcEAqQIDwAAONCAjAnRAIwKaQCMC7kAnwgEAJ8GAAIwBgUYIwAAAKQGDwAAONCAjAeBAIwIKQCMCX4AnwYEAjAGBaUmAAAAMAIF6yQAAAAwBQTXHgAAAOIFJQCkBgwAACyggKQHDwAAONCAjAgbAIwJrQCMCuwAnwcEAqQIDwAAONCAjAkhAIwKegCMC9kAnwgEAJ8GAAIwBgWkEQAAAKQGDAAALKCApAcPAAA40ICMCE0AjAncAIwK7ACfBwQCpAgPAAA40ICMCS8AjAqdAIwL2QCfCAQAnwYAAjAGBRgjAAAAMAIF6yQAAAAwBQSjHwAAAOIFJwCkBgwAACyggKQHDwAAONCAjAj/AIwJPACMCu8AnwcEAqQIDwAAONCAjAk3AIwKUgCMC/8AnwgEAJ8GAAIwBgWkEQAAAKQGDAAALKCApAcPAAA40ICMCP8AjAlrAIwK+ACfBwQCpAgPAAA40ICMCVkAjApKAIwL/wCfCAQAnwYAAjAGBRgjAAAApAYPAAA40ICMByQAjAgcAIwJiwCfBgQCMAYFpSYAAAAwAgXrJAAAADAFBDogAAAA4gUnAKQGDAAALKCApAcPAAA40ICMCP8AjAnnAIwKYACfBwQCpAgPAAA40ICMCegAjArFAIwLRACfCAQAnwYAAjAGBaQRAAAApAYMAAAsoICkBw8AADjQgIwI/wCMCfcAjAqOAJ8HBAKkCA8AADjQgIwJ/wCMCukAjAt4AJ8IBACfBgACMAYFGCMAAACkBg8AADjQgIwHmACMCG4AjAkEAJ8GBAIwBgWlJgAAADACBeskAAAAMAUEyyEAAAAwBAOsEAAAAOIEKgCkBSwAAKzQgG8GLQCfBQICMAUEOhQAAACkBQ8AADjQgIwG/wCMBwAAjAgAAJ8FBAIwBQRvGQAAAKQFDwAAONCAjAb/AIwHpgCMCEAAnwUEAjAFBG4aAAAApAUPAAA40ICMBkMAjAf/AIwIJgCfBQQCMAUEmxsAAACkBQ8AADjQgIwGAACMB+UAjAj/AJ8FBAIwBQSjHwAAAKQFDwAAONCAjAb/AIwHTwCMCPYAnwUEAjAFBNceAAAAMAQDpBEAAADiBC8ApAUPAAA40ICMBv8AjAc8AIwIPACfBQQCMAUEbxkAAACkBQ8AADjQgIwG/wCMB5cAjAguAJ8FBAIwBQRuGgAAAKQFDwAAONCAjAb/AIwH6QCMCEIAnwUEAjAFBH0uAAAApAUPAAA40ICMBlIAjAf/AIwIMwCfBQQCMAUEmxsAAACkBQ8AADjQgIwGogCMB+sAjAj/AJ8FBAIwBQSjHwAAAKQFDwAAONCAjAb/AIwHpgCMCPgAnwUEAjAFBNceAAAApAUPAAA40ICMBsAAjAdyAIwI/wCfBQQCMAUEZx0AAAAwBAP1EgAAAIIDAgAwAwEEAAAAQAMCAwMDBAQAAEBAAwUDBgMHAwgDCQMKBAAsoIADCwMMBAA40IADDQMOAw8FAxAREgMQAxEDEgMTAxQDFQMWAxcDGAMZAxoDGwMcAx0FDhQVFhcYGRobHB0eHyAhAx4DHwUDESMkAyAFBBEjJiQEACzQgAUEESMkJgUGFBkaGx8eAyEEAKzQgAMiAyMFBxkaLhsfHh0AAQABGAACAAAAAAACAAAAAAAAAAAAAAMAAAAAAAAAAAAAAAAAAAcBAQEAAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAABAP0ABgEAAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAABAAAAAAAAAAEA/AAHAQAAAAAAAAAAAAABAAAAAAAAAAAAAAEAAAAAAAAAAAAA/QAGAQAAAAAAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAD8AAcBAAAAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAABAPwABwEAAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAABAAAAAAAAAAEA/AAHAQAAAAAAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAQD8AAcBAAAAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAABAPwABwEAAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAABAP0ABgEAAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAABAAAAAAAAAAEA/AAHAQAAAAAAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAQD8AAcBAAAAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAAAAQD9AAYBAAAAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAABAPwABwEAAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAABAAAAAAAAAAEA/ACoAGABAAAAAAABAAAAAAAAAAEAAAAAAAAAAQAAAAAAAAABAAAAAAAAAAEAAAAAAAAA+gAJAQAAAAAAAAABAAAAAAAAAAEAAAAAAAAAAQAAAAAAAAABAAAAAAAAAAEAAAAAAAAAAQAAAAAAAAD5AAsBAAAAAAAY6hoerGR6KioucIoWy9gU/tXeGypP7d9wMI1yfZNN9kM4JvSCbOYl

local v1 = game:GetService("ReplicatedStorage")
require(v1.Client.Gui.Utils.AutoButtonColor)
local v2 = ColorSequence.new(Color3.fromRGB(236, 236, 52), Color3.fromRGB(217, 166, 63))
local v3 = {}
local v4 = {
    ["Default"] = {
        ["Color"] = ColorSequence.new(Color3.fromRGB(27, 173, 236), Color3.fromRGB(33, 122, 217)),
        ["Enter"] = ColorSequence.new(Color3.fromRGB(77, 220, 236), Color3.fromRGB(47, 157, 217)),
        ["Press"] = v2
    },
    ["Light"] = {
        ["Color"] = ColorSequence.new(Color3.fromRGB(183, 242, 255), Color3.fromRGB(115, 166, 243)),
        ["Enter"] = ColorSequence.new(Color3.fromRGB(212, 245, 255), Color3.fromRGB(153, 204, 243)),
        ["Stroke"] = Color3.fromRGB(87, 102, 199),
        ["Press"] = v2
    },
    ["Empty"] = {
        ["Color"] = ColorSequence.new(Color3.new(1, 1, 1)),
        ["Enter"] = ColorSequence.new(Color3.new(1, 1, 1)),
        ["Press"] = ColorSequence.new(Color3.new(1, 1, 1))
    },
    ["Active"] = {
        ["Color"] = ColorSequence.new(Color3.fromRGB(236, 236, 52), Color3.fromRGB(217, 166, 63)),
        ["Enter"] = ColorSequence.new(Color3.fromRGB(236, 236, 52), Color3.fromRGB(217, 166, 63)),
        ["Press"] = ColorSequence.new(Color3.fromRGB(236, 189, 48), Color3.fromRGB(199, 122, 34)),
        ["Stroke"] = Color3.fromRGB(139, 72, 14)
    },
    ["Inactive"] = {
        ["Color"] = ColorSequence.new(Color3.fromRGB(160, 176, 188), Color3.fromRGB(118, 131, 149)),
        ["Enter"] = ColorSequence.new(Color3.fromRGB(182, 201, 214), Color3.fromRGB(160, 176, 188)),
        ["Stroke"] = Color3.fromRGB(74, 74, 74),
        ["Press"] = v2
    },
    ["Red"] = {
        ["Color"] = ColorSequence.new(Color3.fromRGB(255, 70, 70), Color3.fromRGB(184, 7, 78)),
        ["Enter"] = ColorSequence.new(Color3.fromRGB(255, 99, 88), Color3.fromRGB(184, 35, 94)),
        ["Stroke"] = Color3.fromRGB(136, 0, 0),
        ["Press"] = v2
    },
    ["Orange"] = {
        ["Color"] = ColorSequence.new(Color3.fromRGB(255, 211, 37), Color3.fromRGB(255, 126, 51)),
        ["Enter"] = ColorSequence.new(Color3.fromRGB(255, 244, 85), Color3.fromRGB(255, 175, 64)),
        ["Stroke"] = Color3.fromRGB(139, 72, 14),
        ["Press"] = v2
    },
    ["Green"] = {
        ["Color"] = ColorSequence.new(Color3.fromRGB(208, 255, 0), Color3.fromRGB(38, 230, 38)),
        ["Enter"] = ColorSequence.new(Color3.fromRGB(219, 255, 88), Color3.fromRGB(65, 255, 78)),
        ["Stroke"] = Color3.fromRGB(41, 139, 6),
        ["Press"] = v2
    },
    ["Blue"] = {
        ["Color"] = ColorSequence.new(Color3.fromRGB(0, 216, 236), Color3.fromRGB(7, 135, 255)),
        ["Enter"] = ColorSequence.new(Color3.fromRGB(31, 233, 236), Color3.fromRGB(52, 133, 255)),
        ["Press"] = v2
    },
    ["Purple"] = {
        ["Color"] = ColorSequence.new(Color3.fromRGB(251, 121, 255), Color3.fromRGB(169, 107, 255)),
        ["Enter"] = ColorSequence.new(Color3.fromRGB(182, 101, 223), Color3.fromRGB(125, 86, 223)),
        ["Stroke"] = Color3.fromRGB(111, 41, 161),
        ["Press"] = v2
    },
    ["Pink"] = {
        ["Color"] = ColorSequence.new(Color3.fromRGB(255, 131, 238), Color3.fromRGB(209, 54, 191)),
        ["Enter"] = ColorSequence.new(Color3.fromRGB(255, 171, 251), Color3.fromRGB(209, 105, 185)),
        ["Stroke"] = Color3.fromRGB(129, 41, 126),
        ["Press"] = v2
    },
    ["Cyan"] = {
        ["Color"] = ColorSequence.new(Color3.fromRGB(27, 173, 236), Color3.fromRGB(33, 122, 217)),
        ["Enter"] = ColorSequence.new(Color3.fromRGB(77, 220, 236), Color3.fromRGB(47, 157, 217)),
        ["Press"] = v2
    },
    ["Gem"] = {
        ["Color"] = ColorSequence.new(Color3.fromRGB(255, 60, 239), Color3.fromRGB(55, 82, 255)),
        ["Enter"] = ColorSequence.new(Color3.fromRGB(255, 107, 248), Color3.fromRGB(89, 74, 255)),
        ["Stroke"] = Color3.fromRGB(36, 28, 139),
        ["Press"] = v2
    },
    ["Gold"] = {
        ["Color"] = ColorSequence.new(Color3.fromRGB(255, 231, 96), Color3.fromRGB(232, 197, 68)),
        ["Enter"] = ColorSequence.new(Color3.fromRGB(255, 247, 142), Color3.fromRGB(255, 233, 120)),
        ["Stroke"] = Color3.fromRGB(152, 110, 4),
        ["Press"] = v2
    }
}
v3.Button = v4
v3.Color = {
    ["Default"] = Color3.fromHex("#00295E"),
    ["Red"] = Color3.fromRGB(255, 0, 0),
    ["Orange"] = Color3.fromRGB(255, 166, 64),
    ["Green"] = Color3.fromRGB(67, 255, 38),
    ["Cyan"] = Color3.fromRGB(0, 229, 255),
    ["Pink"] = Color3.fromRGB(255, 79, 246)
}
v3.Text = {
    ["Red"] = Color3.fromRGB(255, 60, 60),
    ["Orange"] = Color3.fromRGB(255, 151, 46),
    ["Yellow"] = Color3.fromRGB(255, 233, 66),
    ["Green"] = Color3.fromRGB(82, 255, 51),
    ["Cyan"] = Color3.fromRGB(162, 235, 255),
    ["Pink"] = Color3.fromRGB(255, 166, 248),
    ["Purple"] = Color3.fromRGB(192, 114, 255)
}
return v3