--devbgascension

-- Bytecode (Base64):
-- BgMGAVgBWQFaB1ZlY3RvcjMDbmV3EEdldFBvc2l0aW9uT25BcmMAAgwEAAAACQYAAAUECAgCAilNBQB5AAAAAE0IAXkAAAAATQkAeQAAAAAmBwgJCQYHA0MEBQZbCQIBCQgJA/UJAgMJBwgJTQgAeAMAAABDBgcITQkBeAMAAABNCgB4AwAAACYICQoJBwgDQwUGB00HAHsEAAAATQoBewQAAABNCwB7BAAAACYJCgsJCAkDQwYHCDQ2BAYFBgAAUggEAFIJBQBSCgYApAcHAAAYUICfBwQCggcCAAgDAQIAAAAAAAAQQAIAAAAAAADwPwMCAwMDBAMFBAAYUIAAAwYBGAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAQAAAAAAAAAAAQAAAAAAAAAACQAAAAABAAABAgAHowAAAMAAAAAYAAC9AQAAADUAAL0BAAAAggACAAIGAAMGAQABAAEYAAIAAA0AAAEAAAAAAZ7bOc0NX8DerB9TWSg/Jzhrj3EYqUwQr2EZRU+KdC2SBeJPzCPq24Q=

function GetPositionOnArc(p1, p2, p3, p4)
    local v5 = p1.X + (p2.X - p1.X) * p4
    local v6 = p3 * 4 * p4 * (1 - p4) + p1.Y + (p2.Y - p1.Y) * p4
    local v7 = p1.Z + (p2.Z - p1.Z) * p4
    return Vector3.new(v5, v6, v7)
end
return GetPositionOnArc