--devbgascension

-- Bytecode (Base64):
-- BgMRBm51bWJlcgZhc3NlcnQKTmV4dE51bWJlcgRtYXRoA2xvZwRzcXJ0A2NvcxhSYW5kb21Ob3JtYWxEaXN0cmlidXRpb24EZ2FtZRFSZXBsaWNhdGVkU3RvcmFnZQpHZXRTZXJ2aWNlB3JlcXVpcmUGU2hhcmVkCUZyYW1ld29yawFUBlJhbmRvbQNuZXcAAgoDAgAACAUAAAUDAgICOvsFAABNBAVgAAAAAFIFAACfBAIATAEAAqQDAgAAABBAnwMAAfsFAABNBAVgAAAAAFIFAQCfBAIATAEAAqQDAgAAABBAnwMAAfsFAABNBAVgAAAAAFIFAgCfBAIATAEAAqQDAgAAABBAnwMAAfsDAQC8AwOFAwAAAJ8DAgL7BAEAvAQEhQMAAACfBAICuxEDA1IJAwCkCAcAABhQgJ8IAgJbBwgEuxkHAqQGCQAAIFCAnwYCAm8JCgAJCAkEuwkIAqQHDAAALFCAnwcCAgkFBgcmCQEAPggJDUMHCAAJCAUCQwYHCIIGAgAOAwEDAgQAABBAAwMCAAAAAAAAAMADBAMFBAAYUIADBgQAIFCAAhgtRFT7IRlAAwcEACxQgAIAAAAAAAAAQAAOCAEYAAAAAAAAAAAAAQAAAAAAAAAAAQAAAAAAAAAAAQAAAAEAAAABAAAAAAAAAAAAAAAAAAAAAAEAAAAAABMAAAAABQAAAQIAF6MAAACkAAEAAAAAQG8CAgC8AAAWAwAAAJ8AAwKkAQUAAABAQE0EABIGAAAATQMEHAcAAABNAgN1CAAAAJ8BAgKkAgsAACiQgJ8CAQLAAwwAEgABABIAAgCCAwIADQMJBAAAAEADCgMLAwwEAABAQAMNAw4DDwMQAxEEACiQgAYAAQABAAEYAAIAAAAAAAEAAAAAAAAAAAEAAAkAABABAAAAAAHIKxltIBIwVfrvc/kF1n5tV81aAapWya+8Dvq3uDYuuX6uBSxjVjqW

local v1 = game:GetService("ReplicatedStorage")
local u2 = require(v1.Shared.Framework.T)
local u3 = Random.new()
return function(p4, p5, p6) --[[Function name: RandomNormalDistribution, line 14]]
    --[[
    Upvalues:
        [1] = u2
        [2] = u3
    --]]
    local v7 = u2.number
    assert(v7(p4))
    local v8 = u2.number
    assert(v8(p5))
    local v9 = u2.number
    assert(v9(p6))
    local v10 = u3:NextNumber()
    local v11 = u3:NextNumber()
    local v12 = math.log(v10) * -2
    local v13 = math.sqrt(v12)
    local v14 = 6.283185307179586 * v11
    local v15 = v13 * math.cos(v14)
    return (p5 - p4) / 2 + p4 + v15 * p6
end