--devbgascension

-- Bytecode (Base64):
-- BgMSBG1hdGgEYWNvcwR0cmlnElBvaW50VG9PYmplY3RTcGFjZQFYAVoFYXRhbjIBWQRzcXJ0BkNGcmFtZQZBbmdsZXMJTWFnbml0dWRlBFVuaXQRaW52ZXJzZUtpbmVtYXRpY3MNZnJvbUF4aXNBbmdsZQNyYWQDbmV3B1NvbHZlSUsABAkDAAAACAUAAAUDAgICDQkHAAAJCAEBQwYHCAkHAgImBQYHWwcAAAkGBwHsBAUGuwMEAqQDAwAACBCAnwMCAoIDAgAEAgAAAAAAAABAAwEDAgQACBCAAAMDARgAAAAAAAAAAAAAAAAACAAAAAAUBAAAAAkGAAAFBAcIAgJfUgYBALwEAMYAAAAAnwQDAk0HBHkBAAAATQkEewIAAAA5CAkAngUHAwgAAACkBgUAABAwgJ8GAwI5BQYATQcEeAYAAABNCwR5AQAAAAQKCwdNDAR7AgAAAAQLDAdDCQoLuxkJAqQICQAAIDCAnwgCAp4FBwMIAAAApAYFAAAQMICfBgMCpAgMAAAsoICMCQAAUgoFAIwLAACfCAQCpAkMAAAsoIBSCgYAjAsAAIwMAACfCQQCCQcICU0IBKoNAAAAjAkAAIwKAABDCwIDYAsGAAgAAABDCAIDTQsEBw4AAAAJBAsIZQAfAIwL//9SDQgACRICAgkTDQ1DERITCRIDAyYQERJbEgIHCRESDewPEBG7Aw8CpA4QAAA8MICfDgICUgwOAAkJCwxSDAgACRECAgkSAwNDEBESCREMDCYPEBFbEQIHCRARA+wODxC7Aw4CpA0QAAA8MICfDQICUgsNAPUKEQtSCwkAUgwKAFINBABSDgUAUg8GAIILBgASAwQDBQMGAwEDBwQAEDCAAwgCAAAAAAAAAEADCQQAIDCAAwoDCwQALKCAAwwDDQMCBAA8MIACGC1EVPshCUAADA4BGAoAAAABAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAABAAEBAgAAAQEAAAACAOoAAAAAAAAAAAAAAAAAF+kAAAAAAAAAAAAAAAAAGgAAAAAACAAAAAAWBQEAAAoHAAAFBQcIAgKCTPsFAABSBgAAUgcBAFIIAgBSCQMAnwUFBqQKAgAABACAUgsHAJANBAO7Fg0CpAwGAAAUQICfDAICnwoDAqQNCAAAHACAjA4AAFIPCACMEAAAnw0EAgkMCg2kDQgAABwAgFIOCQCMDwAAjBAAAJ8NBAIJCwwNCQ4AC6QPCAAAHACAUhAFAIwRAACMEgAAnw8EAgkNDg+kDgoAACQAgIwPAACMEAAAORICAFsREgufDgQCCQwNDgkRAAukEggAABwAgFITBQCMFAAAjBUAAJ8SBAIJEBESpBEKAAAkAICMEgAAjBMAADkUAgCfEQQCCQ8QEaQQCAAAHACAUhEGAIwSAACMEwAAnxAEAgkODxCkDwoAACQAgIwQAACMEQAAORMDAFsSEwufDwQCCQ0OD4IMAwAMAwoDDwQABACAAgAAAAAAAAAAAwEDEAQAFECAAwsEABwAgAMRBAAkAIACAAAAAAAA4D8AJhIBGAAAAAAAAAEAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAQEAAAAAAAABAAAAAAAAAAEBAAAAAAAAAQAAAAAAAAEAAAAAAAABAAAAAAAAAAEtAAAAAAMAAAECAAajAAAAwAAAAMABAQDAAgIAEgABAIICAgADBgAGAQYCAwABAgEAARgAAgkaABYBAAAAAAP2PuAXeTCRIMT6ioMGVvZxsJMAGD58mYi/fUJ12/pz3lW7VDYt0gwO

local function u19(p1, p2, p3, p4) --[[Anonymous function at line 12]]
    local v5 = p1:PointToObjectSpace(p2)
    local v6 = v5.X
    local v7 = -v5.Z
    local v8 = -math.atan2(v6, v7)
    local v9 = v5.Y
    local v10 = v5.X ^ 2 + v5.Z ^ 2
    local v11 = math.sqrt(v10)
    local v12 = math.atan2(v9, v11)
    local _ = CFrame.Angles(0, v8, 0) * CFrame.Angles(v12, 0, 0)
    local v13 = v5.Magnitude
    local v14 = 0
    local v15 = 0
    if p3 + p4 < v13 then
        local v16 = p3 + p4
        v5 = v5.Unit * v16
    else
        local v17 = (p3 * p3 + v13 * v13 - p4 * p4) / (p3 * 2 * v13)
        v14 = -1 * math.acos(v17)
        local v18 = (p3 * p3 + p4 * p4 - v13 * v13) / (p3 * 2 * p4)
        v15 = 3.141592653589793 - math.acos(v18)
    end
    return v14, v15, v5, v8, v12
end
return function(p20, p21, p22, p23, p24) --[[Function name: SolveIK, line 38]]
    --[[
    Upvalues:
        [1] = u19
    --]]
    local v25, v26, v27, v28, v29 = u19(p20, p21, p22, p23)
    local v30 = CFrame.fromAxisAngle(v27, (math.rad(p24 or 0))) * CFrame.Angles(0, v28, 0) * CFrame.Angles(v29, 0, 0)
    return p20 * v30 * CFrame.Angles(v25, 0, 0) * CFrame.new(0, 0, -p22 * 0.5), p20 * v30 * CFrame.Angles(v25, 0, 0) * CFrame.new(0, 0, -p22) * CFrame.Angles(v26, 0, 0) * CFrame.new(0, 0, -p23 * 0.5)
end