--devbgascension

-- Bytecode (Base64):
-- BgMXBlJhcml0eQJYUAJJZAROYW1lBkFtb3VudAVTaGlueQZNeXRoaWMMR2VuZXJhdGVHVUlED0ZpbGxQZXRFbmNoYW50cw9DcmVhdGVQbGF5ZXJQZXQEZ2FtZRFSZXBsaWNhdGVkU3RvcmFnZQpHZXRTZXJ2aWNlC0h0dHBTZXJ2aWNlB3JlcXVpcmUGU2hhcmVkBVR5cGVzBERhdGEEUGV0cwVVdGlscwxQZXRMZXZlbFV0aWwJQ29uc3RhbnRzC0VuY2hhbnRVdGlsAAIKAwMAAAgFAAAFAw8DBEH7BQAAhwQFAU0DBPIAAAAATQUCLgIAAACQBAUB4gUIAPsGAQCpCAAAvAYGpAkAAACfBgMCMAYFlAMAAAAwAQW6BAAAAE0HAisFAAAADgcIAE0HAisFAAAAjAgBAGAIBAAHAAAATQYCKwUAAABlAAEAxgYAADAGBSsFAAAATQcCtAYAAAAqBwMAAQAAgKkGAQBlAAEAxgYAADAGBbQGAAAATQcCpAcAAAAqBwMAAQAAgKkGAQBlAAEAxgYAADAGBaQHAAAAMAQFLgIAAABNBgUrBQAAAEcGCgAAAACAjAYAAGAGBwAEAAAA+wYCAFIIAABSCQUAvAYGZAoAAACfBgQBggUCAAsDAQIAAAAAAAAAAAMCAwMDBAMFAwYDBwUGAwQFBgcCAwgDCQAWCgEYAAAAAAIAAAIBAAAAAAAAAQABAAAAAAAAAAAAAAAAAAEAAAAAAAAAAAEAAAAAAAAAAAEAAgAAAAAAAAEAAAAAAAMbAAAAAAoAAAECADujAAAApAABAAAAAEBvAgIAvAAAFgMAAACfAAMCpAEBAAAAAEBvAwQAvAEBFgMAAACfAQMCpAIGAAAAUEBNBAASBwAAAE0DBO8IAAAAnwICAqQDBgAAAFBATQYAEgcAAABNBQbGCQAAAE0EBegKAAAAnwMCAqQEBgAAAFBATQcAEgcAAABNBgehCwAAAE0FBj0MAAAAnwQCAqQFBgAAAFBATQcAEgcAAABNBgcHDQAAAJ8FAgKkBgYAAABQQE0JABIHAAAATQgJoQsAAABNBwhGDgAAAJ8GAgLABw8AEgADABIAAQASAAYAggcCABADCwQAAABAAwwDDQMOAw8EAABQQAMQAxEDEgMTAxQDFQMWAxcGAAEAAQABGAACAAAAAAABAAAAAAACAAAAAAAAAQAAAAAAAAAAAQAAAAAAAAAAAQAAAAAAAAEAAAAAAAAAAAwAAAAYAQAAAAABnR2bl9rBm5qv2fEDORZONz9dVv3iHgJO1GQhLAhggFVYG0BwKAWEkw==

local v1 = game:GetService("ReplicatedStorage")
local u2 = game:GetService("HttpService")
require(v1.Shared.Types)
local u3 = require(v1.Shared.Data.Pets)
require(v1.Shared.Utils.PetLevelUtil)
require(v1.Shared.Constants)
local u4 = require(v1.Shared.Utils.EnchantUtil)
return function(p5, p6, p7) --[[Function name: CreatePlayerPet, line 22]]
    --[[
    Upvalues:
        [1] = u3
        [2] = u2
        [3] = u4
    --]]
    local _ = u3[p6].Rarity
    local v8 = p7.XP or 0
    local v9 = {
        ["Id"] = u2:GenerateGUID(false),
        ["Name"] = p6
    }
    local v10
    if p7.Amount and p7.Amount > 1 then
        v10 = p7.Amount
    else
        v10 = nil
    end
    v9.Amount = v10
    v9.Shiny = p7.Shiny == true and true or nil
    v9.Mythic = p7.Mythic == true and true or nil
    v9.XP = v8
    if v9.Amount == nil and v8 > 0 then
        u4:FillPetEnchants(p5, v9)
    end
    return v9
end