--devbgascension

-- Bytecode (Base64):
-- BgMYBFR5cGUETmFtZQNQZXQJR2V0Q2hhbmNlBkNvbG9yMwNuZXcHZnJvbVJHQgZNeXRoaWMMTXl0aGljQ2hhbmNlBVNoaW55C1NoaW55Q2hhbmNlBVRvSFNWB2Zyb21IU1YRR2V0UGV0Q2hhbmNlQ29sb3IEZ2FtZRFSZXBsaWNhdGVkU3RvcmFnZQpHZXRTZXJ2aWNlB3JlcXVpcmUGU2hhcmVkBVR5cGVzBVV0aWxzBVN0YXRzB1BldFV0aWwJQ29uc3RhbnRzAAILAQIAAABP+wEAAOIDAgBvBAMAMAQDEQAAAABNBAC6AQAAADAEA7oBAAAAvAEB4QQAAACfAQMCpAIHAAAYUICMAwAAjAQBAIwFAQCfAgQCbwMIAH0BCQADAAAApAMKAAAkUICMBP8AjAUAAIwGZACfAwQCUgIDAGUACgBvAwsAYAEIAAMAAACkAwcAABhQgIwEAACMBQEAjAYAAJ8DBAJSAgMATQMApAwAAAAOAwUA+wUBAE0EBQ4OAAAAPgMEDQkBAQNNAwC0DwAAAA4DBQD7BQEATQQFtxAAAAA+AwQNCQEBA7wDAs0RAAAAnwMCBE0HALQPAAAADgcCAG8GEgBlAAEAjAYAAE0IAKQMAAAADggCAG8HEwBlAAEAjAcAAEMGBgekBxUAAFBQgEMJAwYhCAkWUgkEAFIKBQCfBwQAggcAABcDAQMCBQIAAQMDAwQDBQMGBAAYUIAC/Knx0k1iUD8DBwQAJFCAAnsUrkfhenQ/AwgCAAAAAAAAWUADCQMKAwsDDAIAAAAAAADQPwIzMzMzMzPDPwMNBABQUIACAAAAAAAA8D8ACQ4BGAAAAAAAAAAAAAAAAAEAAAAAAAEAAAEAAAAAAAAAAQAAAQAAAAAAAAMAAAEAAAAAAgAAAQAAAAADAAABAAAAAAABAAAAAAAAAgAAAAAAAAAKAAAAAAcAAAECACSjAAAApAABAAAAAEBvAgIAvAAAFgMAAACfAAMCpAEFAAAAQEBNAwASBgAAAE0CA+8HAAAAnwECAqQCBQAAAEBATQYAEgYAAABNBQahCAAAAE0EBSEJAAAATQMEaQoAAACfAgICpAMFAAAAQEBNBQASBgAAAE0EBQcLAAAAnwMCAsAEDAASAAIAEgADAIIEAgANAw8EAAAAQAMQAxEDEgQAAEBAAxMDFAMVAxYDFwMYBgABAAEAARgAAgAAAAAAAgAAAAAAAAEAAAAAAAAAAAAAAQAAAAAAAAIAABcBAAAAAAF901nIdGrb108XM1xgk1Tru1qpvjPE2o666ESY2/eqIs8VQlUkp3N8

local v1 = game:GetService("ReplicatedStorage")
require(v1.Shared.Types)
local u2 = require(v1.Shared.Utils.Stats.PetUtil)
local u3 = require(v1.Shared.Constants)
return function(p4) --[[Function name: GetPetChanceColor, line 9]]
    --[[
    Upvalues:
        [1] = u2
        [2] = u3
    --]]
    local v5 = u2:GetChance({
        ["Type"] = "Pet",
        ["Name"] = p4.Name
    })
    local v6 = Color3.new(0, 1, 1)
    if v5 <= 0.001 then
        v6 = Color3.fromRGB(255, 0, 100)
    elseif v5 < 0.005 then
        v6 = Color3.new(0, 1, 0)
    end
    if p4.Mythic then
        v5 = v5 * (u3.MythicChance / 100)
    end
    if p4.Shiny then
        local _ = v5 * (u3.ShinyChance / 100)
    end
    local v7, v8, v9 = v6:ToHSV()
    local v10 = (p4.Shiny and 0.25 or 0) + (p4.Mythic and 0.15 or 0)
    return Color3.fromHSV((v7 + v10) % 1, v8, v9)
end