--devbgascension

-- Bytecode (Base64):
-- BgMLEUlzUHJvVHJhZGluZ1BsYXphBGdhbWURUmVwbGljYXRlZFN0b3JhZ2UKR2V0U2VydmljZQdyZXF1aXJlBlNoYXJlZAlDb25zdGFudHMHUGxhY2VJZARQcm9kCFBsYXphUHJvBFRlc3QAAgEAAQAAAAL7AAAAggACAAAADgEBGAAADwAAAAAHAAABAgAoowAAAKQAAQAAAABAbwICALwAABYDAAAAnwADAqQBBQAAAEBATQMAEgYAAABNAgMHBwAAAJ8BAgKkAwEAAAAAQE0CA8UIAAAAqQMBAE0GAcUIAAAATQUG6gkAAABNBAVECgAAAPECCwAEAAAATQYBxQgAAABNBQZ8CwAAAE0EBUQKAAAA8QICAAQAAACpAwABqQMBAMAEDAASAAMAggQCAA0DAgQAAABAAwMDBAMFBAAAQEADBgMHAwgDCQMKAwsGAAEAAQABGAACAAAAAAACAAAAAAAAAgAAAAMAAAAAAAAAAAEAAAAAAAAAAAADAAUBAAAAAAFGrnIMmw56WnRqGJgeC6loRjRfjoXZLbBe3F/UhHXn3E2TwaqcbI8o

local v1 = game:GetService("ReplicatedStorage")
local v2 = require(v1.Shared.Constants)
local v3 = game.PlaceId
local u4 = v3 == v2.PlaceId.Prod.PlazaPro and true or v3 == v2.PlaceId.Test.PlazaPro
return function() --[[Function name: IsProTradingPlaza, line 14]]
    --[[
    Upvalues:
        [1] = u4
    --]]
    return u4
end