--devbgascension

-- Bytecode (Base64):
-- BgMMDklzVHJhZGluZ1BsYXphBGdhbWURUmVwbGljYXRlZFN0b3JhZ2UKR2V0U2VydmljZQdyZXF1aXJlBlNoYXJlZAlDb25zdGFudHMHUGxhY2VJZARQcm9kBVBsYXphCFBsYXphUHJvBFRlc3QAAgEAAQAAAAL7AAAAggACAAAAEQEBGAAAEgAAAAAHAAABAgA6owAAAKQAAQAAAABAbwICALwAABYDAAAAnwADAqQBBQAAAEBATQMAEgYAAABNAgMHBwAAAJ8BAgKkAwEAAAAAQE0CA8UIAAAAqQMBAE0GAcUIAAAATQUG6gkAAABNBAUUCgAAAPECHQAEAAAAqQMBAE0GAcUIAAAATQUG6gkAAABNBAVECwAAAPECFAAEAAAAqQMBAE0GAcUIAAAATQUGfAwAAABNBAUUCgAAAPECCwAEAAAATQYBxQgAAABNBQZ8DAAAAE0EBUQLAAAA8QICAAQAAACpAwABqQMBAMAEDQASAAMAggQCAA4DAgQAAABAAwMDBAMFBAAAQEADBgMHAwgDCQMKAwsDDAYAAQABAAEYAAIAAAAAAAIAAAAAAAACAAAAAwAAAAAAAAAAAAEAAAAAAAAAAAEAAAAAAAAAAQAAAAAAAAAAAAQABQEAAAAAAf25WqOq0Uryz30wN878r+rjeWHfVBIE7dEKFMbIwPosOrfcK3ca/4k=

local v1 = game:GetService("ReplicatedStorage")
local v2 = require(v1.Shared.Constants)
local v3 = game.PlaceId
local u4 = (v3 == v2.PlaceId.Prod.Plaza or (v3 == v2.PlaceId.Prod.PlazaPro or v3 == v2.PlaceId.Test.Plaza)) and true or v3 == v2.PlaceId.Test.PlazaPro
return function() --[[Function name: IsTradingPlaza, line 17]]
    --[[
    Upvalues:
        [1] = u4
    --]]
    return u4
end