--devbgascension

-- Bytecode (Base64):
-- BgMVA25vdwREYXRlBVN0YXJ0DVVuaXhUaW1lc3RhbXAGRmluaXNoB0VuYWJsZWQIQ2FsbGJhY2sGdXBkYXRlBXRhYmxlBmluc2VydApUaW1lZEV2ZW50BGdhbWURUmVwbGljYXRlZFN0b3JhZ2UKR2V0U2VydmljZQdyZXF1aXJlBlNoYXJlZAlGcmFtZXdvcmsJVXRpbGl0aWVzBWV2ZXJ5BE1hdGgEVGltZQAEBgEBAAAOAwACBQEEBwQJAgcEEQIi+wIAAE0BApoAAAAAnwEBAqkCAABNBQDkAQAAAE0EBRwCAAAATQMEtwMAAAB9AwsAAQAAAE0FAOQBAAAATQQF3wQAAABNAwS3AwAAANQBAgADAAAAqQIAAakCAQBNAwDwBQAAAPEDBwACAAAAMAIA8AUAAABNAwBGBgAAAFIEAgCfAwIBggABAAcDAQMCAwMDBAMFAwYDBwAVCAEYAAAAAAEAAAAAAAAAAAAAAAAAAAAAAAABAAAAAQABAAAAAhYAAAAACAICAAAPBAACBQIEBQcGEQIHBhkCMeICAwAwAALkAAAAADABAkYBAAAAxgMAADADAvACAAAA+wQAAE0DBJoEAAAAnwMBAqkEAABNBwLkAAAAAE0GBxwFAAAATQUGtwYAAAB9BQsAAwAAAE0HAuQAAAAATQYH3wcAAABNBQa3BgAAANQDAgAFAAAAqQQAAakEAQBNBQLwAgAAAPEFBwAEAAAAMAQC8AIAAABNBQJGAQAAAFIGBACfBQIB+wQBAJ40BAQCAAAAUgUCAKQDCgAAJICAnwMDAYIAAQALAwIDBwMGBQMAAQIDAQMDAwQDBQMJAwoEACSAgAAeCwEYCQEAAQABAAD0AAAAAQAAAAAAAAAAAAAAAAAAAAAAAAEAAAABAAEAAAALAAAAAAAAARYAAAAACgACAAALAAACBwgNAgcIFQIo+wAAAMYBAADGAgAAZAAhAPsGAQBNBQaaAAAAAJ8FAQKpBgAATQkE5AEAAABNCAkcAgAAAE0HCLcDAAAAfQcLAAUAAABNCQTkAQAAAE0ICd8EAAAATQcItwMAAADUBQIABwAAAKkGAAGpBgEATQcE8AUAAADxBwcABgAAADAGBPAFAAAATQcERgYAAABSCAYAnwcCAW4A3v8CAAAAggABAAcDAQMCAwMDBAMFAwYDBwApAAEYFAAAAOwAAAABAAAAAAAAAAAAAAAAAAAAAAAAAQAAAAEAAQAAABAAAxYAAAAACQAAAQIALaMAAACkAAEAAAAAQG8CAgC8AAAWAwAAAJ8AAwKkAQUAAABAQE0FABIGAAAATQQFHAcAAABNAwS1CAAAAE0CA8QJAAAAnwECAqQCBQAAAEBATQcAEgYAAABNBgccBwAAAE0FBrUIAAAATQQFjAoAAABNAwRKCwAAAJ8CAgL/AwAAAAAAAMAEDAASAAIAwAUNABIAAgASAAMAUgYBAIwHBQDACA4AEgADABIAAgCfBgMBggUCAA8DDAQAAABAAw0DDgMPBAAAQEADEAMRAxIDEwMUAxUGAAYBBgIDAAECAQABGAACAAAAAAACAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAMAAMACQAACwAAAAAABgEAAAAAA8K5W3mE+6PJ8H0x7VSqo4ZAbyTqXzY/iALpRwY7wIzLpiHzbc3UHao=

local v1 = game:GetService("ReplicatedStorage")
local v2 = require(v1.Shared.Framework.Utilities.every)
local u3 = require(v1.Shared.Framework.Utilities.Math.Time)
local u4 = {}
v2(5, function() --[[Anonymous function at line 41]]
    --[[
    Upvalues:
        [1] = u4
        [2] = u3
    --]]
    for _, v5 in u4 do
        local v6 = u3.now()
        local v7
        if v5.Date.Start.UnixTimestamp <= v6 then
            v7 = v6 <= v5.Date.Finish.UnixTimestamp
        else
            v7 = false
        end
        if v5.Enabled ~= v7 then
            v5.Enabled = v7
            v5.Callback(v7)
        end
    end
end)
return function(p8, p9) --[[Function name: TimedEvent, line 30]]
    --[[
    Upvalues:
        [1] = u3
        [2] = u4
    --]]
    local v10 = {
        ["Date"] = p8,
        ["Callback"] = p9,
        ["Enabled"] = nil
    }
    local v11 = u3.now()
    local v12
    if v10.Date.Start.UnixTimestamp <= v11 then
        v12 = v11 <= v10.Date.Finish.UnixTimestamp
    else
        v12 = false
    end
    if v10.Enabled ~= v12 then
        v10.Enabled = v12
        v10.Callback(v12)
    end
    local v13 = u4
    table.insert(v13, v10)
end